### ISSUE TITLE
README.md typo with models path

### ISSUE THREAD

**Issue by entmike** [cubiq/ComfyUI_IPAdapter_plus#1]
Greetings!  Linux user here.  This one tripped me up for a second...

Small typo in `README.md`:

`ComfyUI/custom_nodes/ComfyUI_IPAdapter_Plus/models` should be `ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/models`

**Comment by cubiq** [comment]
fair enough, I'll fix it in the next (hopefully more stable) release

**Comment by entmike** [comment]
Thanks!  I've been using your current alpha with great success.  Keep up the good work!
