### ISSUE TITLE
Possible to get different face angles?

### ISSUE THREAD

**Issue by ParthGandhi** [cubiq/ComfyUI_IPAdapter_plus#101]
When using ip-adapter-face in SDXL and a front portrait, I only seem to get output images with the face pointing at the camera. I guess I know why this happens, but is there any easy hack to allow it to give side profiles etc?

**Comment by cubiq** [comment]
control net

**Comment by ParthGandhi** [comment]
do you mind elaborating please? or just point me to a good tutorial.

**Comment by cubiq** [comment]
there is an example in the documentation and a workflow in the examples directory

![control net](https://raw.githubusercontent.com/cubiq/ComfyUI_IPAdapter_plus/main/examples/canny_controlnet.jpg)

use the face model and any controlnet you want. In your case maybe a pose controlnet or a very light canny/lineart

**Comment by ParthGandhi** [comment]
Thanks! Let me try it out. Would it also work if the face is part of a much larger image?

**Comment by cubiq** [comment]
it's better if you cut out the face
