### ISSUE TITLE
How to use new multiple attention masks feature?

### ISSUE THREAD

**Issue by Arron17** [cubiq/ComfyUI_IPAdapter_plus#102]
I may be understanding the use of this incorrectly, but I thought that the idea with this was to be able to input multiple images and corresponding attention masks using 1 Apply IPAdapter node, instead of having to use multiple.

If this is what it's supposed to be how is it used?

Say I have Image 1 and a corresponding Mask 1 that shows where I want that Image to affect the generation, then I have an image 2 with a Mask 2 that shows another location where I want image 2 to affect the generation, how do I apply that?

I cannot find any nodes that batch masks and my thought was you could batch the masks in the same order as the images that you batch with the "Encode IPAdapter Image" node.

Please correct me if I'm thinking about this incorrectly.

**Comment by cubiq** [comment]
multiple masks are used to batch multiple latents not to mask multiple reference images. This is mostly useful for animations.

If you need to mask 2 images, use 2 IPAdapter apply nodes.

**Comment by Arron17** [comment]
Ok, I was hoping you'd found a way to mask multiple reference images so we could cut down on the memory usage of loading multiple IPAdapter nodes. Thanks.
