### ISSUE TITLE
Import Failure after ComfyUI Update

### ISSUE THREAD

**Issue by stealurfaces** [cubiq/ComfyUI_IPAdapter_plus#103]
Any thoughts? Thanks for your help!

-----------

Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\__init__.py", line 1, in <module>
    from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 7, in <module>
    from comfy.clip_vision import clip_preprocess
ImportError: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (C:\AI\ComfyUI\ComfyUI\comfy\clip_vision.py)

Cannot import C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus module for custom nodes: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (C:\AI\ComfyUI\ComfyUI\comfy\clip_vision.py)

**Comment by cubiq** [comment]
I would say you have an old version and you need to update

**Comment by James-Mart** [comment]
> I would say you have an old version and you need to update

An old version of what, `IPAdapter_plus`? I have the same issue. My suspicion is that it's an old version of `IPAdapter_plus` but it's the version that gets automatically installed with the `ComfyUI-Manager`.

**Comment by cubiq** [comment]
don't trust the Manager, sometimes it doesn't actually update even if it says that it does. Check the IPAdapterPlus.py file content to be sure.

Also be sure to have the latest ComfyUI version (you may need to redownload the portable)

**Comment by James-Mart** [comment]
I updated ComfyUI, uninstalled the Manager-owned version of `IPAdapter_plus` and just cloned this repo myself following the README instructions. It's working now 👍

**Comment by stealurfaces** [comment]
Relying on the Manager was my downfall. Manually updating ComfyUI and reinstalling this repo got it working again. Thanks!
