### ISSUE TITLE
Testing for different weights and noise

### ISSUE THREAD

**Issue by scribbleed** [cubiq/ComfyUI_IPAdapter_plus#107]
Not an issue or request; just want to say thanks for the superb nodes. Also just want to share how I tested for different weights and noise by using the ComfyUI_ezXY plot.

![screenshot](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/110883900/9b69ddca-afc9-4b73-a597-35b0050da51a)

**Comment by cubiq** [comment]
that's very kind of you, thanks :smile: have fun with IPAdapters!
