### ISSUE TITLE
new update increases time at ksampler >2x

### ISSUE THREAD

**Issue by IrfanKheiri** [cubiq/ComfyUI_IPAdapter_plus#112]
After the update that adds time sampling, my workflow slows down at the ksampler. It's taking over twice the time it used to (nearly 3x). I'm also using lc lora and using SDXL checkpoint. I tried removing the ipadapter  from the workflow and the time was as it used to be before the update. I have 3060 12 gb vram and 16 gb ram on windows 10.

**Comment by cubiq** [comment]
you mean timestepping or yesterday's update? what commit number exactly?

**Comment by IrfanKheiri** [comment]
the latest. i updated yesterday.

**Comment by cubiq** [comment]
what version did you have before? What is the commit number that was working fine?

**Comment by cubiq** [comment]
if you didn't have timestepping then it was a few weeks old. I'll see if there's anything weird but if you don't use timestepping or unfold everything is the same as before. If you haven't already, try to refresh the browser, delete the ipadapter nodes and retry.
