### ISSUE TITLE
Clip_vision_output?

### ISSUE THREAD

**Issue by lonelydonut** [cubiq/ComfyUI_IPAdapter_plus#113]
Hi Matteo. In one ComfyUI implementation of IP_adapter I've seen a CLIP_Vision_Output. I've seen folks pass this + the main prompt into an unclip node, and the resulting conditioning going downstream (reinforcing the prompt with a visual element, typically for animation purposes). Is there a way to do something similar? Thank you for these fantastic nodes and tutorials!

**Comment by cubiq** [comment]
there is no need of that because we have a dedicated node for clip vision, just take the output from there (it supports multiple outputs). The result is the same.

**Comment by lonelydonut** [comment]
I see - will try that. Thank you for addressing my naive question!
