### ISSUE TITLE
IPAdapterPlus doesn't handle custom paths in extra_models_paths.yaml

### ISSUE THREAD

**Issue by aarongerber** [cubiq/ComfyUI_IPAdapter_plus#114]
IPAdapterPlus.py file has a line that reads:
GLOBAL_MODELS_DIR = os.path.join(folder_paths.models_dir, "ipadapter")
This line points at the default model folder and doesn't consider folders that have been added to extra_model_paths.yaml

I have all of my models on a separate drive but it is continually looking in the model directory in Comfy.

### SOLUTION
Per comments below by @cubiq you can modify the extra_model_paths.yaml file:
comfyui:
base_path: path/base
checkpoints: models/checkpoints/
_ipadapter: models/ipadapter_

@cubiq THANKS!

**Comment by cubiq** [comment]
if you set an `ipadapter` value in the yaml file it should look for that... at least it should

**Comment by aarongerber** [comment]
I wasn't sure I followed you, but it worked. For those scratching their heads... 
In _extra_model_paths.yaml_ type:
comfyui:
     base_path: path/base
     checkpoints: models/checkpoints/
     **ipadapter: models/ipadapter**

@cubiq THANKS! that wasn't very intuitive in terms of knowing I could just type out ipadapter... it wasn't in the examples. Could you help me understand how to do this for other custom_nodes and/or give me a list of supported locations?

**Comment by aarongerber** [comment]
@cubiq It would be nice if the plugin just detected the folder based on the custom paths, but you have a good enough solution that survives updates, so I'll close as completed. Thanks!
