### ISSUE TITLE
Problem with IP. Adapter Apply.

### ISSUE THREAD

**Issue by Nico53425342** [cubiq/ComfyUI_IPAdapter_plus#124]
This is the error that i got each time that i execute my workflow :

Error occurred when executing IPAdapterApply:

CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 453, in apply_ipadapter
clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 105, in zeroed_hidden_states
outputs = clip_vision.model(pixel_values, output_hidden_states=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 186, in forward
x = self.vision_model(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I have no idea on how to fix it...

**Comment by Nico53425342** [comment]
yes, it worked fine a few days before

**Comment by Nico53425342** [comment]
![Capture d’écran 2023-12-09 191628](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/151887339/cd45a803-5cba-4384-b88a-d261dce4282c)

**Comment by cubiq** [comment]
please run a barebone workflow with just IPAdapter and ksampler and confirm that it is working

**Comment by Nico53425342** [comment]
okay

**Comment by notintricate** [comment]
same here

**Comment by Nico53425342** [comment]
Same Problème :

![Capture d’écran 2023-12-09 201904](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/151887339/1d604bf2-bcd5-4ffc-89b6-14ce8b01b928)

**Comment by cubiq** [comment]
please be sure to have the latest version of ComfyUI and the extension installed

**Comment by entmike** [comment]
This started happening to me today, too:

```
worker        | 2023-12-09 19:22:18,202 DEBG 'comfyui' stderr output:
worker        | ERROR:root:Traceback (most recent call last):
worker        |   File "/ComfyUI/execution.py", line 153, in recursive_execute
worker        |     output_data, output_ui = get_output_data(obj, input_data_all)
worker        |   File "/ComfyUI/execution.py", line 83, in get_output_data
worker        |     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
worker        |   File "/ComfyUI/execution.py", line 76, in map_node_over_list
worker        |     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
worker        |   File "/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 453, in apply_ipadapter
worker        |     clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
worker        |   File "/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 105, in zeroed_hidden_states
worker        |     outputs = clip_vision.model(pixel_values, output_hidden_states=True)
worker        |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
worker        |     return self._call_impl(*args, **kwargs)
worker        |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
worker        |     return forward_call(*args, **kwargs)
worker        |   File "/ComfyUI/comfy/clip_model.py", line 186, in forward
worker        |     x = self.vision_model(*args, **kwargs)
worker        |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
worker        |     return self._call_impl(*args, **kwargs)
worker        |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
worker        |     return forward_call(*args, **kwargs)
worker        | TypeError: CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'
```

**Comment by Nico53425342** [comment]
yeah i update everything each time i open Comfy-UI

**Comment by BigBlueGX** [comment]
I have the same issue.

It only happens with the plus models

**Comment by entmike** [comment]
I think this commit in ComfyUI broke it: `174eba8e957b4b885d4d510d53dca859226ba9ef`

I rolled back to `97015b6b383718bdc65cb617e3050069a156679d` and I'm ok, so it might be a breaking change on the ComfyUI side.

**Comment by cubiq** [comment]
update the extension, thanks for the report

**Comment by aarongerber** [comment]
> update the extension, thanks for the report

I hope you will tolerate this off-topic, but I am truly impressed with your support for this plugin.

**Comment by 2blackbar** [comment]
dood, whos the joker whos breaking stuff on purpose ?

**Comment by Nebuluss** [comment]
Got the same issue this morning 

CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

File "D:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 570, in preprocess
clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])

**Comment by cubiq** [comment]
this has been solved, just update the extension AND comfyui. if you still have issues open a new bug report

**Comment by KINGLIFER** [comment]
I updated everything and still getting CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'
Not sure what is going on. Using Stability Matrix (ComfyUi)

**Comment by cubiq** [comment]
post your full error message

**Comment by SageRhaposdy** [comment]
Same here:

`Error occurred when executing IPAdapter:

CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 238, in clip_vision_encode
outputs = clip_vision.model(pixel_values=pixel_values, output_hidden_states=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 186, in forward
x = self.vision_model(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by cubiq** [comment]
you are using IPAdapter-ComfyUI instead of ComfyUI_IPAdapter_Plus

**Comment by KINGLIFER** [comment]
<img width="662" alt="Screenshot 2023-12-14 115620" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/98950059/8649e4af-770e-4924-8050-65b2d8e84b25">

**Comment by cubiq** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/ca3c213e-3365-43d0-872c-f8e8946b5112)

**Comment by SageRhaposdy** [comment]
The workflow I'm currently attempting to use has it set up like this. It's been previously confirmed that using both versions should work. 

Is there any advice you can provide?

**Comment by ckfivefivefive** [comment]
I agree, I have the same problem following this tutorial: https://civitai.com/articles/2345

Lookings like the whole SDXL workflow is struggling to propose a stable situation?
Or are we missing something? What can we do?

Many thanks.

**Comment by cubiq** [comment]
check the home of this repo. The example directory is full of examples, also I made 4 videos that cover pretty much everything. AloeVera's workflow is old and unsupported

**Comment by ckfivefivefive** [comment]
Alright thanks, since everythings moves fast it's really hard to analyze what's new, fresh, up, to date and working, especially when you're not behind the scene and just a creative wannabe.

**Comment by KINGLIFER** [comment]
I must confess, this is a common challenge that often deters corporations from embracing the open-source community concept. It's important to recognize that contributors, often enthusiastic hobbyists, might not fully grasp the intricate nature of modifying software and its potential impact on established workflows.

While it's true that these efforts are typically undertaken without direct compensation, it's crucial to approach changes with an understanding of the ripple effects they can have. The absence of a comprehensive guide or manual does'nt help the issue much either. Many established processes rely on the existing designs, and sudden alterations can disrupt entire workflows.

Acknowledging this, it becomes evident that such unintended consequences could hinder the broader acceptance and adoption of the software. This is certainly not the desired outcome for anyone involved. Therefore, embracing a collaborative environment where contributors appreciate the broader implications of their modifications is key to maintaining a positive momentum for the software's development.

There should be a hotfix for ipadapters. (as in...) a menu or whatever to replace the previous setup to a basic alterative. Example what would one due if their workflow was based on conditions (After the ip is passed). I know you can unplug and plug but many are in the building/learning process. AloeVera is a dick (Yes I said it) and a racist. So *F* him but instead of pushing people away it would benefit to say well... that is old but what needs to be done is.... (blah).

anyway...

**Comment by KINGLIFER** [comment]
After doing a botched ipadaper conversion I get this error. Any help would be awesome. :

Error occurred when executing IPAdapterModelLoader:

'NoneType' object has no attribute 'lower'

File "D:\Ai\Data\Packages\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\Ai\Data\Packages\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\Ai\Data\Packages\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\Ai\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 384, in load_ipadapter_model
model = comfy.utils.load_torch_file(ckpt_path, safe_load=True)
File "D:\Ai\Data\Packages\ComfyUI\comfy\utils.py", line 12, in load_torch_file
if ckpt.lower().endswith(".safetensors"):

**Comment by cubiq** [comment]
- you can use close source commercial products and get customer support
- remember to read the documentation, also the issue tracker is full of useful information
- update to the latest version of comfy and this extension, the manager doesn't always update correctly, nothing I can do about it. if you are not tech savvy your best option is to start over with a clean installation
- most importantly don't believe anything you read on civitai

that's pretty much it

**Comment by ttulttul** [comment]
For what it's worth, I am getting the same error with everything updated, and I am using ComfyUI_IPAdapter_plus. The workflow attached here demonstrates the failure with the simplest possible setup.

[Basic IPAdapter Breakage Example.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13733373/Basic.IPAdapter.Breakage.Example.json)

**Comment by ttulttul** [comment]
I found the issue. For whatever bizarre reason, git pull was not pulling the freshest commits from the main branch. I blew away the `ComfyUI_IPAdapter_plus` directory and re-cloned the repository and now the latest code is in place. Not sure why git failed me.

**Comment by vchabak** [comment]
[Error.txt](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13734541/Error.txt)
[ComfyUI_temp_yaygy_00061_.zip](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13734566/ComfyUI_temp_yaygy_00061_.zip)
Hello! I confirm the problem with the IPAdapter when working with SDXL. A few days ago I was working with IPAdapter and I still have the generated png file. Today it does not work. I did the update after I received my png file. Now I have spent several hours looking for the problem and found that with SD1.5 it works, but with SDXL it does not. I have attached the file with the error and the archive with the png. I want to say right away that although the workflow is built on Eff-nodes, the same error occurs on standard Ksampler.

Also, after the update, the XY plot script (Efficiency) does not work for several sdxl, but that's another story.

**Comment by shawpook** [comment]
The same issue has not been resolved after following the above steps. Here is my report

Requested to load CLIPVisionModelWithProjection
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 441, in apply_ipadapter
    clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
  File "/root/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 99, in zeroed_hidden_states
    outputs = clip_vision.model(pixel_values=pixel_values, intermediate_output=-2)
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: CLIPVisionModelWithProjection.forward() got an unexpected keyword argument 'intermediate_output'

**Comment by shawpook** [comment]
I changed to IP adapter_ Sdxl. bin+sdxl encoders can now run, previously using ip adapter plus_ Sdxl_ Vit-h.bin cannot run under both encoders

**Comment by vchabak** [comment]
@shawpook     I had a problem tonight when the IPAdapter stopped working with SDXL. I was using Vit-h.safetensors with SD1.5 clip vision. Everything was fine, but after an update I did recently, everything broke. But in a neighboring thread, Mateo advised someone to write --force-fp16 instead of --force-fp32 in the startup parameters. I didn't have this option at all, so I added --force-fp16 and everything works now.

**Comment by KINGLIFER** [comment]
Best thing is to never update anything. Trust me.

**Comment by ElGato2112** [comment]
After updating all I have the same issue with the ip-adapter. Is it solved yet? Because I saw a message on the comfy-ui manager and I don't know what should I do: "Issue News:

[IPAdapter] The maintainer of 'IPAdapter-ComfyUI' has decided to collaborate on development with the 'ComfyUI IPAdapter plus' repository. Users currently using 'IPAdapter-ComfyUI' are recommended to transition to installing 'ComfyUI IPAdapter plus.' 'IPAdapter-ComfyUI' has been moved to the legacy channel." 

And this is the error message I got: "Error occurred when executing IPAdapter:

CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

File "D:\ASTABLE DIFUSION\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ASTABLE DIFUSION\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ASTABLE DIFUSION\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ASTABLE DIFUSION\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
File "D:\ASTABLE DIFUSION\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 238, in clip_vision_encode
outputs = clip_vision.model(pixel_values=pixel_values, output_hidden_states=True)
File "D:\ASTABLE DIFUSION\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "D:\ASTABLE DIFUSION\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 186, in forward
x = self.vision_model(*args, **kwargs)
File "D:\ASTABLE DIFUSION\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)"

**Comment by vchabak** [comment]
@ElGato2112 
After update new path to IpAdapter is ...\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
path to IPAdapter models is ...\ComfyUI\models\ipadapter
path to Clip vision is ...\ComfyUI\models\clip_vision

Try reinstalling IpAdapter through the Manager if you do not have these folders at the specified paths.
I am currently working with IPAdapter and it works great. I had another problem with the IPAdapter, but it was a sampler issue. I described the solution above.

**Comment by ElGato2112** [comment]
> @ElGato2112 After update, new path to IpAdapter is ...\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus path to IPAdapter models is ...\ComfyUI\models\ipadapter path to Clip vision is ...\ComfyUI\models\clip_vision
> 
> Try reinstalling IpAdapter through the Manager if you do not have these folders at the specified paths. I am currently working with IPAdapter and it works great. I had another problem with the IPAdapter, but it was a sampler issue. I described the solution above.

Thank You! It seems to work now but still has problems with the path, I moved the models to  ...\ComfyUI\models\ipadapter Comfy doesn´t detect it :(

**Comment by vchabak** [comment]
> > @ElGato2112 After update, new path to IpAdapter is ...\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus path to IPAdapter models is ...\ComfyUI\models\ipadapter path to Clip vision is ...\ComfyUI\models\clip_vision
> > Try reinstalling IpAdapter through the Manager if you do not have these folders at the specified paths. I am currently working with IPAdapter and it works great. I had another problem with the IPAdapter, but it was a sampler issue. I described the solution above.
> 
> Thank You! It seems to work now but still has problems with the path, I moved the models to ...\ComfyUI\models\ipadapter Comfy doesn´t detect it :(

I had the same problem, but I'm not sure exactly what step I took to solve it. But try to create a new project and see if you can select the model if it is located at a new address. I remember moving the models back and forth a few times, but I was solving a different problem, so I didn't really think about why a model could be selected and not work, or why it wasn't in the list. But for the rest, the models are in the new location and everything works if I create a new project.

**Comment by ElGato2112** [comment]
> > > @ElGato2112 After update, new path to IpAdapter is ...\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus path to IPAdapter models is ...\ComfyUI\models\ipadapter path to Clip vision is ...\ComfyUI\models\clip_vision
> > > Try reinstalling IpAdapter through the Manager if you do not have these folders at the specified paths. I am currently working with IPAdapter and it works great. I had another problem with the IPAdapter, but it was a sampler issue. I described
> > > the solution above.
> > 
> > 
> > Thank You! It seems to work now but still has problems with the path, I moved the models to ...\ComfyUI\models\ipadapter Comfy doesn´t detect it :(
> 
> I had the same problem, but I'm not sure exactly what step I took to solve it. But try to create a new project and see if you can select the model if it is located at a new address. I remember moving the models back and forth a few times, but I was solving a different problem, so I didn't really think about why a model could be selected and not work, or why it wasn't in the list. But for the rest, the models are in the new location and everything works if I create a new project.
> 
> I deleted the old IPAdapter folder, moving the models to the new location first. And then I restarted the server.

I'll try Thank You!

**Comment by elikagan** [comment]
@cubiq i'm having same problem as a lot of other people,
-----
Error occurred when executing IPAdapter:

CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ezXY\autoCastPatch.py", line 299, in map_node_over_list
return _map_node_over_list(obj, input_data_all, func, allow_interrupt)
File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 238, in clip_vision_encode
outputs = clip_vision.model(pixel_values=pixel_values, output_hidden_states=True)
File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 186, in forward
x = self.vision_model(*args, **kwargs)
File "C:\Users\Shadow\Desktop\ComfyUI_new\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
-------
 It's stemming from this workflow: https://github.com/nerdyrodent/AVeryComfyNerd/blob/main/workflows/SD15/Instant_LoRA_1.png

The workflow integrates the old IPAdapter node that got merged with yours I guess? And that seems to be the issue.

My question is really about whether this technique of using 6 images and all the insta lora nodes can work with your updated nodes?

**Comment by cubiq** [comment]
you can do everything you did with the old extension and much more. remove the other extension and use this one (the other extension author and I are working together on this one now)

**Comment by 2blackbar** [comment]
This is still broken! what up devs ? nobody cares ? I did update all in manager just now, still breaks .
I had it working nicelyt like amonth ago, why is it that when you dont do anything in comfy and get back to it after a month - its suddently broken , this is so irritating and happened many times with comfy for me.
`Error occurred when executing IPAdapter:

CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 238, in clip_vision_encode
outputs = clip_vision.model(pixel_values=pixel_values, output_hidden_states=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 186, in forward
x = self.vision_model(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)`

**Comment by cubiq** [comment]
you are using the wrong extension.

**Comment by 2blackbar** [comment]
Well how come the right one became the wrong one suddenly, thanks for the link toe the new one. A simple info within the old one to update would be nice.Or should i fork it myself to put that in.

**Comment by cubiq** [comment]
you are commenting on the right extension to install and you have the wrong one installed.

**Comment by 2blackbar** [comment]
I just downloaded this one in zip and unpacked to cvustom nodes, still broken.
