### ISSUE TITLE
ComfyUI kSampler Does Nothing When using IPAdapter Nodes

### ISSUE THREAD

**Issue by lord-lethris** [cubiq/ComfyUI_IPAdapter_plus#125]
I noted today after a ComfyUI update, that any Workflow that contains the use of an IP Adapter will seem to hang with no errors at the KSample stage.  The system is still responsive so it hasn't hung, it just does nothing, and the queue is still active.

I have tried several kSamplers and I have updated all Nodes.

Working Workflow - Without IPAdapter:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1736720/05a1688c-9199-41eb-9cb6-1be1e6e42c17)

```
got prompt
Requested to load SD1ClipModel
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
100%|██████████████████████████████████████████████████████████████| 15/15 [00:24<00:00,  1.64s/it]
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 28.00 seconds
```

Workflow With IPAdapter - Just sits at KSampler
In fact it sits there and does nothing, no logs, no system activity... nothing  - system still responsive so that hasn't hung:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1736720/c345b0c7-5e18-471b-af6c-9ff0c931760b)

```
got prompt
Requested to load CLIPVisionModelWithProjection
Loading 1 new model
Requested to load SD1ClipModel
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
  0%|                                                                       | 0/15 [00:00<?, ?it/s]
```

**Comment by cubiq** [comment]
1) Are you on AMD?
2) does it work with default nodes? Try with just IPAdapter + default KSampler

**Comment by lord-lethris** [comment]
Bare Bones without IPAdapter.  Working:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1736720/cdab77d0-cd0c-4f3d-9dff-b51c411eb5a0)

Bare Bones with IPAdapter.  Does nothing...:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1736720/e44fa5de-c36a-48dc-8709-5f1e6016e7a8)

Shell log just sits a 0%

`got prompt
Requested to load CLIPVisionModelWithProjection
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
  0%|                                                                       | 0/20 [00:00<?, ?it/s]`

**Comment by cubiq** [comment]
if you are on AMD GPU then it's a duplicate, see here https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/109

Unfortunately it's very likely a driver issue and to find a workaround I would need access (even remotely) to a windows machine with an AMD GPU.
