### ISSUE TITLE
StyleAligned with IP Adapters?

### ISSUE THREAD

**Issue by C00reNUT** [cubiq/ComfyUI_IPAdapter_plus#129]
Maybe add support/combine with https://github.com/brianfitzgerald/style_aligned_comfy

**Comment by cubiq** [comment]
it's interesting but I'm not sure how they could benefit each other?

**Comment by laksjdjf** [comment]
I don't think there are any particularly conflicting parts between `style_align` and `IP-Adapter`, but is there a problem?

**Comment by cubiq** [comment]
there is no conflict but I don't know how they could complement each other. How can we make IPAdapter better by using style align?

**Comment by laksjdjf** [comment]
Would something interesting happen if we applied IP-Adapter only to the first batch referenced by StyleAligned, or vice versa?
 It's just a thought, so I'm not sure what would happen. 😅😅😅

**Comment by cubiq** [comment]
yeah needs a little testing :smiley: 

it's interesting for sure
