### ISSUE TITLE
Error since latest updated of comfyui

### ISSUE THREAD

**Issue by tazmannner** [cubiq/ComfyUI_IPAdapter_plus#131]
Hi I love your node, very cool but since I updated comfyui I have this error when running:
(I have updated comfyui and IPadapter already)

> Error occurred when executing IPAdapter:
> 
> CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'
> 
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
> cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 238, in clip_vision_encode
> outputs = clip_vision.model(pixel_values=pixel_values, output_hidden_states=True)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
> return self._call_impl(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
> return forward_call(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 186, in forward
> x = self.vision_model(*args, **kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\tazmanner\OneDrive\Desktop\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
> return self._call_impl(*args, **kwargs)

**Comment by TheValkyr** [comment]
I'm getting the same error and I updated everything like suggested :/

**Comment by laksjdjf** [comment]
It may be related to https://github.com/comfyanonymous/ComfyUI/commit/174eba8e957b4b885d4d510d53dca859226ba9ef

**Comment by cubiq** [comment]
this was already fixed. OP is using ipadapter_comfyui extension instead of comfyui_ipadapter_plus

**Comment by tazmannner** [comment]
I'm an idiot, lol you're right. I ended up swapping all incorrect parts for ipadapter_plus ones and its now working like it was before.
