### ISSUE TITLE
Compatibility issue when running on fp8 (more specifically, on ComfyUI)

### ISSUE THREAD

**Issue by NoMansPC** [cubiq/ComfyUI_IPAdapter_plus#133]
ComfyUI supports fp8, which I have been using since it saves a lot of VRAM. However, in some instances, like when inpainting with 100% strength or using controlnet (through the Krita plug-in), I get the following error:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
Prompt executed in 4.64 seconds
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 403, in apply_ipadapter
image_prompt_embeds, uncond_image_prompt_embeds = self.ipadapter.get_image_embeds(clip_embed.to(self.device, self.dtype), clip_embed_zeroed.to(self.device, self.dtype))
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 211, in get_image_embeds
image_prompt_embeds = self.image_proj_model(clip_embed)
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 54, in forward
clip_extra_context_tokens = self.proj(embeds).reshape(-1, self.clip_extra_context_tokens, self.cross_attention_dim)
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_cuda" not implemented for 'Float8_e4m3fn'

The guy behind the plug-in asked me to raise the issue here in the hopes that ComfyUI_IPAdapter_plus eventually is adapted to support fp8.

**Comment by cubiq** [comment]
I'll look into it, I hope it's not a problem with the image encoder because in that case there's nothing I can do

**Comment by FNSpd** [comment]
Change self.dtype in line 426 of IPAdapterPlus.py to troch.float16/torch.float32. It's more of a workaround than a proper fix (idk how to make it choose automatically if it should use PF16 or FP32)

**Comment by cubiq** [comment]
yes it should be torch.float32 but I need to make a few other changes

**Comment by cubiq** [comment]
can you try the latest update?

**Comment by NoMansPC** [comment]
> can you try the latest update?

Seems not. Here's the full log with the error:

** ComfyUI startup time: 2023-12-17 12:00:04.698498
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\Scripts\python.exe
** Log path: N:\Stable Diffusion WebUI\Packages\ComfyUI\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages for 'N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux'
 Requirement already satisfied: importlib_metadata in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (6.8.0)
 Requirement already satisfied: zipp>=0.5 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from importlib_metadata) (3.17.0)
 Requirement already satisfied: huggingface_hub in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (0.19.4)
 Requirement already satisfied: filelock in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from huggingface_hub) (3.12.4)
 Requirement already satisfied: fsspec>=2023.5.0 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from huggingface_hub) (2023.9.1)
 Requirement already satisfied: requests in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from huggingface_hub) (2.31.0)
 Requirement already satisfied: tqdm>=4.42.1 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from huggingface_hub) (4.66.1)
 Requirement already satisfied: pyyaml>=5.1 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from huggingface_hub) (6.0.1)
 Requirement already satisfied: typing-extensions>=3.7.4.3 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from huggingface_hub) (4.7.1)
 Requirement already satisfied: packaging>=20.9 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from huggingface_hub) (23.1)
 Requirement already satisfied: colorama in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from tqdm>=4.42.1->huggingface_hub) (0.4.6)
 Requirement already satisfied: charset-normalizer<4,>=2 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from requests->huggingface_hub) (3.2.0)
 Requirement already satisfied: idna<4,>=2.5 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from requests->huggingface_hub) (3.4)
 Requirement already satisfied: urllib3<3,>=1.21.1 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from requests->huggingface_hub) (1.26.18)
 Requirement already satisfied: certifi>=2017.4.17 in n:\stable diffusion webui\packages\comfyui\venv\lib\site-packages (from requests->huggingface_hub) (2023.7.22)
Install: pip packages for 'N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI-Manager'

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   3.7 seconds: N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16296 MB
xformers version: 0.0.22.post4
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Adding extra search path checkpoints N:\Stable Diffusion WebUI\Models\StableDiffusion
Adding extra search path vae N:\Stable Diffusion WebUI\Models\VAE
Adding extra search path loras N:\Stable Diffusion WebUI\Models\Lora
Adding extra search path loras N:\Stable Diffusion WebUI\Models\LyCORIS
Adding extra search path upscale_models N:\Stable Diffusion WebUI\Models\ESRGAN
Adding extra search path upscale_models N:\Stable Diffusion WebUI\Models\RealESRGAN
Adding extra search path upscale_models N:\Stable Diffusion WebUI\Models\SwinIR
Adding extra search path embeddings N:\Stable Diffusion WebUI\Models\TextualInversion
Adding extra search path hypernetworks N:\Stable Diffusion WebUI\Models\Hypernetwork
Adding extra search path controlnet N:\Stable Diffusion WebUI\Models\ControlNet
Adding extra search path clip N:\Stable Diffusion WebUI\Models\CLIP
Adding extra search path diffusers N:\Stable Diffusion WebUI\Models\Diffusers
Adding extra search path gligen N:\Stable Diffusion WebUI\Models\GLIGEN
Adding extra search path vae_approx N:\Stable Diffusion WebUI\Models\ApproxVAE
### Loading: ComfyUI-Manager (V1.14)
### ComfyUI Revision: 1833 [6453dc1c] | Released on '2023-12-16'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[comfyui_controlnet_aux] | INFO -> Using ckpts path: N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:25: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'N:\\Stable Diffusion WebUI\\Packages\\ComfyUI\\custom_nodes\\IPAdapter-ComfyUI\\__init__.py'

Cannot import N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\IPAdapter-ComfyUI module for custom nodes: [Errno 2] No such file or directory: 'N:\\Stable Diffusion WebUI\\Packages\\ComfyUI\\custom_nodes\\IPAdapter-ComfyUI\\__init__.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.4 seconds: N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds: N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type EPS
adm 2816
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
  0%|          | 0/4 [00:00<?, ?it/s]N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torchsde\_brownian\brownian_interval.py:608: UserWarning: Should have tb<=t1 but got tb=14.614644050598145 and t1=14.614643.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
 50%|█████     | 2/4 [00:04<00:03,  1.95s/it]N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torchsde\_brownian\brownian_interval.py:599: UserWarning: Should have ta>=t0 but got ta=0.0291675366461277 and t0=0.029168.
  warnings.warn(f"Should have ta>=t0 but got ta={ta} and t0={self._start}.")
100%|██████████| 4/4 [00:06<00:00,  1.63s/it]
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 31.91 seconds
got prompt
Requested to load CLIPVisionModelProjection
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 464, in apply_ipadapter
    image_prompt_embeds, uncond_image_prompt_embeds = self.ipadapter.get_image_embeds(clip_embed.to(self.device, dtype=self.embeds_dtype), clip_embed_zeroed.to(self.device, dtype=self.embeds_dtype))
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 200, in get_image_embeds
    image_prompt_embeds = self.image_proj_model(clip_embed)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 55, in forward
    clip_extra_context_tokens = self.proj(embeds).reshape(-1, self.clip_extra_context_tokens, self.cross_attention_dim)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_cuda" not implemented for 'Float8_e4m3fn'

**Comment by cubiq** [comment]
should be fixed now

**Comment by NoMansPC** [comment]
> should be fixed now

Sweet! Thanks a lot.
