### ISSUE TITLE
Correct safetensors model links

### ISSUE THREAD

**Issue by McxCZE** [cubiq/ComfyUI_IPAdapter_plus#134]
Hi, awesome work BTW, however what really bugs me off, or what gave me the most headache is to find on the web the correct models. 

Half of the people recompile them, rename them, than I have to manually download each model scattered throughout the internet, trying to figure out and pausing your videos on youtube, what models did you use. 

Because the IPAdapter breaks if I use juggernautXL models with CLIP visions that are not supported, or the output image is for example completely green. 

Also would be it super awesome, if you could post a link to a .safetensors or .bin models And with a little guide which goes where. 

Awesome work, keep it up !

**Comment by cubiq** [comment]
The repository README contains the link to all files you need.

safetensors and bin are the same. You can pick one or the other.

good luck!

**Comment by McxCZE** [comment]
Awesome, I consider it close also, I have bene able to figure it out. For anyone wondering, 

I had issue with a VAE, thats why it did not work, and outputed all orangeish image. 

Also I recommend when downloading the files, rename them after you download them, because they are named generically, and can cause a little confusion.
