### ISSUE TITLE
Please include the raw input images in the repository

### ISSUE THREAD

**Issue by MoezGholami** [cubiq/ComfyUI_IPAdapter_plus#136]
When we are trying to follow your work, one of the problems we have (often with many other Youtubers too) is that we can't just use the workflows out of the box as we miss the input photos. We also don't have an idea on what the resolution of the photos are. When we just use our own photos and can't regenerate the results, we don't know if it is because of us screwing up somewhere or just the bad quality or incompatibility of our photos.

If you just include the initial input photos somewhere, it would drastically reduce our time spent to get the workflows running.

Thanks for the great work by the way.

**Comment by cubiq** [comment]
I'll consider this, thanks for your feedback
