### ISSUE TITLE
Compressing image problems

### ISSUE THREAD

**Issue by FresHHerB** [cubiq/ComfyUI_IPAdapter_plus#139]
I'm having some kind of problem compressing the images, I think I installed all the models and files correctly, but when I try to use Ipadapter Face Swap, I'm having this problem

I've already tested with infinite different images (both formats and sizes) and the error remains the same, I have the same type of distortion in the image result, a bluish/greenish image, with no quality

I already changed the interpolation when preparing the image and nothing happened either

![Captura de tela 2023-12-17 054043](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/a969dbb0-3898-413d-9f13-09e464c2b6df)

**Comment by cubiq** [comment]
wrong VAE for SDXL

PS: it's not a "face swap", only a face model

**Comment by FresHHerB** [comment]
> wrong VAE for SDXL
> 
> PS: it's not a "face swap", only a face model

What would be the correct vae for SDXL? I only found this on hugginface

**Comment by cubiq** [comment]
you need an SDXL VAE, or you could get the one embedded in the model

**Comment by FresHHerB** [comment]
> you need an SDXL VAE, or you could get the one embedded in the model

When I use what's already included in the model, the image is all green

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/ffd11e33-e549-4e73-a2e1-2107b97a596f)

**Comment by cubiq** [comment]
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main/vae

**Comment by FresHHerB** [comment]
> https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main/vae

not the same problem, but similar (I tested the fp16 too and it didn't solve it)

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/8d22fa4e-e4ee-42cd-a3c0-f61bb6b45b90)
