### ISSUE TITLE
cannot import name 'clip_preprocess' from 'comfy.clip_vision'

### ISSUE THREAD

**Issue by ShannieCapri** [cubiq/ComfyUI_IPAdapter_plus#142]
Hello Every Buddies here.

I'm newbie with SD. I'm struggling with IPAdapter Plus recently.

![screenshot_1702886517](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/154218701/1175c2be-9d16-4330-a07b-c740259ea7bc)

My logs:

File "D:\Stable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\[IPAdapterPlus.py](https://ipadapterplus.py/)", line 8, in <module>

from comfy.clip_vision import clip_preprocess

ImportError: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (D:\Stable\ComfyUI_windows_portable\ComfyUI\comfy\clip_vision.py)

I tried a lot, but everything is impossible. I started this problem one week ago.
Could some friend could help me with this, thanks a lot.

**Comment by cubiq** [comment]
you have a very old version of comfyUI, you need to update

**Comment by ShannieCapri** [comment]
yes thanks for your addvice,
but actually, I press update in Comfy Manager thousand times but in vain. 
I tried to run update "update_comfyui" too, but nothing happen.
What should I do next.

**Comment by txirrindulari** [comment]
> yes thanks for your addvice, but actually, I press update in Comfy Manager thousand times but in vain. I tried to run update "update_comfyui" too, but nothing happen. What should I do next.

Maybe you can manually delete comfyui manager from custome_nodes folder. Reinstall it. And try again

**Comment by cubiq** [comment]
on windows there should be 2 manual update .bat scripts. Those should bring your installation up to date

**Comment by ShannieCapri** [comment]
Yes, I would follow your instruction and would tell you after. Thanks a lot

**Comment by ShannieCapri** [comment]
D:\Stable\ComfyUI_windows_portable\update>..\python_embeded\python.exe .\update.py ..\ComfyUI\
stashing current changes
nothing to stash
creating backup branch: backup_branch_2023-12-25_11_09_41
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "D:\Stable\ComfyUI_windows_portable\update\update.py", line 62, in <module>
    pull(repo)
  File "D:\Stable\ComfyUI_windows_portable\update\update.py", line 16, in pull
    repo.checkout_tree(repo.get(remote_master_id))
  File "D:\Stable\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\repository.py", line 459, in checkout_tree
    payload.check_error(err)
  File "D:\Stable\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\callbacks.py", line 98, in check_error
    check_error(error_code)
  File "D:\Stable\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: 2 conflicts prevent checkout

D:\Stable\ComfyUI_windows_portable\update>pause
Press any key to continue . . .

This message shown wwhen I run Update.bat

**Comment by ShannieCapri** [comment]
Yes, I update everything, reinstall comfy UI and it works.
Thanks a lot for helping me
