### ISSUE TITLE
Doesn't start on AMD card using DirectML

### ISSUE THREAD

**Issue by JarekDerp** [cubiq/ComfyUI_IPAdapter_plus#143]
Hi,

I have some problems running it on the AMD card. The whole workflow gets to the KSampler and stops there, no CPU and no GPU being used on 0% completion. No messages in the log, no indication what could be wrong.
Tried on 2 machines with different AMD cards and different ComfyUI installations (not like running from pendrive or something).

When I launched ComfyUI with parameter --cpu instead of --directml then it worked, running on my CPU and taking forever but it worked. So it's not like my workflow is wrong.

Working on CPU:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/54577977/d9f81ea9-3310-4a91-af12-a0e71779196a)

Not working on AMD GPU (left it like this for a couple minutes and nothing):
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/54577977/b004bde4-1439-4115-95d0-d612bc517450)

**Comment by cubiq** [comment]
duplicate https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/109

It's likely a driver issue, there's little I can do without access to a windows machine with AMD.
