### ISSUE TITLE
Hard to replicate: Comfy sometimes doesn't implement changes to the node map

### ISSUE THREAD

**Issue by ttulttul** [cubiq/ComfyUI_IPAdapter_plus#148]
I have found that Comfy sometimes seems to get confused when models are patched with nodes like FreeU_V2 and IPAdapterApply. After running a workflow where, for instance, FreeU_V2 is connected, if I then delete the FreeU_V2 node entirely and run the workflow again, the FreeU_V2 node is still hanging around like a phantom.

It is as if the modified and patched model has become cached in the GPU and is not being replaced on subsequence runs. I haven't been able to reliably replicate this problem, but was wondering if anyone else has seen the same thing happening in workflows. The remedy is to reboot the machine, which clears out the GPU entirely.

**Comment by ttulttul** [comment]
Actually, even rebooting does not seem to fix this problem. Sorry I can't be more specific. I will keep trying to replicate this.

**Comment by cubiq** [comment]
please post your full system info and init comfy message
