### ISSUE TITLE
I would like to ask if the input picture size of CLIP visual model is larger than 224*224？

### ISSUE THREAD

**Issue by xunte** [cubiq/ComfyUI_IPAdapter_plus#149]
I would like to ask if the input picture size of CLIP visual model is larger than 224*224. Because I feel that its attention is too small, when I redraw the video, the background will float, which is very magical

**Comment by cubiq** [comment]
the image is always resized to 224x224, at the moment that is hardcoded into comfy.

I'll explore the possibility of training a bigger model

**Comment by ttulttul** [comment]
Matteo, do you need some money for training?

**Comment by cubiq** [comment]
I need compute powa! :zap:

**Comment by ttulttul** [comment]
I have a budget for that. Let's chat on Element.

**Comment by cubiq** [comment]
sure, I'm `@matt3o` there, or reach me on discord https://latent.vision/discord
