### ISSUE TITLE
I don't understand how to install insightface in a portable comfyui

### ISSUE THREAD

**Issue by aistudentik** [cubiq/ComfyUI_IPAdapter_plus#154]
I'm very sorry, but I can't figure out how to properly install insightface in a portable comfyui (windows)?

**Comment by aistudentik** [comment]
.\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl
.\python_embeded\python.exe -m pip install onnxruntime

**Comment by cqwcqwcqwa** [comment]
It shows that the installation was successful, but-----
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 529, in load_insight_face
    raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')

**Comment by aidifussion** [comment]
thank you solve my problem with phyton 3.12 and insigthface cp312
