### ISSUE TITLE
'ClipVisionModel' object has no attribute 'get'

### ISSUE THREAD

**Issue by captain1023** [cubiq/ComfyUI_IPAdapter_plus#155]
have tried 2 clip model of IP adapter. Both of them have same error. 

full error message below:

Error occurred when executing IPAdapterApply:

'ClipVisionModel' object has no attribute 'get'

File "D:\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 510, in apply_ipadapter
clip_embed = clip_vision.get(tensorToCV(image)) # TODO: support multiple images (is it needed?)
^^^^^^^^^^^^^^^

**Comment by captain1023** [comment]
additional information:

it happened when I running the enhanced workflow and selected 2 faceID model. 

But if select 1 face ID model and 1 other model, it works well.

**Comment by hinablue** [comment]
I also got this error when I used only 1 face ID model.

**Comment by offmybach** [comment]
> have tried 2 clip model of IP adapter. Both of them have same error.
> 
> full error message below:
> 
> Error occurred when executing IPAdapterApply:
> 
> 'ClipVisionModel' object has no attribute 'get'
> 
> File "D:\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 510, in apply_ipadapter clip_embed = clip_vision.get(tensorToCV(image)) # TODO: support multiple images (is it needed?) ^^^^^^^^^^^^^^^

Were you ever able to figure this out? I can't get it to work

**Comment by GoDJr** [comment]
I'm having the same issue using only the faceid model.

**Comment by wangwenqiao666** [comment]
I have the same problem, how to solve this problem.
===================================================================
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 510, in apply_ipadapter
    clip_embed = clip_vision.get(tensorToCV(image)) # TODO: support multiple images (is it needed?)
                 ^^^^^^^^^^^^^^^
AttributeError: 'ClipVisionModel' object has no attribute 'get'
