### ISSUE TITLE
Using face-ID got error 'onnx.onnx_cpp2py_export' is not a package

### ISSUE THREAD

**Issue by ultimatech-cn** [cubiq/ComfyUI_IPAdapter_plus#156]
When I trying new face-id sample got following error

> ERROR:root:Traceback (most recent call last):
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 457, in load_insight_face
>     from insightface.app import FaceAnalysis
>   File "E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\__init__.py", line 16, in <module>
>     from . import model_zoo
>   File "E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
>     from .model_zoo import get_model
>   File "E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
>     from .arcface_onnx import *
>   File "E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
>     import onnx
>   File "E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\__init__.py", line 116, in <module>
>     from onnx import (
>   File "E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\checker.py", line 29, in <module>
>     import onnx.defs
>   File "E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\defs\__init__.py", line 22, in <module>
>     import onnx.onnx_cpp2py_export.defs as C  # noqa: N812
> ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package

Check the package insighface and onnx by pip show
> ...>..\..\python_embeded\python.exe -m pip show insightface
> WARNING: Ignoring invalid distribution -rotobuf (e:\dev\comfyui_windows_portable\python_embeded\lib\site-packages)
> Name: insightface
> Version: 0.7.3
> Summary: InsightFace Python Library
> Home-page: https://github.com/deepinsight/insightface
> Author: InsightFace Contributors
.......

I try to import module in python as below, there is no error.
> E:\DEV\ComfyUI_windows_portable>python_embeded\python.exe
> Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import onnx.onnx_cpp2py_export.defs as C
> >>> from insightface.app import FaceAnalysis

Any workaround for this?

**Comment by Edmaximus** [comment]
I'm facing the same issue with the Load InsightFace node in ComfyUI Portable(Python 3.10. I've already tried all the troubleshooting steps below to no success:
Uninstalled, installed and verified onnx and onnxruntime.
Tested manually importing onnx and onnxruntime by themselves, which worked without issues.
Explicitly imported onnxruntime before insightface in the load_insight_face function
Downgrading onnx a few versions to check if they work.
Made sure there's no conflict between this python environment and my other ones.
Checked the onnx package directory and found the .pyd file corresponding to the onnx_cpp2py_export module.
Fixed a dependency conflicts between protobuf and mediapipe. 

I have Reactor on this same comfyui install and it's using Insightface perfectly fine. Any assistance with this would be appreciated.

**Comment by ultimatech-cn** [comment]
I solved the error by adding
set PYTHONPATH=E:\DEV\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx
By trace sys.path, I found there is no path referring file onnx_cpp2py_export.cp310-win_amd64.pyd. You can also copy the file to some path that python can import.

**Comment by ultimatech-cn** [comment]
I find a strange workaround  for that, but I think it is related to python module importing on Windows.
1. stop comfyUI.
2. changing something in "..\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\defs\__init__.py" to cause error when initialing. 
3. starting comfyui.
4. load the face id sample workflow and prompt, you will find error reporting
5.  changing \python_embeded\Lib\site-packages\onnx\defs\__init__.py file back.
6. prompt the workflow again, it works

There may besome other way to solve the problem.

**Comment by Edmaximus** [comment]
@ultimatech-cn Strange workaround indeed.  Unfortunately, once comfyui is restarted we go back to the same situation. Maybe something is being cached once ONNX is initially loaded and causing a conflict with insightface or the other modules. Once we make the change to __init__.py, the cache is purged. This is all a guess tho since I know next to nothing about the onnx module.

**Comment by ultimatech-cn** [comment]
> @ultimatech-cn Strange workaround indeed. Unfortunately, once comfyui is restarted we go back to the same situation. Maybe something is being cached once ONNX is initially loaded and causing a conflict with insightface or the other modules. Once we make the change to **init**.py, the cache is purged. This is all a guess tho since I know next to nothing about the onnx module.

You are right, it is related to insightface package importing. I have changed the code of IPAdapterPlus.py.  First and # to  line from 457 to 460.  And add   "from insightface.app import FaceAnalysis" to top of the code

>    def load_insight_face(self, provider):
>         # try:
>         #     from insightface.app import FaceAnalysis
>         # except ImportError:
>         #     raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')

**Comment by harelc** [comment]
Had the same problem. If comfyui-reactor-node is loaded as well, the problem persis even when moving the import to the beginning of IPAdapterPlus.py as suggested above. It's some kind of clash between reactor-node's use of onnx/protobuf and IPAdapter-plus's use of it when loading the insightface/buffalo model.

**Comment by Edmaximus** [comment]
I can confirm the issue is indeed caused by a conflict with the comfyui-reactor node.

**Comment by chlowden** [comment]
I am getting the error below ... If the [ReActor Node for ComfyUI](https://github.com/Gourieff/comfyui-reactor-node) node is ENABLED in the ComfyUI Manager. DISABLING the ReActor node in the manager resolves the issue.

`Error occurred when executing InsightFaceLoader:

No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package

  File "/home/admin/ComfyUI/execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/admin/ComfyUI/execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/admin/ComfyUI/execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/admin/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 529, in load_insight_face
    raise Exception(e)`

**Comment by balibell** [comment]
> I am getting the error below ... If the [ReActor Node for ComfyUI](https://github.com/Gourieff/comfyui-reactor-node) node is ENABLED in the ComfyUI Manager. DISABLING the ReActor node in the manager resolves the issue.
> 
> `Error occurred when executing InsightFaceLoader:
> 
> No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package
> 
> File "/home/admin/ComfyUI/execution.py", line 154, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/home/admin/ComfyUI/execution.py", line 84, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/home/admin/ComfyUI/execution.py", line 77, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/home/admin/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 529, in load_insight_face raise Exception(e)`

And also ComfyUI_roop may cause the same problem.

**Comment by zejacky** [comment]
The same "problem" here. I did already reinstall as mentioned. (using python 3.10.10 on Windows)
Reactor works without issues.

As workaround I move the custom node "reactor" out of comfyui, and it works. 
However, I would like to use faceid together with reactor. As many other users too, I guess ;-)

I will try to reinstall comfyui from scratch, and see if it works.

Thank you for a hint.

**Comment by zejacky** [comment]
> The same "problem" here. I did already reinstall as mentioned. (using python 3.10.10 on Windows) Reactor works without issues.
> 
> As workaround I move the custom node "reactor" out of comfyui, and it works. However, I would like to use faceid together with reactor. As many other users too, I guess ;-)
> 
> I will try to reinstall comfyui from scratch, and see if it works.
> 
> Thank you for a hint.

It works for me! Yesterday I reinstalled comfy from scratch (not portable).
After I installed first Reactor, then ipadapter-plus.

Now I just did a Update all inside comfyui manager. Enabled Reactor node again, and no errors anymore,
I tried with SD1.5 and SDXL.

Thanks a lot👍

**Comment by bihailantian655** [comment]
Had the same problem

**Comment by xiaohaihui-smart** [comment]
> I find a strange workaround for that, but I think it is related to python module importing on Windows.
> 
> 1. stop comfyUI.
> 2. changing something in "..\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\defs__init__.py" to cause error when initialing.
> 3. starting comfyui.
> 4. load the face id sample workflow and prompt, you will find error reporting
> 5. changing \python_embeded\Lib\site-packages\onnx\defs__init__.py file back.
> 6. prompt the workflow again, it works
> 
> There may be some other way to solve the problem.

how to chang defs__init_.py file ，i had same problem

**Comment by bihailantian655** [comment]
> > I find a strange workaround for that, but I think it is related to python module importing on Windows.
> > 
> > 1. stop comfyUI.
> > 2. changing something in "..\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\defs__init__.py" to cause error when initialing.
> > 3. starting comfyui.
> > 4. load the face id sample workflow and prompt, you will find error reporting
> > 5. changing \python_embeded\Lib\site-packages\onnx\defs__init__.py file back.
> > 6. prompt the workflow again, it works
> > 
> > There may be some other way to solve the problem.
> 
> how to chang defs__init_.py file ，i had same problem
> 

我觉得他的意思大概是，随便写点什么，让comfui启动报错。

**Comment by bihailantian655** [comment]
> > I find a strange workaround for that, but I think it is related to python module importing on Windows.
> > 
> > 1. stop comfyUI.
> > 2. changing something in "..\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\defs__init__.py" to cause error when initialing.
> > 3. starting comfyui.
> > 4. load the face id sample workflow and prompt, you will find error reporting
> > 5. changing \python_embeded\Lib\site-packages\onnx\defs__init__.py file back.
> > 6. prompt the workflow again, it works
> > 
> > There may be some other way to solve the problem.
> 
> how to chang defs__init_.py file ，i had same problem
> 

我觉得他的意思大概是，随便写点什么，让comfui启动报错。

**Comment by ultimatech-cn** [comment]
> > > I find a strange workaround for that, but I think it is related to python module importing on Windows.
> > > 
> > > 1. stop comfyUI.
> > > 2. changing something in "..\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\defs__init__.py" to cause error when initialing.
> > > 3. starting comfyui.
> > > 4. load the face id sample workflow and prompt, you will find error reporting
> > > 5. changing \python_embeded\Lib\site-packages\onnx\defs__init__.py file back.
> > > 6. prompt the workflow again, it works
> > > 
> > > There may be some other way to solve the problem.
> > 
> > 
> > how to chang defs__init_.py file ，i had same problem
> 
> 我觉得他的意思大概是，随便写点什么，让comfui启动报错。

还可以参考我那个修改代码的方法。
You are right, it is related to insightface package importing. I have changed the code of IPAdapterPlus.py. First and # to line from 457 to 460. And add "from insightface.app import FaceAnalysis" to top of the code

def load_insight_face(self, provider):
# try:
# from insightface.app import FaceAnalysis
# except ImportError:
# raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')

**Comment by zejacky** [comment]
> > The same "problem" here. I did already reinstall as mentioned. (using python 3.10.10 on Windows) Reactor works without issues.
> > As workaround I move the custom node "reactor" out of comfyui, and it works. However, I would like to use faceid together with reactor. As many other users too, I guess ;-)
> > I will try to reinstall comfyui from scratch, and see if it works.
> > Thank you for a hint.
> 
> It works for me! Yesterday I reinstalled comfy from scratch (not portable). After I installed first Reactor, then ipadapter-plus.
> 
> Now I just did a Update all inside comfyui manager. Enabled Reactor node again, and no errors anymore, I tried with SD1.5 and SDXL.
> 
> Thanks a lot👍

What I need to mention. I installed comfyui from scratch using python 3.12 and the nightly version of pytorch.

**Comment by xiaohaihui-smart** [comment]
> 还可以参考我那个修改代码的方法。 You are right, it is related to insightface package importing. I have changed the code of IPAdapterPlus.py. First and # to line from 457 to 460. And add "from insightface.app import FaceAnalysis" to top of the code
> 
> ```
> def load_insight_face(self, provider):
> # try:
> # from insightface.app import FaceAnalysis
> # except ImportError:
> # raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')
> ```
方便提供一下具体代码吗，我把from insightface.app import FaceAnalysis这个加载首行，直接就报错，IPAdapterPlus直接就不可用,非常感谢

**Comment by xiaohaihui-smart** [comment]
> > > I find a strange workaround for that, but I think it is related to python module importing on Windows.
> > > 
> > > 1. stop comfyUI.
> > > 2. changing something in "..\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\defs__init__.py" to cause error when initialing.
> > > 3. starting comfyui.
> > > 4. load the face id sample workflow and prompt, you will find error reporting
> > > 5. changing \python_embeded\Lib\site-packages\onnx\defs__init__.py file back.
> > > 6. prompt the workflow again, it works
> > > 
> > > There may be some other way to solve the problem.
> > 
> > 
> > how to chang defs__init_.py file ，i had same problem
> 
> 我觉得他的意思大概是，随便写点什么，让comfui启动报错。

 你配置的IPAdapterPlus插件是可以工作了吗

**Comment by superfruitymusic** [comment]
> You are right, it is related to insightface package importing. I have changed the code of IPAdapterPlus.py. First and # to line from 457 to 460. And add "from insightface.app import FaceAnalysis" to top of the code
```
def load_insight_face(self, provider):
# try:
# from insightface.app import FaceAnalysis
# except ImportError:
# raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')
```

worked for me as well, thanks 🙏 IP-Adapter && Reactor both work in the same flow with this fix.

For others with same problem: Find this method `def load_insight_face(self, provider):` in ` IPAdapterPlus.py` and add hashtag in front of the lines the first few lines like mentioned above. It might be different lines than 457 to 460, depending on your version

Then change top of the file to be like this:

```
import torch
import contextlib
import os
import math
from insightface.app import FaceAnalysis
```

**Comment by xiaohaihui-smart** [comment]
> > You are right, it is related to insightface package importing. I have changed the code of IPAdapterPlus.py. First and # to line from 457 to 460. And add "from insightface.app import FaceAnalysis" to top of the code
> 
> ```
> def load_insight_face(self, provider):
> # try:
> # from insightface.app import FaceAnalysis
> # except ImportError:
> # raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')
> ```
> 
> worked for me as well, thanks 🙏 IP-Adapter && Reactor both work in the same flow with this fix.
> 
> For others with same problem, trying to clarify what is meant: Find this method `def load_insight_face(self, provider):` in ` IPAdapterPlus.py` and add `#` in front of the first 4 lines, like mentioned above. Note It might not be lines 457 to 460, depending on your version - doesnt matter.
> 
> Then change top of the file to be like this:
> 
> ```
> import torch
> import contextlib
> import os
> import math
> from insightface.app import FaceAnalysis
> ```
> 
> Then restart ComfyUI and error should be gone.
更改了之后还是报一样的错误，是跟系统环境有关系吗，我用的cuda 11.7 torch 2.0.1 windows系统

**Comment by cubiq** [comment]
we already have a thread about insightface

https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162

moving the import position is not a great solution anyway

**Comment by Gourieff** [comment]
Hi @cubiq 
Fixed from my side!
FaceID + ReActor works fine now, without any conflicts!

**Comment by chlowden** [comment]
@Gourieff Thank you so much. This is great news.

**Comment by weisy11** [comment]
> > > > I find a strange workaround for that, but I think it is related to python module importing on Windows.
> > > > 
> > > > 1. stop comfyUI.
> > > > 2. changing something in "..\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\defs__init__.py" to cause error when initialing.
> > > > 3. starting comfyui.
> > > > 4. load the face id sample workflow and prompt, you will find error reporting
> > > > 5. changing \python_embeded\Lib\site-packages\onnx\defs__init__.py file back.
> > > > 6. prompt the workflow again, it works
> > > > 
> > > > There may be some other way to solve the problem.
> > > 
> > > 
> > > how to chang defs__init_.py file ，i had same problem
> > 
> > 
> > 我觉得他的意思大概是，随便写点什么，让comfui启动报错。
> 
> 你配置的IPAdapterPlus插件是可以工作了吗

Add 
`from insightface.app import FaceAnalysis` 
at the top of main.py of ComfyUI will solve the problem. The problem is you should import FaceAnalysis first, then other modules which have conflicts.
