### ISSUE TITLE
Blue image result (face model)

### ISSUE THREAD

**Issue by FresHHerB** [cubiq/ComfyUI_IPAdapter_plus#157]
I'm having this result when trying to use the face model:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/54b8b76a-f89a-4394-8c73-255aec4eebe5)

Here are the parameters and models I am using:

Load IPAdapter Model: https://huggingface.co/h94/IP-Adapter/blob/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors

CLIP Vision: [CLIP-ViT-H-14-laion2B-s32B-b79K](https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors)

Checkpoint: [SDXL 1.0](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0)

Vae: [sd_xl_base_1.0_0.9vae.safetensors](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0_0.9vae.safetensors)

Can someone explain to me what I'm doing wrong?

I was a Stable Diffusion user and recently migrated to ComfyUI, but I believe everything is configured correctly, if anyone can help me with this problem I will be grateful

If someone could make a list of which files I should use on each nodle it would be perfect, completing:

IPAdapter model:
CLIP Vision:
Checkpoint:
VAE:

**Comment by cubiq** [comment]
the image size is wrong, for SDXL should be 1024x1024, apart from that everything else seems fine. maybe try to re-download the models

**Comment by joeduffy52** [comment]
You're using an SDXL checkpoint so you can increase the latent size to 1024x1024. I would also recommend you rename the Clip vision models as recommended by Matteo as both files have the same name. We can't say for sure you're using the correct one as it just says model.safetensors in your node.

**Comment by FresHHerB** [comment]
> You're using an SDXL checkpoint so you can increase the latent size to 1024x1024. I would also recommend you rename the Clip vision models as recommended by Matteo as both files have the same name. We can't say for sure you're using the correct one as it just says model.safetensors in your node.

I put the link to the clip vision that I am using as a hyperlink

**Comment by cubiq** [comment]
it's the right encoder but sometimes the file gets corrupted during the download

**Comment by FresHHerB** [comment]
> it's the right encoder but sometimes the file gets corrupted during the download

Can you provide me with the link to the vision clip and VAE what should I use? (for plus-face_sdxl and sd_xl_base model) ?

**Comment by FresHHerB** [comment]
using sdxl models:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/d4d2bbdd-e416-4663-a9db-ba09da377119)

**Comment by cubiq** [comment]
please post you system info and the comfyui init message

**Comment by joeduffy52** [comment]
I think the VAE you linked to in your first post is wrong. It's 20 times the size of the SDXL VAE I have, that seems wrong? I recreate your workflow and used the exact files you link to and I get the same pink square.

**Comment by joeduffy52** [comment]
Try this one: https://huggingface.co/stabilityai/sdxl-vae/resolve/main/sdxl_vae.safetensors?download=true

**Comment by cubiq** [comment]
closing for lack of updates, feel free to reopen if you still have issues
