### ISSUE TITLE
No module named 'Cython' when installing in ComfyUI

### ISSUE THREAD

**Issue by dionysius** [cubiq/ComfyUI_IPAdapter_plus#158]
Merry Christmas!

After installing this from the comfyui manager, requiring restart, the startup of comfyui reports:
```
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: C:\Users\Dionysius\Scratch\ComfyUI\python_embeded\python.exe -m pip install --upgrade pip

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\Dionysius\\Scratch\\ComfyUI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'insightface']

## Execute install/(de)activation script for '.'
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   × Getting requirements to build wheel did not run successfully.
[!]   │ exit code: 1
[!]   ╰─> [18 lines of output]
[!]       Traceback (most recent call last):
[!]         File "C:\Users\Dionysius\Scratch\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]           main()
[!]         File "C:\Users\Dionysius\Scratch\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]           json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]         File "C:\Users\Dionysius\Scratch\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]           return hook(config_settings)
[!]                  ^^^^^^^^^^^^^^^^^^^^^
[!]         File "C:\Users\Dionysius\Scratch\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
[!]           return self._get_build_requires(config_settings, requirements=['wheel'])
[!]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]         File "C:\Users\Dionysius\Scratch\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
[!]           self.run_setup()
[!]         File "C:\Users\Dionysius\Scratch\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
[!]           exec(code, locals())
[!]         File "<string>", line 11, in <module>
[!]       ModuleNotFoundError: No module named 'Cython'
[!]       [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] × Getting requirements to build wheel did not run successfully.
[!] │ exit code: 1
[!] ╰─> See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
[!]
[!] [notice] A new release of pip is available: 23.3.1 -> 23.3.2
[!] [notice] To update, run: C:\Users\Dionysius\Scratch\ComfyUI\python_embeded\python.exe -m pip install --upgrade pip
install/(de)activation script failed: .

[ComfyUI-Manager] Startup script completed.
#######################################################################
```

Using the workflow: https://f.latent.vision/download/faceid.zip

The nodes seem to have loaded in the UI, but it will get stuck at node `Load Insightface`:
```
Error occurred when executing InsightFaceLoader:

IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.

File "C:\Users\Dionysius\Scratch\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Dionysius\Scratch\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Dionysius\Scratch\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Dionysius\Scratch\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 459, in load_insight_face
raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')
```

Which I assume is correctly failing since installing it above at startup failed

**Comment by Huythuy1** [comment]
i think I have relatively the same problem. Comfy UI show "Insightface is not installed ... " :( 

`ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 457, in load_insight_face
    from insightface.app import FaceAnalysis
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\__init__.py", line 52, in <module>
    from onnx import (
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\checker.py", line 16, in <module>
    import onnx.defs
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\defs\__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C  # noqa: N812
ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 459, in load_insight_face
    raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.')
Exception: IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.`

please help

**Comment by ultimatech-cn** [comment]
> i think I have relatively the same problem. Comfy UI show "Insightface is not installed ... " :(
> 
> > `ERROR:root:!!! Exception during processing !!!
> > ERROR:root:Traceback (most recent call last):
> > File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 457, in load_insight_face
> > from insightface.app import FaceAnalysis
> > File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface__init__.py", line 16, in 
> > from . import model_zoo
> > File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo__init__.py", line 1, in 
> > from .model_zoo import get_model
> > File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in 
> > from .arcface_onnx import *
> > File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in 
> > import onnx
> > File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx__init__.py", line 52, in 
> > from onnx import (
> > File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\checker.py", line 16, in 
> > import onnx.defs
> > File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnx\defs__init__.py", line 7, in 
> > import onnx.onnx_cpp2py_export.defs as C  # noqa: N812
> > ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package
> 
> > During handling of the above exception, another exception occurred:
> 
> > `Traceback` (most recent call last):
> 
> File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 459, in load_insight_face raise Exception('IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.') Exception: IPAdapter: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.`
> 
> i have installed and upgraded onnxruntime and onnxruntime-gpu please help
You can try adding a enviroment var by 
set PYTHONPATH=E:\DEV\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx

**Comment by cubiq** [comment]
try to pip install cython then

**Comment by dionysius** [comment]
I am using the portable variant of comfyui which ships its own python (folder python_embedded) and it is unclear to me what exactly must be met to operate within that python environment (I don't see any venv, etc.). But I'm no python guru so I might miss something.

But at last the source of the issue is insightface itself and not this project - there are plenty of issues there: https://github.com/deepinsight/insightface/issues?q=is%3Aissue+is%3Aopen+cython.
So I'm gonna close the issue here

**Comment by crapthings** [comment]
windows ->

comfy ui portable

```
cd python_embeded
./python.exe -m pip install cython
```
