### ISSUE TITLE
can you add requirements.txt?

### ISSUE THREAD

**Issue by ThisisLandu** [cubiq/ComfyUI_IPAdapter_plus#159]
need to install insightFace manually.
If you put insightface in requirements.txt,
comfyUI automatically installs it.

I think there are a lot of people here who find it difficult to install manually.
Difficult to install manually

thank you

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/36629328/2bfb2242-73d8-4ea6-b060-52e61518bc49)

**Comment by cubiq** [comment]
There are instructions in the documentation. At the moment it has to be installed manually, I'm not sure I want to force insightface installation, some people might not actually needed. I'll think about it. Thanks for your feedback

**Comment by ThisisLandu** [comment]
> There are instructions in the documentation. At the moment it has to be installed manually, I'm not sure I want to force insightface installation, some people might not actually needed it. I'll think about it. Thanks for your feedback

https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/154#issuecomment-1868312552
i tried this,
but it did't work,  this is why i asked you ( successfully installed in console, but above error appears on executing example)
and for many other guys who don't know how to do python well,  it can help them
