### ISSUE TITLE
Can I ask you a question, can the Apply IPAdapter weight be entered into an array, or some other form of multiple variables?

### ISSUE THREAD

**Issue by xunte** [cubiq/ComfyUI_IPAdapter_plus#160]
![screenshot20231224](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/58557441/02041d7b-10f2-4d6f-88eb-ce046bfbab84)

**Comment by cubiq** [comment]
not at this time, you can change the images weight though with the image encode node
