### ISSUE TITLE
Error when executing Ksampler

### ISSUE THREAD

**Issue by TopGremlin** [cubiq/ComfyUI_IPAdapter_plus#166]
im unsure what the problem is but i tried to replicate what was done in the example given
![Screenshot (32)](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/145896329/5199491b-568f-4abb-9538-7e335498e2a3)
![Screenshot (33)](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/145896329/2745394e-c951-4a3c-81b4-30bf1048aeaa)

**Comment by cubiq** [comment]
do you have a 10xx GPU? use --force-fp16

**Comment by TopGremlin** [comment]
how do i do that?

**Comment by TopGremlin** [comment]
i turned run_nvidia_gpu.bat into run_nvidia_gpu.txt and i put --force-fp16 in the first line, turned it back into bat, ran it and it worked fine
