### ISSUE TITLE
Bad results using FaceID IPA Model

### ISSUE THREAD

**Issue by FresHHerB** [cubiq/ComfyUI_IPAdapter_plus#168]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/50578875-4514-4f28-a4d7-5f532b1c52c7)

Can anyone tell me why I have such bad results using FaceID IPA Model?

When I use the full face I have satisfactory results (although it is a little far from the input face)

However, when I use FaceID (which I believe should be more accurate) I am trying to get a result very far from the input face

I have an RTX 3060Ti and Ryzen 5 5600

this is the image I'm using:

![ComfyUI_00874_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/eaa9acfc-cba4-43c9-b82a-289992558ad5)

**Comment by FresHHerB** [comment]
using this model: https://civitai.com/models/57319/a-zovya-photoreal

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/4bdd6ab3-c94d-4f56-94ae-0ab047549dd6)


The FaceID Model is always the furthest result from expected

**Comment by cubiq** [comment]
check the enhanced workflow, FaceID needs to be augmented by either plus face or full face

**Comment by FresHHerB** [comment]
> check the enhanced workflow, FaceID needs to be augmented by either plus face or full face

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22122291/b036cf13-c11e-4212-8a78-ecc6a0421588)

really thanks, thats work now, last quesiton, although the result is quite satisfactory, following the tutorial video on YouTube, it seems to me that the results obtained in the video are much more similar to the input image, is there any additional configuration I can do to make the model even more similar?

Thank you very much for all the support and congratulations on the incredible work!

**Comment by cubiq** [comment]
try with different checkpoints, also don't cut the head too close to the face. As enhancer try both plus face and full face, sometimes one is better than the other. Play with the weight of each ipadapter and the lora.

Ultimately is still not perfect especially with anything that is not a pretty girl.

**Comment by FresHHerB** [comment]
> try with different checkpoints, also don't cut the head too close to the face. As enhancer try both plus face and full face, sometimes one is better than the other. Play with the weight of each ipadapter and the lora.
> 
> Ultimately is still not perfect especially with anything that is not a pretty girl.

Do you have any preferred checkpoints to recommend for more realistic photos? no cartoon look

**Comment by cubiq** [comment]
try lifelike diffusion for "ethnicity", ICBINP does good portraits, realistic vision sometimes works well
