### ISSUE TITLE
module 'cv2.gapi.wip.draw' has no attribute 'Text'

### ISSUE THREAD

**Issue by dongboka** [cubiq/ComfyUI_IPAdapter_plus#170]
Hello! I am getting this error whenever I try to use Load InsightFace node;

> Error occurred when executing InsightFaceLoader:
> 
> module 'cv2.gapi.wip.draw' has no attribute 'Text'
> 
> File "C:\GitHub\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\GitHub\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\GitHub\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\GitHub\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main\IPAdapterPlus.py", line 457, in load_insight_face
> from insightface.app import FaceAnalysis
> File "C:\GitHub\ComfyUI\ComfyUI\custom_nodes\insightface\app\__init__.py", line 1, in
> from .face_analysis import *
> File "C:\GitHub\ComfyUI\ComfyUI\custom_nodes\insightface\app\face_analysis.py", line 17, in
from ..model_zoo import model_zoo
> File "C:\GitHub\ComfyUI\ComfyUI\custom_nodes\insightface\model_zoo\__init__.py", line 1, in
from .model_zoo import get_model
> File "C:\GitHub\ComfyUI\ComfyUI\custom_nodes\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
> File "C:\GitHub\ComfyUI\ComfyUI\custom_nodes\insightface\model_zoo\arcface_onnx.py", line 9, in
> import cv2
> File "C:\GitHub\ComfyUI\python_embeded\Lib\site-packages\cv2\__init__.py", line 181, in
bootstrap()
> File "C:\GitHub\ComfyUI\python_embeded\Lib\site-packages\cv2\__init__.py", line 175, in bootstrap
> if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\GitHub\ComfyUI\python_embeded\Lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
py_module = importlib.import_module(module_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "importlib\__init__.py", line 126, in import_module
File "C:\GitHub\ComfyUI\python_embeded\Lib\site-packages\cv2\typing\__init__.py", line 157, in
Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
^^^^^^^^^^^^^^^^^^^^^^
> 

I've tried few methods I could find online such as

`pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless`
`pip install opencv-python==4.7.0.72`

and running the "update_comfyui_and_python_dependencies.bat". 

Whenever I do uninstall/reinstall the opencv-python to an older version, it throws 
"IPAdapter: Insightface not installed" error. 
If I reinstall insightface, it goes right back to the first mentioned error, and I am stumped.

Any help would be appreciated, thanks!

**Comment by cubiq** [comment]
I honestly have no clue. Refer to this https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162 for installation instructions of insightface
