### ISSUE TITLE
Working with 3D illustration models

### ISSUE THREAD

**Issue by ParthGandhi** [cubiq/ComfyUI_IPAdapter_plus#171]
I can't seem to get the face-swap to work particularly well with 3d animations using the https://civitai.com/models/75650/disney-pixar-cartoon-type-b model. All the images tend to be a bit wider and not _quite_ correct. 

Any suggestions? I've also tried the new faceId.

**Comment by cubiq** [comment]
you'd probably need to train IPAdapter for that specific style I'm guessing. I noticed that ipadapter doesn't work very well with over trained models

**Comment by ParthGandhi** [comment]
Thats what i'd thought as well. Was checking in case i'd missed something.

Any resources to training ipadapter?

**Comment by cubiq** [comment]
example training script

https://github.com/tencent-ailab/IP-Adapter/blob/main/tutorial_train_plus.py
