### ISSUE TITLE
When will the new ipadapter-faceid-plus be supported?

### ISSUE THREAD

**Issue by ultimatech-cn** [cubiq/ComfyUI_IPAdapter_plus#172]

**Comment by Winnougan** [comment]
Yep, just saw it 46 mins ago was uploaded on Huggingface

**Comment by cubiq** [comment]
guys give me a break :smile:

**Comment by Winnougan** [comment]
> guys give me a break 😄

Enjoy your holidays, Matteo! Lol, the advances in AI won't sleep.

**Comment by Winnougan** [comment]
> _No description provided._

Here you go, just load the new Face ID Plus and the new LORA.
https://huggingface.co/h94/IP-Adapter-FaceID/tree/main

**Comment by cubiq** [comment]
it won't work, I'll post an update later today to use the new model

**Comment by cubiq** [comment]
It's done, I'll push the code tomorrow. You can check preliminary results here

https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/145#issuecomment-1870527894
