### ISSUE TITLE
im getting (RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument tensors in method wrapper_CUDA_cat))

### ISSUE THREAD

**Issue by abuyazid955** [cubiq/ComfyUI_IPAdapter_plus#175]
After generating some images using ipadapter plus face on SDXL, im getting this error
This error occurs when i change the weight on the IPAdapter after generating some images.

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 521, in apply_ipadapter
    clip_embed = clip_vision.encode_image(image)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\clip_vision.py", line 50, in encode_image
    out = self.model(pixel_values=pixel_values, intermediate_output=-2)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 186, in forward
    x = self.vision_model(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 172, in forward
    x = self.embeddings(pixel_values)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\clip_model.py", line 154, in forward
    return torch.cat([self.class_embedding.expand(pixel_values.shape[0], 1, -1), embeds], dim=1) + self.position_embedding.weight
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument tensors in method wrapper_CUDA_cat)
```

*Using efficient nodes.

and if using NOT using efficient nodes, the images output is blank.

to fix this, i change to --lowvram and it is fixed.
before update, --normalvram is work like a charm, and now getting this error and bugs.

**Comment by cubiq** [comment]
update comfyui, it should be fixed

**Comment by abuyazid955** [comment]
> update comfyui, it should be fixed

Hello, Thank you for your fast response!

However, I have already updated the ComfyUI and then turn back my --normalvram.
and then, i generate an images at first and the output came out like this. 

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/896019f7-2024-49b9-8af9-7a40e47bda82)

I have also attached the screenshot of my workflow.
I think updating the comfyUI still not fixed this issues.

Thanks.

**Comment by abuyazid955** [comment]
> update comfyui, it should be fixed

Hello, Thank you for your fast response!

However, I have already updated the ComfyUI and then turn back my --normalvram.
and then, i generate an images at first and the output came out like this.

![WhatsApp Image 2023-12-28 at 05 15 04_af92837b](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/afb9a947-6f75-419d-8e60-697434a07eb1)

I have also attached the screenshot of my workflow.
I think updating the comfyUI still not fixed this issues.

Thanks.

**Comment by cubiq** [comment]
the original issue was resolved few minutes after your initial report. It was a small bug in the comfyui clipvision.

do you get the same result using other image encoders like revision?

Also post your comfy init message

**Comment by abuyazid955** [comment]
Hi, thanks again for your response. I have retry to generate an images with SDXL using --normalvram.

There is no error, however the output is still weird. 
Also i have a question. where i can get the other image encoderrs like revision? i would like to try using that.

Here is the screenshot and there is no error in the comfy init message 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/60ca039c-2c03-4ad3-9531-89dc43507b72)

**Comment by cubiq** [comment]
can you try without xformers?

**Comment by abuyazid955** [comment]
> can you try without xformers?

how to disable the xformers?

**Comment by abuyazid955** [comment]
> can you try without xformers?

Hi, i have tried to disable xformers, however there is another error occured.

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/e5218be6-ff8e-4e10-af92-885b2a8b1de2)

**Comment by cubiq** [comment]
you are probably using the wrong encoder

**Comment by abuyazid955** [comment]
> you are probably using the wrong encoder

Hi, i'm not sure if i'm using the wrong encoder. However as i mentioned before, it will work when i'm not disable the xformers and not using --normalvram. 

but before updating ipadapter everything is normal, i can use --normalvram too.

**Comment by abuyazid955** [comment]
> you are probably using the wrong encoder

Hi, yes sorry i was forget to change the encoder. 
So after trying to disable the xformers. There is nothing change at all. The output is still weird. 

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/144f439b-4145-4d46-abab-0b005c20b8b8)

**Comment by abuyazid955** [comment]
I think it's comfyui issues. I tried not using ipadapter nodes and the output is still the same

![Uploading image.png…]()

**Comment by cubiq** [comment]
try to open an issue on comfyui github
