### ISSUE TITLE
AttributeError: 'ClipVisionModel' object has no attribute 'get'

### ISSUE THREAD

**Issue by xeruthos** [cubiq/ComfyUI_IPAdapter_plus#176]
Hi, i have tried updating ComfyUI, install insightface with a custom .whl-file and many other things. I still get this error no matter what.

ERROR:root:Traceback (most recent call last):
  File "C:\Users\xery555\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xery555\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xery555\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xery555\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 510, in apply_ipadapter
    clip_embed = clip_vision.get(tensorToCV(image)) # TODO: support multiple images (is it needed?)
                 ^^^^^^^^^^^^^^^
AttributeError: 'ClipVisionModel' object has no attribute 'get'

**Comment by JPW0080** [comment]
If attempting to use faceid model, swap CLIPVidsionLoader node for the InsightFaceLoader node.

**Comment by nyukers** [comment]
> If attempting to use faceid model, swap CLIPVisionLoader node for the InsightFaceLoader node.

And you will get another error: InsightFace is not installed! Install the missing dependencies if you wish to use FaceID models.)

**Comment by cubiq** [comment]
closing for lack of updates, feel free to reopen if you still have issues
