### ISSUE TITLE
Support for IP-Adapter-FaceID-Plus

### ISSUE THREAD

**Issue by h3clikejava** [cubiq/ComfyUI_IPAdapter_plus#178]
One gets the following error when using with the current nodes:

Error occurred when executing IPAdapterApply:

```
Error(s) in loading state_dict for MLPProjModelFaceId:
Unexpected key(s) in state_dict: "perceiver_resampler.proj_in.weight", "perceiver_resampler.proj_in.bias", "perceiver_resampler.proj_out.weight", "perceiver_resampler.proj_out.bias", "perceiver_resampler.norm_out.weight", "perceiver_resampler.norm_out.bias", "perceiver_resampler.layers.0.0.norm1.weight", "perceiver_resampler.layers.0.0.norm1.bias", "perceiver_resampler.layers.0.0.norm2.weight", "perceiver_resampler.layers.0.0.norm2.bias", "perceiver_resampler.layers.0.0.to_q.weight", "perceiver_resampler.layers.0.0.to_kv.weight", "perceiver_resampler.layers.0.0.to_out.weight", "perceiver_resampler.layers.0.1.0.weight", "perceiver_resampler.layers.0.1.0.bias", "perceiver_resampler.layers.0.1.1.weight", "perceiver_resampler.layers.0.1.3.weight", "perceiver_resampler.layers.1.0.norm1.weight", "perceiver_resampler.layers.1.0.norm1.bias", "perceiver_resampler.layers.1.0.norm2.weight", "perceiver_resampler.layers.1.0.norm2.bias", "perceiver_resampler.layers.1.0.to_q.weight", "perceiver_resampler.layers.1.0.to_kv.weight", "perceiver_resampler.layers.1.0.to_out.weight", "perceiver_resampler.layers.1.1.0.weight", "perceiver_resampler.layers.1.1.0.bias", "perceiver_resampler.layers.1.1.1.weight", "perceiver_resampler.layers.1.1.3.weight", "perceiver_resampler.layers.2.0.norm1.weight", "perceiver_resampler.layers.2.0.norm1.bias", "perceiver_resampler.layers.2.0.norm2.weight", "perceiver_resampler.layers.2.0.norm2.bias", "perceiver_resampler.layers.2.0.to_q.weight", "perceiver_resampler.layers.2.0.to_kv.weight", "perceiver_resampler.layers.2.0.to_out.weight", "perceiver_resampler.layers.2.1.0.weight", "perceiver_resampler.layers.2.1.0.bias", "perceiver_resampler.layers.2.1.1.weight", "perceiver_resampler.layers.2.1.3.weight", "perceiver_resampler.layers.3.0.norm1.weight", "perceiver_resampler.layers.3.0.norm1.bias", "perceiver_resampler.layers.3.0.norm2.weight", "perceiver_resampler.layers.3.0.norm2.bias", "perceiver_resampler.layers.3.0.to_q.weight", "perceiver_resampler.layers.3.0.to_kv.weight", "perceiver_resampler.layers.3.0.to_out.weight", "perceiver_resampler.layers.3.1.0.weight", "perceiver_resampler.layers.3.1.0.bias", "perceiver_resampler.layers.3.1.1.weight", "perceiver_resampler.layers.3.1.3.weight".

File "/home/timehut/Documents/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/timehut/Documents/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/timehut/Documents/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/timehut/Documents/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 539, in apply_ipadapter
self.ipadapter = IPAdapter(
File "/home/timehut/Documents/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 213, in __init__
self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
File "/home/timehut/miniconda3/envs/mmdet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

```

New Model here: https://huggingface.co/h94/IP-Adapter-FaceID

**Comment by cubiq** [comment]
Also adding support for multiple images to FaceID :smile: 

![EjCYJJGCbeLRPFkmrSmepZrV](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/1eb95a0f-37eb-42f2-a237-6bbdd352eb46)
![sHiJcKRvlCNtKxOzCHwGNFTv](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/cc2a2ea8-ac5f-428c-a93a-086cd59a829a)

**Comment by cubiq** [comment]
I think Tencent lab should sponsor me :stuck_out_tongue:

**Comment by cubiq** [comment]
FaceID Plus is now supported.

**Important:** this update breaks the previous implementation of FaceID. Check the updated workflows in the example directory!

**Comment by xiaohu2015** [comment]
add v2 preview at https://huggingface.co/h94/IP-Adapter-FaceID

**Comment by cubiq** [comment]
damn guys, you never rest :smile:

**Comment by Arron17** [comment]
> Also adding support for multiple images to FaceID 😄
> 
> ![EjCYJJGCbeLRPFkmrSmepZrV](https://private-user-images.githubusercontent.com/427614/293197629-1eb95a0f-37eb-42f2-a237-6bbdd352eb46.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODA5ODEsIm5iZiI6MTcwMzc4MDY4MSwicGF0aCI6Ii80Mjc2MTQvMjkzMTk3NjI5LTFlYjk1YTBmLTM3ZWItNDJmMi1hMjM3LTZiYmRkMzUyZWI0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxNjI0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGY2YzE1NmIzYzQzMWUxYTI0NjliM2I2NGUzYmQyMWMxZDc5MDg5MmZhMGE4ZmQ2ZWUxY2IwMTI2Njg0MTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hMf5njSkZYJDC9_k3LHqVOqY-CN-qeEsnEXpskyeIg8) ![sHiJcKRvlCNtKxOzCHwGNFTv](https://private-user-images.githubusercontent.com/427614/293197632-cc2a2ea8-ac5f-428c-a93a-086cd59a829a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3ODA5ODEsIm5iZiI6MTcwMzc4MDY4MSwicGF0aCI6Ii80Mjc2MTQvMjkzMTk3NjMyLWNjMmEyZWE4LWFjNWYtNDI4Yy1hOTNhLTA4NmNkNTlhODI5YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxNjI0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGNlYThiYzJkM2JlZmNlMGRhMTBhNmQ3ZmE1YTVmN2ZjOTcyNWU3ODhhZDYxNmQ1NTViNTI1MjE0YzJlY2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kd1RJ-0gkI2wLSyiRDH-EoTOzt65_kQTXC370HFTbCw)

How do you do this? Do you have to chain multiple Apply IPAdapter Nodes together, one with each image? As there isn't an Insightface input on the "Apply IPAdapter from Encoded" node, which I'd normally use to pass multiple images through an IPAdapter.

**Comment by cubiq** [comment]
you just send an image batch

**Comment by emptybamboo** [comment]
You are such a great developer, it is great to let people experience the latest features first, every comfyui user must love you so much!!😘

**Comment by emptybamboo** [comment]
> FaceID Plus is now supported.现在支持 FaceID Plus。
> 
> **Important:** this update breaks the previous implementation of FaceID. Check the updated workflows in the example directory!重要提示：此更新中断了之前的 FaceID 实现。检查示例目录中更新的工作流程！

You are such a great developer, it is great to let people experience the latest features first, every comfyui user must love you so much!!😘

**Comment by Arron17** [comment]
> you just send an image batch

Ah ok thank you, I was over complicating it.

**Comment by ultimatech-cn** [comment]
Great work！！

**Comment by xiaohu2015** [comment]
> you just send an image batch

IP-Adapter-FaceID-Plusv2 is released, see https://huggingface.co/h94/IP-Adapter-FaceID

**Comment by cubiq** [comment]
as far as I can tell the code for faceid plus should work for faceid plus v2 as well with the only difference that the weight is always 1.

what's the difference in the training, because the weight could be applied to v1 as well.

v1 seems to perform better than v2 honestly

**Comment by jepjoo** [comment]
Yes, V2 output seems pretty poor. So poor in fact, that I was wondering whether it's working correctly.

**Comment by xiaohu2015** [comment]
> Yes, V2 output seems pretty poor. So poor in fact, that I was wondering whether it's working correctly.

can you give some examples？

in fact,  the result should be better in terms of id cos Similarity

**Comment by xiaohu2015** [comment]
> as far as I can tell the code for faceid plus should work for faceid plus v2 as well with the only difference that the weight is always 1.
> 
> what's the difference in the training, because the weight could be applied to v1 as well.
> 
> v1 seems to perform better than v2 honestly

they are training differently, it has a shortcut compared to v1

**Comment by Arron17** [comment]
@xiaohu2015 I tend to agree with @jepjoo about it being worse under V2 than V1, It's possible it's to do with the new weighing on V2.

Here is an example, all done with the same settings, only change is using the V1 IPAdapter + LoRA vs the V2 IPAdapter + LoRA:
Input Image:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/87210034/b9fa1782-2779-4ec0-9fa2-000d50247b69)


V1 Results:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/87210034/976575a5-29ce-45d4-a3b2-3756d40a4521)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/87210034/eef92ca5-65bb-45ce-9ea7-f9ce29b488b4)

V2 Results:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/87210034/59e70894-49f1-4516-970b-4d1db22bb68a)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/87210034/e8b4c0f5-7540-49aa-820e-eaf075676330)


It feels like to me on V2 it's taking the position of the image more, but it is a lot worse at getting the face.

**Comment by xiaohu2015** [comment]
@Arron17 You tested with comfyui?

**Comment by Arron17** [comment]
> @Arron17 You tested with comfyui? Currently comfyui seems not support v2

Yes, it was a demonstration of it not working correctly currently in ComfyUI.

**Comment by cubiq** [comment]
v1 vs v2

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/8b8670d0-6982-4411-8519-e6814d650198)

will v1 still be developed/used? Because there's no way for me to identify the two (the keys seem identical, maybe you can add an identifying key somewhere?)... Basically I would need to make a new node just for v2 or add a "shortcut" option (and people will forget to enable it and get bad results)

**Comment by xiaohu2015** [comment]
v2 and v1 use same parameters (but train differently), but the forward is a little different. i am not sure which one is best for users, although i think v2 is better (more consistency and freedom). Hence i wish to keep both (a new node is good) to let users choose the best one.

**Comment by cubiq** [comment]
Preliminary tests

![v2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/6ea9a532-f735-4bb8-b1a6-32d8779bccaf)

**Comment by xiaohu2015** [comment]
@cubiq thanks a lot, in fact, i think v2 and v1 are similar, but v2 can adjust the weight.

**Comment by cubiq** [comment]
I'll do more comprehensive testing also comparing v1+plus-face to v2. Now I have to update the documentation and the workflows (again :smile: ) and I'll push the code

**Comment by Arron17** [comment]
Just tried out the V2 model on the new update, it's looking very good now. Seems to get the likeness better and is also a lot more flexible than V1. For example changing hair colour or style was very difficult on V1, on V2 it works just fine. Thanks for the update.

**Comment by cubiq** [comment]
v2 at Different weights

![v2_weights](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/cfcb1a99-4165-43bc-9e1c-590c2becf6e3)

**Comment by ultimatech-cn** [comment]
> v2 at Different weights
> 
> ![v2_weights](https://private-user-images.githubusercontent.com/427614/293478608-cfcb1a99-4165-43bc-9e1c-590c2becf6e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDIyMTUsIm5iZiI6MTcwNDAwMTkxNSwicGF0aCI6Ii80Mjc2MTQvMjkzNDc4NjA4LWNmY2IxYTk5LTQxNjUtNDNiYy05ZTFjLTU5MGMyYmVjZjZlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMVQwNTUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGM0MTNlNTY3NTgwYjAwMjNlZjY0OTEzYmY3NGYxY2Y0OTkzNWFlZjZhOGViMTkxZTc0NWU0YWI3YmI4ZjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QicRTcP_lBDGS5e27QLto07KUluOZ4HQZtk898MzjuU)

Have you tried higher weight? Is v2 only for weight control? There is no better face quality in V2.

**Comment by ultimatech-cn** [comment]
> Just tried out the V2 model on the new update, it's looking very good now. Seems to get the likeness better and is also a lot more flexible than V1. For example changing hair colour or style was very difficult on V1, on V2 it works just fine. Thanks for the update.

Really?
It is most appreciated if you provide some examples.

**Comment by JorgeR81** [comment]
Here is my test of the 4 new workflows, with the original settings. 
I still prever Plus V1, but V2 is a nice alternative. 
The V2 seems to be closer to the enhanced workflow, but perhaps with slightly better quality.
I wonder if it would be possible to "merge" the V1 and V2 models ( as we do with checkpoints ).

![test10](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/72734038/8beddb65-2a03-4968-ab2a-106dfd15c927)

**Comment by JorgeR81** [comment]
Here is a comparison with the ReActor node
The source image is the same one as above.
The input images are  from the V2 workflow ( one of them with IPA disabled ). 

With the ReActor node alone, we lose the facial expression and the hair from the original source image.
I also tried using the ReActor node after IPA V2, but I think it just makes the image worse. 
I find the Reactor node images a bit softer, and the facial features a bit more generic.

![teactr10](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/72734038/aed62adb-f134-4b6a-9597-422923d2b1e4)

**Comment by JorgeR81** [comment]
Here is the V2 workflow, with different weights, for seeds "1" and "2".

At a lower weight of about 0.6, the images start to get a bit softer and with more generic facial features, like the ReActor node images, but here we still keep the hair and facial expression from the original image.

![teactrw110](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/72734038/21830ed8-3fea-4dbf-99a8-43dd4afa2d8d)

**Comment by cubiq** [comment]
This workflow compares all face models (well not all the combinations... but a good portion of them)

![comparison](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/9668184e-d928-4800-884d-a7a2268ca6d7)

[face_models_comparison.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13801810/face_models_comparison.json)

**Comment by xiaohu2015** [comment]
v2 weight can be 2.0

**Comment by cubiq** [comment]
the value can go form -1.0 to 3.0 :smile:

**Comment by ultimatech-cn** [comment]
My test result as below
![1704178900492](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/142652112/5c1025c1-aae8-4b89-9ca3-4916b95d2433)

**Comment by xiaohu2015** [comment]
> My test result as below ![1704178900492](https://private-user-images.githubusercontent.com/142652112/293640698-5c1025c1-aae8-4b89-9ca3-4916b95d2433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODIyMzMsIm5iZiI6MTcwNDE4MTkzMywicGF0aCI6Ii8xNDI2NTIxMTIvMjkzNjQwNjk4LTVjMTAyNWMxLWFhZTgtNGI4OS05Y2EzLTQ5MTZiOTVkMjQzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwNzUyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDRiZDM2NGUzMTg4YjFmYmZjYzZhYTMwMmM3NjNlYjNjOTVjNzQ3YTgxZTAxYjY0ZDQ4ZjU5M2I1YTRiZDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2YtpbWYnVQPIfFwac1_E_6xxHHp9oaNAPC-NeOVfKy4)

do you use face++ API to compute the ID consistency?

**Comment by cubiq** [comment]
I'll run a mega comparison with some face descriptor later today :smile: have you done it already @xiaohu2015 ?

**Comment by xiaohu2015** [comment]
> I'll run a mega comparison with some face descriptor later today 😄 have you done it already @xiaohu2015 ?

yes. Before releasing each model, I evaluate the consistency of the generation (Currently, I use a face recognition model from insightface to calculate cosine similarity)

**Comment by xiaohu2015** [comment]
@cubiq maybe next day I will open FaceID v2 model  (no LoRA, but performs much better)

**Comment by ultimatech-cn** [comment]
> > My test result as below ![1704178900492](https://private-user-images.githubusercontent.com/142652112/293640698-5c1025c1-aae8-4b89-9ca3-4916b95d2433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODIyMzMsIm5iZiI6MTcwNDE4MTkzMywicGF0aCI6Ii8xNDI2NTIxMTIvMjkzNjQwNjk4LTVjMTAyNWMxLWFhZTgtNGI4OS05Y2EzLTQ5MTZiOTVkMjQzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwNzUyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDRiZDM2NGUzMTg4YjFmYmZjYzZhYTMwMmM3NjNlYjNjOTVjNzQ3YTgxZTAxYjY0ZDQ4ZjU5M2I1YTRiZDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2YtpbWYnVQPIfFwac1_E_6xxHHp9oaNAPC-NeOVfKy4)
> 
> do you use face++ API to compute the ID consistency?

yes, Face++ API，

**Comment by ultimatech-cn** [comment]
Test result of lora strength，faceid plus v2
![2aa2034fad822067f06cc80a9b32a84](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/142652112/7165c16b-76ae-481d-9df8-59c8a1545c13)

**Comment by ultimatech-cn** [comment]
Testing result of weight_v2,  
![1704212149905](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/142652112/35166e8f-6f38-4107-aa8c-79c7f9889b0a)

**Comment by cubiq** [comment]
I finally made a script to automatically compare all the models and get a numeric approximation, I'm generating all the images with many checkpoints. I'll post the results soon
