### ISSUE TITLE
The current IP adapter node takes a long time, 4-5 seconds

### ISSUE THREAD

**Issue by xiaocaijiayou** [cubiq/ComfyUI_IPAdapter_plus#179]
The current IP adapter node  takes a long time, for my case 4-5 seconds. This is independent with the model loading process. 

Does it make sense? The ip adapter part should be not heavy, right?

<img width="357" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/5426787/0f6c93e7-6a13-42d3-8fb0-86eab1588a2c">

**Comment by xiaocaijiayou** [comment]
I am using SDXL, face IP adapter, on V100

**Comment by cubiq** [comment]
it should take a lot of time only is you encode like 200 images at a time. Can you show me the full workflow?

**Comment by xiaocaijiayou** [comment]
> it should take a lot of time only is you encode like 200 images at a time. Can you show me the full workflow?

[workflow_api.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13784750/workflow_api.json)
Here is my workflow. Thank you!

**Comment by cubiq** [comment]
there's no reason for it to be slow, something else is going on in your system. I'm sorry I can't say what. Maybe post your comfyui init text

**Comment by xiaocaijiayou** [comment]
Total VRAM 81251 MB, total RAM 2063598 MB                                                                                                                     
Set vram state to: NORMAL_VRAM                                                                                                                                
Device: cuda:0 NVIDIA A100-SXM4-80GB : cudaMallocAsync                                                                                                        
VAE dtype: torch.bfloat16                                                                                                                                     
Using pytorch cross attention                                                                                                                                                                                                                                                
                                                                                                                                                              
Import times for custom nodes:
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /root/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus

Starting server

To see the GUI go to: http://0.0.0.0:9099
got prompt/root/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use ten
sor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Requested to load CLIPVisionModelProjection
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.50it/s]
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 83.75 seconds
got prompt
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.85it/s]
Prompt executed in 11.61 seconds

**Comment by cubiq** [comment]
I don't see anything weird. How long does it take bypassing IPAdapter?

**Comment by xiaocaijiayou** [comment]
> I don't see anything weird. How long does it take bypassing IPAdapter?

For Apply IPAdapter node, almost 4s. How long should it take?

**Comment by cubiq** [comment]
once all models are loaded the generation takes 11 seconds, right?

the same workflow how long does it take without IPAdapter?

you have 81251 VRam, an SDXL model might take 6GB + the image encoder + IPAdapter model, it is possible the Comfy needs to unload something from the VRAM and reload it at each generation

**Comment by xiaocaijiayou** [comment]
> once all models are loaded the generation takes 11 seconds, right?
> 
> the same workflow how long does it take without IPAdapter?
> 
> you have 81251 VRam, an SDXL model might take 6GB + the image encoder + IPAdapter model, it is possible the Comfy needs to unload something from the VRAM and reload it at each generation

Without IPAdapter, it takes around 5 seconds. 
Maybe that's the reason, every time it says requested to load SDXL.
<img width="1126" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/5426787/6be5d587-bf00-4ce5-8518-2252552843df">

**Comment by cubiq** [comment]
yes it is reloading the SDXL model each time. You may try by saving the embeds with the save embeds node. that will space you 1.4gb of image encoder

**Comment by xiaocaijiayou** [comment]
> yes it is reloading the SDXL model each time. You may try by saving the embeds with the save embeds node. that will space you 1.4gb of image encoder

It is weird though, I am now testing with A100, with 80G VRAM (VRAM 81251 MB), but still is going through this...

**Comment by cubiq** [comment]
ahaha sorry I misread your config :smile: 

why do you use NORMAL_VRAM then?!

**Comment by xiaocaijiayou** [comment]
> ahaha sorry I misread your config 😄
> 
> why do you use NORMAL_VRAM then?!

I didn't set parameter for that, what parameter should I set to use more VRAM?

**Comment by cubiq** [comment]
are you sure? There must be an error in the GPU detection then. Just run comfy with --highvram option

**Comment by xiaocaijiayou** [comment]
<img width="492" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/5426787/d14cbcef-6c15-4b1e-8cdf-a1a1ab3d4555">
<img width="1193" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/5426787/21489288-4f24-4d45-8e6b-5d4157a2b6dc">
Now it's weird. Already in highvram mode, but still reloading SDXL every time.

**Comment by cubiq** [comment]
the generation is faster though, honestly I don't see any problem here. The IPAdapter model will impact the generation

**Comment by tabisheva** [comment]
Hello, @cubiq, I change the pictures in the adapter, and after that the sdxl is loaded again every time, is it possible to prevent this from happening? For what purpose is sdxl loaded again every time?

**Comment by cubiq** [comment]
models are loaded unloaded based on the vram requirements. the only thing you can do is to set highvram

**Comment by tabisheva** [comment]
I run comfy with --highvram option, on a100 with 80g, every ipadapter faceid node is working for 5-6s. Is this how it should be?

**Comment by AlexFeYang** [comment]
hey, why the issues is closed, I have the same problem here

**Comment by TmLev** [comment]
Experiencing the same issue on H100 80GB even with the `--highvram` option enabled.
