### ISSUE TITLE
Insightface plus IPAdapter error

### ISSUE THREAD

**Issue by mahlv** [cubiq/ComfyUI_IPAdapter_plus#182]
Error occurred when executing IPAdapterApply:

IPAdapterApply.apply_ipadapter() got an unexpected keyword argument 'insightface'

https://snipboard.io/bM39y1.jpg

**Comment by blormp** [comment]
maybe this will help, I had the same issue [ https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/181](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/181)

**Comment by cubiq** [comment]
duplicate
