### ISSUE TITLE
Ask for help "InsightFace must be provided for FaceID models"

### ISSUE THREAD

**Issue by xalildd** [cubiq/ComfyUI_IPAdapter_plus#185]
Error occurred when executing IPAdapterApply:

InsightFace must be provided for FaceID models.

File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 571, in apply_ipadapter
raise Exception('InsightFace must be provided for FaceID models.')

what should i do?

**Comment by cubiq** [comment]
provide the workflow

**Comment by xalildd** [comment]
[face_models_comparison.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13799438/face_models_comparison.json)

**Comment by JPW0080** [comment]
Try connecting all unconnected insightface from the Apply IPAdapter(s) to the Load InsightFace

**Comment by xalildd** [comment]
thanks man ,it worked.

**Comment by linnew007** [comment]
> thanks man ,it worked.

 I have a same Error. what did you do ?need some details.

**Comment by zhangbiwen** [comment]
> 谢谢，伙计，它成功了。

Same error, can you give more details?

**Comment by OnurOnE** [comment]
Also ame problem with no idea how to solve. Can you give me an hint for that problem to solve?
[2D_to_3D.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14050534/2D_to_3D.json)

Thank you

**Comment by R0stys1av** [comment]
I also face an issue with most vasic flow
[IpAdaptererror.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14100895/IpAdaptererror.json)

**Comment by Murshid-Malik** [comment]
load the node ip adapter faceID, there will be extra connection of insightface, connect that to the node "Load Insight Face"

**Comment by fksldl55** [comment]
I have this problem too, I need the correct provide the workflow

**Comment by R0stys1av** [comment]
> load the node ip adapter faceID, there will be extra connection of insightface, connect that to the node "Load Insight Face"

Yes, it helps
@fksldl55 here updated workflow, I hope it will help you
[workflowIpAdapterFixed.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14141157/workflowIpAdapterFixed.json)

**Comment by PowerZones** [comment]
> Murshid

Man if i just saw this comment 6 hours earlier i wouldnt spend that much time

**Comment by LQPso** [comment]
3q
