### ISSUE TITLE
Confusion regarding weight widgets in new FaceID node.

### ISSUE THREAD

**Issue by StellarBeing25** [cubiq/ComfyUI_IPAdapter_plus#189]
There are two weight widgets in the new FaceID node, but it is not clear which one is for clip_vision and which one is for insightface embedding when using FaceID V2. It would be great if they were better organized with labels.

**Comment by cubiq** [comment]
it was very hasty implementation, things will change a little in the future. weight_v2 is what you want to change for v2 models.

the main "weight" is global (to the aggregated embeddings)

**Comment by StellarBeing25** [comment]
I do not understand what you mean by global weight. Till now, I was using two nodes, ipadapter_full_face at weight 0.30 and FaceID at 0.70, but since FaceID v2 combines the functionality of both models, I want to replicate the same with the new node, but I am not getting which weight is for FaceID and which one is us for full_face or It is completely different implementation..

**Comment by cubiq** [comment]
FaceID Plus v2 is not the same as FaceID+FullFace

**Comment by StellarBeing25** [comment]
Oh, I thought it is the combination of the two since it uses inputs from both clipvision and insightface.
