### ISSUE TITLE
`NoneType' object has no attribute 'encode_image'

### ISSUE THREAD

**Issue by rikhuijzer** [cubiq/ComfyUI_IPAdapter_plus#190]
I'm trying to run the tutorial from https://civitai.com/articles/3099/combine-multiple-images-with-ipadapter-a-workflow-for-comfyui and am getting a `NoneType' object has no attribute 'encode_image'` error.

A fully reproducible notebook called `combine.ipynb` is available at https://github.com/rikhuijzer/ComfyUI_IPAdapter_plus-minimal-example/tree/main. I've tried the solutions from https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108 including using the latest `ComfyUI` and `ComfyUI_IPAdapter_plus`.

Apologies for the mess I made out of downloading all kinds of models to all kinds of places. The problem probably lies in the things I've downloaded.

I'm running this inside the latest `pytorch/pytorch` Docker image on a AMD Epyc 7551P with a RTX 3060.

**Comment by cubiq** [comment]
I'm pretty sure your comfyui is still not updated

**Comment by rikhuijzer** [comment]
@cubiq how should I update it then? I cloned the latest version in that script, or is there another way?

**Comment by cubiq** [comment]
provide the full backtrace (the error from the console)

**Comment by rikhuijzer** [comment]
Solved by switching to https://comfyanonymous.github.io/ComfyUI_examples/sdxl/.
