### ISSUE TITLE
Load InsightFace module shows "CLIP_VISION" as output instead "INSIGHTFACE" return type

### ISSUE THREAD

**Issue by avinashchakravarthi** [cubiq/ComfyUI_IPAdapter_plus#191]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10574594/e33588e0-4d52-463e-8c12-29827f83b541)

Despite [ RETURN_TYPES = ("INSIGHTFACE",) L521 ](url) in IPAdapterPlus.py, On UI, output is shown as "CLIP_VISION". How to join the InsightFaceLoader and IPAdapterApplyFaceID ?

**Comment by cubiq** [comment]
stop comfy, update the extension, delete the node, refresh your browser or use an incognito window and recreate the node

**Comment by avinashchakravarthi** [comment]
I have tried deleting the custom node and re-installing the comfyUI_IPAdapter_Plus extension..

**Comment by cubiq** [comment]
you need to update the extension, you have an old version

**Comment by JackBaron-s** [comment]
I update the IPA to the newest version, but still have the same problem. Alerting me, ERROR:root:  - Return type mismatch between linked nodes: clip_vision, INSIGHTFACE != CLIP_VISION. Pls, give me some advice thx.

**Comment by cubiq** [comment]
you probably have an outdated workflow, you need to delete the nodes and recreate them
