### ISSUE TITLE
Using IP adapter_ SD15 has no effect on the image

### ISSUE THREAD

**Issue by shawpook** [cubiq/ComfyUI_IPAdapter_plus#192]
Using IP adapter_ SD15 has no effect on the image
Using IP adapter plus_ Sd15 reported the following error: CLIPViewModelWithProjection. forward() got an unexpected keyword argument 'intermediate'_ Output
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/37041220/ba38d75b-31c3-4330-b0be-2901fee49b7b)

**Comment by cubiq** [comment]
please check the common issues https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108

you need to update comfy

**Comment by shawpook** [comment]
> 请检查常见问题#108
> 
> 你需要更新舒适

thanks
