### ISSUE TITLE
 Exception: InsightFace must be provided for FaceID models.？？？？？？？？？I'm exhausted, this problem, how to solve this problem?

### ISSUE THREAD

**Issue by kevinwbryant** [cubiq/ComfyUI_IPAdapter_plus#194]
![QQ截图20240103202659](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135085430/02189150-b978-4932-99bb-a2953945b30b)

**Comment by julien-blanchon** [comment]
I'm exhausted too 😞

**Comment by cubiq** [comment]
duplicate

https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162

**Comment by ViniciusFXavier** [comment]
Solution https://www.youtube.com/watch?v=vCCVxGtCyho
