### ISSUE TITLE
Face Swapping Controls

### ISSUE THREAD

**Issue by Charuru** [cubiq/ComfyUI_IPAdapter_plus#196]
Reactor Node has support for selecting which face you want to replace in an image, could that be built into this as well or somehow combined with reactor face? If not built into nodes maybe a tutorial for selection with existing nodes?

**Comment by cubiq** [comment]
I'm sorry this is outside the scope of this node, but it can be easily done using any face detection node. I'll consider offering a tutorial sooner or later

**Comment by stephantual** [comment]
I can confirm i use a face detection node to obtain identical results. It's a matter of taste/workflow preference at this point.

**Comment by Charuru** [comment]
> I can confirm i use a face detection node to obtain identical results. It's a matter of taste/workflow preference at this point.

It works by index?

**Comment by stephantual** [comment]
@Charuru negative, AFAIk (i could be entirely wrong of course) only reactor supports multiple faces in 'one node' .  However, given the way IPA works, what you could do (and what i think @cubiq is refering to, is that you could detect faces, pass them to an array, and then process them on by one using the standard method used with IPA. It's basically how i've seen it done in 'packaged' software. I haven't tried to do it (my job involves only changing one face per picture for now) but i might give it a shot in the future.

**Comment by Charuru** [comment]
> @Charuru negative, AFAIk (i could be entirely wrong of course) only reactor supports multiple faces in 'one node' . However, given the way IPA works, what you could do (and what i think @cubiq is refering to, is that you could detect faces, pass them to an array, and then process them on by one using the standard method used with IPA). It's basically how i've seen it done in 'packaged' software and (i'm not in front of my regular pc - i _think_ i saw someone on YT do just this (it was in german, that's all i remmber). I haven't tried to do it (my job involves only changing one face per picture for now) but i might give it a shot in the future.

Thank you, it sounds like it should be possible using a combination of nodes.
