### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Michlozz** [cubiq/ComfyUI_IPAdapter_plus#197]
didn't manage to install it. Do you have some installation tutorial? I have in: 
"ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus"
folder all the files from github. But there is no node called "Load IPAdapter" in my UI. 
So what do I need to install first? I tried to load an exmple image and got:

```
When loading the graph, the following node types were not found: 
    IPAdapterApply
    IPAdapterModelLoader
Nodes that have failed to load will show as red on the graph.
```

How, how to install these missing nodes?

**Comment by 2PeteShakur** [comment]
have you updated to latest comfyui and also the missing nodes via comfy manager

**Comment by Michlozz** [comment]
If I click on "install missing custom nodes" I get the same: ComfyUI_IPAdapter_plus,  that I can uninstall or disable. 

update: disabling, restarting, enabling, restarting make it work.
