### ISSUE TITLE
size mismatch for proj_in.weight: 

### ISSUE THREAD

**Issue by xnmt9** [cubiq/ComfyUI_IPAdapter_plus#2]
Hello - the repo works great when using the base ipadapter_sd15.bin model - however when I move up to the plus model without changing anything else in my workflow, I get the following error:

`Error occurred when executing IPAdapterApply:

Error(s) in loading state_dict for Resampler:
size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1024]).

File "/home/-user/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/-user/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/-user/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/-user/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 237, in apply_ipadapter
self.ipadapter = IPAdapterPlus(
File "/home/-user/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 90, in __init__
self.image_proj_model.load_state_dict(self.ipadapter_model["image_proj"])
File "/home/-user/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

`

Just wondering if you have any idea or if this is a known issue

**Comment by cubiq** [comment]
At the moment IPAdapter Plus requires data that the comfy clip vision object doesn't provide. The other ipadapter extension works because the author rewrote the clip vision encode which is not a sustainable solution.

I'm working on a more stable solution (that will also require an update to comfy), it should be ready soon

**Comment by cubiq** [comment]
This should be now fixed!

Please note that the the PLUS model requires the new `CLIP Vision Encode (IPAdapter)` node. The non-plus version works with both  the standard `CLIP Vision Encode` and the new one.

**Comment by xnmt9** [comment]
Amazing! Cheers!

Regards,

Naeem Talukdar

**Comment by aicryptoking1** [comment]
I posted a similar post, but still do not understand this solution
