### ISSUE TITLE
IPAdapter model loader node is stuck on undefined and there is no way to change it

### ISSUE THREAD

**Issue by alectprasad** [cubiq/ComfyUI_IPAdapter_plus#201]
![Screenshot 2024-01-05 084202](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22129443/9bc63da7-c4ad-46e7-ae14-8776153d5198)

**Comment by areid280** [comment]
Got the same issue here, wont pick up a .bin or .safetensors file

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/150479393/38bf5ca3-d478-47b0-8801-cdb99ae564a4)

**Comment by stephantual** [comment]
Did you try refreshing (i mean press refresh, AND reload the page after saving the workflow)? MIne has been a bit finiscky in the first run. Restaring the server sometimes mysteriously helps. Just suggesting a few things - also dump your log file so we can check for errors.

**Comment by areid280** [comment]
> Did you try refreshing (i mean press refresh, AND reload the page after saving the workflow)? MIne has been a bit finiscky in the first run. Restaring the server sometimes mysteriously helps. Just suggesting a few things - also dump your log file so we can check for errors.

Hi managed to solve this, I think it's a nuance of my installation, my root directory is C:, however I point everything files, models etc to the F: drive to avoid filling up my smaller C: SSD

for whatever reason the IPAdapter model is still reading from 
**C:**\Users\xxxx\AppData\Roaming\StabilityMatrix\Models\IpAdapter

Where I put a redirect for anything in C:\User\AppData\Roamining\Stability matrix to repoint to **F:**\User\AppData\Roamining\Stability matrix, but it's clearly not working in this instance


Placing my Ipadaptor models in the C drive appears to have fixed this issue, 

Long term I think I need to start the whole thing afresh, with a new windows installation and everything sat on a large C drive SSD

**Comment by stephantual** [comment]
Oh stability matrix, say no more :) I don't want to be mean, but SM has just been headaches for me. Switched to portable, and planning to switch to the regular good old fashion git pull at the next install.
