### ISSUE TITLE
Plus Models are not working

### ISSUE THREAD

**Issue by cjdop** [cubiq/ComfyUI_IPAdapter_plus#202]
I'm new to using IP Adapters. I've installed everything as per the instructions. All the models 1.5, SDXL and Face ID are working fine. The plus models both in 1.5 and SDXL are throwing an error. I checked the common issues thread and updated my comfy and also performed a fresh installation. I am still getting this error. Please help rectifying this. 
![Screenshot_2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/155737935/07f28ed8-ade1-443b-b2ec-38924d0a1793)

**Comment by cubiq** [comment]
can't replicate. you are probably using an older version of comfyui.

the manager doesn't count as an update, it has to be done manually.
