### ISSUE TITLE
IPAdapter error: CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

### ISSUE THREAD

**Issue by mrlament** [cubiq/ComfyUI_IPAdapter_plus#205]
I'm running into an error when trying to use IPAdapter. I have the latest ComfyUI and have also deleted and reinstalled all of the IPAdapter and IPAdapter plus plugins, but the error persists... here's the full message:

> Error occurred when executing IPAdapter:
> 
> CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'
> 
>   File "W:\PYTHON STUFF\ComfyUI\ComfyUI\execution.py", line 154, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\ComfyUI\execution.py", line 84, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\ComfyUI\execution.py", line 77, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
>     cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 238, in clip_vision_encode
>     outputs = clip_vision.model(pixel_values=pixel_values, output_hidden_states=True)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\ComfyUI\comfy\clip_model.py", line 186, in forward
>     x = self.vision_model(*args, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "W:\PYTHON STUFF\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I'm working from a NerdyRodent workflow which I've attached. 
![Uploading Reposer_Plus_BG.png…]()
Can anyone suggest any fixes?

**Comment by cubiq** [comment]
I believe you have an old version of comfyui

**Comment by mrlament** [comment]
> I believe you have an old version of comfyui

I don't believe so. I've updated comfyui successfully through the manager, and even tried a fresh install from scratch and received the same error. 

Is there any way to confirm I'm on the right version other than that?

**Comment by cubiq** [comment]
you need to update from the scripts in the update directory

**Comment by mrlament** [comment]
> you need to update from the scripts in the update directory

Thanks for your help. I tried that, but I'm still getting the same error message. Anything else it could be?

**Comment by cubiq** [comment]
you are using the wrong extension. `IPAdapter-ComfyUI` is deprecated.

**Comment by mrlament** [comment]
Thank you. Any guidance on how I can switch out for the correct one instead?

**Comment by mtksm** [comment]
same issue here after full reinstall of comfy and IPAdapter, any word on how to switch out correct extension?
