### ISSUE TITLE
attention masking can it be used in lora?

### ISSUE THREAD

**Issue by jakeute** [cubiq/ComfyUI_IPAdapter_plus#208]
I watched the video of attention masking and found that its effect is very surprising，I want to know if it can work with lora. I also imagine using two characters lora in one picture.like [sd-webui-additional-networks](https://github.com/kohya-ss/sd-webui-additional-networks) mask image
<img width="852" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/47204876/648fdfb5-c002-4ae7-b8dc-a13c96b425ce">

**Comment by jakeute** [comment]
Attention masking is very useful when there are multiple loras, but comfyui has never had such a plug-in. I would like to ask if attention masking can be extended so that it can act on loras.

**Comment by cubiq** [comment]
AFAIK the models have to be trained specifically for that task, this is interesting but outside of what IPAdapter can do.

**Comment by jakeute** [comment]
@cubiq  I mean to develop a separate plugin to adapt Attention Mask to LoRa, there are several similar plugins in the SD WebUI community that use Mask to control LoRa areas, but Cofyui has not had one so far.
I'm not very sure how to associate LoRa with Mask, but it should be similar to the attention masking of ipadapter. Limit a lora to the corresponding mask. I don't know if you're familiar with LoRa, but if you can, I hope you have the time to implement it

**Comment by cubiq** [comment]
it's very interesting for sure and it's in my wishlist since a long time. I'll see what I can do

**Comment by jakeute** [comment]
@cubiq Thank you so much
