### ISSUE TITLE
FaceID SDXL gives worse results? 

### ISSUE THREAD

**Issue by ParthGandhi** [cubiq/ComfyUI_IPAdapter_plus#210]
Is it meant to be used the same way as the 1.5 faceid model? Do you have an example for SDXL that works well? 

I tried various combinations and it just always gives a worse output.

**Comment by jepjoo** [comment]
I could be wrong but I've understood that the LoRA file is in diffusers format and needs to be converted. Otherwise the LoRA won't work correctly.

If someone can upload a working LoRA, would be appreciated. I didn't manage to get the conversion thing working, have no experience using python etc.

It was discussed here:
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/195#issuecomment-1878575886

**Comment by cubiq** [comment]
This is the workflow for SDXL. The lora is already available

[FaceID_SDXL.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13860505/FaceID_SDXL.json)

**Comment by jepjoo** [comment]
> This is the workflow for SDXL. The lora is already available
> 
> [FaceID_SDXL.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13860505/FaceID_SDXL.json)

That LoRA works in your workflow? I have downloaded this:
https://huggingface.co/h94/IP-Adapter-FaceID/blob/main/ip-adapter-faceid_sdxl_lora.safetensors

And it doesn't do anything whether the LoRA is enabled or disabled. It pukes a long error into cmd window, short snippet:

```
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_k_proj.alpha
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_k_proj.lora_down.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_k_proj.lora_up.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_out_proj.alpha
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_out_proj.lora_down.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_out_proj.lora_up.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_q_proj.alpha
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_q_proj.lora_down.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_q_proj.lora_up.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_v_proj.alpha
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_v_proj.lora_down.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn1_v_proj.lora_up.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn2_k_proj.alpha
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn2_k_proj.lora_down.weight
lora key not loaded down_blocks_1_attentions_0_transformer_blocks_0_attn2_k_proj.lora_up.weight
```

**Comment by cubiq** [comment]
the model works without lora and it's not terrible when used with the workflow I linked above

**Comment by xiaohu2015** [comment]
> the model works without lora and it's not terrible when used with the workflow I linked above

hi, What is the current problem? Is there a problem with lora weight, or is it something else?

**Comment by xiaohu2015** [comment]
> I could be wrong but I've understood that the LoRA file is in diffusers format and needs to be converted. Otherwise the LoRA won't work correctly.
> 
> If someone can upload a working LoRA, would be appreciated. I didn't manage to get the conversion thing working, have no experience using python etc.
> 
> It was discussed here: [#195 (comment)](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/195#issuecomment-1878575886)

but I used diffusers scipt to convert it to a webui-format lora

**Comment by jepjoo** [comment]
> > I could be wrong but I've understood that the LoRA file is in diffusers format and needs to be converted. Otherwise the LoRA won't work correctly.
> > If someone can upload a working LoRA, would be appreciated. I didn't manage to get the conversion thing working, have no experience using python etc.
> > It was discussed here: [#195 (comment)](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/195#issuecomment-1878575886)
> 
> but I used diffusers scipt to convert it to a webui-format lora

Is the converted lora available somewhere? I think the lora file in huggingface is still in diffusers format and doesn't work in Comfy, right?

**Comment by xiaohu2015** [comment]
> > > I could be wrong but I've understood that the LoRA file is in diffusers format and needs to be converted. Otherwise the LoRA won't work correctly.
> > > If someone can upload a working LoRA, would be appreciated. I didn't manage to get the conversion thing working, have no experience using python etc.
> > > It was discussed here: [#195 (comment)](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/195#issuecomment-1878575886)
> > 
> > 
> > but I used diffusers scipt to convert it to a webui-format lora
> 
> Is the converted lora available somewhere? I think the lora file in huggingface is still in diffusers format and doesn't work in Comfy, right?
> 
> edit: Oh I see there was new further discussion in the other thread. I will wait patiently. Thanks for your work. <3

hi, can you give a normal SDXL lora file which works well on comfyui? e.g. https://civitai.com/models/222949/sdxl-loras-i-apologize-for, then I can convert to the same format

**Comment by xiaohu2015** [comment]
@jepjoo the lora weight file has been updated: https://huggingface.co/h94/IP-Adapter-FaceID/blob/main/ip-adapter-faceid_sdxl_lora.safetensors. It should work.

**Comment by xiaohu2015** [comment]
Did you test only ip-adapter-face-id (lora weight = 1.0,  face-id weight 1.0, and no face plus)

**Comment by xiaohu2015** [comment]
do you also test https://huggingface.co/h94/IP-Adapter-FaceID#ip-adapter-faceid-sdxl. In fact, I don't test comfyui

**Comment by ParthGandhi** [comment]
I've not tested the diffusers code, I can try that. But so far i've not been able to get any variation to work reasonably well on comfy.

**Comment by cubiq** [comment]
from my testing the SDXL is not as good as SD1.5 but not as bad as others are painting it. I'll run my face recognition code to see how much worse it is

**Comment by xiaohu2015** [comment]
> from my testing the SDXL is not as good as SD1.5 but not as bad as others are painting it. I'll run my face recognition code to see how much worse it is

can it also work together with face plus? 

in my benchmark run, sdxl face id is better than sd 1.5 in cos similarity from face recognition model

**Comment by cubiq** [comment]
yes, I agree that for faceid alone SDXL is probably slightly better.

**Comment by cubiq** [comment]
I've added a few benchmark results about SDXL here https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/195
