### ISSUE TITLE
Can the IPAdapter Embed be used as regular embeds

### ISSUE THREAD

**Issue by jedi4ever** [cubiq/ComfyUI_IPAdapter_plus#211]
From one of the videos I learned that there is a way to save IPAdapter as embeds.
Loading these IPAdapter has a specific IPAdapter node.

I'm wondering if we can load them as regular embeds?
One reason would be to allow to specify embeds per line in AnimateDiff allow to switch styles.

Thank you for clarifying.

**Comment by cubiq** [comment]
that would be technically feasible, at the moment it can be sorta done but it's a very convulsed process

**Comment by IrfanKheiri** [comment]
that would be cool if it helps saves VRAM usage

**Comment by jedi4ever** [comment]
thanks for the reply - look forward to when this might be implemented.
Till then I salute you for your amazing work and wonderful Youtube videos
