### ISSUE TITLE
Error occurred when executing IPAdapterApply

### ISSUE THREAD

**Issue by selim-yildirim** [cubiq/ComfyUI_IPAdapter_plus#212]
Hi everone!

Error occurred when executing IPAdapterApply:

Error(s) in loading state_dict for Resampler:
size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1664]).

File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 636, in apply_ipadapter
self.ipadapter = IPAdapter(
File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 272, in __init__
self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

I keep getting this error.
I tried it on different models.
I updated the IPadapter but it didn't work.
I deleted it and reinstalled it and it still didn't work.
I updated comfyui but it didn't fix it.

If anyone has a solution I would really appreciate it.
Best regards

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/59798944/7bd0711f-6857-424b-ba6e-fdcc272552d4)

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/59798944/c500c844-5bb2-4768-98f3-ce01bbc0c112)

**Comment by cubiq** [comment]
probably using the wrong encoder

see https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108

**Comment by DenisLAvrov14** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/42438187/c380e750-a70e-4664-8082-89831a08e8bc)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/42438187/d651d0a0-a30b-4925-a7b1-1e23fd36448f)
Hi! How fix it?

**Comment by LukeG89** [comment]
@DenisLAvrov14 Replace them with `IPAdapter Advanced`. IPAdapter Apply doesn't exit anymore after the complete code rewrite, to learn more about the new IPAdapter V2 features check the readme file

**Comment by DenisLAvrov14** [comment]
Hi! I find desicion of my previos error and use another json file(link in Youtube pin comments)
But i have a new one, anyone know how fix it?
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/42438187/03f336fd-e8e4-4bee-850f-86b9527e71ce)

**Comment by Kevinchen985** [comment]
@selim-yildirim 
CLIP-ViT-H-14-laion2B-s32B-b79K / CLIP-ViT-bigG-14-laion2B-39B-b160k
You may have named these two files in reverse.Check it out.

**Comment by nahuanba** [comment]
我以前选择的是plus face模型，一直这样报错，后来选择vit-g就不会报错了，应该是模型选择错误

**Comment by PlevanTem** [comment]
> 我以前选择的是plus face模型，一直这样报错，后来选择vit-g就不会报错了，应该是模型选择错误

![image](https://github.com/user-attachments/assets/31024e8b-8a0f-4f35-afbb-6985e3e94fff)

我也解决了，I fixed by using node IPAdapter Loader, vit-g.
