### ISSUE TITLE
Using ipadapter will slow down the workflow loading speed, and faceid will greatly exacerbate this situation

### ISSUE THREAD

**Issue by whmc76** [cubiq/ComfyUI_IPAdapter_plus#213]
[stuck issue sample.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13865485/stuck.issue.sample.json)

Using the full workflow with faceid, until 60 seconds, the drawing did not start, and all nodes were working at a very slow speed, which was very frustrating.
In the same case, just delete the node where the ipdapter is applied, and the whole process is completed in 40 seconds.
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/129386342/b4459e19-a0f8-4802-804b-aaee375c8537)

**Comment by IrfanKheiri** [comment]
It happens to me as well, especially when i'm near to exhausting vram. If i let it run for one generation, then things often speedup. Seems either there is a mem leak or ipadapter just takes up a lot of vram.

**Comment by cubiq** [comment]
what hardware?

**Comment by whmc76** [comment]
> what hardware?

12700k,32G,4090,4T ssd

**Comment by IrfanKheiri** [comment]
16G RAM, 12G 3060, old i7 7th gen

**Comment by whmc76** [comment]
> protobuf

i have tried this , but not good for me, it is still very slow.

**Comment by IrfanKheiri** [comment]
how do i add new protobuf ?

**Comment by whmc76** [comment]
> how do i add new protobuf ?

you should already have it,try pip install --upgrade protobuf
