### ISSUE TITLE
A couple of questions about optimal use .

### ISSUE THREAD

**Issue by User1231300** [cubiq/ComfyUI_IPAdapter_plus#214]
Hello, ciao Matteo.

I don't know if this is the right place for this, but i have a couple questions about optimal use of IPadapter.

1 - as Matteo described the ipadapter "sends" a black image and a reference image by default. Sometimes, while feeding 512x768 images using the "pad" option, the image gets sent as an image with 2 black stripes on the sides. In that case, would it be smart to put the noise to 0 so that the black of the reference image merges with the other black from the full black image?

2 - I'm using IPadapter to create basically instant LORAs of people. My current workflow is to do base model -> faceidlora -> 75%  ipadpter face id -> 35% ipadpter  face_plus -> 35% ipadapter plus, but this last one on another image that shows the body type of the person. Is this a good way to do things?

3 - I would love an ipadapter trained on describing the body type of the person in the reference image like the face one that does that for faces. Is there any way that we could train our own ipadapter to do this?

Apologies if this is all garbage thinking, i'm new to IPadapter.

Continua così e grazie miller per il lavoro che fai!

**Comment by cubiq** [comment]
1. no doesn't work that way. the black image is sent as uncod (negative), generally speaking it's a bad idea to send padded images. I have an idea for content aware stretching though
2. yes, that's totally fine
3. yes it's possible to train an ipadapter as you describe, the official repository has some scripts, maybe I will make a tutorial sooner or later

Ciao!

**Comment by User1231300** [comment]
Grazie matteo. Does the order in which the various IPadapters matter?  If so how?
