### ISSUE TITLE
ComfyUI SDXL FaceSwap -Question-

### ISSUE THREAD

**Issue by andieier** [cubiq/ComfyUI_IPAdapter_plus#216]
Hi guys,

I try to do a few face swaps for fare well gifts. The general idea and buildup of my workflow is:

1. Create a picture consisting of a person doing things they are known for/are characteristic for them (i.e. (just the short version): photograph of a person as a sailor with a yellow rain coat on a ship in the rough ocean with a pipe in his mouth OR photograph of a young man in a sports car with a diamond chain and golden teeth, shot through the driver side window, another person on the passenger seat in the background OR a photograph of a man dressed as a a viking with a white energy drink can in his hand). I am very spoiled from midjourney [(those are the attached one just to give you an idea of what my goal is)](https://imgur.com/a/LNvfvUo)....
The detailed prompt already describes the general look of the person

**Question: Which SDXL model do you guys recommend. I tried JuggernautXL 8 but the results aren't really consistent. Very often I get mutations as well as strange outputs in general (not following the prompt). I work with negative when needed.**
Info: Load Checkpoint - Positive and negative - CLIPTextEncodeSDXL - KSampler (Advanced) with dpmpp_2m karras, 30-40 steps, cfg 4.0-7.0 (everything set to 512x512)

2. Use the latent/pixel image and feed it into IPAdapter (my goal because of the versatility and less limitations (like the 128x128 from Reactor))

- (using the workflow for sdxl with two adapters provided by https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/210). But the "double geneation" of an image makes it somehow worse. Therefore: Is there a way to feed an already existing image as target image into the workflow? Right now I use the latent image as well as checkpoint and prompt nodes created in 1. Seed number also is the same in both KSamplers. Can I somehow skip the second model generation or make it better?

3. Upscale (wip). I understand that starting with low resolution and then upscaling it in small steps with low denoise is critical with Reactor. Anybody have an existing and working workflow to inspire me?

Overall goal is keeping the face/looks (duh)

I lover tinkering woth ComfyUI. But still: For some things I need to get a look at an existing and working workflow to integrate it into my "chaos". Priorities are consistent images following my description and a reliable face swap that doen't change the generated image too much.

Thank you guys in advance!

**Comment by cubiq** [comment]
check this https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/195
