### ISSUE TITLE
Request: raise an error for "InsightFace didn't detect any face."

### ISSUE THREAD

**Issue by Acly** [cubiq/ComfyUI_IPAdapter_plus#218]
Would it be possible to raise an exception for the case where no face is detected? Currently there is a warning, but:
* it's a fatal error, the very next line (`torch.stack` on empty embed) is going to raise anyway
* gives a better error message in the web UI, without having to look into console log
* allows other clients which connect to a running comfy server to detect this more robustly

**Comment by cubiq** [comment]
agreed

**Comment by cubiq** [comment]
this is implemented
