### ISSUE TITLE
Request: Apply IPAdapter FaceID using weighted face embeds.

### ISSUE THREAD

**Issue by sm079** [cubiq/ComfyUI_IPAdapter_plus#219]
https://github.com/Hillobar/Rope/ allows averaging embeddings from multiple faces, which has been shown to slightly improve face likeness. Could you please add two nodes that:

1. Create a weighted sum of face embeddings, similar to the node "Encode IPAdapter Image."
2. Apply IPAdapter FaceID using these embeddings, similar to the node "Apply IPAdapter from Encoded."

Something like:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/57704054/6a7d0475-6a0f-4c7d-b617-05220162be90)

**Comment by cubiq** [comment]
you can send multiple faces with a batch. I'm working on a refactor of the image encoding/weight anyway
