### ISSUE TITLE
A question about min weight 1.19e-05.

### ISSUE THREAD

**Issue by endman100** [cubiq/ComfyUI_IPAdapter_plus#223]
Hello,

I was reviewing the code in IPAdapterPlus.py at line 858 and have the following questions regarding the code segment:

```python
def preprocess(self, clip_vision, image_1, ipadapter_plus, noise, weight_1, image_2=None, image_3=None, image_4=None, weight_2=1.0, weight_3=1.0, weight_4=1.0):
    weight_1 *= (0.1 + (weight_1 - 0.1))
    weight_1 = 1.19e-05 if weight_1 <= 1.19e-05 else weight_1
    weight_2 *= (0.1 + (weight_2 - 0.1))
    weight_2 = 1.19e-05 if weight_2 <= 1.19e-05 else weight_2
    weight_3 *= (0.1 + (weight_3 - 0.1))
    weight_3 = 1.19e-05 if weight_3 <= 1.19e-05 else weight_3
    weight_4 *= (0.1 + (weight_4 - 0.1))
    weight_5 = 1.19e-05 if weight_4 <= 1.19e-05 else weight_4
```
My questions are:

1. What is the purpose of using 1.19e-05 in the code?
2. Why is weight_4 assigned to weight_5 not weight_4?
I would appreciate your response. Thank you.

**Comment by cubiq** [comment]
1.19e-05 is just so we don't have zero, but just a very very small number just close to zero, but I think I'll remove it. But I have to rework the whole weight thing, it's already in my to-do
2. I think it's just an oversight, I'll check later
