### ISSUE TITLE
PhotoMaker

### ISSUE THREAD

**Issue by TingTingin** [cubiq/ComfyUI_IPAdapter_plus#224]
https://github.com/TencentARC/PhotoMaker

Photomaker apparently uses a process similar to faceid the code is already out im unaware if it can be easily supported so posting it here

**Comment by StellarBeing25** [comment]
The Photomaker model seems to generate better facial structure similarity than the IPAdapter full-face model while also being more flexible with prompts to change facial features and hairstyles. When combined with face swapping, it can give amazing results, but I am not sure whether the node to use it can be released under IPAdapter Plus. I am requesting the node here because of the process similarity with IPAdapter.

**Comment by hben35096** [comment]
This is the first good news received today

**Comment by StellarBeing25** [comment]
That's amazing. But can you tell why Lora has to be extracted even when the node sits between the checkpoint and Ksampler, just like the Lora loader node?

**Comment by cubiq** [comment]
the lora is not in the right format and needs to be converted anyway, at that point we can just save it and use the nodes we already have for it

**Comment by shiimizu** [comment]
https://github.com/shiimizu/ComfyUI-PhotoMaker

**Comment by cubiq** [comment]
doesn't work for me, but it's a good start :)

**Comment by Blucknote** [comment]
> https://github.com/shiimizu/ComfyUI-PhotoMaker

Managed to launch this but results not even close to source

**Comment by cubiq** [comment]
I'll see if we can collaborate with @shiimizu or I'll make a new one

**Comment by hben35096** [comment]
https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker
Another version, but I'm still looking forward to the cubiq version

**Comment by xpeng** [comment]
https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker not working for me. wait cubiq version

**Comment by shiimizu** [comment]
@cubiq You're free to do whatever you like, but I wouldn't want you to waste your time and energy implementing something that's already done, since mine gets pretty much the same results as the original diffusers implementation (as seen in `https://github.com/shiimizu/ComfyUI-PhotoMaker/issues/3#issuecomment-1900543421`).

**Comment by cubiq** [comment]
if it works it works, I tried it when you first posted and I had a lot of issues. Possibly you fixed it now.

I don't want to waste time. There are a few things that I don't like much in your implementation, maybe you are open to PRs

**Comment by shiimizu** [comment]
Thanks, it had a rough start cause I was a bit sleep deprived. For sure, PRs are welcome! :)

**Comment by cubiq** [comment]
then I see no reason for making a new extension

**Comment by Arcitec** [comment]
Does anyone know the latest status of PhotoMaker in ComfyUI?

- shiimizu's, which I got a good impression from but for some reason has 130 stars and 11 open issues: https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus
- ZHO's, which I got an impression was sloppy but now has 706 stars, 47 open issues and 3 pull requests: https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker-ZHO

From that, it seems ZHO's gained a lot more activity, users and popularity.

I can't judge at a glance which version is more feature complete. Does anyone have any insights?

**Comment by cubiq** [comment]
ZHO's one is a diffusers sandbox and should be avoided if possible. The other seems to be native but ComfyUI supports photomaker internally now, so I don't think there's much reason to use anything else. If there is the author of the extension should send the updates to the ComfyUI repo

**Comment by Arcitec** [comment]
@cubiq Thanks a lot, that makes sense, and I agree that if anyone has improvements they should be sent to ComfyUI's repo instead. I'll use the native implementation. <3
