### ISSUE TITLE
Issue with conditioning: set mask area and FaceID adapter

### ISSUE THREAD

**Issue by agawrylak** [cubiq/ComfyUI_IPAdapter_plus#226]
https://blenderneko.github.io/ComfyUI-docs/Core%20Nodes/Conditioning/ConditioningSetMask/#inputs

if you apply multiple ipadapter faceids to different areas, and use set_cond_area = mask bounds in conditioning set mask nodes, then ipadapters will affect the whole picture, merging all faces into one.

**Comment by cubiq** [comment]
Seems to be working. You need of course attention masking for each person.

![ComfyUI_temp_hfxif_00020_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/d281f80c-1ea4-4e23-a0b3-4d0bd6f31b1c)

**Comment by agawrylak** [comment]
@cubiq it works because there is no mentioned node in WF you provided. it is condition mask node with set_cond_area = mask bounds

**Comment by agawrylak** [comment]
here is image with set_cond_area=default 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/64438253/631a1b5d-c724-452a-a04c-609c55bdb31b)

**Comment by agawrylak** [comment]
this is the settings. 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/64438253/48c140c5-c629-4479-8fba-9b9f6ea4b241)
multiareaconditioning node, which is probably the only sane way to do regional prompting also does not work with faceid adapters - it causes bleeding. maybe could be using the mask_bound underneath?
