### ISSUE TITLE
Negative image prompt

### ISSUE THREAD

**Issue by andrewsagio** [cubiq/ComfyUI_IPAdapter_plus#229]
@cubiq , I recently experimented with negative image prompts with IP-adapter [here](https://github.com/sagiodev/IP-Adapter-Negative). 

Some people found it useful and asked for a ComfyUI node. I think it would be a great addition to this custom node.

Are you open to a PR for enabling an optional negative image to the IPAdapterApply?  I want to confirm before coding it all up... 🤣

**Comment by cubiq** [comment]
thanks for your message. I've implemented the negative images code a while back now. The code is available here https://github.com/cubiq/Diffusers_IPAdapter which is a better implementation of the diffusers code for IPAdapter. You can send multiple reference images and multiple negative images.

The "noise" option in the comfyui extension is actually based on that concept.

By my original testing the results with negative embeds were a bit hit-and-miss and decided to keep the comfy extension simple and ultimately I did not included the option here.

I was thinking of bringing it back but we need to find a way to make it simple and compatible with the current noise implementation.

**Comment by andrewsagio** [comment]
Nice work!

How about keeping the same behavior when the negative image is not used? Add noise to negative image when it is used.


Noise = 0
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/3319909/1cfb0aa3-8afa-4dfd-ae98-217d845fb425)

Noise = 0.2
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/3319909/c0c667a1-682b-4b8a-9458-033e2ea37a62)

**Comment by cubiq** [comment]
if you don't provide a negative, nothing changes and the current implementation should stay the same.

If you provide a negative image, that should be used. If you also add noise, the noise is added to the image you provided but the noise strategy should be different from the current "add noise" as we don't need shuffling.

Also in case of batches of images, positive and negative images should match in number so I need to find a strategy for that as well. Not to mention that everything has to be compatible with the batch_unfold option.

Also IPAdapter is trained with black negative images, so I would also try to make some testing by sending the negative image together with noise and/or black images.

**Comment by andrewsagio** [comment]
Sounds good. I would add putting the image and the negative image on an equal footing so that one or both can be accepted.

If I understand correctly, you have a plan to work on it.

I put in an implementation [here](https://github.com/sagiodev/ComfyUI_IPAdapter_plus). I am happy to work on a PR if you find it useful.

**Comment by cubiq** [comment]
yeah like I said implementing it is not a big problem, it's mostly just a matter of adding the image input... but it has to be compatible with the whole current ecosystem. There's also the image encode node for example. Also it might be interesting to be able to send multiple negatives, maybe doing a means avg (1 pos, multiple negs), worth a try.

I'll look into it.

**Comment by xiaohu2015** [comment]
> Nice work!
> 
> How about keeping the same behavior when the negative image is not used? Add noise to negative image when it is used.
> 
> Noise = 0 ![image](https://private-user-images.githubusercontent.com/3319909/298149519-1cfb0aa3-8afa-4dfd-ae98-217d845fb425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjEyNjcsIm5iZiI6MTcwNjAyMDk2NywicGF0aCI6Ii8zMzE5OTA5LzI5ODE0OTUxOS0xY2ZiMGFhMy04YWZhLTRkZmQtYWU5OC0yMTdkODQ1ZmI0MjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTQ0MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVmMTMzYzU2ZDBjNGRlNGZiZmNiNmJmYTYyYzgzNTg0NjIyMDY3YTZjMGU0ZGVjMWY5YjRmNzBmNTU2MDY1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3zTBLi7FdF20g6SAcQqyczI5ANEnasQqku8HLu8rPCw)
> 
> Noise = 0.2 ![image](https://private-user-images.githubusercontent.com/3319909/298149352-c0c667a1-682b-4b8a-9458-033e2ea37a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjEyNjcsIm5iZiI6MTcwNjAyMDk2NywicGF0aCI6Ii8zMzE5OTA5LzI5ODE0OTM1Mi1jMGM2NjdhMS02ODJiLTRiOGEtOTQ1OC0wMzNlMmVhMzdhNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTQ0MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjNjMTgxMDUzYmVkZjUyYzVhMzA4NjQzZjljZTBhNDcxYjFiNTMzOGRkMmNhMTEwNWQwMWYwMGM5YmRkZGU3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BZBOuzhH82WX7sIiljYTrfxkl0qWG59iRAAZLJsqFjA)

looks very great!

**Comment by cubiq** [comment]
now supported

**Comment by ultimatech-cn** [comment]
Great work!
