### ISSUE TITLE
Multiple IPAdapters become extremely slow

### ISSUE THREAD

**Issue by JoeNavark** [cubiq/ComfyUI_IPAdapter_plus#232]
If I use 3 adapters I can gen in 10 seconds, but at 4 or more adapters I get about a 60 second delay before the green execution box even appears on my workflow.

**Comment by cubiq** [comment]
that's because you are out of vram and the models need to be loaded/unloaded

**Comment by JoeNavark** [comment]
task manager is showing my dedicated gpu memory usage is still only about about 1/3rd full

**Comment by cubiq** [comment]
ensure your python environment is up to date

**Comment by Arcitec** [comment]
@JoeNavark Try this:

https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/238#issuecomment-1903230961

**Comment by JoeNavark** [comment]
I put together a completely clean environment and got everything updated. The issue seems to have been that loading insightface was happening silently before the rest of the workflow showed up. Now I get a much more verbose loading of insightface and can see what's going on. 

@Arcitec Protobuf 4 really does make a big difference, but having to give up mediapipe to get it is a tough choice.
