### ISSUE TITLE
Clip Vision needed for models without the need for an image encoder

### ISSUE THREAD

**Issue by SoulxSlayer** [cubiq/ComfyUI_IPAdapter_plus#233]
The "clip vision" node is needed for some FaceID IPAdapter models which don't have the requirement. I think it wasn't like that in one update, which was when FaceID was just released. 

Am I missing some node to fix this? I am pretty sure I've used FaceID without the need of a clip vision.

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/43785565/df250083-6398-4d1d-a1ad-b7760786746e)

**Comment by SoulxSlayer** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/43785565/66428e76-f56a-4ca0-bc67-d4fb8f5a31d7)

**Comment by cubiq** [comment]
at the very beginning it wasn't needed because we had only v1. Now it's not technically needed but used for the "noise" option anyway
