### ISSUE TITLE
None of the provided workflows load

### ISSUE THREAD

**Issue by Dampfinchen** [cubiq/ComfyUI_IPAdapter_plus#236]
Hello,

when I add any of the workflows to the comfy UI nothing happens. Everything is up to date

**Comment by cubiq** [comment]
can you be just a little bit more specific....

**Comment by JorgeR81** [comment]
This also happens to me, if I right click, and do "save as", for the json files in the examples folder. 

![wf0](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/72734038/c9b9925f-be45-4a6d-9737-4013fbd48867)

For the json file to work correctly, you need to left click, to see the file and then use the download button. 

![wf](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/72734038/c916268d-715f-4b00-ae5e-c875da015c3c)

**Comment by cubiq** [comment]
they are in your custom_nodes/ComfyUI_IPAdapter_Plus/examples/ directory. Those should work

**Comment by JorgeR81** [comment]
Yes, but in my experience, if you download the json file via right click, it seems to become corrupt. 
Look at the size difference between the same file downloaded in different ways.
I'm on Windows 10.

![wf3](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/72734038/6f197e61-7520-41ee-bdf6-0cff9d7a461b)

**Comment by cubiq** [comment]
don't right click, just click

**Comment by Dampfinchen** [comment]
> This also happens to me, if I right click, and do "save as", for the json files in the examples folder. 
> 
> ![wf0](https://private-user-images.githubusercontent.com/72734038/298397803-c9b9925f-be45-4a6d-9737-4013fbd48867.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTczMzcsIm5iZiI6MTcwNTk1NzAzNywicGF0aCI6Ii83MjczNDAzOC8yOTgzOTc4MDMtYzliOTkyNWYtYmU0NS00YTZkLTk3MzctNDAxM2ZiZDQ4ODY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDIwNTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYWVkMjc0NjQxYjU1MGI0ODY2ODY2ZmViYmI3ZTZmNTgxNWZmMzU0MzEzYTFkNTc3MDgxZjExODMzZmVmNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ojil-GxSNQL2jXRk0HdzRKeK69jwUewZqYSgIss9Hrw)
> 
> For the json file to work correctly, you need to left click, to see the file and then use the download button.
> 
> ![wf](https://private-user-images.githubusercontent.com/72734038/298397849-c916268d-715f-4b00-ae5e-c875da015c3c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTczMzcsIm5iZiI6MTcwNTk1NzAzNywicGF0aCI6Ii83MjczNDAzOC8yOTgzOTc4NDktYzkxNjI2OGQtNzE1Zi00YjAwLWFlNWUtYzg3NWRhMDE1YzNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDIwNTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NWIzM2M5YTU0ZjM2MDYyYWYyNWYxZmZhNTc5NzZjOGFiODU4NmY2YTBmNjRjMDExODBmOWM1NGNkY2Q2YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVjIaH9QrqHd2wKmR8N8WhP03x9w9lB6OIf9yLCFDlU)

Thank you, this works. The Json files load now. Sadly the jpegs still don't. Do you have a trick for these as well?

**Comment by JorgeR81** [comment]
For the workflow to be stored in the image file, it needs to be saved in PDF.

https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#features
