### ISSUE TITLE
FAQ/GUIDE: I've figured out why CUDA isn't available in Insightface!

### ISSUE THREAD

**Issue by Arcitec** [cubiq/ComfyUI_IPAdapter_plus#238]
Hi there cubiq, and everyone else who suffers with lack of CUDA support! :)

I've seen your FAQ, which says "Note that your CUDA version might not be compatible with onnxruntime, in that case you can select the "CPU" provider from the Load InsightFace model node", and I've seen various posts here where people just cannot figure out why CUDA works for some people and doesn't work for others.

Well, now I finally know why. It's a very complicated topic.

It's as follows:

- `insightface` itself is just a model, which can be run on CPU by default, or can be run on GPU (such as CUDA) if the necessary framework `onnxruntime-gpu` is available and is CUDA-capable.
- `onnxruntime-gpu` is [currently limited to CUDA 11.8](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html). The new version supporting CUDA 12 will finally (after a year or more of waiting) be [released soon at the end of January, 2024](https://github.com/microsoft/onnxruntime/issues/18850#issuecomment-1892977993), in ONNX Runtime 1.17. When that's out, it should be possible to run insightface on GPU with Python 3.11+ with CUDA 12 instead.
- `onnxruntime-gpu` doesn't need `torch`. But some people have discovered that if you `import torch` before you import `insightface`, you end up with CUDA support as long as your Torch CUDA version matches (or is similar enough) to the one required by insightface. Why? Well, I discovered that Torch loads a bunch of CUDA and CUDNN `.so` / `.dll` libraries into the Python process when you `import torch`. But that's just a very silly workaround. We should fix this properly.
- So... to use CUDA 11.8 so that we get GPU acceleration in ONNX and insightface, you will need several things on your system.
- First of all, you MUST have the CUDA 11.8 libraries. This is not easy to setup on Linux and is different on every distro. Which is why many people use NVIDIA's official docker containers with pre-installed CUDA 11.x instead. Luckily, I have created a much easier method and will show you in this guide.
- Secondly, you MUST have CUDNN and other CUDA libraries such as CUFFT, etc, with an appropriate version for CUDA 11.8. This is again, very hard to set up officially. Yet again, I have created a much easier method.
- Lastly, you MUST USE PYTHON 3.11 (or 3.10), because 3.12 isn't compatible with the required libraries yet.

Let's tackle each requirement one by one:

- CUDA Toolkit 11.8: You [can install this on your Linux host](https://developer.nvidia.com/cuda-11-8-0-download-archive). It's tedious and involves trial and error and is different on every distro. I don't recommend installing it on the host. Continue reading this guide instead!
- CUDNN and other assistance libraries: You can [yet again install ithis on your Linux host](https://developer.nvidia.com/cudnn). And again, it's tedious and I don't recommend installing it on the host. Continue reading this guide instead!
- Python 3.11: I recommend using [pyenv](https://github.com/pyenv/pyenv), an amazing tool. It makes it easy to manage different Python versions simultaneously.
- You also need to create a new venv and reinstall all libraries.

Now let's look at the hardest requirement on that list: The CUDA Toolkit, CUDNN and other AI libraries from NVIDIA. 

- If you install those on the host, you will have to mess around with outdated NVIDIA repositories, annoying manually installed package files, file conflicts with your host's newer libraries, etc. I do NOT recommend installing them on the host. I've come up with a much better way.
- I was investigating why `import torch` is able to "fix" insightface/onnx GPU acceleration for people. Then I saw that Torch was installing a bunch of `nvidia-cu*` Python packages, and discovered that they contain the actual `.so` files for CUDA Toolkit, CUDNN and other libraries. They are the same library files that you would install natively on your host. This gave me an idea...
- Basically, if you install the missing CUDA 11.8 libraries as Python packages in your venv, you only need to tell Python how to find those `.so` files, and it will be able to detect and use CUDA 11.8 without infecting your host with old junk files. So that's the path I spent time on. And thankfully, I had success!
- Note that Torch installs about a dozen different `nvidia-cu*` libraries, and my chosen path was to rely on Torch's versions of those libraries, and only install the TWO older libraries that we actually need for the remaining, missing CUDA 11.8 files. Because there's a lot of overlap between releases of CUDNN for different CUDA toolkits. This means that we'll run CUDA 11.8 with mostly newer CUDNN support libraries, but that works for me and it's up to NVIDIA to increase the `.so.X` version number if they're ever incompatible with each other. You should always strive to have the newest CUDNN files, so that they're compatible with your newest installed CUDA toolkit, and my method achieves exactly that. In fact, I did my testing without importing "torch", which means that I have found the full list of older libraries that onnx/insightface needs. So my testing and the filenames themselves indicates that my installation method is safe and correct.

Alright, so let's do it!

1. Carefully read the instructions on the [pyenv](https://github.com/pyenv/pyenv) main page, and install it. You will need to set up pyenv, the shell autocompletions, PATH injection, and the build dependencies. Their excellent README explains the whole process. It's worth it. It's the only worthwhile way to reliably manage Python versions on Linux.
2. Install Python 3.11 (this automatically picks the newest 3.11.x release).
```sh
pyenv install 3.11
```
3. Navigate to the directory where you will have ComfyUI (or any directory above it in the path), and tell pyenv that all `python` and `pip` related commands anywhere within that directory hierarchy will use Python 3.11:
```
cd /your/path/to/comfyui
pyenv local 3.11
```
4. Create a new venv and activate it. This will hold all your libraries in an isolated environment that won't conflict with the host machine.
```
rm -rf .venv  # if you have an old venv folder, we delete it first
python -m venv .venv
. .venv/bin/activate
```
5. Install the CUDA 12 version of Torch (newest version) and the newest ONNX runtimes, along with insightface. Torch's dependencies will automatically take care of installing a ton of CUDA-related libraries for us (you can see them in the installation log, they will all follow the `nvidia-*-cu12` naming style).
```sh
pip install torch torchvision torchaudio onnxruntime onnxruntime-gpu insightface
```
6. (Skip this step if you read this after ONNX has CUDA 12 support!) Manually add the extra libraries that we will require for CUDA 11.8 support, at least as far as insightface/onnx goes (we don't add any extra, useless libraries here). We will add the toolkit itself, along with the older CUBLAS and CUFFT libraries that are required for CUDA 11. Note that the actual `.so` on-disk filenames differ from the newer libraries, so you can be sure that there won't be any conflicts with the CUDA 12 stuff above.
```sh
pip install nvidia-cublas-cu11 nvidia-cufft-cu11
```
7. Create a file named `test-insightface.py`, place it **next to** your `.venv` location, and put the following contents in it (and preferably edit its `inface_models` path if your ComfyUI folder isn't exactly named "comfyui" at that exact path, because if you provide a correct path to the models directory, you can reuse the existing model in the ComfyUI installation; if the path cannot be found, it will automatically be created and downloaded instead):
```python
from insightface.app import FaceAnalysis
from pathlib import Path

THIS_DIR = Path(__file__).parent
inface_models = THIS_DIR / "comfyui/models/insightface"
model = FaceAnalysis(name="buffalo_l", root=str(inface_models), providers=['CUDAExecutionProvider',])
model.prepare(ctx_id=0, det_size=(640, 640))
```
8. Create a file named `test-run.sh`, and place that **next to** your `.venv` location, and put the following contents in it (you can edit `_VENV_DIR=` to another value if you use a different venv folder name, and future readers should also beware the hardcoded `python3.11` in the path, which you should change if that's no longer relevant for you):
```sh
#!/usr/bin/env bash

set -e

_VENV_DIR=".venv"

. "${_VENV_DIR}/bin/activate"

for lib in cublas cudnn cufft curand; do LD_LIBRARY_PATH="./${_VENV_DIR}/lib/python3.11/site-packages/nvidia/${lib}/lib/:${LD_LIBRARY_PATH}"; done

echo "$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
python test-insightface.py
```
9. Make the test-file executable, and run it by executing these commands in your terminal. Your goal is to see a bunch of CUDA information, without any errors about failing to load libraries/CUDA.
```sh
chmod +x test.sh
./test.sh
```
10. If you still see errors saying that you don't have CUDA, then you should reinstall `onnxruntime-gpu`. For some dumb reason, I always have to reinstall it after all the setup. It makes no sense to me, but it may be some dumb post-install script that runs inside that package and doesn't understand that you have CUDA until you do this.
```sh
pip install --upgrade --force-reinstall onnxruntime-gpu
```
11. Alright, at this point of the guide, I have CUDA support on my machine. If you've done everything right, you should have CUDA support too. As the astute readers may have noticed, the way the test-script worked is that we inject extra ".so" library loading paths into Python's environment, so that it can find CUDA inside our venv environment instead of needing to have the libraries on the host machine.
12. While you're still inside your venv, you should now install all ComfyUI + ComfyUI Custom Modules `requirements.txt` libraries again, since your actual ComfyUI modules are going to need all of that too.
13. Now we finally need to make the "library injection" technique into a permanent startup script for ComfyUI, which you will use to start the server. Name it something like `run-comfyui.sh` and place this anywhere you want, and *optionally* edit the `SCRIPT_VENV`, `PY_SITEPKG_VER`, `COMFYUI_MAIN` and `COMFYUI_PORT` near the top of the script if you need to modify your locations, folder names and settings.
```sh
#!/usr/bin/env bash

# Exit on errors in commands or pipes.
set -e

# Ensure that we are in the correct directory.
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "${SCRIPT_DIR}"

# Set this to your desired VENV path.
SCRIPT_VENV="${SCRIPT_DIR}/.venv"

# Set this to your current Python version,
# without minor suffix (ie. "3.11", not "3.11.2").
PY_SITEPKG_VER="3.11"

# Set this to your ComfyUI main.py path.
COMFYUI_MAIN="comfyui/main.py"

# Set this to your desired ComfyUI listening port.
COMFYUI_PORT="11000"

# Activate the venv.
source "${SCRIPT_VENV}/bin/activate"

# Generate the extra library paths.
for lib in cublas cudnn cufft curand; do
    LD_LIBRARY_PATH="${SCRIPT_VENV}/lib/python${PY_SITEPKG_VER}/site-packages/nvidia/${lib}/lib/:${LD_LIBRARY_PATH}"
done
export LD_LIBRARY_PATH

# Start the ComfyUI server.
python "${COMFYUI_MAIN}" --listen --port "${COMFYUI_PORT}"
```
14. Make it executable.
```sh
chmod +x run-comfyui.sh
```
15. From now on, always start ComfyUI via the launcher script. You can run it from anywhere (you don't have to be in the same folder as the script when launching it), since it automatically handles relative and absolute paths. Enjoy!
```sh
./run-comfyui.sh
```

Anyway, all this information may soon be slightly outdated when `onnxruntime-gpu` comes out with CUDA 12 (Python 3.11) support around the end of this month.

But it might actually not become outdated at all, if it turns out that we still need CUDA + CUDNN on the host. Most people don't have that, since CUDNN is a specially licensed package that you have to request from NVIDIA, so it's not bundled by any distros by default. And CUDA + CUDNN are a huge PITA to install on the host on Linux.

And then there's all the people who run immutable distros who can't even install it on the host. This guide will be very useful for them too.

So, even after the new release of ONNX with CUDA 12 support, we will still need my method, except that we won't need to specifically install the extra `-cu11` packages anymore, since ONNX will be able to use Torch's `-cu12` packages instead.

I am also sure that this information will be very useful again after a year, when the next CUDA toolkit is inevitably released and we have the exact same problem again!

Hope this helps people! Have fun! :)

**Comment by Arcitec** [comment]
If anyone is on Fedora, I can tell you how to install CUDA Toolkit 11. These instructions ONLY work on Fedora, but other people can use them as inspiration for their own distros. This way of installing the toolkit will create "parallel files" that peacefully exist side by side with the latest CUDA Toolkit 12 (at the moment) from our official RPM Fusion NVIDIA driver repo. And yes, this says Fedora 35. That's on purpose. It's the final repo NVIDIA published with CUDA 11. It doesn't matter, you can use it on any future Fedora versions, because the actual library files are not versioned towards any specific Fedora version. And old CUDA libraries always work with all newer NVIDIA drivers!

1. Execute the FIRST command from [the CUDA Toolkit 11 Fedora installation page](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Fedora&target_version=35&target_type=rpm_network) to add their repository, but don't execute ANY OTHER COMMANDS on that page (the other commands break your DNF dependency resolvers). The command is: `sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/fedora35/x86_64/cuda-fedora35.repo`
2. Open the repo definition file in a root privilege text editor. I will use nano out of respect for people who don't know how to exit vim (hehe): `sudo nano /etc/yum.repos.d/cuda-fedora35.repo`
3. Add the following line at the bottom of the file, which is super important, otherwise you will break your system due to outdated NVIDIA drivers with clashing package names that would conflict with RPM Fusion's new NVIDIA drivers: `exclude=kmod-* nvidia-*`
4. Save and exit the text editor.
5. Ensure that your file now looks like mine: `cat /etc/yum.repos.d/cuda-fedora35.repo`

```ini
[cuda-fedora35-x86_64]
name=cuda-fedora35-x86_64
baseurl=https://developer.download.nvidia.com/compute/cuda/repos/fedora35/x86_64
enabled=1
gpgcheck=1
gpgkey=https://developer.download.nvidia.com/compute/cuda/repos/fedora35/x86_64/D42D0685.pub
exclude=kmod-* nvidia-*
```

6. Alright, you have now disabled (excluded) all the harmful, outdated drivers, and you've got full access to the old CUDA Toolkit itself.
7. So now you install the CUDA 11 libraries as follows: `sudo dnf install --refresh cuda-toolkit-11-8`
8. That's it. Your machine now has a working CUDA Toolkit 11.8, which was the final release of that toolkit.
9. Now you just need to use [pyenv](https://github.com/pyenv/pyenv) (read their installation instructions to properly install pyenv itself first), and then use it to install Python 3.10 (this automatically picks the newest 3.10.x release): `pyenv install 3.10`
10. Then navigate to your project folder where you have comfyui, and tell pyenv that you want Python 3.10 for all `python` and `pip` commands within that folder: `pyenv local 3.10`
11. Finally, create a venv within this folder: `python -m venv .venv`
12. Activate the venv: `. .venv/bin/activate`
13. Now install all libraries again and you will have 3.10 with CUDA 11.8 support.
14. Note: You are able to use the latest PyTorch with CUDA 12 support within this environment, since both NVIDIA and Torch themselves publish CUDA 12 related packages for Python 3.10. So just [install torch](https://pytorch.org/get-started/locally/) as usual with the "CUDA 12" command, which is currently: `pip install torch torchvision torchaudio`

CUDA Toolkits all coexist fine side by side, so you can run Python 3.10 with Torch on CUDA 12 and ONNX (Insightface) on CUDA 11 simultaneously within the same ComfyUI environment. :)

**Comment by Arcitec** [comment]
Oh yeah, your README also mentions that "every time you run the workflow for the first time InsightFace will take quite a few seconds to load".

That is fixable with this command inside your venv:

```sh
pip install --upgrade protobuf
```

Reason: Protobuf 3.x takes 33 seconds to load. Protobuf 4.x takes 1 second to load.

It's really that simple.

**Comment by ansonkao** [comment]
Looks like CUDA12 support is now live with onnxruntime v1.17!
https://github.com/microsoft/onnxruntime/releases/tag/v1.17.0

**Comment by BradVidler** [comment]
Thanks @Arcitec for this invaluable info. I've been wondering why the Reactor node is so slow, even on an H100, and I think this might be why.

**Comment by Autantpourmoi** [comment]
hi i followed your tuto letter by letter as i don't understand anything in code . when it come to insightface is that message normal :

**Comment by xXWarMachineRoXx** [comment]
> hi i followed your tuto letter by letter as i don't understand anything in code . when it come to insightface is that message normal : /home/theduc/ComfyUI/.venv/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider' warnings.warn( Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} and my comfyui is now on the adress 0.0.0.0:11000 which doesn't seems to be secure , what can i do about it ? thanks again

Well i tried the same, changed it to `CUDAExecutionProvider` and I think @Arcitec 's solution to use `onnxruntime-gpu` would be the solution.

**Comment by Arcitec** [comment]
@ansonkao

> Looks like CUDA12 support is now live with onnxruntime v1.17!
> https://github.com/microsoft/onnxruntime/releases/tag/v1.17.0

Yeah it's live, which means ONNX will now work with your latest host-installed CUDA, which is pretty easy to get on most distros. It will break again the future when NVIDIA creates another CUDA version which doesn't match the version needed by ONNX.

Therefore I simply recommend using my method to launch ComfyUI. Just skip the step that says "Skip this step if you read this after ONNX has CUDA 12 supportSkip this step if you read this after ONNX has CUDA 12 support".

My method ensures that ONNX will use the CUDA runtime that exists *inside* the Python virtual environment, exactly what Torch does too. That's way more reliable than using the host's CUDA runtime.

I wish ONNX officially coded whatever thing that PyTorch does, since PyTorch is capable of automatically finding CUDA inside the Python library folders. I suspect that PyTorch looks for the folder and injects the paths into Python's environment, which explains why doing `import torch` before `import onnxruntime` works too.

@BradVidler 

> Thanks @Arcitec for this invaluable info. I've been wondering why the Reactor node is so slow, even on an H100, and I think this might be why.

Glad I could help you! You were probably running ONNX with CPU mode which is definitely super slow. You should also upgrade protobuf as mentioned here, since that speeds up the startup by over half a minute:

https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/238#issuecomment-1903230961

@Autantpourmoi 

> hi i followed your tuto letter by letter as i don't understand anything in code . when it come to insightface is that message normal :
> /home/theduc/ComfyUI/.venv/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
> and my comfyui is now on the adress 0.0.0.0:11000 which doesn't seems to be secure , what can i do about it ? thanks again

That looks like `onnxruntime` is installed. You need to uninstall `onnxruntime` from your virtual environment and install `onnxruntime-gpu` instead.

And to change the listening port, edit the number in `COMFYUI_PORT="11000"` in the startup script that I provided. :)

@xXWarMachineRoXx

> Well i tried the same, changed it to `CUDAExecutionProvider` and I think @Arcitec 's solution to use `onnxruntime-gpu` would be the solution.

That's right. Sometimes ComfyUI modules will install `onnxruntime` instead. Or the user might mistakenly install it.

ONNX has two versions, `onnxruntime` for CPU, and `onnxruntime-gpu` for GPU. You should only install one version, not both (their official docs mention this). The `onnxruntime-gpu` variant is required for `CUDAExecutionProvider` support. :)

Sorry for my delayed responses to everyone. I guess everyone's solved things already, but this message is a followup for any future readers too!

Good luck, everyone! :)

**Comment by xXWarMachineRoXx** [comment]
> Therefore I simply recommend using my method to launch ComfyUI. Just skip the step that says "Skip this step if you read this after ONNX has CUDA 12 support". To skip installing the older CUDA libraries which aren't needed anymore.


Well thats it , but I was using for another project and encountered this error

I was doing a vision task and my insight-face model wasnt using the gpu and i found it might be an issue with the version diff so i updated my python packages and hacked around until i found this thread, well it didnt work for me but its working well enough on the cou for now so 🤷

**Comment by Arcitec** [comment]
> it didnt work for me

I'm using this method. It's definitely working. Maybe you didn't set the variables in the startup script? Especially the Python version is very important to set correctly, because that's how we detect the path where the CUDA libraries exist. :)

Also keep in mind, ONNX now uses CUDA 12.

**Comment by Arcitec** [comment]
@xXWarMachineRoXx 

> I was doing a vision task and my insight-face model wasnt using the gpu and i found it might be an issue with the version diff so i updated my python packages and hacked around until i found this thread, well it didnt work for me but its working well enough on the cou for now so 🤷

I have found the issue. ONNX for Python 3.11 still uses CUDA 11. Torch for Python 3.11 now uses CUDA 12. So this means we need some slight adjustments.

I have rewritten each script in the original post to adapt to the new requirement, and also rewrote the Python version detection to be automatic in the scripts now (easier to maintain when you update things in the future).

The short list of changes: We need to install one more CUDA-related package manually now (see original post) and use my updated scripts to launch it.

I also changed the scripts to look for the folder "ComfyUI" instead of "comfyui", since the official repo has been renamed to be use some uppercase letters now, so this makes it easier to use the scripts.

Enjoy!

**Comment by xXWarMachineRoXx** [comment]
> @xXWarMachineRoXx
> 
> > I was doing a vision task and my insight-face model wasnt using the gpu and i found it might be an issue with the version diff so i updated my python packages and hacked around until i found this thread, well it didnt work for me but its working well enough on the cou for now so 🤷
> 
> I have found the issue. ONNX for Python 3.11 still uses CUDA 11. Torch for Python 3.11 now uses CUDA 12. So this means we need some slight adjustments to add another package that Torch used to give us.
> 
> I have rewritten each script in the original post to adapt to the new requirement, and also rewrote the Python version detection to be automatic in the scripts now (easier to maintain when you update things in the future).
> 
> The short list of changes: We need to install one more CUDA 11-related package manually now (see original post) and use my updated scripts to launch it.
> 
> I also changed the scripts to look for the directory named "ComfyUI" instead of "comfyui", since the official repo has been renamed to use some uppercase letters now, so this makes it easier to use the scripts with the default directory name.
> 
> Enjoy!

Thanks, Will check it out!

**Comment by qjm100** [comment]
My CUDA is 12.6 and cudnn is 9.5.
But when I try to use insightface I got the same problem.
 [ 1 ; 3 1 m 2 0 2 4 - 1 1 - 0 8   1 5 : 1 1 : 4 7 . 6 2 1 1 9 9 7   [ E : o n n x r u n t i m e : D e f a u l t ,   p r o v i d e r _ b r i d g e _ o r t . c c : 1 8 6 2   o n n x r u n t i m e : : T r y G e t P r o v i d e r I n f o _ C U D A ]   D : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ s e s s i o n \ p r o v i d e r _ b r i d g e _ o r t . c c : 1 5 3 9   o n n x r u n t i m e : : P r o v i d e r L i b r a r y : : G e t   [ O N N X R u n t i m e E r r o r ]   :   1   :   F A I L   :   L o a d L i b r a r y   f a i l e d   w i t h   e r r o r   1 2 6   " "   w h e n   t r y i n g   t o   l o a d   " C : \ U s e r s \ 1 7 2 3 6 \ P y c h a r m P r o j e c t s \ L e e t c o d e S t u d y \ . v e n v \ L i b \ s i t e - p a c k a g e s \ o n n x r u n t i m e \ c a p i \ o n n x r u n t i m e _ p r o v i d e r s _ c u d a . d l l " 
  [ m 
 What should I do that it can use GPU to run the project. Anyway my GPU is Nvidea 4060 Laptop and onnxruntime-gpu version is 1.20

**Comment by student7545** [comment]
please let me know of any solution people, been having diffculty with this my self too

**Comment by Arcitec** [comment]
@qjm100 I used the Linux word a lot in the guide, but I've edited the top of the guide to be very clear: This method does not work on Windows, because Windows uses a totally different way to load CUDA libraries. If you run ComfyUI inside WSL (Linux on Windows), it would work though.

**Comment by Arcitec** [comment]
Final Update: ONNX now has a built-in function to preload the libraries on both Linux and Windows. See this post: https://github.com/microsoft/onnxruntime/issues/11092#issuecomment-3322064635

Unfortunately it's not automatic and needs code changes in everyone that uses ONNX, so my method is still "easier" in most cases.
