### ISSUE TITLE
Feature Req: Add randomization to embed selection loader node

### ISSUE THREAD

**Issue by sedetweiler** [cubiq/ComfyUI_IPAdapter_plus#24]
I have a directory of embeds and want to have the system select a random one for each generation.  This would be amazing!

**Comment by cubiq** [comment]
that is a bit beyond the scope of this extension... but I agree it would be cool :+1:

**Comment by sedetweiler** [comment]
It would really help with adoption, as no one else is going to create a loader for this specific file type that will contain this feature.

**Comment by cubiq** [comment]
This is surprisingly already implemented

![random](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/6dbff930-d29b-4ccd-b493-fdd2e5b52a35)

**Comment by sedetweiler** [comment]
Ahh, interesting!  Thank you for looking into this. Great nodes you have created here.
