### ISSUE TITLE
how to use in img2img

### ISSUE THREAD

**Issue by starinskycc** [cubiq/ComfyUI_IPAdapter_plus#240]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/6244330/29738758-e8b2-4649-921c-76850a6558fd)
When I just want to change my face, it doesn't work. Can you give me a workflow example?

**Comment by cubiq** [comment]
try with inpainting. there's a workflow for that

**Comment by zhanwenchen** [comment]
@SamTyurenkov I found the missing workflow JSONs from a fork: https://github.com/zigzag-tech/ComfyUI_IPAdapter_plus/blob/main/examples/IPAdapter_inpaint.json
