### ISSUE TITLE
InstantId

### ISSUE THREAD

**Issue by TingTingin** [cubiq/ComfyUI_IPAdapter_plus#242]
looking into https://github.com/InstantID/InstantID it seems like its actually also uses insightface and ipadapter might be easy to integrate

**Comment by hben35096** [comment]
The effect is fantastic!!
Hopefully, it will work well with other nodes in Comfyui.

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/139383150/0a1100b3-3493-4f0f-87a0-74ea8ea1a2e6)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/139383150/b91a2654-8f88-4684-82c3-f2282c8b3575)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/139383150/73ec22e5-7fb2-4df1-9193-668b53481158)

**Comment by cubiq** [comment]
OMG we are all gonna die!
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/76b0d1dd-4295-4d5e-b8ef-35df396be59a)

**Comment by hben35096** [comment]
> OMG we are all gonna die! !


This feature has been added??!!!

**Comment by cubiq** [comment]
I'm just kidding, just wanted to show that I'm working on the instantid extension. It's so similar to IPAdapter that I could put everything together (but I will make an external plugin)

**Comment by xiaohu2015** [comment]
> I'm just kidding, just wanted to show that I'm working on the instantid extension. It's so similar to IPAdapter that I could put everything together (but I will make an external plugin)

yes, IP-Adapter plus ControlNet, i would also like to combine InstantID with other ip adapters

**Comment by hben35096** [comment]
It's really exciting

**Comment by zsxkib** [comment]
great work!

**Comment by johndpope** [comment]
@zho-zho-zho crafted comfyui-instantid - I'm looking to use ip adapter with it. 

this is the repo - 
https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/

I want to plug in an image ref instead of the text prompt as described here
https://github.com/InstantID/InstantID/issues/56

anyone able to assist?

**Comment by hben35096** [comment]
> crafted comfyui-instantid - 我想用 ip 适配器来使用它。
> 
> 这是回购 - https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/
> 
> 我想插入图像引用而不是文本提示，如此处所述 InstantID[/InstantID#56](https://github.com/InstantID/InstantID/issues/56)
> 
> 有人能帮忙吗？
> 
> 更新 - 看起来有一些更新的工作流程 ![Screenshot from 2024-01-25 13-46-02](https://private-user-images.githubusercontent.com/289994/299521236-a7af3ad0-75a1-4a85-ad85-d49afeffd576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjExMDgsIm5iZiI6MTcwNjE2MDgwOCwicGF0aCI6Ii8yODk5OTQvMjk5NTIxMjM2LWE3YWYzYWQwLTc1YTEtNGE4NS1hZDg1LWQ0OWFmZWZmZDU3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwNTMzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzAwMGU4ZTExMzEwMTkwM2YxZWJhMDZmZDkyYWJjYTI4MmNhMzhlYmY1OTc2ZThmOGEzZWQxZTk3MTc2MzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kbmlQKDKplRfuwmazm2IuYW0Cbi9galdMeVD6U-7k7Y)



> @ZHO-ZHO-ZHO crafted comfyui-instantid - I'm looking to use ip adapter with it.
> 
> this is the repo - https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/
> 
> I want to plug in an image ref instead of the text prompt as described here [InstantID/InstantID#56](https://github.com/InstantID/InstantID/issues/56)
> 
> anyone able to assist?

As far as I know, ZHO's ComfyUI-InstantID can't even connect to the one that comes with Comfyui
KSampler, although its version can be opened in Comfyui, is difficult to use with other nodes in Comfyui.

**Comment by GXcells** [comment]
> OMG we are all gonna die! ![image](https://private-user-images.githubusercontent.com/427614/298708416-76b0d1dd-4295-4d5e-b8ef-35df396be59a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjk1NTMsIm5iZiI6MTcwNjE2OTI1MywicGF0aCI6Ii80Mjc2MTQvMjk4NzA4NDE2LTc2YjBkMWRkLTQyOTUtNGQ1ZS1iOGVmLTM1ZGYzOTZiZTU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwNzU0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2VmOTU3NGM1N2EwYmNmYmNkZDVhZTQ3NWU1NTFkYjcyYTAwMjQyZTFiMWQ1ZjkzMjg2NmVlZTcwOWQ5YzA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uqRk-aE0m0uP0ZW6UuYXqIJy1TgsJohWb_5TcWr07to)

There is also a LORA for InstandID to add in addition to the IP adapter?

**Comment by GXcells** [comment]
> @ZHO-ZHO-ZHO crafted comfyui-instantid - I'm looking to use ip adapter with it.
> 
> this is the repo - https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/
> 
> I want to plug in an image ref instead of the text prompt as described here [InstantID/InstantID#56](https://github.com/InstantID/InstantID/issues/56)
> 
> anyone able to assist?
> 
> UPDATE - looks like there's some updated workflows ![Screenshot from 2024-01-25 13-46-02](https://private-user-images.githubusercontent.com/289994/299521236-a7af3ad0-75a1-4a85-ad85-d49afeffd576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjk5OTAsIm5iZiI6MTcwNjE2OTY5MCwicGF0aCI6Ii8yODk5OTQvMjk5NTIxMjM2LWE3YWYzYWQwLTc1YTEtNGE4NS1hZDg1LWQ0OWFmZWZmZDU3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwODAxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDdlYzdkN2EwMTdjZjg0ODMwYjZkYjZjMjQ5MTE0ZDUxOGM5ZmU2M2FiYWRhYmZkZmMzMjcxOGU4NWMyZjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HIIqIdSAMoBXISv99CbiyvyQnL4Nx4loUDNe7kmV74M)

This repo is a bit complicated. 
I will wait for Cubiq's own implementation that will be probably much cleaner and easy.

**Comment by jesenzhang** [comment]
> > @ZHO-ZHO-ZHO crafted comfyui-instantid - I'm looking to use ip adapter with it.
> > this is the repo - https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/
> > I want to plug in an image ref instead of the text prompt as described here [InstantID/InstantID#56](https://github.com/InstantID/InstantID/issues/56)
> > anyone able to assist?
> > UPDATE - looks like there's some updated workflows ![Screenshot from 2024-01-25 13-46-02](https://private-user-images.githubusercontent.com/289994/299521236-a7af3ad0-75a1-4a85-ad85-d49afeffd576.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjk5OTAsIm5iZiI6MTcwNjE2OTY5MCwicGF0aCI6Ii8yODk5OTQvMjk5NTIxMjM2LWE3YWYzYWQwLTc1YTEtNGE4NS1hZDg1LWQ0OWFmZWZmZDU3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwODAxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDdlYzdkN2EwMTdjZjg0ODMwYjZkYjZjMjQ5MTE0ZDUxOGM5ZmU2M2FiYWRhYmZkZmMzMjcxOGU4NWMyZjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HIIqIdSAMoBXISv99CbiyvyQnL4Nx4loUDNe7kmV74M)
> 
> This repo is a bit complicated. I will wait for Cubiq's own implementation that will be probably much cleaner and easy.

I'm waiting too.

**Comment by johndpope** [comment]
I ask @zho-zho-zho to switch his insightfaceloader over - https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/issues/49 - please upvote.

**Comment by thibaudart** [comment]
> OMG we are all gonna die! ![image](https://private-user-images.githubusercontent.com/427614/298708416-76b0d1dd-4295-4d5e-b8ef-35df396be59a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNDM3NjgsIm5iZiI6MTcwNjM0MzQ2OCwicGF0aCI6Ii80Mjc2MTQvMjk4NzA4NDE2LTc2YjBkMWRkLTQyOTUtNGQ1ZS1iOGVmLTM1ZGYzOTZiZTU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwODE3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzYxOTFkMWFiYTZiNWI2MzIzMDZlNzY5NGNmM2I5OGE0NWYzMTVjOTI5ZjY5OGJlNjkwOWNhZmY4Y2JmMjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AFdVlJBAbfkzRnj6B7Pbfwx404CG71tiwCivvXtpsKY)

did you fix your last issue with the controlnet part?

**Comment by cubiq** [comment]
not completely I have issues with high/low CFG for some reason. I hadn't much time to work on it yet unfortunately.

**Comment by thibaudart** [comment]
thanks to start the implementation . maybe if you share someone can find a solution. 
you did an important work with your extension. thank you so much.

**Comment by cubiq** [comment]
@thibaudart I have no problem at sharing my shitty code :smile: https://github.com/cubiq/ComfyUI_InstantID

that is the base code, but more work is needed, it's not the latest version that I have locally but it's a good starting point.

**Comment by hben35096** [comment]
https://github.com/Mikubill/sd-webui-controlnet/discussions/2589
ControlNet has added Instant ID and seems to fix some issues

**Comment by thibaudart** [comment]
@cubiq thanks for sharing!
@hben35096 it's for webui not comfy :(

**Comment by jesenzhang** [comment]
Any updates?

**Comment by spenc-r** [comment]
Curious if attention masking would work with InstantID. Any resources anyone could point me to? Found [this commit](https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/bf0508bd5945c6e301070fa92b65b5ddbae9a8f1) but hard for me to understand, as I am new to SD.

**Comment by johndpope** [comment]
https://github.com/InstantID/InstantID/pull/89 this has some masking - [spenc-r](https://github.com/spenc-r)

**Comment by cubiq** [comment]
yes attention masking is possible

**Comment by qqqllppp** [comment]
ZHO^3 's [instantID](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID) eats too much vram, im getting oom even on 12gb vram 😭 Im crossing my fingers hoping the implementation here would eat less vram 🙏🏼

**Comment by JorgeR81** [comment]
> ZHO^3 's instantID eats too much vram, im getting oom even on 12gb vram

I think this may be due to a bug in that implementation.
https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/issues/66

( and apparently InstantID works well in A1111, with 6gb vram, in low vram mode )
https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/issues/66#issuecomment-1914496544

**Comment by thibaudart** [comment]
the biggest issue with Zho implementation is the fact we can’t use it in a
complex workflow :(



T

**Comment by cubiq** [comment]
I just pushed a tiled node for IPAdapter and I'm also working on a clip-vision mask option (probably tomorrow), then I'll check the InstantID. I think I have it 90% sorted out already

**Comment by hortom** [comment]
Maybe it could be useful: I added some amateur-ish VRAM optimisations to ZHO's node here: https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/pull/87

**Comment by cubiq** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/90eea876-2e95-44e8-860e-51fe6c003254)

It is finally working!

I'll post the code tomorrow

**Comment by cubiq** [comment]
Okay the InstantID native code is live. I think it's still beta but seems to be working very well. **Please** read the README file for important information.

https://github.com/cubiq/ComfyUI_InstantID

<img src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/aa544e56-5f3c-4533-ac2c-753b8d46fe02" width="512" height="512" alt="instantid" />

<img src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/6514e42a-9189-4855-8ff0-74fd2a4a08ad" width="512" height="512" alt="instantid" />

/cc @xiaohu2015

**Comment by camoody1** [comment]
@cubiq Thank you! Quick question... In your Readme file, you mention watermarks being everywhere. Is this because of the turbo model you're using or from the InstantID model?

**Comment by cubiq** [comment]
it comes from the instantID model. it can be fixed easily by changing the resolution slightly

**Comment by hortom** [comment]
As I see, it is suggested to use a preprocessor for the sample images for insight face. I use padding for the pose.

**Comment by edtjulien** [comment]
@cubiq Thanks so much for your work!

**Comment by cubiq** [comment]
also supports multiple people

![ComfyUI_temp_shjmq_00009_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/8ed7822a-c856-410b-8164-666dddb36aa3)
