### ISSUE TITLE
Models not detected within ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models  within StabilityMatrix

### ISSUE THREAD

**Issue by ForestEco** [cubiq/ComfyUI_IPAdapter_plus#244]
Will someone please help me figure out why the loader wont find the models I have in the models folder? 
I've tried placing models in both locations and used the Comfy-UI Manager extension as well with no success in its directory.

Am I missing a step below? I saw one video had a .zip folder for all the models and the speaker was able to use it, but they don't come that way on the HuggingFace file sharing, so I am not sure how to repack it or how if that step is needed or perhaps not?

My current steps:
1. Git cloned the repo or tried the Manager tool
2. Tried placing the models here: 
- StabilityMatrix\Data\Packages\ComfyUI\models\ipadapter
-StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models

GUI shows "undefined" and "Null" in place of model names, but I have models located in the models folder.
ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65578840/502daffe-45a0-4985-b9b8-c8ed2dd89410)

Here is the folder:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65578840/ae1e8e36-3168-40a8-a6a8-9e8466b30035)

**Comment by ForestEco** [comment]
**SOLUTION**: Looks like I could place the models **in the StabilityMatrix models** folder rather than into ComfyUI at all. Hope this helps someone else! But the embeds didn't pick up the models in the folder.

**Comment by Sorry-Im-Stupid** [comment]
Is there a solution to this problem for Linux? I've tried putting the files in both folders and neither work.
