### ISSUE TITLE
InsightFaceLoader not working. "module 'cv2.gapi.wip.draw' has no attribute 'Text'"

### ISSUE THREAD

**Issue by waynoedm** [cubiq/ComfyUI_IPAdapter_plus#251]
New install of ComfyUI. IPAdapter Plus itself works fine. However, the it isn't working with InsightFace models.

> Error occurred when executing InsightFaceLoader:
> 
> module 'cv2.gapi.wip.draw' has no attribute 'Text'
> 
> File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 535, in load_insight_face
> from insightface.app import FaceAnalysis
> File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 16, in
> from . import model_zoo
> File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\__init__.py", line 1, in
> from .model_zoo import get_model
> File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
> from .arcface_onnx import *
> File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 9, in
> import cv2
> File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 181, in
> bootstrap()
> File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 175, in bootstrap
> if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
> py_module = importlib.import_module(module_name)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "importlib\__init__.py", line 126, in import_module
> File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\typing\__init__.py", line 156, in
> Prim = _typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
> ^^^^^^^^^^^^^^^^^^^^^^

**Comment by procomp91** [comment]
Had this problem because I also had reactor installed. disabling/uninstalling it did the trick. I finally got them both running at the same time using the solution from this thread: https://github.com/Gourieff/comfyui-reactor-node/issues/139
