### ISSUE TITLE
"Load IPAdapter Model" node no longer respects my extra_model_paths.yaml

### ISSUE THREAD

**Issue by ManOrMonster** [cubiq/ComfyUI_IPAdapter_plus#254]
I use a custom path for ipadapter in my extra_model_paths.yaml.

At some point in the last few days the "Load IPAdapter Model" node no longer is following this path. I now need to put models in ComfyUI models\ipadapter.

Not sure how this could happen, as I don't see any changes in the code that would cause this. Maybe some other custom node is overriding it?

**Comment by cubiq** [comment]
does it work if you delete the model/ipadapter folder?

**Comment by ManOrMonster** [comment]
It did not. In fact, doing that broke the node until I restarted. After restart, no models available again.

**Comment by eniadel** [comment]
same problem
![Screenshot 2024-02-06 223048](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/125200111/f5a1905f-c0fa-4607-a9a9-3ab6060cc870)

**Comment by corolorn** [comment]
> does it work if you delete the model/ipadapter folder?
 Hi using tiledIpAdapter get this error, model in ComfyUI\models\ipadapter, delete and reinstal with manager not help
```
Error occurred when executing TiledIPAdapter:

'TiledIPAdapter' object has no attribute 'apply_patch'

File "C:\Users\corol\pinokio\api\comfyui.pinokio.git\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\corol\pinokio\api\comfyui.pinokio.git\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\corol\pinokio\api\comfyui.pinokio.git\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\corol\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI_TiledIPAdapter\nodes.py", line 45, in process
foo = IPAdapterApply.apply_ipadapter(self, ipadapter, model, ipadapter_weight, clip_vision, image, "original", 0.0, None, None)
File "C:\Users\corol\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 828, in apply_ipadapter
self.apply_patch(patch_kwargs)
```

**Comment by cubiq** [comment]
> It did not. In fact, doing that broke the node until I restarted. After restart, no models available again.

please check the issue tracker (also the closed issues). Others with the same problem seem to have found a solution.

I personally cannot replicate so it's very hard for me to escalate this issue

**Comment by JeffreyBull76** [comment]
> > It did not. In fact, doing that broke the node until I restarted. After restart, no models available again.
> 
> please check the issue tracker (also the closed issues). Others with the same problem seem to have found a solution.
> 
> I personally cannot replicate so it's very hard for me to escalate this issue

When you say others seem to have found a solution, searching for this topic finds only this reply (I cant see a solution even in the closed issues) could you direct me to the correct link please?

**Comment by corolorn** [comment]
> > > It did not. In fact, doing that broke the node until I restarted. After restart, no models available again.
> > 
> > 
> > please check the issue tracker (also the closed issues). Others with the same problem seem to have found a solution.
> > I personally cannot replicate so it's very hard for me to escalate this issue
> 
> When you say others seem to have found a solution, searching for this topic finds only this reply (I cant see a solution even in the closed issues) could you direct me to the correct link please?

Hello, I think we contacted the wrong developer, in my case most likely the error is from kinfolk0117/ComfyUI_TiledIPAdapter. I apologize to the developer of this repository.

**Comment by cubiq** [comment]
there's no need of a dedicated extension, Tiled IPAdapter is already supported here
