### ISSUE TITLE
IPAdapterApply Node is quite slow on A100

### ISSUE THREAD

**Issue by ynie** [cubiq/ComfyUI_IPAdapter_plus#257]
Hey all, 

I have 3 IPAdapterApply(IPAdapter Plus Face/IPAdapter Plus) nodes sin my workflow and I noticed each of them take ~4s on A100(total 12s). It doesn't seem like embedding speed things up.

Looking more close to the code:

 ```
self.ipadapter = IPAdapter(
            ipadapter,
            cross_attention_dim=cross_attention_dim,
            output_cross_attention_dim=output_cross_attention_dim,
            clip_embeddings_dim=clip_embeddings_dim,
            clip_extra_context_tokens=clip_extra_context_tokens,
            is_sdxl=self.is_sdxl,
            is_plus=self.is_plus,
            is_full=self.is_full,
            is_faceid=self.is_faceid,
        )
```

This blocks of code takes 90% of the time. 

Inside the IPAdapter init method, are we repeatedly loading the ipAdapter model into memory? Could these IPAdapters sharing the same model in memory? Thanks!

**Comment by cubiq** [comment]
technically yes, but that's not how comfyui works. I could add a "share model" option but that won't speed up the block of code that you are outlining (that is were the ipadapter model is applied), it would lower the memory usage though.

**Comment by ynie** [comment]
Thanks! I also notice the GPU utilization is almost 0 during IPAdapterApply. Are we doing the work here only on CPU?

**Comment by cubiq** [comment]
yeah we are very conservative with GPU memory considering people use comfy with 6gb of vram (or less), maybe I could check the available vram... I dunno, I'll consider it in the upcoming code rewrite.

**Comment by ynie** [comment]
Is there anything you would recommend me to try? I can even help submit a change.. I just want to know what can I even try to change to take advantage of the 80gb GPU ram.

**Comment by cubiq** [comment]
as far as I understand server grade gpus work a little different, I'm not 100% sure why and I can't make tests since I don't have access to one. I need to do a little code analysis but I'm about to perform a complete code rewrite so I'll work on that then

**Comment by tomudo** [comment]
May dev look into this. It does not use GPU , most load put into CPU during process.

**Comment by ynie** [comment]
Thanks. Who are the May dev? Is there a thread about it?

**Comment by cubiq** [comment]
I did a complete code rewrite, hopefully things got better
