### ISSUE TITLE
How do I stop it from unloading from vram? It is quite slow and has to load/reload all the time I run the workflow.

### ISSUE THREAD

**Issue by cian0** [cubiq/ComfyUI_IPAdapter_plus#258]
Are there any comfyui startup flags for it?

**Comment by ac-pill** [comment]
Hi @cubiq I have the same issue, but I'll decompose a bit.

Even using --highvram if the Apply IPAdapter node changes the input image batch, the models IP and Clip, are unloaded and loaded again.

If the node (and its dependent inputs are still the same), the model persists in memory, which is a bit contradictory as the input changes will necessarily happen. Do we need to load models per session with input change?

I'll try to check on the code at some point next week.

Great work on maintaining this repo.
