### ISSUE TITLE
Error occurred when executing InsightFaceLoader: Unable to import dependency onnxruntime.

### ISSUE THREAD

**Issue by irshadangillath** [cubiq/ComfyUI_IPAdapter_plus#259]
File "C:\Users\muhdi\OneDrive\Documents\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\muhdi\OneDrive\Documents\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\muhdi\OneDrive\Documents\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\muhdi\OneDrive\Documents\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 529, in load_insight_face
ip_k = ip_k * W
![Screenshot 2024-02-11 005310](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/159653664/052e4227-2d7e-48fe-9679-16b4a97f21e3)

**Comment by cubiq** [comment]
insightface is not properly installed https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162

**Comment by sajmon83** [comment]
You need to install onnxruntime
python.exe -m pip install onnxruntime
python.exe -m pip install onnxruntime-gpu
Remember that if you are using a virtual environment you must install in the virtual environment

**Comment by Nick-xl** [comment]
Error occurred when executing InsightFaceLoader_Zho:

[ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from J:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-InstantID\models\antelopev2\1k3d68. onnx failed:Protobuf parsing failed.

**Comment by WetDogma** [comment]
> Error occurred when executing InsightFaceLoader_Zho:
> 
> [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from J:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-InstantID\models\antelopev2\1k3d68. onnx failed:Protobuf parsing failed.
> 
> What went wrong, may I ask you？？

Ever work this out? I have the exact same error.

**Comment by cubiq** [comment]
`InsightFaceLoader_Zho:` you are using the wrong loader
