### ISSUE TITLE
Load IPAdapter Model node undefined

### ISSUE THREAD

**Issue by danilasenko** [cubiq/ComfyUI_IPAdapter_plus#262]
I put ipadapter model there
ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models\ip-adapter-plus_sdxl_vit-h.safetensors

But it doesn't show in Load IPAdapter Model in ComfyUI. All it shows is "undefined". Someone had a similar issue on reddit, saying that it stopped working properly after a recent update.

I am sorry, I am new to all this and wish I could provide more information.
Maybe there is some kind of command to check what location the node is using to get it's models or something?

**Comment by danilasenko** [comment]
ok, I figured it out. looks like the node takes models from Stability Matrix\Models\IpAdapter. I put my models there and now I can see them.

**Comment by alexdimella** [comment]
Same issue here. "Undefined" in load ipadapter model node. No other options in drop-down.

**Comment by alexdimella** [comment]
I would be great to have a folder button on each Custom node that when clicking it, it opens the folder location so you know where extensions should go more easily.
