### ISSUE TITLE
Error occurred when executing InstantIDFaceAnalysis:

### ISSUE THREAD

**Issue by RamonGuthrie** [cubiq/ComfyUI_IPAdapter_plus#263]
<img width="972" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/156688666/32374e4d-ce17-463f-a982-9c1fa718356a">

**Comment by RamonGuthrie** [comment]
> you need to post the full backtrace from the terminal not just a screenshot

Sorry here you go

**Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\models\insightface\models\antelopev2\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\models\insightface\models\antelopev2\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 359, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Prompt executed in 38.36 seconds**

**Comment by pvbang** [comment]
Same error: 
Error occurred when executing InstantIDFaceAnalysis:

File "/home/ubuntu/pvbang/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/pvbang/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/pvbang/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/pvbang/ComfyUI/custom_nodes/ComfyUI_InstantID/InstantID.py", line 360, in load_insight_face
model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # buffalo_l
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/pvbang/ComfyUI/venv/lib/python3.11/site-packages/insightface/app/face_analysis.py", line 43, in __init__
assert 'detection' in self.models
^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Dnozz** [comment]
Im getting this same error. I had to create the directory "insightface" and "instantid" in the models folder. After installing both neither were created. What am I doing wrong?

**Comment by mnnbir** [comment]
@Dnozz 
This worked, Thank You

**Comment by wenson** [comment]
> ComfyUI/models/insightface/models/antelopev2
fix my bug .

**Comment by parthwagh9999** [comment]
This error will resolve when you have models in perfect folder.

> Im getting this same error. I had to create the directory "insightface" and "instantid" in the models folder. After installing both neither were created. What am I doing wrong?
> 
> Nevermind.. I had the model in ./models/antelopev2/antelopev2/... cutting out a "antelopev2" directory fixed it. But still had to create the directories.

This solved my issue

**Comment by rachelcenter** [comment]
> This error will resolve when you have models in perfect folder.
> 
> > Im getting this same error. I had to create the directory "insightface" and "instantid" in the models folder. After installing both neither were created. What am I doing wrong?
> > Nevermind.. I had the model in ./models/antelopev2/antelopev2/... cutting out a "antelopev2" directory fixed it. But still had to create the directories.
> 
> This solved my issue

same i had the double /models/antelopev2/antelopev2/  THANK YOU!

**Comment by rokpopovic** [comment]
Hi, I have 2 questions.
1. I am installing this to ComfyDeploy so I can't unzip the folder once I download it. Is there a download link with unzipped file?
2. In which folder specifically should I put antelopev2 model?

**Comment by RunebinderOG** [comment]
Hi, I have the same error> I've checked the folder path and mine is ComfyUI\models\insightface\models\antelopev2 which should be correct reading the replies, but I can't get past the error. I've tried the zip file and when that didn't work I deleted it and used Comfy Manager to download the Antelopev2 files.

Any ideas as the only fix I can find is about the model path, but mine appears to be correct.

**Comment by ziguishian** [comment]
> Im getting this same error. I had to create the directory "insightface" and "instantid" in the models folder. After installing both neither were created. What am I doing wrong?
> 
> Nevermind.. I had the model in ./models/antelopev2/antelopev2/... cutting out a "antelopev2" directory fixed it. But still had to create the directories.

It works, thank you

<img width="674" height="257" alt="Image" src="https://github.com/user-attachments/assets/7859a361-fe26-4a52-8b0d-347308eab6d1" />
