### ISSUE TITLE
Question: inpaint workflow can run ,But no result

### ISSUE THREAD

**Issue by AILTY** [cubiq/ComfyUI_IPAdapter_plus#267]
Great job! But I run the workflow "IPAdapter_inpaint.json", find a question as follows, could you help me?
![1](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/30465925/1b695054-460d-4aca-b955-5123ad363d0f)

![2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/30465925/29ce1e83-aa5f-40b7-95f5-28d5f0240f21)

**Comment by cubiq** [comment]
change the image to inpaint and draw the mask with the mask editor
