### ISSUE TITLE
bad images with ipadapter on comfyui for sdxl

### ISSUE THREAD

**Issue by ykhasia** [cubiq/ComfyUI_IPAdapter_plus#270]
Attachement is my workflow json file and and reference image and generated image with ipadapter.
The image is bad.. what's wrong with my workflow configs ?

[workflow1.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14361373/workflow1.json)

![1](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/52735731/a01bbb1a-4319-4f3a-9dd8-5972b55f615e)
![IPAdapter_00035_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/52735731/4066aeed-985a-40d2-a935-7e8a49925ee2)

**Comment by zhichangyao** [comment]
I have the same issue. the face is well when I use 1.5 version model. it doesn't work when I use SDXL version.

**Comment by cubiq** [comment]
try to change checkpoint and vae. works as expected here.
