### ISSUE TITLE
How to input multiple images for the portrait model?

### ISSUE THREAD

**Issue by DENG-XC** [cubiq/ComfyUI_IPAdapter_plus#272]
![faceid_portrait_sd15](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/153186602/f1be0d69-d298-427a-97e5-1b02297d7a95)
Hi, there is an images indicate that the portrait model can be input multiple images for a better result, 
can someone tell me how to input multiple images in comfyui?

**Comment by VGF64** [comment]
I tried 4 different images of the same person and I keep getting this error.

![Screenshot (301)](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/126835875/5c3f5c61-a12e-4315-814d-5910235c06fc)

**Comment by cubiq** [comment]
that's an issue with the WAS node
