### ISSUE TITLE
Suddenly not models found

### ISSUE THREAD

**Issue by OPeixe** [cubiq/ComfyUI_IPAdapter_plus#274]
Hi, I was using IPAdapter_plus heavily in my generations, today it simply can't find any model, I have my models in the models/ directory under **custom_nodes\ComfyUI_IPAdapter_plus\models**. I've also tried to add them through extra_model_paths.yaml to my big container as **ipadapter: ipadapter/models** still no luck.

Please, I can't generate anything without IPAdapter_plus anymore, any help or ideas or suggestions will be greatly appreciated.

PD I repeat that I was using it without problems until today, i did not change anything in particular that I can think of.

**Comment by cubiq** [comment]
put them under ComfyUI/models/ipadapter

**Comment by OPeixe** [comment]
Thanks, it worked.
