### ISSUE TITLE
Difficulty applying styles to faces

### ISSUE THREAD

**Issue by ChrGriffin** [cubiq/ComfyUI_IPAdapter_plus#277]
I'm having difficulty getting my prompts to apply styles to the faces that come out of IPAdapter. They all come out clean and realistic-looking -- still according to the "base style" of the base model I'm using -- instead of having my styles applied to them, but the rest of the image accepts the style just fine. For instance, here's my attempts to create an oil painting of a face:

![ComfyUI_00498_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10466686/e494ba4c-2e59-403c-a0cc-cc36a1094f86)
![ComfyUI_00499_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10466686/41266562-53df-45f3-bc5b-cf7aee55cc19)
![ComfyUI_00500_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10466686/65e41add-c4c1-45ba-a835-039c2a43a30f)

As you can see, while the surrounding area (including the clothes and upper body) is happily taking the style of an oil painting, with brush strokes and other artifacts, the face itself is coming out smooth and more or less realistic (it's clearly TRYING to take in the style, just not very well). I've tried playing with the denoise in the Ksampler node and the weights in the Apply IPAdapter FaceID node, but whatever I try doesn't seem to be have any effect (or causes other problems, like setting the denoise way too low).

![Screenshot 2024-02-26 095624](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10466686/a769570d-a9eb-463d-97b0-80a676aa09a3)
![Screenshot 2024-02-26 095847](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10466686/7b03ff05-3a62-427b-8e0b-050799f194ef)

Am I missing something (I'll admit I'm new to ComfyUI), or is this a limitation of IPAdapter?

I'm using Realistic Vision 5.1 in the examples, but I've tried with various versions of Dreamshaper and Art Universe, and it's more or less the same problem, albeit with slightly more cartoonish/animeish base styles.

**Comment by ChrGriffin** [comment]
I mean, the HuggingFace page literally shows a chart of applying different styles to faces. And I am using the portrait model. But no worries, I'll keep tinkering. Thanks!

**Comment by cubiq** [comment]
"literally" they had to release a new model (faiceid potrait) because the standard faceid models are not great at keeping the resemblance at low weight. if you want to strongly style them you need to lower the weight
