### ISSUE TITLE
Embeds save to image output directory

### ISSUE THREAD

**Issue by kronkinatorix** [cubiq/ComfyUI_IPAdapter_plus#28]
It looks like the code tries to load embeds from the input directory but saves them to the default image output directory, with a default "embeds/" dialogue box opening up in comfyui itself. 

I symlinked the {default output}/embeds folder to input/embeds which fixed it, and changed 

files = [f for f in os.listdir(f'{input_dir}/embeds/') if os.path.isfile(os.path.join(input_dir, f)) and f.endswith(".ipadpt")]

to 

embedsdir = os.path.join(input_dir, 'embeds')
        files = [f for f in os.listdir(embedsdir) if os.path.isfile(os.path.join(embedsdir, f)) and f.endswith(".ipadpt")]

**Comment by cubiq** [comment]
yeah I hear you, that's how comfyui does things. I followed the guideline from the default nodes "save/load latent" which basically do the same thing. All saves go in /output, all inputs should go in /input

I agree it's a bit weird but that's how comfy works apparently.

**Comment by kronkinatorix** [comment]
I guess the issue was I didn't see how I could load the embeds without changing the code (my initial comment was too hasty :D). 

Updated with the tweak i made to the code anyway. All works now.

**Comment by kronkinatorix** [comment]
Also, entirely seperate issue that I can delete if needed, but I'm getting OOM errors constantly with this. 11gb 2080 ti. Think it's on comfy's end. You'd mentioned they changed something recently with memory handling - do you know when so I can roll back Comfyui to before that?

**Comment by cubiq** [comment]
try `--disable-smart-memory` and `--lowvram`

**Comment by cubiq** [comment]
this should be hopefully fixed
