### ISSUE TITLE
[Feature Request] unfold batch at 1 latent

### ISSUE THREAD

**Issue by MoonMoon82** [cubiq/ComfyUI_IPAdapter_plus#282]
Hi!

At first, let me describe my current issue:
Usually I need to chain several IPAdapters together with different reference images and masks to compose an (a single) image.
That leads to a confusing, exceeding workflow and (to me it seems) a higher workload during sampling process.

To solve this I had the idea to collect all different reference images and masks in batches (the order of ref. images and masks of course need to match!) to feed them all into ONE IPAdapter node.
Currently of course, on one hand this leads to a mixture of all ref. images and masks if the "unfold batch" option is disabled.
And on the other hand, as long as it's only sampling a single latent/image, only the first elements of the batches will be considered if the unfold batch is enabled.

Now the feature request:
Enabling the unfold batch option is useless (IMHO) as long you're only sampling one single latent image.
Could the behavior of the unfold batch option be changed, in case it's only sampling one single latent image? That would ease the pain of chaining many IPAdapters.

Kind regards

**Comment by cubiq** [comment]
no relevant anymore as the new version relies on "batch nodes" instead of unfold batch option

**Comment by MoonMoon82** [comment]
@cubiq I'm sorry, but this is not yet implemented yet, like the way I requested this feature!
It seems the new version of IPAdapter only considers the batched images, but not the batched attention masks! It's only considering the first mask and all batched images are mixed together instead of separated by each mask.

**Comment by cubiq** [comment]
not sure I follow, attention masks are always batched

**Comment by MoonMoon82** [comment]
@cubiq Yes, but my feature request was about if ONE latent is used - then all batched reference images and the according attention masks should be applied all at once.

If my feature request would be implemented, the following example would work:
![grafik](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/41437842/da446d24-7025-47bc-a692-b42bb4f60444)
(currently the IPAdapter Batch (Adv.) node does not work that way, neither the usual IPAdapter node does)

**Comment by cubiq** [comment]
that is not possible because the attention mask is one per ipadapter per latent. To do what you are asking you need to daisychain 2 ipadapters.

**Comment by MoonMoon82** [comment]
@cubiq Yes, but daisychaining is exactly what I want to avoid! That is what my workflows make huge, complicated and slow.

Now after the update, I could also imagine, that adding an att_mask input to the IPAdapter Encoder node would also be sufficient - instead of my original feature request.
![grafik](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/41437842/eb501086-ae37-4301-8809-da9c479339d2)

**Comment by MoonMoon82** [comment]
I really hoped there is a tiny chance to minimize the complexity of workflows and especially the VRAM usage (particularly in SDXL it's horrible) by using 1 IPAdapter instead of multiple IPAdapters chained together. 

But ok, I understand! Thank you for caring!

**Comment by cubiq** [comment]
I thought about it a little better and while it's true that with the current implementation it wouldn't be possible, I think it's actually feasible with a bit of code rewrite. I'll put it in my to-do but I'm not sure when I'll be able to do it and if the added complexity will be worth it
