### ISSUE TITLE
Use the basic workflow will generate some bad results

### ISSUE THREAD

**Issue by zhiyuXiao1221** [cubiq/ComfyUI_IPAdapter_plus#283]
<img width="1474" alt="Snipaste_2024-03-01_12-54-44" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/68151509/75f476be-6087-4532-852b-e4728b095d13">
  I have no idea why this happens, though i have updated my instantID, i also tries some other sdxl modesl, this same issue still happens

**Comment by cubiq** [comment]
that is instantid not ipadapter.

anyway you need to upgrade comfyui
