### ISSUE TITLE
'NoneType' object is not subscriptable - self.is_full = "proj.3.weight" in ipadapter["image_proj"]

### ISSUE THREAD

**Issue by xpluscal** [cubiq/ComfyUI_IPAdapter_plus#287]
I just setup the workflow exactly as described here: https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/regional-ipadapter.png

Getting the following error, anyone has an idea?

<img width="888" alt="Screenshot 2024-03-06 at 17 18 12" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/3706722/51361232-ac28-431c-a27e-4d9e465b7496">

**Comment by xpluscal** [comment]
What makes you think that? I was wondering if it was related to: https://github.com/cubiq/ComfyUI_IPAdapter_plus/pull/266

**Comment by cubiq** [comment]
do you an AMD card?

**Comment by fengxiaofeng1** [comment]
My problem has been solved,This is because your IPadapter missing

**Comment by Alexander-RPR** [comment]
> Mi problema se ha solucionado, esto se debe a que falta el adaptador de IP.

Please could you explain in more detail what you mean?
Because for example I get that error even though I have the IPAdapter installed
