### ISSUE TITLE
style aligned support

### ISSUE THREAD

**Issue by extra-large-onions** [cubiq/ComfyUI_IPAdapter_plus#289]
( Sorry to ask this here. I have no idea where else to ask ) Any chance you can write an extension for [style aligned](https://github.com/google/style-aligned) ? There's another implementation at https://github.com/brianfitzgerald/style_aligned_comfy but it hasn't been updated for a while and quite buggy.

**Comment by cubiq** [comment]
if I had the time... :smile:
