### ISSUE TITLE
[Windows] Runs using the same seed produce different results with certain negative embeddings

### ISSUE THREAD

**Issue by nickve28** [cubiq/ComfyUI_IPAdapter_plus#29]
It seems certain negative embeddings cause repeated runs, using the same configuration, to give different images as result. A friend checked this on a linux machine and it seemed to work fine there.

I've tried changing the denoise settings or other settings but the culprit seems to be in negative embeddings.
I've attached a small workflow which runs 2 samplers, which should, with the same configuration, return the same image.

but instead the following images are returned.
1.
![ComfyUI_temp_fmeyt_00008_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/4688199/a2a34956-d37c-4e36-83b2-b38a7ee0a306)
2.
![ComfyUI_temp_uvpzn_00006_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/4688199/3f63c90c-385b-4b55-81c6-309ba7cd66f4)

They're identical, but slightly different.
I used the following pic as input.
![rose](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/4688199/42efc491-9cc1-430f-93dd-2549c8b3bc45)

If i replace the negative embedding `embedding:ng_deepnegative_v1_75t` with `embedding:EasyNegative`, it does seem to work. So it seems very specific.

Do you have any idea what could cause this quite particular behavior?

**Comment by cubiq** [comment]
this is so specific (windows+only_with_this_one_embedding) that I don't even know where to start to debug this :smile: Maybe your friend has a different version of comfy? If they are on linux they probably have the latest installed.

Also does it do the same without IPAdapter?

**Comment by nickve28** [comment]
Hey, thanks for the swift reply!

Upgrading to pytorch cu121 seemed to have solved the issue. I was on the cu118 version before.

It seemed specific to IPadapter because pictures without were reproducible.
