### ISSUE TITLE
I have a problem with Apply IPAdapter node.

### ISSUE THREAD

**Issue by Dendi4a** [cubiq/ComfyUI_IPAdapter_plus#290]
I have a problem when using Apply IPAdapter node. 

I get this: 

Error occurred when executing IPAdapterApply:

Error(s) in loading state_dict for Resampler:
size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).

File "C:\Users\admin\Desktop\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\admin\Desktop\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\admin\Desktop\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\admin\Desktop\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 769, in apply_ipadapter
self.ipadapter = IPAdapter(
^^^^^^^^^^
File "C:\Users\admin\Desktop\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 369, in __init__
self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
File "C:\Users\admin\Desktop\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by afd2046** [comment]
Error occurred when executing IPAdapter:

Error(s) in loading state_dict for Resampler:
size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1024]).

File "E:\1111111111_ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\1111111111_ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\1111111111_ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\1111111111_ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 517, in apply_ipadapter
return (ipadapter_execute(model.clone(), ipadapter['ipadapter']['model'], ipadapter['clipvision']['model'], **ipa_args), )
File "E:\1111111111_ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 272, in ipadapter_execute
ipa = IPAdapter(
File "E:\1111111111_ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 68, in __init__
self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
File "E:\1111111111_ComfyUI\venv3\lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by LukeG89** [comment]
Just copied from the **Common Issues**:

▶️ **size mismatch for proj_in.weight: copying a param with shape torch.Size([..., ...]) from checkpoint, the shape in current model is torch.Size([..., ...])**

Any tensor size mismatch error is caused by the wrong combination of IPAdapter model, image encoder and/or base checkpoint.

All -vit-h models require the SD1.5 image encoder. At the moment only one SDXL model and the vit-G SD1.5 model need the bigger image encoder.

If you use the dedicated Encode IPAdapter Image you need to remember to select the ipadapter_plus option when you use any of the plus model.

**Comment by afd2046** [comment]
> 执行 IPAdapter 时出错：
> 
> Resampler 的加载state_dict错误：proj_in.weight 的大小不匹配：使用形状割炬复制参数。尺寸（[1280， 1280]） 从检查点开始，当前模型中的形状为火炬。大小（[1280， 1024]）。
> 
> 文件“E：\1111111111_ComfyUI\execution.py”，第 151 行，recursive_execute output_data，output_ui = get_output_data（obj， input_data_all） 文件“E：\1111111111_ComfyUI\execution.py”，第 81 行，get_output_data return_values = map_node_over_list（obj， input_data_all， obj.FUNCTION， allow_interrupt=True） 文件 “E：\1111111111_ComfyUI\execution.py”，第 74 行，在 map_node_over_list results.append（getattr（obj， func）（**slice_dict（input_data_all， i））） 文件“E：\1111111111_ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py”，第 517 行，apply_ipadapter返回 （ipadapter_execute（model.clone（）， ipadapter['ipadapter']['model']， ipadapter['clipvision']['model']， **ipa_args）， ）文件“E：\1111111111_ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py”，第 272 行，ipadapter_execute ipa = IPAdapter（ 文件“E：\1111111111_ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py”，第 68 行，**init** self.image_proj_model.load_state_dict（ipadapter_model[“image_proj”]） 文件“E：\1111111111_ComfyUI\venv3\lib\site-packages\torch\nn\modules\module.py”，第 2153 行，load_state_dict raise RuntimeError（'加载 {} state_dict时出现错误：\n\t{}'.format（

刚刚解决了，严格阅读安装要求，各模型放入对应文件夹，不要改名字。
Strictly read the installation requirements and place each model in its corresponding folder without changing its name

**Comment by LukeG89** [comment]
> 刚刚解决了，严格阅读安装要求，各模型放入对应文件夹，不要改名字。

Great, but this is a problem of wrong combination of IPAdapter model, image encoder and/or base checkpoint. 

- What checkpoint are you using?
- What IPAdapter model?
- What Clip Vision?

Check if the combination of these three models are correct and try again

**Comment by cubiq** [comment]
this thread went a little overboard. feel free to open a new one if you still have issues
