### ISSUE TITLE
使用FaceID的过程中

### ISSUE THREAD

**Issue by weakorpunyones** [cubiq/ComfyUI_IPAdapter_plus#298]
![微信图片_20240319145319](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/163387094/8419e580-6f02-4647-8aa8-3dc97e4ca765)

**Comment by weakorpunyones** [comment]
![1710831423679](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/163387094/d82d2597-8add-4277-9d31-0a60e9036e18)

**Comment by cubiq** [comment]
if buffalo_l is not downloaded automatically you have to get it manually like from here https://github.com/deepinsight/insightface/releases

**Comment by weakorpunyones** [comment]
> 如果buffalo_l没有自动下载，则必须手动获取它，就像从这里 https://github.com/deepinsight/insightface/releases

放在这个提示的文件里吗？

**Comment by cubiq** [comment]
you need to unzip the file under the following directory:

`ComfyUI/models/insightface/models/buffalo_l/`

**Comment by weakorpunyones** [comment]
> 您需要将文件解压缩到以下目录下：
> 
> `ComfyUI/models/insightface/models/buffalo_l/`

可我用的是Stable Diffusion

**Comment by cubiq** [comment]
if you use automatic1111 webui then you are asking in the wrong repository
