### ISSUE TITLE
Performance degradation since update of `ip-adapter-faceid_sdxl_lora`

### ISSUE THREAD

**Issue by julien-blanchon** [cubiq/ComfyUI_IPAdapter_plus#301]
This isn't really a `ComfyUI_IPAdapter_plus` problem, but I'd like to see if anyone else is experiencing the same problem.
My previous workflow using `ip-adapter-faceid_sdxl_lora` was no longer working as expected and was giving fairly poor results. I discovered that this was due to a change in the control point of `ip-adapter-faceid_sdxl_lora`. See this post I made in the `h94/IP-Adapter-FaceID` hf repo: https://huggingface.co/h94/IP-Adapter-FaceID/discussions/46

Have you figured out why this new LoRA is malfunctioning and have you figured out how to adjust your workflow to make it work?

**Comment by cubiq** [comment]
I can't help with that, sorry. Consider that the image might look better but the face embeds look closer with the new version. I should check with the face analysis tools but at the end it's very personal
