### ISSUE TITLE
ipadater not working ?

### ISSUE THREAD

**Issue by bihailantian655** [cubiq/ComfyUI_IPAdapter_plus#304]
![{A9AC423E-B52C-48dd-96BF-A8826D12EAF4}](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/35267721/b4fdf68c-e5b5-4786-a02b-e01c57076af0)

pic1 is  the   pic for  clip vision    ,   pic3  is  the  attention  mask  of  the  pants ,  pic2 is  the   result   after  sample .   text  promt  is  a girl  wearing  red pants  .  why  the  result    is  yellow  color .

**Comment by cubiq** [comment]
closing for now
