### ISSUE TITLE
Today's update breaks everything but the kitchen sink

### ISSUE THREAD

**Issue by NetAndif** [cubiq/ComfyUI_IPAdapter_plus#308]
Need to realize that from now on, most of my workflows will not work anymore.
But what currently bugs me awfully is that i can't try the beautiful Krita integration with my ComfyUI.
Is there a way to downgrade to the old version?
This is a really sad situation, i think.

**Comment by NetAndif** [comment]
But i do understand the intention of the Author.
Live goes on.

**Comment by NetAndif** [comment]
Hint: Krita works nicely with its own installed ComfyUI

**Comment by cubiq** [comment]
I warned you! :smile: 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/52dc77d3-b70f-4a60-9d88-30909f69eb03)

anyway you can revert to any prior version. that's the beauty of git

**Comment by NetAndif** [comment]
I feel like i haven't been warned though ;)
Well, i don't always check the github page for the changes before i update.
I rather trust them if they are in ComfyUI.
However, this is a special case. I am not a conservative guy.
I don't insist in things that used to work for me, but now don't, because the creator decided to change the path to go.

**Comment by cubiq** [comment]
this is an important update, there was no other way. It opens to far better control of the embeds. I'll post a video soon

**Comment by NetAndif** [comment]
Thanks a lot man. As i said, life goes on and i am open to anything you come up with :)
