### ISSUE TITLE
Import failed on torch 1.13.0

### ISSUE THREAD

**Issue by 49RpK5dY** [cubiq/ComfyUI_IPAdapter_plus#309]
Fails to import after update on torch: 1.13.0+rocm5.2
```
Traceback (most recent call last):
  File "/sd/ComfyUI/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/sd/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/__init__.py", line 17, in <module>
    from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/sd/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 13, in <module>
    import torchvision.transforms.v2 as T
ModuleNotFoundError: No module named 'torchvision.transforms.v2'

Cannot import /sd/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus module for custom nodes: No module named 'torchvision.transforms.v2'
```

**Comment by RONNYKHALIL** [comment]
+1

**Comment by cubiq** [comment]
you need to update torch, you must have a very old version

**Comment by RONNYKHALIL** [comment]
> Fails to import after update on torch: 1.13.0+rocm5.2
> 
> ```
> Traceback (most recent call last):
>   File "/sd/ComfyUI/nodes.py", line 1888, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/sd/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/__init__.py", line 17, in <module>
>     from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "/sd/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 13, in <module>
>     import torchvision.transforms.v2 as T
> ModuleNotFoundError: No module named 'torchvision.transforms.v2'
> 
> Cannot import /sd/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus module for custom nodes: No module named 'torchvision.transforms.v2'
> ```

Speaking for myself here so YMMV, but i'm using Paperspace and the whole Torch updating issue has been a pain point for a while now. But i just found this posted 2 weeks ago, and it worked! 

https://github.com/TheLastBen/fast-stable-diffusion/issues/2670#issuecomment-1983323737

"Here's a workaround.

Run the notebook as usual.
Open a terminal from the icon on the left menu bar.
Paste this and press enter: pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 xformers==0.0.23post1
Restart the kernel and rerun the notebook. The updated packages will now persist."

this worked for me. hope this helps!

**Comment by 49RpK5dY** [comment]
Sadly this is the latest version that works on RX5700 so updating torch is impossible without buying a new gpu first.

**Comment by cubiq** [comment]
I'll add a fallback tomorrow

**Comment by 49RpK5dY** [comment]
Thanks. Would love to check the new features.

**Comment by cubiq** [comment]
should work now

**Comment by 49RpK5dY** [comment]
Still fails with the same error.

**Comment by 49RpK5dY** [comment]
Thanks. Works again.
