### ISSUE TITLE
In ComfyUI, there's an error when using ip-adapter-plus_sdxl_vit-h.bin as IPAdapter model and sd1.5 image encoders

### ISSUE THREAD

**Issue by dodo522** [cubiq/ComfyUI_IPAdapter_plus#31]
![企业微信截图_16967596872784](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/66875947/ff335edd-b4ed-4301-a7c4-2a52fcb9a899)
The workflow file is here:
[Uploading ipadapter_error.zip…]()

and this is the model I use:
checkpoint: sd_xl_base1.0
IpAdapter model and image encoder mode:
![企业微信截图_16967597948988](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/66875947/6905f6f4-15a2-44ca-8168-cfc13a968382)

**Comment by cubiq** [comment]
you are using an older version of ComfyUI, you need to update

**Comment by dodo522** [comment]
Update ComfyUI works, thanks :)
