### ISSUE TITLE
Error occurred when executing IPAdapterUnifiedLoaderFaceID:  ClipVision model not found.

### ISSUE THREAD

**Issue by LukeG89** [cubiq/ComfyUI_IPAdapter_plus#310]
Just tried the new `ipadapter_faceid` workflow:

![ClipVision_not_found](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/161304036/d6df7d1c-402d-41f4-a4ef-9ea0dae0b7f5)

**Comment by cubiq** [comment]
update and use the naming suggested in the readme. otherwise let me know how the clipvision is called

**Comment by LukeG89** [comment]
Ok, now it's working!
