### ISSUE TITLE
Error occurred when executing IPAdapterUnifiedLoaderFaceID:

### ISSUE THREAD

**Issue by RamonGuthrie** [cubiq/ComfyUI_IPAdapter_plus#311]
Hi, I am getting an error the **models** used to be placed here: _D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models_

Where do the **models** go now, and **what should the folder be named**? 

> Error occurred when executing IPAdapterUnifiedLoaderFaceID:
> 
> IPAdapter model not found.
> 
> File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 151, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 81, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\execution.py", line 74, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "D:\Stable_Diffusion\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 382, in load_models
> raise Exception("IPAdapter model not found.")
<img width="1346" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/156688666/0b2390c3-0ce4-44ae-b66e-1cc26896da1c">

**Comment by LukeG89** [comment]
Hi, you should place your models inside `ComfyUI\models\ipadapter`

**Comment by RamonGuthrie** [comment]
> ipadapter

Thanks that solved the problem
