### ISSUE TITLE
Where is the Channel Penalty weight type in the new version ?

### ISSUE THREAD

**Issue by Djanghost** [cubiq/ComfyUI_IPAdapter_plus#314]
Hello,

This type of weight is not present in the new version. Impossibe to recover the results of our old workflows by replacing our old nodes with the new ones without this type of weight.

Could you fix this ?

Thank you

**Comment by cubiq** [comment]
the author insists on releasing the channel penalty code under a commercial license, I asked him multiple times but got no answer so I cannot include it into a GPL licensed code.

I'll see if I can reach similar results in another way

**Comment by Djanghost** [comment]
this is very sad, didnt find any alternative testing all the new weight types. For people having this big issue, use Impact Pack that still have Channel Penalty as weight type.

**Comment by cubiq** [comment]
I have an idea on how to make it no worries

**Comment by Djanghost** [comment]
It would be great as i prefere your nodes, i come back to the previous commit of your repo waiting this !
Full support for all your work.

**Comment by cubiq** [comment]
it's already implemented, I'll push it tomorrow
