### ISSUE TITLE
node types were not found:  IPAdapterApply

### ISSUE THREAD

**Issue by soklamon** [cubiq/ComfyUI_IPAdapter_plus#318]
Hey, using the following workflow that includes the node IPAdapterApply 
https://civitai.com/articles/3194/guide-adding-ip-adapter-to-your-animations-including-batch-unfold-an-inner-reflections-guide

I have tried to delete and replace the IPAdapter nodes, but I am not sure what is the new equivalent of IPAdapterApply? 

The closest seems to be IPAdapter Advanced but it does not include the Noise parameter. Also the weight_type does not include the option Original (is it linear the equivalent?)

**Comment by sacd1859** [comment]
I have the same question.
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/30915573/588392d1-93f0-47e2-b783-d31008416fdd)

**Comment by cubiq** [comment]
Please check the main README file and the examples directory

**Comment by sacd1859** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cpucpu1477** [comment]
换旧版本就好了

**Comment by nothingness6** [comment]
I faced the same issue. Have you figured it out?

**Comment by soklamon** [comment]
> Please check the main README file and the examples directory

I checked the example directory 
but it is not clear to me which node replaces IPAdapterApply

**Comment by soklamon** [comment]
> I faced the same issue. Have you figured it out?

no solution for now, 
I when back to the last February version

**Comment by soklamon** [comment]
> 换旧版本就好了

yes, this is what I did for now too

**Comment by soklamon** [comment]
> Please check the main README file and the examples directory

sorry, but this is not a closed issue. 
the problem is that we do not know the connection between the old and new nodes. it is rather risky and complicated to redesign workflows that have been working

**Comment by LukeG89** [comment]
@soklamon To understand the new nodes you can watch this video tutorial: [IPAdapter v2: all the new features!](https://youtu.be/_JzDcgKgghY)

**Comment by cubiq** [comment]
@soklamon IPAdapter Advanced it's a drop in replacement of IPAdapter Apply.

just take an old workflow delete ipadapter apply, create an ipadapter advanced and move all the pipes to it. It will work like before

**Comment by 1376588939** [comment]
> 换旧版本就好了

你好，请问这个旧版哪里有啊

**Comment by LukeG89** [comment]
> > > 换旧版本就好了
> > 
> > 
> > yes, this is what I did for now too
> 
> Could you please provide the old version of the IPAdapter?

@1376588939 Here you go: https://github.com/cubiq/ComfyUI_IPAdapter_plus/tree/6a411dcb2c6c3b91a3aac97adfb080a77ade7d38

**Comment by audioscavenger** [comment]
> @soklamon IPAdapter Advanced it's a drop in replacement of IPAdapter Apply.
> 
> just take an old workflow delete ipadapter apply, create an ipadapter advanced and move all the pipes to it. It will work like before

I believed you until I notice the noise input is not matched: what is it replaced by? 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/3853962/b4b18102-611b-4cc0-a62c-5a1d17fa19e7)

**Comment by sacd1859** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nexusdragoon** [comment]
> > @soklamon IPAdapter Advanced it's a drop in replacement of IPAdapter Apply.
> > just take an old workflow delete ipadapter apply, create an ipadapter advanced and move all the pipes to it. It will work like before
> 
> I believed you until I notice the noise input is not matched: what is it replaced by? ![image](https://private-user-images.githubusercontent.com/3853962/327593924-b4b18102-611b-4cc0-a62c-5a1d17fa19e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjYyODksIm5iZiI6MTcxNDcyNTk4OSwicGF0aCI6Ii8zODUzOTYyLzMyNzU5MzkyNC1iNGIxODEwMi02MTFiLTRjYzAtYTYyYy01YTFkMTdmYTE5ZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMDg0NjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDY5NWEzMDZkNzc5NjgwYjRlODFmMjc5ZjI1MTAzN2VjMWRiYTYyNzc5OTQ5Y2U5YjY3ZjA0YzA1MzUzMTM2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ebmCjJPqk67ZWpWckeSSitDWLHCtxSl5rYgziU35kWQ)

convert widget to input

**Comment by nexusdragoon** [comment]
> > @soklamon IPAdapter Advanced it's a drop in replacement of IPAdapter Apply.
> > just take an old workflow delete ipadapter apply, create an ipadapter advanced and move all the pipes to it. It will work like before
> 
> I believed you until I notice the noise input is not matched: what is it replaced by? ![image](https://private-user-images.githubusercontent.com/3853962/327593924-b4b18102-611b-4cc0-a62c-5a1d17fa19e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjYyODksIm5iZiI6MTcxNDcyNTk4OSwicGF0aCI6Ii8zODUzOTYyLzMyNzU5MzkyNC1iNGIxODEwMi02MTFiLTRjYzAtYTYyYy01YTFkMTdmYTE5ZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMDg0NjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDY5NWEzMDZkNzc5NjgwYjRlODFmMjc5ZjI1MTAzN2VjMWRiYTYyNzc5OTQ5Y2U5YjY3ZjA0YzA1MzUzMTM2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ebmCjJPqk67ZWpWckeSSitDWLHCtxSl5rYgziU35kWQ)

The “IP Adapter apply noise input” in ComfyUI was replaced with the IPAdapter Advanced node. [This new node includes the clip_vision input, which seems to be the best replacement for the functionality that was previously provided by the “apply noise input” feature](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/321)

**Comment by occultskyrong** [comment]
> 换旧版本就好了

我切换到这个版本，可以用

```
https://github.com/cubiq/ComfyUI_IPAdapter_plus/tree/6a411dcb2c6c3b91a3aac97adfb080a77ade7d38
```

**Comment by sacd1859** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by icemagno** [comment]
YOU MESSED ALL THIS, MAN...
This "UNIFIED" is a piece of shit. All freedom was gone. 
Please, stop making shit and bring back the old loader and the adapterapply.

**Comment by sacd1859** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cubiq** [comment]
> YOU MESSED ALL THIS, MAN... This "UNIFIED" is a piece of caca. All freedom was gone. Please, stop this and bring back the old loader and the adapterapply.

the old loader is still there

**Comment by Kelthic** [comment]
> https://github.com/cubiq/ComfyUI_IPAdapter_plus/tree/6a411dcb2c6c3b91a3aac97adfb080a77ade7d38

Hell yeah, bro. You saved my life. Thank you a lot!

**Comment by sacd1859** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
