### ISSUE TITLE
IPAdapter Unified Loader FacelD module error

### ISSUE THREAD

**Issue by rong7932** [cubiq/ComfyUI_IPAdapter_plus#319]
![微信截图_20240324230714](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/61302333/f62bef13-ae9e-4be7-88d3-43b4a0721e3d)

The file contains the model, selecting any option will result in an error

**Comment by LukeG89** [comment]
Yesterday I had the same problem: https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/310

**Comment by rong7932** [comment]
> ![微信截图_20240324230714](https://private-user-images.githubusercontent.com/61302333/316318812-f62bef13-ae9e-4be7-88d3-43b4a0721e3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjU0OTAsIm5iZiI6MTcxMTMyNTE5MCwicGF0aCI6Ii82MTMwMjMzMy8zMTYzMTg4MTItZjYyYmVmMTMtYWU5ZS00YmU3LTg4ZDMtNDNiNGEwNzIxZTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAwMDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NDFmM2I5MmUwZDEyZjliNTdhOGRhNDcxYTIzMTQwYjhiZDE1ZDIzNjcyYThlNzE1YzBkOGRiNTRhOWY2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mjd5zzL1JG2Jo6rqLCjkxzwoK6OiMXctPZReAl4Kd44)
> 
> 文件包含模型，选择任何选项都会导致错误

The solution was solved by modifying clip_vision and changing model.safetensors to CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors. 
![微信截图_20240325080048](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/61302333/8ece02ad-882f-408f-813a-dc4df3240a6e)
Then the error continues. Are the names and positions of other models adjusted? Result Unable to read original model location name?

**Comment by xingren23** [comment]
same issue

**Comment by LukeG89** [comment]
> Are the names and positions of other models adjusted?

Are your models located in `ComfyUI/models/ipadapter`? If not, move all your ipadapter models there. Also I think you have to keep the original file names as well

**Comment by rong7932** [comment]
> > 其他型号的名称和位置是否进行了调整？
> 
> 您的模型位于 ？如果没有，请将所有 ipadapter 型号移到那里。此外，我认为您还必须保留原始文件名`ComfyUI/models/ipadapter`

Thank you for reminding me. I moved the original model location {ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\models} to the location you mentioned and it solved the problem.

**Comment by jokero3answer** [comment]
需要改clip模型的名称吗

**Comment by LukeG89** [comment]
> 需要改clip模型的名称吗

Yes, you have to name them:

- CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
- CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors

**Comment by VLevithan** [comment]
Hello! And I have a similar problem.
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/160181737/18247dce-9d4e-4c99-9919-fca7ebf40db8)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/160181737/a43517f5-39bc-4746-8a93-34770513150e)
Efficient Loader Models Cache:
Ckpt:
  [1] dreamshaper_8
Lora:
  [1] base_ckpt: dreamshaper_8
      lora(mod,clip): add_detail_tweaker_SD1.5(3.0,1.0)
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 388, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

**Comment by Conmiro** [comment]
@VLevithan since you're using StabilityMatrix, you need to put your IpAdapter files inside:
`\AppData\Roaming\StabilityMatrix\Models\IpAdapter`

**Comment by VLevithan** [comment]
> @VLevithan since you're using StabilityMatrix, you need to put your IpAdapter files inside: `\AppData\Roaming\StabilityMatrix\Models\IpAdapter`

I've already figured it out. It's case-sensitive, you have to write everything in small letters, then it finds it. Thanks)
