### ISSUE TITLE
Where take the other parameter files ? (Not clear from install instructions)

### ISSUE THREAD

**Issue by ProkopHapala** [cubiq/ComfyUI_IPAdapter_plus#32]
I installed ComfyUI in order to test this very promissing plugin (before I was using automatic 1111 webgui for stable diffusion, so I have no experience with ConfyUI)

When I load the workflow form json file there are set these models:
vae-ft-mse-840000-ema-pruned.safetensors
control_v11p_sd15_canny_fp16.safetensors

where can I download them?

**Comment by cubiq** [comment]
vae-ft-mse-840000-ema-pruned.safetensors is just the vae that I'm using. If you google the name you can find it straight away

control_v11p_sd15_canny_fp16.safetensors is a controlnet processor, again google the name as it is and you'll find it on huggingface
