### ISSUE TITLE
What happened to the Apply IPAdapter node?

### ISSUE THREAD

**Issue by a-niess** [cubiq/ComfyUI_IPAdapter_plus#321]
I cannot locate the `Apply IPAdapter` node. Has it been deleted? If so, what node do you recommend as a replacement? ComfyUI and `ComfyUI_IPAdapter_plus` are up to date as of 2024-03-24.

<img width="590" alt="Screenshot 2024-03-24 at 4 52 25 PM" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135653878/fa6dd69d-3d23-427a-9246-4c9b4a6c42d6">

**Comment by LukeG89** [comment]
Read this: https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#warning-ipadapter-v2-complete-code-rewrite-warning

You can use `IPAdapter` or `IPAdaper Advanced`: 

![ipadapter_menu](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/161304036/8ba04cd4-4240-4166-95ae-d2e0b3e8fe0f)

**Comment by spammeduh** [comment]
Thank you for all your effort in updating this amazing package of nodes. I've found that a direct replacement for `Apply IPAdapter` would be the `IpAdapter Advanced`, I'm itching to read the documentation about the new nodes! For now, I will try to download the example workflows and experiment for myself. Thank you!

**Comment by a-niess** [comment]
Thanks @LukeG89 @spammeduh. `IPAdapter Advanced` seems like the best replacement since it includes `clip_vision` inputs.

**Comment by a-niess** [comment]
Thanks @LukeG89 and @spammeduh. `IPAdapter Advanced` seems like the best replacement since it includes `clip_vision` inputs.
