### ISSUE TITLE
Some thoughts on V2

### ISSUE THREAD

**Issue by clayne** [cubiq/ComfyUI_IPAdapter_plus#324]
1. As a matter of principle, unless there's a really good reason for it, breaking changes should be avoided. Backwards compatibility is paramount. IMO the new nodes should be released as V2 suffixes for all of them and the "legacy" nodes kept for some reasonable period of time for transition. This allows people to migrate to the new nodes without breaking all their workflows and causing undue cognitive load out of the blue to figure out what's going on. It also preserves the validity of all the tutorials out there etc while still offering a path to use the new code via new "V2" nodes. I get the desire to rewrite things and delete "old" code but there needs to be a balance here.

2. IPAdapterAdvanced offers an image input whereas IPAdapater does not but relies on the unified loader. This is kind of awkward to use in a way, particularly when people are already used to loading an ip adapter model alongside something like "Apply IPAdapter". Additionally the updated workflow example / screen cap  immediately jumps right into the deep end with multiple images, embedding merges, etc. whereas most people starting out are just using a single image.

3. If the unified loader is supposed to be the "simple" approach, why not just roll it into IPAdapter then? I understand that the way the various upstream ip adapter models has been released is a bit of a confusing mess (particularly when used with control net) and the unfixed loader might be trying to work around that there's just something about the V2 approach that seems more awkward to use for people who are used to how the old model control flows worked.

4. Similar to point 1, if you know everything will break and everything has changed then I would try and avoid "get-there-itis" and add updated documentation first, even if it delays the release. A week or two isn't going to make or break anybody's workflows but the alternative of not doing it is going to cause chaos. I know you're strapped for resources and all of this takes a ton of work. It isn't unnoticed or unappreciated. I'm sharing my thoughts as a professional developer (albeit in a different line of work).

**Comment by cubiq** [comment]
thanks for your feedback. I do not have much to say. I suggest you to revert to the previous version. The main features are all there.
