### ISSUE TITLE
Cache Optimization for InsightFace in IPAdapter Unified Loader FaceID

### ISSUE THREAD

**Issue by ozbayb** [cubiq/ComfyUI_IPAdapter_plus#326]
Thanks for the continued improvement of IPAdapter Plus – it's been incredibly useful. I've noticed a small issue in the "IPAdapter Unified Loader FaceID" node where the insightface model re-caches more often than it seems it should, especially after unrelated changes in the model pipeline. This recaching adds unnecessary wait times.

### Steps to Reproduce:
1. Set up the pipeline including insightface.
2. Notice insightface caches on first run.
3. After any upstream model pipeline tweak, insightface recaches.

### Expected Behavior
Insightface keeps its cache unless directly impacted by changes. This could save us some valuable time and streamline our workflow.

### Workaround
We still have the ability to load the lora, ipadapter model, and insightface through separate nodes, but I would prefer to use the unified node for its convenience.

### Suggested Fix
Could there be a way to check if changes directly affect insightface before deciding to recache?

Thanks for your hard work on this project; it's greatly appreciated.

**Comment by cubiq** [comment]
yeah it's already in my to-do, thanks for the headsup

**Comment by dchatel** [comment]
Meanwhile, in `utils.py` line 124, you can replace the function with this one:
```python
insightface_faceanalysis = None
def insightface_loader(provider):
    global insightface_faceanalysis
    if insightface_faceanalysis is None:
        try:
            from insightface.app import FaceAnalysis
        except ImportError as e:
            raise Exception(e)

        path = os.path.join(folder_paths.models_dir, "insightface")
        model = FaceAnalysis(name="buffalo_l", root=path, providers=[provider + 'ExecutionProvider',])
        model.prepare(ctx_id=0, det_size=(640, 640))
        insightface_faceanalysis = model

    return insightface_faceanalysis
```

It will have a slightly bad effect of keeping insightface in memory until you close comyfui, but insightface model doesn't eat that much memory anyway.

**Comment by cubiq** [comment]
this should be fixed
