### ISSUE TITLE
PrepImageForClipVision error: 'module' object is not subscriptable

### ISSUE THREAD

**Issue by a-niess** [cubiq/ComfyUI_IPAdapter_plus#327]
When using `PrepImageForClipVision` I am getting the below error. I have updated ComfyUI_IPAdapter_plus since the recent changes. Thanks for all your work with the updates and improvements. Any suggestions on resolving this error?

<img width="1108" alt="Screenshot 2024-03-25 at 10 27 44 AM" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135653878/9bb67bba-65e1-45ec-b728-924c9b81e460">

```
Error occurred when executing PrepImageForClipVision:

'module' object is not subscriptable

File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 1042, in prep_image
img = img.resize(size, resample=Image.Resampling[interpolation])
```

**Comment by kinfolk0117** [comment]
Ensure you have a recent version of pillow. I had the same problem and solved with `pip install pillow==10.2.0`
