### ISSUE TITLE
could anyone tell me how to roll back to a previous version of this one?

### ISSUE THREAD

**Issue by e-tier-n00b** [cubiq/ComfyUI_IPAdapter_plus#328]
I tried replacing the nodes to match the new version, but the results are not as good as before, so I want to download the custom node folder of the previous version of "ComfyUI_IPAdapter_plus" and roll it back, how could I do that?

**Comment by LukeG89** [comment]
Here you go: https://github.com/cubiq/ComfyUI_IPAdapter_plus/tree/6a411dcb2c6c3b91a3aac97adfb080a77ade7d38

**Comment by LukeG89** [comment]
> > Here you go: https://github.com/cubiq/ComfyUI_IPAdapter_plus/tree/6a411dcb2c6c3b91a3aac97adfb080a77ade7d38
> 
> thanks for letting me know where to get it, maybe GitHub has a way to go back to the point-in-time code by date? I'll look into it a bit more, thanks.

As far as I know, I think there are a couple of git commands: `git reset` and `git revert`  

This user suggested using the reset one: https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/317
