### ISSUE TITLE
[Not an issue] My xp with the noise option

### ISSUE THREAD

**Issue by Guillaume-Fgt** [cubiq/ComfyUI_IPAdapter_plus#33]
As you are asking for feedback in your readme, I did several test with the noise option. In my case, it makes the image closer to what I ask in the prompt without having to reduce the weight of the ipadapter. 
For example:
> grim reaper origami, minimalist background, 8k photo wallpaper
* CFG 5.5
![ComfyUI_00290_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/66461774/c422020e-fe59-46a9-b69b-58a2f9093d6f)
* CFG 9.0
![ComfyUI_00291_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/66461774/e7254747-f713-422f-9c01-994ac4ab4387)

Origami and minimalist background are clearly more prominent in the "1" version. The Ipadapter weight is at 0.35.
I wonder if you should not change the name though. Maybe inspired by ControlNet, something like "my prompt is more important"? And just keep a switch with 0 and 1 values applied?

**Comment by cubiq** [comment]
thanks for your feedback, really appreciate it.

I agree "noise" is a bit misleading but couldn't find anything better at that moment. The effect of noise varies based on checkpoint and the prompt of course. Noise 1 sometimes burns the image too much so having .25/.5./.75/1 would be probably better, but at that point we could better just leave all the spectrum... even though --as everything with SD-- the results are often random :smile:

**Comment by Guillaume-Fgt** [comment]
> the results are often random

so true...This is why I had the idea of decreasing the "noise" to 2 values. But I understand your point. Having so much parameters at every level is sometimes overwhelming.
