### ISSUE TITLE
Images for example workflows?

### ISSUE THREAD

**Issue by zackabrams** [cubiq/ComfyUI_IPAdapter_plus#331]
Hey! Any chance we can get the images used for the example workflows? It would help to understand the new features. 
Thanks for all your hard work!

**Comment by cubiq** [comment]
you can use really whatever you want. I'm not sure I can distribute all the pictures, some of them are here
![face2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/ebba7332-fdba-41d7-aae0-32264f6ab35a)
![portrait](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/3934f595-8114-41e1-9876-f7b74fad1746)
![girl_sitting](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/8b1c56c3-1cf9-4a74-93f8-973c177bb4ed)

![warrior_woman](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/2fbd6da9-6005-420c-ae3c-7b53d6f44683)
