### ISSUE TITLE
CLIP continues to report errors

### ISSUE THREAD

**Issue by yuegu2401** [cubiq/ComfyUI_IPAdapter_plus#332]
![e76932db6166679861ecb0d86b08cb0](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/157941633/e3411197-1b30-45ce-8b55-8e138879cf92)
Whichever way you choose. CLIP always reports mistakes, and the video doesn't make it clear
![639f6df9127a864dee5809cdbf266dc](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/157941633/1bc0399d-0e6a-4420-8dbb-be7eb9abce2c)
![903ee9a3ef65e90d4e43bd524600284](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/157941633/1055d3e1-864c-4cbc-a22f-000145f0df5c)
![d9f3b639e9bec23f6f398789f0fec16](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/157941633/da7aec11-c277-4921-9c08-5d6a2331a0d0)

**Comment by cubiq** [comment]
you need to delete the now deprecated IPAdapter_ComfyUI Extension. Use only ComfyUI_IPAdapter_Plus
