### ISSUE TITLE
Exception: insightface model is required for FaceID models

### ISSUE THREAD

**Issue by MohammadAboulEla** [cubiq/ComfyUI_IPAdapter_plus#333]
INFO: InsightFace model loaded with CPU provider
Requested to load CLIPVisionModelProjection
Loading 1 new model
D:\programing\Stable Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:345: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\programing\Stable Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programing\Stable Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programing\Stable Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programing\Stable Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 837, in apply_ipadapter
    return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programing\Stable Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 176, in ipadapter_execute
    raise Exception("insightface model is required for FaceID models")
Exception: insightface model is required for FaceID models

Prompt executed in 9.24 seconds

how can I fix this! I have tried uninstall and re insatll insightface  but nothing works for me

**Comment by cubiq** [comment]
impossible to say without seeing the workflow

**Comment by MohammadAboulEla** [comment]
[workflow.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14758626/workflow.json)

**Comment by cubiq** [comment]
you need to use IPAdapter FaceID for FaceID models and also connect the insightface pipeline. Otherwise you can use the unified loader and connect ONLY the ipadapter pipeline.

At the moment it's not possible to use the IPAdapter Embeds with FaceID, I might work on that if there's interest

**Comment by OranJo** [comment]
Same problem.I reinstalled FreeU_advanced node to version 3ce68d4, fixed.
