### ISSUE TITLE
[Feature]: use DEPRECATED in the future

### ISSUE THREAD

**Issue by dchatel** [cubiq/ComfyUI_IPAdapter_plus#334]
For future breaking updates, instead of "there will be blood", don't remove obsolete nodes right away. Put a DEPRECATED warning either in the name or in the generation process, or both, put the obsolete nodes in a DEPRECATED folder. So people know they will eventually have to change their workflow soon, instead of suddenly breaking everyone workflows without warning.

**Comment by cubiq** [comment]
revert back to the previous version. GIT is great for that
