### ISSUE TITLE
Confused by IPadapter unified loader, where should I put the models？Thanks!

### ISSUE THREAD

**Issue by chimelea666** [cubiq/ComfyUI_IPAdapter_plus#335]
I've downloaded the models, and rename them as FacelD, FacelD Plus, FacelD Plus v2, FacelD Portrait, and put them in E:\comfyui\models\ipadapter flolder. But when I use IPadapter unified loader, it prompts as follows.

Error occurred when executing IPAdapterUnifiedLoaderFaceID:

ClipVision model not found.

File "E:\comfyui-auto\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\comfyui-auto\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\comfyui-auto\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\comfyui-auto\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 373, in load_models
raise Exception("ClipVision model not found.")

**Comment by AugustRush** [comment]
models/clip_vision

**Comment by cubiq** [comment]
please read the documentation. "Installation instructions"
