### ISSUE TITLE
ClipVision model not found

### ISSUE THREAD

**Issue by shimib577** [cubiq/ComfyUI_IPAdapter_plus#337]
I am trying to use the new IPAdapter UnifiedLoader
It tells me I don't have the CLIPVISION models
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/165001443/51042576-36ce-4345-8c15-79967986beee)

**Comment by luoluoluooo** [comment]
same error

**Comment by cubiq** [comment]
The clipvision models are the following and should be re-named like so:
[CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors) and [CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors)

**Comment by giusparsifal** [comment]
> The clipvision models are the following and should be re-named like so: [CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors) and [CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors)

Hello, I'm a newbie and maybe I'm doing some mistake, I downloaded and renamed but maybe I put the model in the wrong folder. Coul you tell me where I have to save them? Thanks!

**Comment by jia10000** [comment]
ComfyUI-aki-v1.3\models\clip_vision

**Comment by giusparsifal** [comment]
> ComfyUI-aki-v1.3\models\clip_vision

Hello and thanks, I stored also there but nothing works...

**Comment by LiEH222** [comment]
> > ComfyUI-aki-v1.3\models\clip_vision
> 
> 您好，谢谢，我也存储在那里，但没有任何效果......
出现了一样的问题，请问解决了吗？

**Comment by carloslogg** [comment]
> The clipvision models are the following and should be re-named like so: [CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors) and [CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors)

ok but, where to load these models mate?

**Comment by Axiongs** [comment]
I had the same problem

**Comment by Olalekan-Ojo** [comment]
This worked for me .... But im somewhere trapped at this 


IPAdapter model not found

**Comment by Dahong1023** [comment]
ip-adapter-plus_sd15.safetensors
ComfyUI-aki-v1.3\models\ipadapter




> This worked for me .... But im somewhere trapped at this
> 
> IPAdapter model not found

**Comment by GCF-chFox** [comment]
I suggest taking a look at the author's introductionhttps://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file

**Comment by Vocall1986** [comment]
这个问题也困扰了我很久，当我发现comfyui文件夹里有extra_model_paths.yaml和extra_model_paths.yaml.example文件，删除了extra_model_paths.yaml.example文件后重启comfyui后一切运行正常。

This problem also bothered me for a long time. When I found that there were extra_model_paths.yaml and extra_model_paths.yaml.example files in the comfyui folder, I deleted the extra_model_paths.yaml.example file and restarted comfyui, everything ran normally.
