### ISSUE TITLE
Noob question about retroactive compatibility

### ISSUE THREAD

**Issue by User1231300** [cubiq/ComfyUI_IPAdapter_plus#339]
Hello Matteo from Abruzzo :).

Thank you for your hard work!

I use your IPadapter nodes for a variety of workflows that i  have consolidated trough time, and it would be a real pain for me to reconstruct them all, mostly because I have many workflows that differ slightly between one another, and it would mean reconstructing them one by one. 

For now, i have simply used the "git checkout" command to put the repo to the point right before the changes happened (i asked chatgpt how to do it...). But I was wondering: maybe i could keep the old version like this, and then "install" the new version in a separate folder? Would this be possible? What would I need to change to make it work?

**Comment by cubiq** [comment]
updating old workflows is very simple. the IPAdapter Advanced node is a drop in replacement of the previous IPAdapter Apply node. All you have to do is to reconnect the pipelines

**Comment by User1231300** [comment]
Thanks Matteo for the answer, i'll give that a try.
