### ISSUE TITLE
Exception: IPAdapter model not found.

### ISSUE THREAD

**Issue by dancemanUK** [cubiq/ComfyUI_IPAdapter_plus#342]
[rgthree] Using rgthree's optimized recursive execution.
INFO: Clip Vision model loaded from G:\comfyUI+AnimateDiff\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
!!! Exception during processing !!!
Traceback (most recent call last):
  File "G:\comfyUI+AnimateDiff\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "G:\comfyUI+AnimateDiff\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "G:\comfyUI+AnimateDiff\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 388, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

<img width="1571" alt="wechat_20240326211024" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1702623/22644494-edd5-4a7c-a7b5-dd10076cbb4d">
<img width="660" alt="wechat_20240326211124" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1702623/953702e1-34a4-4c28-9638-dec33bc4da35">

**Comment by LukeG89** [comment]
Are your IPAdaper models located in `ComfyUI/models/ipadapter`? If not, move all your ipadapter models there.

**Comment by dancemanUK** [comment]
> Are your IPAdaper models located in `ComfyUI/models/ipadapter`? If not, move all your ipadapter models there.

yes,  I copy all.

<img width="618" alt="wechat_20240326214847" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1702623/cd3bcc26-ef08-42e3-abd7-9adc55928c4c">
![Uploading wechat.png…]()

**Comment by dancemanUK** [comment]
it 's OK   delete   ipadapter: models/ipadapter     in extra_model_paths.yaml 
<img width="1088" alt="wechat_20240326221436" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1702623/e677b4da-c165-433f-985d-c8cb5ab2b156">
<img width="1538" alt="wechat_20240326221446" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1702623/5039d854-4b8f-470b-b3f6-ccab892159db">
