### ISSUE TITLE
Missing CLIPVision model.

### ISSUE THREAD

**Issue by wing349** [cubiq/ComfyUI_IPAdapter_plus#343]
CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors、CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors are already in the folder clip_vision，but Error executing ipadapter embeds

Error occurred when executing IPAdapterEmbeds:

Missing CLIPVision model.

File "G:\AI\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "G:\AI\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "G:\AI\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "G:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 838, in apply_ipadapter
raise Exception("Missing CLIPVision model.")

**Comment by SRagy** [comment]
I get the same issue, but my clip_vision models are in my AUTOMATIC1111 directory (with the comfyui extra_model_paths.yaml correctly pointing to this). They are also in .pth rather than safetensors format. Not sure if this relates.

**Comment by Seryogerr** [comment]
Same thing only with Unified loader
Have all models in right place
I tried:
Edit extra_model_paths
#     clip: models/clip/
#     clip_vision: models/clip_vision/
#     ipadapter: models/ipadapter/ 
Have legacy name clip_visions CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors  and CLIP-ViT-H-14-laion2B-s32B.safetensors in models/clip_vision/

.bin in models/ipadapter/  ofc

**Comment by AgitoRivers** [comment]
> I get the same issue, but my clip_vision models are in my AUTOMATIC1111 directory (with the comfyui extra_model_paths.yaml correctly pointing to this). They are also in .pth rather than safetensors format. Not sure if this relates.
> 
> EDIT: After looking through the code I renamed the files to CLIP-ViT-H-14-laion2B-s32B-b79K.bin and similarly with the other and this fixed the problem. Maybe you could try renaming the files; if yours are in .safetensors format then use .safetensors rather than .bin.
> 
> Additionally, if like me, your ipadapter models are in your AUTOMATIC1111 controlnet directory, you will probably also want to add `ipadapter: extensions/sd-webui-controlnet/models` to the AUTOMATIC1111 section of your extra_model_paths.yaml

Thanks

> I get the same issue, but my clip_vision models are in my AUTOMATIC1111 directory (with the comfyui extra_model_paths.yaml correctly pointing to this). They are also in .pth rather than safetensors format. Not sure if this relates.
> 
> EDIT: After looking through the code I renamed the files to CLIP-ViT-H-14-laion2B-s32B-b79K.bin and similarly with the other and this fixed the problem. Maybe you could try renaming the files; if yours are in .safetensors format then use .safetensors rather than .bin.
> 
> Additionally, if like me, your ipadapter models are in your AUTOMATIC1111 controlnet directory, you will probably also want to add `ipadapter: extensions/sd-webui-controlnet/models` to the AUTOMATIC1111 section of your extra_model_paths.yaml

Thanks mate, that helped!!

**Comment by cubiq** [comment]
I guess this is solved now

**Comment by 961516491** [comment]
Sorry, I didn't understand how to solve the problem.
I think I have already placed the file in models/clip_vision.
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/42242548/879f7867-64c2-48d5-9aa2-3a9bc64e2263)
This is my error report: 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/42242548/7d145a09-5d97-4330-a6fc-16b8e0876f25)
@cubiq

**Comment by CoUIfy** [comment]
Where do you get these files?

**Comment by x-GeneSin-x** [comment]
> Where do you get these files?

https://huggingface.co/laion

**Comment by lavibeats** [comment]
It worked for me thanks !

**Comment by GCF-chFox** [comment]
I suggest reading the author's introduction

https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file
