### ISSUE TITLE
ip_plus_composition_sdxl.safetensors

### ISSUE THREAD

**Issue by freke70** [cubiq/ComfyUI_IPAdapter_plus#344]
Hi,

Thanks for the great node.
I wondered if this is still compatible with the updated ipadapter?

https://huggingface.co/ostris/ip-composition-adapter/tree/main

I don't know if it is still possible to load different ipadapter models, besides the main ones.

Thanks!

**Comment by cubiq** [comment]
yes it is possible but you have to use the legacy loaders. I will add community models in a dedicated unified loader later on

**Comment by freke70** [comment]
Thanks, I got it working using the ipadapter advanced.
Using the ipadapter input and clipvision
