### ISSUE TITLE
The unexpected Tile result

### ISSUE THREAD

**Issue by 1zhangyy1** [cubiq/ComfyUI_IPAdapter_plus#345]
50%happen unexpected blank ，Use Ipadapter Tile

![20240327-193821](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/128666664/77d0cf0f-0d36-43bf-9330-681c47450788)

**Comment by cubiq** [comment]
please be sure to have the latest version installed. if you do please post the workflow and the reference image

**Comment by 1zhangyy1** [comment]
> please be sure to have the latest version installed. if you do please post the workflow and the reference image

![workflow](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/128666664/dea05f11-1231-4572-ae08-07bba15ecbfa)

It's the latest version,  50%happens ,I am so confuse,
It's the reference image 
![20240308-164429](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/128666664/9bd7cea4-697d-4d16-8e67-6aa12a40faa2)

**Comment by cubiq** [comment]
have you tried the tiled batch node? if you need multiple results with the tiled node I think you need the batch version

**Comment by cubiq** [comment]
Seems to be working

![tile_batch](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/5b466d3d-ff62-4ad8-932d-7260e881173a)

**Comment by 1zhangyy1** [comment]
Thank you very much for your testing, this is really strange. Whether or not “batch” is used with other images, the result is the same, but when I use this beach girl picture, there is also an abnormal white bar with “batch”. Could it be the cause of the picture (I have also tried a picture with the same resolution, which can also run normally)?
![workflow (3)](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/128666664/4e0b399b-1146-4633-8c3d-cd3fa57820d4)
![workflow (2)](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/128666664/b662610f-83a2-4c09-9f51-2d75cfd5e418)

**Comment by phoenisx** [comment]
Hi @cubiq 
This has been happening with me as well.

I debugged it a little bit, and found that cropping (segmentation) of the source image seems to change drastically when image aspect ration is `4:5`.
For me I got 4 segmented images instead of `2` (top and bottom segments of the image), when using a source image of size `720x900`.

**Comment by phoenisx** [comment]
I think this is also causing issues with using an `attn_mask` of the same size (720x900), cause the mask is broken into 4 segments, and changes the original mask entirely.

**Comment by cubiq** [comment]
I'm not able to replicate even with the standard (not batched) node. It's important to remember that the reference image should be more or less in the same aspect ratio of the final latent. If the difference it's too much the model might not be able to accomodate

![tiled](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/ea238f51-39aa-457b-aba4-6aeb3a9c9697)

**Comment by phoenisx** [comment]
Oh I think the discussion here is about some other issue, **_but I feel it's related to mine as well._**

I am seeing the following segments generated using IPAdapter Tiled Node:

<img width="1192" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/11786283/d4d089fe-e713-4994-adea-e1e7badd0f5e">

Is this expected? The source image is getting chopped into 4 pieces, of 256x256 square segmented images, and my mask has completely changed.
