### ISSUE TITLE
Testing v2, I am getting this error

### ISSUE THREAD

**Issue by Latentnaut** [cubiq/ComfyUI_IPAdapter_plus#347]
Hi Mateo,

testing your new actualization and I found this error:

The combination is `Unificed Loader FaceID` with `IPAdapter Embeds`. The error is asking for `Insigthface` model.

Any idea?

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22867200/537cee41-a550-4170-b79e-e888acb798bb)

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22867200/0920e5ce-6ec1-483f-8834-cda933ad66e3)

`Error occurred when executing IPAdapterEmbeds:

insightface model is required for FaceID models

File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 839, in apply_ipadapter
return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 176, in ipadapter_execute
raise Exception("insightface model is required for FaceID models")`

**Comment by Latentnaut** [comment]
The issue gets the same error with `Tiled`

**Comment by LukeG89** [comment]
FaceID only works with `IPAdaper FaceID` and `IPAdaper FaceID Batch` (https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/333)

**Comment by Latentnaut** [comment]
Oh I see, I thought the IPAdapter node was also unified.

That you for the help ;)
