### ISSUE TITLE
Why IPAdapter Encoder Node requires IPAdapter model to work? 

### ISSUE THREAD

**Issue by StellarBeing25** [cubiq/ComfyUI_IPAdapter_plus#351]
I planned to save merged embeddings and use them with both Plus-Face SD1.5 and Plus-Face SDXL since both use the same CLIP Vision encoder, but I saw that the IPAdapter Encoder Node also requires specific model input. Why does it require a model input for encoding? Can it work with just CLIP vision model?

**Comment by cubiq** [comment]
because the embeds change based on the ipadapter model. Plus face and plus face SDXL would be compatible with each other so you can do it.
