### ISSUE TITLE
Error occurred when executing IPAdapterUnifiedLoaderFacelD:

### ISSUE THREAD

**Issue by waenggl** [cubiq/ComfyUI_IPAdapter_plus#352]
Hello, I tried to use the workflow you provided [ipadapter_faceid.json], but it seems to have some issues when running. Can you tell me which folder these models should be placed in? I downloaded the faceid model but it doesn't seem to work. Could you please tell me the reason for this issue?
![1711618849448](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/151861391/66834d2f-7c49-4ec8-a369-1d5ac75ebc59)

**Comment by waenggl** [comment]
![Uploading 1711618721224.png…]()

**Comment by LukeG89** [comment]
The models have to be placed inside:
IPAdapers: `ComfyUI/models/ipadapter`
LoRAs: `ComfyUI/models/loras`
ClipVision: `ComfyUI/models/clip_vision`
Also named:
- CLIP-ViT-H-14-laion2B-s32B-b79K
- CLIP-ViT-bigG-14-laion2B-39B-b160k

If needed, you can also place all the modes inside subfolders.

Did you have renamed your LoRA? I think the Unified Loader can't find it because of that

**Comment by wibur0620** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/131615326/24f06b26-6a31-4c9f-9fed-0a0468047c7b)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/131615326/771ab73a-8b84-41a1-b0ca-07d2470c01cb)

**Comment by wibur0620** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/131615326/70025017-c09c-4661-a2bb-9d62adc75a53)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/131615326/85dac871-72a0-494c-a091-7be3711c1150)

**Comment by wibur0620** [comment]
why?

**Comment by LukeG89** [comment]
@wibur0620 That's strange, both SD15 and SDXL Portrait are working to me. Are your ComfyUI and IPAdapter updated to the latest version?

**Comment by TheWingAg90** [comment]
me too. i has error "Exception: IPAdapter model not found"
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/157227635/c800f199-d081-4340-b5eb-6a0694cdba9b)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/157227635/05965e7f-ed00-4c35-96c9-7bd8bab129e0)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/157227635/a96d22d8-dbbf-4a86-a8a2-d84ef48c4dec)

**Comment by cubiq** [comment]
I hope you guys solved this, I'm closing for now since it shouldn't be a bug
