### ISSUE TITLE
IPAdapterApply "Nodes that have failed to load will show as red on the graph."

### ISSUE THREAD

**Issue by altzh666** [cubiq/ComfyUI_IPAdapter_plus#354]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/34838717/6d539976-70d8-48ea-9a7f-099361b2f1b3)
help!everyone! I had do everything,but still can't got it.

**Comment by cubiq** [comment]
use IPAdapter Advanced instead
