### ISSUE TITLE
I'm new, need help to install

### ISSUE THREAD

**Issue by LuisHans** [cubiq/ComfyUI_IPAdapter_plus#355]
I have an issue, I try to use   IPAdapterApply node

![imagen](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/76133177/b9ba0fa7-a602-469a-82dc-5483a099560c)

I already have the repository installed
![imagen](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/76133177/f8c9cc77-acac-476d-92dd-940f65ff90d5)

custom_nodes folder:
![imagen](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/76133177/0b63e37c-7fb2-4223-928d-8f3a7f5c78c6)

And also I have the models
![imagen](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/76133177/b703c701-0a1d-4681-bb7d-f27dd42e8688)

![imagen](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/76133177/7f800ea0-15a0-4361-9773-0c9fc18bd6ea)

![imagen](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/76133177/72e0b598-dacb-476f-b85d-8708dbbe40c7)

In fact, there it doesn't appears in the search console

![imagen](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/76133177/d2fe61b1-48c6-4556-9b20-e6abbd840b8c)

The 'ipadapter' folder doesn't exist so I created and add into the 'folder_paths.py' file

![imagen](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/76133177/d64582ab-65bf-4c40-9734-b5fbf3a3a705)

Someone know what I forgot in the installation?

**Comment by LukeG89** [comment]
`Apply IPAdapter` doesn't exist anymore, recently Matteo (the owner of this node) has updated to V2 with a complete rewrite of the code. Now you can use `IPAdaper Advanced` instead.
I suggest you to watch his video tutorial so you can learn everything about the new nodes: [IPAdapter v2: all the new features!](https://youtu.be/_JzDcgKgghY)

**Comment by cubiq** [comment]
duplicate https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/354 please always check the previous bug reports
