### ISSUE TITLE
Clarification about Models' License for Commercial Usage.

### ISSUE THREAD

**Issue by MaxHelios** [cubiq/ComfyUI_IPAdapter_plus#356]
Hello.
I would like to clarify a few moments about IPAdapter models and their commercial usage. (Selling end result)

https://huggingface.co/h94/IP-Adapter-FaceID
States, that because of insightface, it is only for Non-Commercial usage.

https://huggingface.co/h94/IP-Adapter
Has apache-2.0 license. So it is allowed for commercial usage.

So, if I stick to using only models from https://huggingface.co/h94/IP-Adapter and CLIP models which allows commercial usage, does that mean I can use IPAdapter for commercial purpose?

**Comment by cubiq** [comment]
that is correct
