### ISSUE TITLE
Workflow that includes Refiner.

### ISSUE THREAD

**Issue by Beamhi** [cubiq/ComfyUI_IPAdapter_plus#36]
Could you explain or make a workflow that includes Refiner? When I try to include refiner, it hugely changes the style. Thanks!

**Comment by cubiq** [comment]
You apply the IPAdapter only to the base, not the refiner

![sdxl_workflow](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/c1412189-b924-40ae-9b2a-c134f22c7e80)

**Comment by Beamhi** [comment]
Thanks!!!
