### ISSUE TITLE
IPAdapter Model Not Found

### ISSUE THREAD

**Issue by jbm0674** [cubiq/ComfyUI_IPAdapter_plus#365]
Error occurred when executing IPAdapterUnifiedLoader:  IPAdapter model not found.  File "/Users/juliusmoore/AI-SD/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/Users/juliusmoore/AI-SD/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/Users/juliusmoore/AI-SD/StableSwarmUI/dlbackend/ComfyUI/execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/Users/juliusmoore/AI-SD/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 393, in load_models raise Exception("IPAdapter model not found.")

Models were placed where instructed, renamed if needed and I still can't solve this issue.

**Comment by vootox** [comment]
I'm getting the same error but only with the preset 'FACEID PLUS - SD1.5' selected from the dropdown list.

**Comment by cubiq** [comment]
post your directory structure

**Comment by vootox** [comment]
jbm0674 should have priority. Here's mine in the meantime...

C:\Users\Brian\Programs\ComfyUI_windows_portable_3\ComfyUI\models\ipadapter>dir /b
ip-adapter-faceid-plusv2_sd15.bin
ip-adapter-faceid-portrait-v11_sd15.bin
ip-adapter-faceid-portrait_sdxl.bin
ip-adapter-faceid_sd15.bin
ip-adapter-faceid_sdxl.bin
ip-adapter-full-face_sd15.safetensors
ip-adapter-plus-face_sd15.safetensors
ip-adapter-plus-face_sdxl_vit-h.safetensors
ip-adapter-plus_sd15.safetensors
ip-adapter-plus_sdxl_vit-h.safetensors
ip-adapter_sd15.safetensors
ip-adapter_sd15_light.safetensors
ip-adapter_sd15_light_v11.bin
ip-adapter_sd15_vit-G.safetensors
ip-adapter_sdxl.safetensors
ip-adapter_sdxl_vit-h.safetensors

C:\Users\Brian\Programs\ComfyUI_windows_portable_3\ComfyUI\models\loras>dir /b
DetailedEyes_V3.safetensors
ip-adapter-faceid-plusv2_sd15_lora.safetensors
ip-adapter-faceid-plusv2_sdxl_lora.safetensors
ip-adapter-faceid_sd15_lora.safetensors
ip-adapter-faceid_sdxl_lora.safetensors
lcm-lora-sdv1-5.safetensors
lcm-lora-sdxl.safetensors
lcm-lora-ssd-1b.safetensors
print_loras.txt
put_loras_here
v2_lora_PanLeft.ckpt
v2_lora_PanRight.ckpt
v2_lora_RollingAnticlockwise.ckpt
v2_lora_RollingClockwise.ckpt
v2_lora_TiltDown.ckpt
v2_lora_TiltUp.ckpt
v2_lora_ZoomIn.ckpt
v2_lora_ZoomOut.ckpt


C:\Users\Brian\Programs\ComfyUI_windows_portable_3\ComfyUI\models\clip_vision>dir /b
CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors
CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
put_clip_vision_models_here

**Comment by cubiq** [comment]
you miss
ip-adapter-faceid-plus_sd15.bin
ip-adapter-faceid-plus_sd15_lora.safetensors

**Comment by vootox** [comment]
Thank you! That fixed mine.
Before posting I had tried the 1st one (FaceID plus v1) but never included the 2nd (Lora), so when it didn't work and was deprecated I deleted it (in haste) but now I guess it needed both. Thanks again.

**Comment by jbm0674** [comment]
<img width="1216" alt="Screenshot 2024-03-30 at 8 14 23 AM" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/163554297/2cadc4f3-0241-489d-a61f-a9c9820afded">
<img width="1209" alt="Screenshot 2024-03-30 at 8 13 53 AM" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/163554297/091a42ee-cc22-4872-a574-5ddbe4c570df">

**Comment by jbm0674** [comment]
<img width="1195" alt="Screenshot 2024-03-30 at 8 11 44 AM" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/163554297/01b2bb04-d3e2-4aeb-b0d5-1704a817540e">

I didn't mean to split my response, shown is were my files are and what they are named, im running a MacBook Pro with an M3Pro Chip (if that matters any at all)

**Comment by jbm0674** [comment]
Hi there can you look at my files, im still getting that error?

**Comment by LukeG89** [comment]
@jbm0674 I think it is because your model folder is named `ip-adapter` instead of `ipadapter`

**Comment by jbm0674** [comment]
That was it, thanks
