### ISSUE TITLE
ERROR: Wheel 'insightface' is invalid.

### ISSUE THREAD

**Issue by arlechinu** [cubiq/ComfyUI_IPAdapter_plus#369]
Hi there! Was trying to get the faceIP working and install insightface but get this error:

ERROR: Wheel 'insightface' located at D:\ComfyUI01\insightface-0.7.3-cp311-cp311-win_amd64.whl is invalid.

Any ideas or a chance for a solution? Cheers!

**Comment by LukeG89** [comment]
Installing Insightface is a real pain. Did you check this issue? https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162 (especially this comment: https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162#issuecomment-1869035844)
