### ISSUE TITLE
ipadapter model loader

### ISSUE THREAD

**Issue by altroxa** [cubiq/ComfyUI_IPAdapter_plus#371]
ipadapter models do not appear in the "ipadapter model loader" node.

**Comment by emourdavid** [comment]
I have same problem. Even I re-clone this node many times, update ComfyUI... but when I drap and drop ipadapter workflow to ComfyUI , it said can not found all the times
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/139842563/1f1b81f5-7efe-4143-a6a7-ddd8f885ea64)

**Comment by arcotrr** [comment]
Open a new folder called "ipadapter" inside the "model" folder. Put your ipadapter model files in it. This is how my problem was solved.

**Comment by cubiq** [comment]
I guess this is solved, feel free to reopen if you still have issues
