### ISSUE TITLE
Easy Apply IPadapter (Advanced) with clipvision issue

### ISSUE THREAD

**Issue by okdwa** [cubiq/ComfyUI_IPAdapter_plus#372]
using new Advanced IPAdapter Apply, clipvision wrong, I have downloaded the clip vision model of 1.5 and XL

<img width="805" alt="issue" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135505857/5df4a0e9-e979-48c7-80cd-09fc79dccc59">

**Comment by cubiq** [comment]
what node is that? did you create a group?

**Comment by Juliano1972** [comment]
Please.
I  installed the IPAdapter plus from ConfyUI Manager, but the "Apply IPAdapter" not appear to use.
What happened?
I need some help... tks.

**Comment by Juliano1972** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/166563115/0f515640-ff84-454c-8ca7-d4b63fb2fef6)

**Comment by cubiq** [comment]
use IPAdapterAdvanced node. also remove the old comfyui_ipadapter extension if you have it.

**Comment by Juliano1972** [comment]
I'll try this. Tks a lot.

Em sex., 12 de abr. de 2024, 05:37, Matteo Spinelli <
***@***.***> escreveu:
