### ISSUE TITLE
FaceId Batch example is broken

### ISSUE THREAD

**Issue by worthy7** [cubiq/ComfyUI_IPAdapter_plus#373]
I know you did a rewrite, but I would really appreciate an example of batch inputs for face id (so I give several pics of the same face, hoping to improve results)

https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/examples/ipadapter_faceid_batch.json

Thanks

**Comment by cubiq** [comment]
why do you say that it is broken?

**Comment by worthy7** [comment]
I cloned the repo and when I load that particular workflow I have 2 spots, did I miss something?

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/4762399/12eadf1a-6de7-4e1e-baac-2078668cbed3)

**Comment by cubiq** [comment]
that would the FaceAnalysis extension that is used to improve the likeliness but it's not technically needed. I will make an example that doesn't require it

**Comment by worthy7** [comment]
Ah, I understand. in that case just a note inside the workflow would be great!
I really appreate your work, I am watching your videos right now and they are really perfect. Your explainations, the pace of the videos. the clear examples - thank you so much.

**Comment by cubiq** [comment]
thanks!

for now you can just take one of the images and connect it directly to the second ipadapter (and delete the red nodes and "image list to batch")
