### ISSUE TITLE
Melty Bug appeared right on time 🐰 🕐 

### ISSUE THREAD

**Issue by someaka** [cubiq/ComfyUI_IPAdapter_plus#378]
![ComfyUI_temp_ajppy_00007_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/84462932/78129046-5fb5-408a-a8e1-91cb754a5231)

this type of issue started occuring today a couple hours ago, minimal workflow should be in the picture hopefully 🤞

**Comment by someaka** [comment]
reduced it to 10 for the repro, 25 should give the same results

**Comment by cubiq** [comment]
I cannot replicate, works as expected here. try to upgrade

**Comment by someaka** [comment]
thanks for the quick response,
i was about to delete the runpod but maybe it can be used for diagnostic

https://y00xdys4g1xz74-8188.proxy.runpod.net/

just ran it again with both 1.5 and xl with 25 steps to make sure it's still having the issue

**Comment by someaka** [comment]
```
![ComfyUI_temp_blura_00009_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/84462932/971381ee-5355-48fd-ae31-95414eb29b04)
![ComfyUI_temp_blura_00007_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/84462932/13e6931e-4736-48c4-8aea-5fcf951b269c)
![ComfyUI_temp_blura_00006_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/84462932/68a21c07-3609-4fd3-b25e-0f43c84bc98a)
![ComfyUI_temp_blura_00002_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/84462932/01dc5cdf-c5f2-47d3-a34f-952d8a9d03f9)

```

here's a couple more tests with different step sizes and 1.5 / xl, 
i'll delete the runpod now and try with a fresh one later.

**Comment by cubiq** [comment]
I don't have a solution for you, I feel the installation is just broken, maybe the extension is not properly upgraded or something

**Comment by someaka** [comment]
alright let's try this again, 
using a runpod with the same docker but a 4090 this time, here's the gits of it:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/84462932/b4f288ec-531c-4198-bcfd-9f8b67526fbf)
[debugWorkflow-1.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14839483/debugWorkflow-1.json)

won't be able to let it run though as renting 4090s is rather expensive :D 
the good news being that regular IPAdapter with SDXL seems to be fine,
if there's anything more i can do to advance things please let me know.

**Comment by someaka** [comment]
solved in your video here

https://youtu.be/wt0EZHBSjz8?si=L3Ia_cG0Z2vgPCAm&t=3158

thanks again for all the amazing work and videos !
