### ISSUE TITLE
"Exception: insightface model is required for FaceID models" (NOT THE SAME ONE AS "InsightFace must be provided for FaceID models")

### ISSUE THREAD

**Issue by zulfadzlie** [cubiq/ComfyUI_IPAdapter_plus#379]
I was following Latent Vision's tutorial here https://www.youtube.com/watch?v=_JzDcgKgghY&t=151s
I got the error below when I started using the IPAdapter Advanced node.

I have inswapper_128.onnx and inswapper_128_fp16.onnx in \ComfyUI\models\insightface
I also have antelopev2 and buffalo_l folders in \ComfyUI\models\insightface\models

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/55380804/bf949e8a-0dc2-4dba-865e-f2438b2c6d99)

**Comment by cubiq** [comment]
you are using a faceid model with the ipadapter advanced node. You need to use the IPAdapter FaceID node.

**Comment by zulfadzlie** [comment]
> you are using a faceid model with the ipadapter advanced node. You need to use the IPAdapter FaceID node.

Thanks for this!
I was using ip-adapter-faceid-plusv2_sd15.bin and it gave me the errors.
I tried using ip-adapter-plus_sd15.safetensors and I got no errors.

**Comment by Jalon-Github** [comment]
I download all ipadapter models， ipadapter faceid models and ostris/ip-composition-adapter models in ipadapter folder。
then download insightface model buffalo_l.zip in folder models/insightface/models, and unzip it to buffalo_l folder. eg: models/insightface/models/buffalo_l/det_10g.onnx

finally，resolve this problem！
