### ISSUE TITLE
Error occurred when executing IPAdapterUnifiedLoaderFaceID: IPAdapter model not found. whats the FIX

### ISSUE THREAD

**Issue by MIKETUFFIN66** [cubiq/ComfyUI_IPAdapter_plus#382]
Hello , 
i have this :
Error occurred when executing IPAdapterUnifiedLoaderFaceID:
IPAdapter model not found.

whats the fix please, i downloaded the reqired files

![111111](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/162156359/0c005c95-50dc-4283-bfc5-8c3c9d9ef908)

![2222](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/162156359/c384a475-c84f-4e1c-9338-1bcf4fcc587b)

**Comment by danton267** [comment]
Did you download the lora too?
sdxl:
- ipadapter model `faceid.plusv2.sdxl` and lora `faceid.plusv2.sdxl.lora`

15:
- `faceid.plusv2.sd15` and lora `faceid.plusv2.sd15.lora`

ipadapter models need to be in `/ComfyUI/models/ipadapter`
loras need to be in `/ComfyUI/models/loras`

see [installation](https://github.com/cubiq/ComfyUI_IPAdapter_plus).

**Comment by WeirdScienceX** [comment]
I had the same issue, it was because of: ip-adapter-faceid-portrait-v11_sd15.bin

I only had the SD15 model, which is now deprecated.

**Comment by MIKETUFFIN66** [comment]
> Did you download loras as well as the ipadapter model? you need both sdxl:
> 
> * ipadapter model `faceid-plusv2_sdxl` and lora `faceid-plusv2_sdxl_lora`
> 
> 15:
> 
> * `faceid-plusv2_sd15` and lora `faceid-plusv2_sd15_lora`
> 
> ipadapter models need to be in `/ComfyUI/models/ipadapter` loras need to be in `/ComfyUI/models/loras`
> 
> see [installation](https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#installation) FaceID part.

Thank you very much the exact name was required and Lora i have missed to download it ... i should read more before i rush things .. its working now . thanks again :)

**Comment by giusparsifal** [comment]
Hello, I downloaded all the files (bin, loras) listed in the installation ID part and stored where it it says. But still I get the same error, ipadadpter model not found...

**Comment by killmen9925** [comment]
faceid-plusv2_sdxl is placed in the appropriate folder, but it is not recognized.
