### ISSUE TITLE
How to use the new version can get the same result as the old version does ?

### ISSUE THREAD

**Issue by jesenzhang** [cubiq/ComfyUI_IPAdapter_plus#383]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/7984556/8db01420-1a07-459e-8472-156bfecff9dd)
I just update the workflow ,and  there are some more setting items, so how to set the combine embeds method 、the weight_type 、embeds_scaling and so on the get the same result as the old version does?
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/7984556/1f0c2690-2c66-4925-b535-1dfd91498813)

**Comment by cubiq** [comment]
the defaults should be the same as before. There might be some difference in how the weights are applied but it's just a matter of increasing / lowering the value
