### ISSUE TITLE
We want to continue using the old version.

### ISSUE THREAD

**Issue by stephbertodk** [cubiq/ComfyUI_IPAdapter_plus#385]
I think the old version works better in my own workflows. Now I can't get similar quality, I have to constantly update the settings. Especially since there was an original option, it should come back. First of all, please prepare a node that I can use in the old version.

**Comment by cubiq** [comment]
original is == v only. which is the default

**Comment by stephbertodk** [comment]
For these two "weight type, combine embeds", I need to constantly update the settings in two parts. First of all, when I choose linear, it tries to do the same thing, playing with the settings does not help. I don't want to keep choosing options.

What I mean is, in the past, I would choose the original and get very good results. Now I'm dealing with the extra settings you put. There is no basic node where I can use the old version.

I think some nodes merging with the old one would be better. For example, the tiled issue is very meaningful. It would be great if there was something I could use in the old version, as well as negative and batch. So there are no settings as simple as the old version. And I have to constantly adjust. I spend more time.

> original is == v only. which is the default

**Comment by stephbertodk** [comment]
> original is == v only. which is the default

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/108632562/52273af4-8266-4254-b999-31c40392a0fd)
Look, let me give you example. I definitely would not have gotten such a result before. I could easily see the pattern on it. In the past, he would understand that it was a pattern (sometimes I didn't even need to write a prompt) and combine it creatively on the outfit without distorting the reality of the outfit. Now even control-net (I used Teed, sd1.5) blocks it and loses details directly.

**Comment by cubiq** [comment]
you can revert to any revision you want. that's the beauty of github

**Comment by Zakutu** [comment]
> 必要なリビジョンに戻すことができます。それが github の利点です

Can you please tell me the procedure to revert to the previous version? I have never done it.

**Comment by ohahaps2** [comment]
For me the old version works better in my own workflows.
same mode settings---ip-adapter-faceid-plusv2_sdxl.bin
but I have revert to the old revision, but get this:
Error occurred when executing IPAdapterApplyFaceID:

Error(s) in loading state_dict for ProjModelFaceIdPlus:
size mismatch for proj.2.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([5120, 1024]).
size mismatch for proj.2.bias: copying a param with shape torch.Size([8192]) from checkpoint, the shape in current model is torch.Size([5120]).
size mismatch for norm.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for norm.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.proj_in.weight: copying a param with shape torch.Size([2048, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.proj_in.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.proj_out.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.proj_out.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.norm_out.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.norm_out.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.0.0.norm1.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.0.0.norm1.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.0.0.norm2.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.0.0.norm2.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.0.0.to_q.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.layers.0.0.to_kv.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([2560, 1280]).
size mismatch for perceiver_resampler.layers.0.0.to_out.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.layers.0.1.0.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.0.1.0.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.0.1.1.weight: copying a param with shape torch.Size([8192, 2048]) from checkpoint, the shape in current model is torch.Size([5120, 1280]).
size mismatch for perceiver_resampler.layers.0.1.3.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1280, 5120]).
size mismatch for perceiver_resampler.layers.1.0.norm1.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.1.0.norm1.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.1.0.norm2.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.1.0.norm2.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.1.0.to_q.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.layers.1.0.to_kv.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([2560, 1280]).
size mismatch for perceiver_resampler.layers.1.0.to_out.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.layers.1.1.0.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.1.1.0.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.1.1.1.weight: copying a param with shape torch.Size([8192, 2048]) from checkpoint, the shape in current model is torch.Size([5120, 1280]).
size mismatch for perceiver_resampler.layers.1.1.3.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1280, 5120]).
size mismatch for perceiver_resampler.layers.2.0.norm1.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.2.0.norm1.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.2.0.norm2.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.2.0.norm2.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.2.0.to_q.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.layers.2.0.to_kv.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([2560, 1280]).
size mismatch for perceiver_resampler.layers.2.0.to_out.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.layers.2.1.0.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.2.1.0.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.2.1.1.weight: copying a param with shape torch.Size([8192, 2048]) from checkpoint, the shape in current model is torch.Size([5120, 1280]).
size mismatch for perceiver_resampler.layers.2.1.3.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1280, 5120]).
size mismatch for perceiver_resampler.layers.3.0.norm1.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.3.0.norm1.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.3.0.norm2.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.3.0.norm2.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.3.0.to_q.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.layers.3.0.to_kv.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([2560, 1280]).
size mismatch for perceiver_resampler.layers.3.0.to_out.weight: copying a param with shape torch.Size([2048, 2048]) from checkpoint, the shape in current model is torch.Size([1280, 1280]).
size mismatch for perceiver_resampler.layers.3.1.0.weight: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.3.1.0.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1280]).
size mismatch for perceiver_resampler.layers.3.1.1.weight: copying a param with shape torch.Size([8192, 2048]) from checkpoint, the shape in current model is torch.Size([5120, 1280]).
size mismatch for perceiver_resampler.layers.3.1.3.weight: copying a param with shape torch.Size([2048, 8192]) from checkpoint, the shape in current model is torch.Size([1280, 5120]).

**Comment by ohahaps2** [comment]
The new version getting more artifacts and blur after upscare，how can we use  the old version, Thanks a lot!

**Comment by ohahaps2** [comment]
![Uploading 1415115341541.png…]()
