### ISSUE TITLE
Rounding issue?

### ISSUE THREAD

**Issue by melMass** [cubiq/ComfyUI_IPAdapter_plus#39]
Hi, 

I did not look into it deeply and don't know IPAdapter much so maybe there is another reason but it seems like there is a rounding issue in the weights blending 

https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/7041726/aa343d0a-635a-466f-a6b8-f26366341a0e

**Comment by cubiq** [comment]
so given the weighting it is still beta-ish... this is not an easy test to make especially with the face model. Remember that the model is "face descriptor" not a "face swap". I'm pretty sure we'll always have some level of rounding issue but I don't think this is the case. The weighting is not linear so the difference between 1.0 and 0.99 is not 0.01 but actually greater.  I'll leave this issue open until I make some more tests anyway

**Comment by melMass** [comment]
Thanks, yes I don't have real ground truth to compare with but it's seemed intriguing what happens after 0.3 onward as it's bouncing (popping) back to previous "weights" I'll do more test too in case it can help

**Comment by cubiq** [comment]
try to get very similar pictures of the two subjects (like two closeups taken at the same angle). That would be a good starting point for a controlled experiment.

**Comment by melMass** [comment]
I'll do that and try doing edits here too since I don't get the way weights are blended: https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/b07f9821ed0ef939ef4637685bcb7cb6dd358832/IPAdapterPlus.py#L473-L480
