### ISSUE TITLE
how to use deprecated models??? the old one?  like ip-adapter-faceid-plus_sd15.binand ip-adapter-faceid-portrait_sd15.bin ??? please help...

### ISSUE THREAD

**Issue by max140x** [cubiq/ComfyUI_IPAdapter_plus#393]
I want to to use these models:

Deprecated [ip-adapter-faceid-plus_sd15.bin, FaceID plus v1

Deprecated [ip-adapter-faceid-portrait_sd15.bin, v1 of the portrait model

also with it's own lora :

Deprecated [ip-adapter-faceid-plus_sd15_lora.safetensors, LoRA for the deprecated FaceID plus v1 model

what's the options to use that???

**Comment by cubiq** [comment]
you can still use them, they all work as normal, the unified loader will pick them automatically

**Comment by max140x** [comment]
> you can still use them, they all work as normal, the unified loader will pick them automatically

![Screenshot 2024-04-07 073656](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/153641803/0ed8d28c-6fcb-4031-a92c-e00e5e71fbe0)
 thanks so much for reply but i mean same name no option to choose old or new , so how can i do it without delete one of them?

**Comment by cubiq** [comment]
then you can use the legacy loaders (ipadapter model loader)

**Comment by Judith-Alvarez** [comment]
> then you can use the legacy loaders (ipadapter model loader)

The root of the problem is that sometimes you want to use another ipadapter like this one https://civitai.com/models/305534/ip-adapter-plus-anime-fine-tune for example.

You can't use a legacy loader - it throws an error with new nodes, And legacy Apply IPAdapter is not available anymore...

**Comment by cubiq** [comment]
the legacy loader is exactly the same as before
