### ISSUE TITLE
IPAdapter model not found

### ISSUE THREAD

**Issue by pythiantech** [cubiq/ComfyUI_IPAdapter_plus#396]
I know a lot of people have faced this issue, but I just can't seem to detect where the problem lies. Here's the error:

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/dhirajkhanna/Documents/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhirajkhanna/Documents/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhirajkhanna/Documents/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhirajkhanna/Documents/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 420, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

```
In `utils.py` I printed the `ipadapter_list` and this is what I get:
`['ip-adapter-faceid-plusv2_sd15.bin', 'ip-adapter-faceid-plusv2_sdxl.bin', 'ip-adapter-faceid-portrait-v11_sd15.bin', 'ip-adapter-faceid-portrait_sdxl.bin', 'ip-adapter-faceid_sd15.bin', 'ip-adapter-full-face_sd15.safetensors', 'ip-adapter-plus-face_sd15.safetensors', 'ip-adapter-plus_sd15.safetensors', 'ip-adapter_sd15.safetensors', 'ip-adapter_sd15_vit-G.safetensors']`

The preset I use is `plus (high strength)` and `is_sdxl` is `True`. I suspect `re.search(pattern, e, re.IGNORECASE)` is always returning False. Not sure what to do now.

I also have the 2 models in the `clip_vision` folder and named exactly as suggested.

**Comment by cubiq** [comment]
you do not have the SDXL plus model
