### ISSUE TITLE
how to make xy plot with ipAdapter in comfyui with diffrent checkpoints

### ISSUE THREAD

**Issue by czcz1024** [cubiq/ComfyUI_IPAdapter_plus#399]
i want test some checkpoints to see whitch better work with ipAdapter
how could i make xy plot and make each checkpoints apply ipadapter?
i test the efficiency nodes，but when i add the xy plot,the model not apply ipAdapter.
anyone can help?

**Comment by GrigJr** [comment]
You can use [ComfyRoll nodes](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes) to plot any "noodle"-able params in a workflow. Here are [some examples](https://civitai.com/models/159165/comfyui-xy-grid-demos-xy-anything) how to set it up.
Here's how [weight_type vs weight looks for various ip models](https://i.imgur.com/FIOvABG.png).
