### ISSUE TITLE
IPadapter seems to diffuse elements that don't belong to the face.

### ISSUE THREAD

**Issue by stephantual** [cubiq/ComfyUI_IPAdapter_plus#400]
Workflow:
[ipabugreport.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14890281/ipabugreport.json)

Image: 

![clooney](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1596070/06648383-e812-4e40-9fdd-1e129d3bb38f)

Output:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1596070/a320868e-9241-4c1b-a59e-08861e62fe51)

thanks for having a look. I have the same issue with sdxl or sd15, regardless of which face model i choose.

**Comment by cubiq** [comment]
lower the CFG, increase the steps, use better positive and negative. also the reference image is not ideal for insightface, you need to pick a picture a little more distant for faceid. it's fine for full/plus face

**Comment by stephantual** [comment]
Thanks Matteo!
