### ISSUE TITLE
I use bfloat and the error is this doesn't want bfloat it wants half.

### ISSUE THREAD

**Issue by DarkAlchy** [cubiq/ComfyUI_IPAdapter_plus#402]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10561690/58e681c6-ed24-446d-ac3c-bde3ddfb4aaf)

**Comment by cubiq** [comment]
please check the common issues https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108
