### ISSUE TITLE
I need to understand this

### ISSUE THREAD

**Issue by MohammadAboulEla** [cubiq/ComfyUI_IPAdapter_plus#403]
![Untitled2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/89942942/e01af5c9-3128-4889-8adc-0521c80be6ca)

as I understand when you passed the adapter like this from the first unified loader does that mean you have override the selected adapter in the second loader?

**Comment by cubiq** [comment]
yes.
what is the error?

**Comment by MohammadAboulEla** [comment]
no error I edit the title sorry for that. I just need to understand when you passed the adapter like this from the first unified loader does that mean you have override the selected adapter in the second loader?

**Comment by cubiq** [comment]
the two unified loaders share the common models and the new one is overridden

**Comment by MohammadAboulEla** [comment]
but if the second loader using is using "faceid id v2 adapter" from the first loader! how can you load it and in the normal unified loader shouldn't it be unified loader faceid like the first one?

**Comment by cubiq** [comment]
no, you can mix loaders. they are smart enough to know what to do
