### ISSUE TITLE
IPAdapter Batch(Adv.) update breaks KSampler ?  module 'comfy.sample' has no attribute 'prepare_mask'

### ISSUE THREAD

**Issue by Cybrak** [cubiq/ComfyUI_IPAdapter_plus#407]
Hello, 
I played 2 days ago with the workflow ipivs-morph-img2vid that is using IPAdapter Batch(Adv.)
https://civitai.com/models/372584/ipivs-morph-img2vid-animatediff-lcm
I was all working fine but that workflow is now breaking since the 2024/04/04 update. Was IPAdapter Batch(Adv.) even updated or something else broke ?
I tried re-create the nodes but the error is still the same issue. Any idea what is happening ?

Error occurred when executing KSampler:
module 'comfy.sample' has no attribute 'prepare_mask'

Thanks !

**Comment by cubiq** [comment]
comfyui made some breaking updates recently, I'll look into it

**Comment by juanigsrz** [comment]
> comfyui made some breaking updates recently, I'll look into it

From a fresh state, latest ComfyUI works fine with the latest ComfyUI_IPAdapter_Plus

I suggest anyone having these kind of issues to update both

**Comment by Cybrak** [comment]
ComfyUI_IPAdapter_Plus works fine its, its the ksampler that is erroring. It still failing after update everything I will try to rebuild all the nodes. Thanks guys !

**Comment by Cybrak** [comment]
Ok found the issue was actually coming from a node just before the IPAdapter Batch, It was fixed yesterday 
https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/blob/main/animatediff/sampling.py
Scusate per il tempo sprecato, grazie per il vostro fantastico lavoro <3 !

**Comment by nalisten** [comment]
@Cybrak Im stuck at the same spot. I tried to download that file in the link you posted and replaced it in the animatediff evolved folder, I also tried to update the animatediff evolved node and that didnt work for me either. can you tell me what exactly did you do to get it working again.
