### ISSUE TITLE
Error occurred when executing IPAdapterNoise:  Argument interpolation should be an `InterpolationMode` or a corresponding Pillow integer constant, but got InterpolationMode.BICUBIC.

### ISSUE THREAD

**Issue by EdisonHaJimi** [cubiq/ComfyUI_IPAdapter_plus#408]
Hello, what’s wrong with my IPAdapter Noise?
![微信图片_20240406231749](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/159610840/690e5c43-383c-4d96-a20f-dd408a8558ae)
![微信图片_20240407102005](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/159610840/21112b10-379b-413e-be02-f5294be0558b)

**Comment by cubiq** [comment]
you probably have an old version of pillow, you need to upgrade

**Comment by firelife2008** [comment]
check your nodes, if have a node name: comfyui-reactor-node , delete it ,and try again.
I fixed it .good luck

**Comment by EdisonHaJimi** [comment]
Thank you very much, it's fixed.

**Comment by magang84** [comment]
May I ask how you resolved it? Thank you!

> 非常感谢，已经解决了。

**Comment by Imagewwg78** [comment]
May I ask how you resolved it?

**Comment by EdisonHaJimi** [comment]
Upgrade or delete nodes, comfyui-reactor-node
Of course IPAdapter also needs to be updated
