### ISSUE TITLE
the composition transfer option is not showing in my node drop-down menu, i have allready downloaded the model in to the respective folder

### ISSUE THREAD

**Issue by Manish-cel** [cubiq/ComfyUI_IPAdapter_plus#410]
![chrome_l6CZR2TUv8](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/140691855/30fe24d5-5be5-47e2-97bc-3e913f3e9b05)

**Comment by cubiq** [comment]
you just need to refresh your browser or try with an incognito window
