### ISSUE TITLE
Error occurred when executing IPAdapterEmbeds:  "addmm_cuda" not implemented for 'Float8_e4m3fn'

### ISSUE THREAD

**Issue by emptybamboo** [cubiq/ComfyUI_IPAdapter_plus#413]
This was not the case on April 6, but the problem appeared on April 7, seemingly because my comfyui started fp8, and both fp8 modes would lead to execution failure, and after trying to find that not only IPAdapterEmbeds apply would lead to execution failure, but IPAdapter apply would also fail

Error occurred when executing IPAdapter:
"addmm_cuda" not implemented for 'Float8_e4m3fn'
![360截图20240407195806875](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/47071080/5f52070a-03b8-4dda-a93f-cdcd55bd9801)
![360截图20240407200352244](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/47071080/02fb40b6-7adc-4210-ba82-3c2647a60f12)

**Comment by cubiq** [comment]
this should be fixed now

**Comment by emptybamboo** [comment]
Thank you for your work, you are a great developer
