### ISSUE TITLE
Worked fine with 20240401 version, now get error with 20240404 version

### ISSUE THREAD

**Issue by RudyB24** [cubiq/ComfyUI_IPAdapter_plus#414]
Hi Matteo,
First of all a big thank you for your IPAdapter work.

I'm sorry to say that with the last update 20240404, where the new combined style and composition node is introduced, I get below error message when using your provided ipadapter_advanced workflow. I get similar (though different error details) messages with my own workflows.

With version 20240401 all worked well. I use(d) the default model names to be able to work with the Unified Loader, I did not change anything, only performed the update to 20230404, after which I get the errors.

EDIT: I just confirmed that the previous version 20240401 still works. I downloaded the ZIP of that version from Github and now all my workflows work again. This tells me nothing else had changed om my end.

Greetings, Rudy (from the videos, the last one of which was on your IPAdapter:  https://www.youtube.com/playlist?list=PLyC6aoYnRBZbU7RDv3bvnXjDHTn1zoyuY  :)

Error occurred when executing IPAdapterAdvanced:

'ModelPatcher' object has no attribute 'get_model_object'

File "D:\AI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 637, in apply_ipadapter
return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 327, in ipadapter_execute
sigma_start = model.get_model_object("model_sampling").percent_to_sigma(start_at)
^^^^^^^^^^^^^^^^^^^^^^

**Comment by cubiq** [comment]
please be sure to have the latest version of comfyui installed and report back

**Comment by frukostkungen** [comment]
getting the latest version of comfyui resolved this issues for me 

however, it's worth noting that this also broke SeargeSDXL
https://github.com/SeargeDP/SeargeSDXL/issues/137

while not directly related, it's good to know

**Comment by cubiq** [comment]
comfyui recently pushed a breaking update. All nodes dealing directly with the sampler need update

**Comment by RudyB24** [comment]
Thanks for reaching out Matteo. And yes ... update ComfyUI solved the issue. 

LOL ... it's on line one of your FAQ! And usually I always update ComfyUI when I install something new. This time though my last update had been just 3 days ago ... who would have thought developments go that quick? :)
