### ISSUE TITLE
Request / help

### ISSUE THREAD

**Issue by nodegraphics** [cubiq/ComfyUI_IPAdapter_plus#419]
Hi, 
i opened up one of my old workflow and having diffucult time generating the same result due to some of the missing nodes. I was wondeering what i should replace it with so that i can get the similar result as my original workflow.?

<img width="764" alt="Screenshot - 2024-04-07 21 09 31" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10071439/093fc2a8-44a7-4582-978e-76a94e8b0f4a">
<img width="955" alt="Screenshot - 2024-04-07 21 09 43" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/10071439/a1dbb0fc-be02-4039-a22d-0a404c9a6e85">

Thank you

**Comment by cubiq** [comment]
now it's called IPAadpter Embeds, and IPAdapter Encoder
