### ISSUE TITLE
Error occurred when executing IPAdapterApply:

### ISSUE THREAD

**Issue by msskaa12** [cubiq/ComfyUI_IPAdapter_plus#42]
when i run the example of IPAdapter_inpaint.json , it comes error

![Screenshot from 2023-10-18 17-25-21](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/78275037/3c576560-a52b-4c94-82bd-5f26c6ce4915)

![avc](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/78275037/822b16f3-ff99-4b04-98a0-147d12d65bc0)

**Comment by cubiq** [comment]
you are using the wrong clip vision for SDXL. the file naming on my setup is probably different than yours so the first one in the list has been selected, which is not the right one
