### ISSUE TITLE
 Is [ip-adapter-faceid-portrait_sd15.bin] Deprecated? 

### ISSUE THREAD

**Issue by uiueux** [cubiq/ComfyUI_IPAdapter_plus#421]
I found that the URLs of these 2 model files are the same (one of them is marked as deprecated), is it marked wrong?
![微信截图_20240408162311](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/4375543/73584260-2df9-4edf-8d87-4d490b1913aa)

**Comment by cubiq** [comment]
there's an error in the link the model is `ip-adapter-faceid-portrait_sd15.bin`. I will fix it later
