### ISSUE TITLE
Error occurred when executing IPAdapterStyleComposition

### ISSUE THREAD

**Issue by Dragoy** [cubiq/ComfyUI_IPAdapter_plus#424]
Can't start workflow with IPAdapter:

> Error occurred when executing IPAdapterStyleComposition:
> 
> 'ModelPatcher' object has no attribute 'get_model_object'
> 
> File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 639, in apply_ipadapter
> return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 329, in ipadapter_execute
> sigma_start = model.get_model_object("model_sampling").percent_to_sigma(start_at)
> ^^^^^^^^^^^^^^^^^^^^^^

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/4968313/c3aae446-b5fe-4309-a31f-58afd2a1f057)

**Comment by cubiq** [comment]
upgrade comfy https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108
