### ISSUE TITLE
Unified Loader FaceIDdoesn't want to use yaml path

### ISSUE THREAD

**Issue by koppimashin** [cubiq/ComfyUI_IPAdapter_plus#425]
Works fine when using SDXL models, then decided to try with SD1.5 so I made minor adjustment until it doesn't want to read the yaml anymore but as you can see clip vision was perfectly loaded from the yaml path.

INFO: Clip Vision model loaded from E:/comfyuimodels/models/clip_vision/CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 422, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/147228392/5c55ca27-8ec2-4711-bec1-2541ac943a4c)

**Comment by lovisdotio** [comment]
Same error here

**Comment by cubiq** [comment]
the models are all loaded from the same location, if one works they should all work. it's probably a file name issue

**Comment by koppimashin** [comment]
I actually first tried it on the sd15 and it worked perfectly then spent most of the time on the sdxl lightning models then tried going back to the sd15, and this happened.

**Comment by koppimashin** [comment]
It works with the other model, turns out when I try to use "faceid plus sd1.5" that's where it can't find the model. So what I did was just avoid using that model and after a while of experimenting with other faceid models, I got this error.

!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 420, in load_models
    ipadapter_file, is_insightface, lora_pattern = get_ipadapter_file(preset, is_sdxl)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 29, in get_ipadapter_file
    ipadapter_list = folder_paths.get_filename_list("ipadapter")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 221, in get_filename_list
    out = cached_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 209, in cached_filename_list_
    if os.path.getmtime(folder) != time_modified:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 55, in getmtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:/comfyuimodels/models/ipadapter/'

Prompt executed in 0.06 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 420, in load_models
    ipadapter_file, is_insightface, lora_pattern = get_ipadapter_file(preset, is_sdxl)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 29, in get_ipadapter_file
    ipadapter_list = folder_paths.get_filename_list("ipadapter")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 221, in get_filename_list
    out = cached_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 209, in cached_filename_list_
    if os.path.getmtime(folder) != time_modified:
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 55, in getmtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:/comfyuimodels/models/ipadapter/'

**Comment by Mozoloa** [comment]
I have the same problem, clearly got "G:\AI\Image\Stable Diffusion\Data\Models\IpAdapter" in my extra paths, and all of its content is detected by other nodes (before the update, it's where I loaded the adapters from, for my faceid workflow), the models are at the root of it, I even copied all the name from the readme to make sure they matched, still :
```
Error occurred when executing IPAdapterUnifiedLoaderFaceID:

IPAdapter model not found.
```

**Comment by koppimashin** [comment]
- Updated comfyui and it's dependencies
- Works perfectly at first, building my own workflow from scratch to understand it well
- Constantly experiment with SD1.5 and SDXL Lightning.
- The node starts to fail when finding the FaceID Plus SD1.5
- Try to verify the existence of the model, it was there.
- Downloads everthing again just to make sure.
- Still the node fails to find the FaceID Plus SD1.5
- I just avoided it and started using another model instead.
- I did a little experimentation, detailing the face and enlarging the scale.
- I tried to change the checkpoint version.
- I tried using different models of ipadapter again except FaceID Plus SD1.5
- Node can't find any models now
- I reinstalled the node
- Rechecked ipadapter models again, but ipadapter models folder itself is missing
- I tried to download everything again and the browser tells me that the file already exists but I can't see it when I try to search the folder.

Is uninstalling IPAdapter nodes the culprit? I checked the IPAdapter models folder, but it seems like the entire folder vanished. It feels like it self-deleted somehow.

BTW when I tried redownloading the models for the second time, it said the file already existed, even though I couldn't see it anywhere. When the FaceID Plus SD1.5 issue first occurred, I verified its presence, and then I redownloaded everything just to be safe. But it still couldn't find the model.

![Screenshot_46](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/147228392/df31e5cc-2912-4b86-91a4-5b74130f0b95)
![Screenshot_1](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/147228392/9785af47-9f64-43ef-8773-74bc181d0c4d)

**Comment by green-anger** [comment]
> the models are all loaded from the same location, if one works they should all work. it's probably a file name issue

@cubiq Can you elaborate what this from the description mean, `The models can be placed into sub-directories`?

I thought it'd scan all the sub-directories, track all files and then pick the first one found when the name matches. I kept the same relative structure as in h94 huggingface repo, so it has two directories sd15 and sdxl and each has directory `image_encoder` with relative clip vision model. Plus both main directories are nested in couple of other dirs for convenience.

How does it search for the models? Should it all be in one single directory?

**Comment by sanane-ulan** [comment]
> I have the same problem, clearly got "G:\AI\Image\Stable Diffusion\Data\Models\IpAdapter" in my extra paths, and all of its content is detected by other nodes (before the update, it's where I loaded the adapters from, for my faceid workflow), the models are at the root of it, I even copied all the name from the readme to make sure they matched, still :
> 
> ```
> Error occurred when executing IPAdapterUnifiedLoaderFaceID:
> 
> IPAdapter model not found.
> ```

Same problem here

**Comment by rajinipreethajohn** [comment]
Same problem here!

Error occurred when executing IPAdapterUnifiedLoader:

IPAdapter model not found.

**Comment by escalate007** [comment]
> Works fine when using SDXL models, then decided to try with SD1.5 so I made minor adjustment until it doesn't want to read the yaml anymore but as you can see clip vision was perfectly loaded from the yaml path.
> 
> INFO: Clip Vision model loaded from E:/comfyuimodels/models/clip_vision/CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors !!! Exception during processing !!! Traceback (most recent call last): File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 422, in load_models raise Exception("IPAdapter model not found.") Exception: IPAdapter model not found. ![image](https://private-user-images.githubusercontent.com/147228392/320593481-5c55ca27-8ec2-4711-bec1-2541ac943a4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjg1NjUsIm5iZiI6MTcxMzAyODI2NSwicGF0aCI6Ii8xNDcyMjgzOTIvMzIwNTkzNDgxLTVjNTVjYTI3LThlYzItNDcxMS1iZWMxLTI1NDFhYzk0M2E0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxNzExMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzJkMzJmYWQwYTEzNDk5ZTViMzIwZjY0OTA1YzNjNmE0ZWRlYzcxODc2YmJkMTQxMTg4YWZjZWE1NmI2ZmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._zO7_af-Tl5WNa9b1Y1uLSNaP9oc4exnBefaRIDKdAE)

it happened to me

**Comment by escalate007** [comment]
![图片](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/55056146/0668491d-57d8-4faf-b4aa-e986ee8ade34)
All file names were checked carefully.But whenI ran 'faceid plus sd1.5 only'with SD15 Model,this error occoured as same as @koppimashin.

At the same time,the other three preset method 'faceid', 'face plusV2' and'faceid portrait' went smoothly without problem. Only this one are out of work.
![图片](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/55056146/82b8796d-6ee2-4fe0-a4c4-96b51d57e785)

By the way,I found 5 preset methods below in the ipadapterunifiedloader are OK.
![图片](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/55056146/edcf63c5-d012-476d-9399-b57a6a5860ba)

**Comment by escalate007** [comment]
aha,I found it.
ip-adapter-faceid-plus_sd15.bin and faceid-plus_sd15_lora.safetensors are for  'faceid plus sd1.5 only',I put them back to models/ipadapter folder. It works now!

**Comment by koppimashin** [comment]
> aha,I found it. ip-adapter-faceid-plus_sd15.bin and faceid-plus_sd15_lora.safetensors are for 'faceid plus sd1.5 only',I put them back to models/ipadapter folder. It works now

@escalate007 did you fix it so we can close this? we have the same exact problem.

**Comment by escalate007** [comment]
> > aha,I found it. ip-adapter-faceid-plus_sd15.bin and faceid-plus_sd15_lora.safetensors are for 'faceid plus sd1.5 only',I put them back to models/ipadapter folder. It works now
> 
> @escalate007 did you fix it so we can close this? we have the same exact problem.

Ok if you solved it too.
