### ISSUE TITLE
Error occurred when executing IPAdapterAdvanced

### ISSUE THREAD

**Issue by yaboosat** [cubiq/ComfyUI_IPAdapter_plus#427]
Hello,
I'm getting this error when I want to run the ipAdapter Plus model.

Error occurred when executing IPAdapterAdvanced:

'ModelPatcher' object has no attribute 'get_model_object'

  File "/home/gp/cu/ComfyUI/execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/gp/cu/ComfyUI/execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/gp/cu/ComfyUI/execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/gp/cu/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 639, in apply_ipadapter
    return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
  File "/home/gp/cu/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 329, in ipadapter_execute
    sigma_start = model.get_model_object("model_sampling").percent_to_sigma(start_at)
    
    I've downloaded and put all ipadapter models as instructed on github page into a /model/ipadapter

**Comment by aleph65** [comment]
I just got this as well

**Comment by Anning-Li** [comment]
got this as well, error occurred when using sdxl model for ipadapter advanced

**Comment by cubiq** [comment]
Please search the issue tracked before posting a new issue. This is also answered in pinned "common issues" https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108

**Comment by yaboosat** [comment]
Ok, I was able to solve my issue. The problem is my ComfyUI version was outdated and I had to updated it as well. I thought I should only need to update the extension.
