### ISSUE TITLE
must add line in folder_paths.py to get unified loader to work.

### ISSUE THREAD

**Issue by magicbot42** [cubiq/ComfyUI_IPAdapter_plus#428]
@cubiq. I just noticed that I had to add this new line 35:
folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], {""})

in:
\ComfyUI\\folder_paths.py

with the latest version of comfyui in order to get these lines in your utils module to work:

    ipadapter_file = [e for e in ipadapter_list if re.search(pattern, e, re.IGNORECASE)]
    ipadapter_file = folder_paths.get_full_path("ipadapter", ipadapter_file[0]) if ipadapter_file else None

Otherwise your IPAdaptor unified loader doesn't find the ipadapters in that folder that you list in your setup steps.
Maybe it's a known issue.  Just reporting.  Thanks for all.

**Comment by cubiq** [comment]
I don't know what this happens. It doesn't happen to me like it doesn't happen to most people. It must be some issue in the environment but I'm not able to replicate

**Comment by magicbot42** [comment]
I'm using stability matrix, and I updated comfyui via the manager in case it makes a difference for anyone else seeing this.

**Comment by magicbot42** [comment]
seems like a known issue anyway. I'll close this
