### ISSUE TITLE
[Request] About the model placement location

### ISSUE THREAD

**Issue by za-wa-n-go** [cubiq/ComfyUI_IPAdapter_plus#43]
Could you include a mechanism, like Comfy's yaml, that allows us to change to a specified location?

Ideally, it would be easier to use it here as a default.
ComfyUI/models/controlnet

**Comment by cubiq** [comment]
I agree it should stay in ComfyUI/models/ipadapter but now we already have a userbase and it would break their installation. I should add a script that moves the models if they are in the old location and possibly automatically download them if they are not there yet. It's in my to-do but I don't know when I'll be able to do that, sorry

**Comment by za-wa-n-go** [comment]
Yes.....................I am not sure if I am right or not. I'm having a hard time with this....
I think users like those who use IP-Adapter-Plus should be bullish, as I think they can quickly respond to an update that would change the placement of the model.
This is just my personal opinion!

**Comment by cubiq** [comment]
this is finally supported
