### ISSUE TITLE
IPAdapterAdvanced.apply_ipadapter() got an unexpected keyword argument 'layer_weights'

### ISSUE THREAD

**Issue by freke70** [cubiq/ComfyUI_IPAdapter_plus#435]
Just updated the ipadapter.
I now get this error:

Error occurred when executing IPAdapterFaceID:

IPAdapterAdvanced.apply_ipadapter() got an unexpected keyword argument 'layer_weights'

File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))

I used the same workflow that worked before the update and used the one in the examples: ipadapter_faceid_batch.json

But error happens in both.

**Comment by cubiq** [comment]
okay fixed with the latest update
