### ISSUE TITLE
Convert weight to input error

### ISSUE THREAD

**Issue by Mackay031** [cubiq/ComfyUI_IPAdapter_plus#436]
I am trying to update my IPAdapter to the new version. When I choose the 'convert weight to input' option and then try and connect this input from a 'weight' node, it doesn't connect and then it wont let go ie. it starts to drag the node all over the place as it connect to my mouse. Any ideas? Thanks

**Comment by cubiq** [comment]
like this?

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/0686c402-10a2-44d7-b326-e748085d7931)

**Comment by Mackay031** [comment]
Hi, yes like that. Maybe its the Weight node that is causing the issue. Am I using an old one? Which node is that? Thanks :)

![Screen Recording 2024-04-09 at 15 31 28](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/102358798/55d3fdf4-6cf1-44a7-9ddd-4a093eb54bef)

**Comment by cubiq** [comment]
I don't know what is happening there, but it's not the weight's fault I guess. try in an incognito window

**Comment by Mackay031** [comment]
Yeah, I was running ComfyUI in the cloud (I use thinkdiffusion for heavier workflows as I am Mac based). When I tried on my local install, it worked fine. Weird.
