### ISSUE TITLE
After "Update All" in ComfyUI Manager, IPAdapater node stopped working

### ISSUE THREAD

**Issue by edhub** [cubiq/ComfyUI_IPAdapter_plus#439]
Here's the error message I got:
```
Error occurred when executing IPAdapterUnifiedLoader:

module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'

File "/root/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/root/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/root/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 414, in load_models
is_sdxl = isinstance(model.model, (comfy.model_base.SDXL, comfy.model_base.SDXLRefiner, comfy.model_base.SDXL_instructpix2pix))
```

**Comment by LeonidTheGod2** [comment]
same

**Comment by LeonidTheGod2** [comment]
> Here's the error message I got:
> 
> ```
> Error occurred when executing IPAdapterUnifiedLoader:
> 
> module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'
> 
> File "/root/ComfyUI/execution.py", line 152, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "/root/ComfyUI/execution.py", line 82, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "/root/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 414, in load_models
> is_sdxl = isinstance(model.model, (comfy.model_base.SDXL, comfy.model_base.SDXLRefiner, comfy.model_base.SDXL_instructpix2pix))
> ```

downgrade to commit from 1-2 april, it helped me =)

**Comment by tanglup** [comment]
The confyui ontology may need to be upgraded to the latest version

**Comment by cubiq** [comment]
update comfyui https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108
