### ISSUE TITLE
[REQUEST] - Weights for image inputs

### ISSUE THREAD

**Issue by rethink-studios** [cubiq/ComfyUI_IPAdapter_plus#44]
Hey hey!!
Great work on this, very impressive for sure.
I'm not sure IP_Adapter works like this or not, but will ask anyways.

As a feature request, I'm wondering if it's possible to add controls or a node that weighs how much of an image contributes to a set of batch images. Example below:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/60104539/f24e9b8b-e7ea-4671-90ce-4923c2d53a16)

**Comment by cubiq** [comment]
yes, it is already possible check https://github.com/cubiq/ComfyUI_IPAdapter_plus#image-weighting

**Comment by rethink-studios** [comment]
!! Thanks for this !!
