### ISSUE TITLE
Error occurred when executing IPAdapterStyleComposition:  'ModelPatcher' object has no attribute 'get_model_object'

### ISSUE THREAD

**Issue by luanluan-l** [cubiq/ComfyUI_IPAdapter_plus#444]

**Comment by cubiq** [comment]
please check old closed issues before opening a new one

https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108

**Comment by yaboosat** [comment]
Ok, I was able to solve my issue. The problem is my ComfyUI version was outdated and I had to updated it as well. I thought I should only need to update the extension.
