### ISSUE TITLE
AttributeError: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'

### ISSUE THREAD

**Issue by zhuhanyuan** [cubiq/ComfyUI_IPAdapter_plus#447]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 436, in load_models
    is_sdxl = isinstance(model.model, (comfy.model_base.SDXL, comfy.model_base.SDXLRefiner, comfy.model_base.SDXL_instructpix2pix))
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'
<img width="780" alt="Screenshot 2024-04-10 at 22 51 23" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/8264002/0eb3d0d3-6408-4d75-ae7a-51b423a4b0ae">
<img width="783" alt="Screenshot 2024-04-10 at 22 49 44" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/8264002/eae9c49c-d05c-45bc-9c08-e2bec0d6c007">

**Comment by cubiq** [comment]
upgrade comfyui

**Comment by DING03015** [comment]
> 升级comfyui

After entering "git pull", the display is "Already up to date.", but AttributeError: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix' is still displayed.
I want to ask what should I do correctly?
