### ISSUE TITLE
Black output

### ISSUE THREAD

**Issue by Mackay031** [cubiq/ComfyUI_IPAdapter_plus#448]
Hi, I am have a workflow (from Purz) that is now updated with the new IPAdapter. The workflow runs but produces black outputs. I searched known issues and found the reference to black outputs (naming of files) but I am not sure if this is still relevant with the updated IPAdapter, using IPAdapter Unified Loader. Previously there was a know issue with AnimateDiff-Evolved on a Mac but this has been resolved so I am not sure where the issue lies. I am running the workflow with an LCM model. Any thoughts? I can include the workflow if that helps? Thanks again :)

**Comment by cubiq** [comment]
it's impossible to tell without a workflow

**Comment by Mackay031** [comment]
Hi, how are you? Here is the workflow.  

[AnimateLCM_-_6_Color_RGBCMY_-_Context_Smashing_-_Updated_IPA (3).json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14967430/AnimateLCM_-_6_Color_RGBCMY_-_Context_Smashing_-_Updated_IPA.3.json)

Also, I am trying to get me head around the IPAdapter and am struggling a little. Would you be to look at the below workflow and give some advice on how to update to the new IPAdapter. I am not sure what to do with the 'noise' node. It is a variation on the above workflow. As mentioned in another issue, I am still getting the connector issue when I try to connect the weight float to the weight input on the new IPAdapter so I cant get further than that. I tried in an incognito browser as you previously suggested but it still wont let go of the node when I release it. I am using Chrome on a Mac.

[Variation.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14967438/Variation.json)

Thanks for all your efforts and support and apologies to ask for so much help. I am excited to progress with the new IPAdapter.

**Comment by cubiq** [comment]
please if you want me to review your workflows build the minimum workflow that triggers the error, possibly without any extra extension except for ipadapter

**Comment by Mackay031** [comment]
No problem. I seem to have figured it all out eventually, although I am not sure how :)
