### ISSUE TITLE
AttributeError: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'

### ISSUE THREAD

**Issue by mishafarms** [cubiq/ComfyUI_IPAdapter_plus#449]
Just updated to the latest code and tried the example/ipadapter_faceid.json and got this error.
everything works with a git checkout 971585a9430c073e7edf75c476daa6ccbc78bd8a

Thank you.
Michael

**Comment by RandomMaxx** [comment]
Same issue on my side!

**Comment by mishafarms** [comment]
I updated my ComfyUI and it appears to work now.

**Comment by DING03015** [comment]
> 我更新了 ComfyUI，现在似乎可以工作了。 参见问题#447

hi，I also have this problem，how to update comfy UI

**Comment by DING03015** [comment]
> 我更新了 ComfyUI，它现在似乎可以工作了。 参见问题#447

"ComfyUI is already up to date with the latest version.", but AttributeError still occurs: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'
I'd like to ask if there are any other ways
![截屏2024-05-08 10 05 30](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/163505072/5c8430cf-9105-4cb4-b769-1108f84691e6)
