### ISSUE TITLE
Style Transfer for IMG2IMG

### ISSUE THREAD

**Issue by yaboosat** [cubiq/ComfyUI_IPAdapter_plus#452]
Hey guys,
Matteo has provided a workflow that only works for text2image but it doesn't work for img2img like what you can see in this project:

https://github.com/naver-ai/Visual-Style-Prompting

Is there anyone has worked on that? :)

**Comment by cubiq** [comment]
depends what you want to do, for example it would be very simple to style a b/w drawing... like a sort of coloring book.

To completely change the style of an existing photo is more complicated, it can be done to a certain extent but depends how much of the original you want to keep

**Comment by yaboosat** [comment]
Thanks for your response. For example please see this workflow:
https://ibb.co/jMhwyF8

Source: https://github.com/ExponentialML/ComfyUI_VisualStylePrompting/issues/7

It would be great if you could provide a sample workflow like this then we can play with that. I wasn't able to do the same.

**Comment by yaboosat** [comment]
Any update? :)

**Comment by cubiq** [comment]
I published this video that covers that

https://www.youtube.com/watch?v=gmwZGC8UVHE

**Comment by yaboosat** [comment]
That's amazing. I just wanted to say thank you for your hard work.
