### ISSUE TITLE
IPAdapterUnifiedLoaderFaceID:  module 'cv2.dnn' has no attribute 'DictValue'

### ISSUE THREAD

**Issue by yedidyakfir** [cubiq/ComfyUI_IPAdapter_plus#453]
I am trying to use ipadapter unifeid loader face id however I get the following error

> IPAdapterUnifiedLoaderFaceID: module 'cv2.dnn' has no attribute 'DictValue'

This seems like an error with cv2 but I couldn't find any solution.
My opencv version is 3.0.8.76
python 3.10.12
I am using a linux server to run my comfyui
What are the correct version? has anyone encountered this issue?

**Comment by cubiq** [comment]
that's a very old version of opencv, just upgrade it

**Comment by yedidyakfir** [comment]
> that's a very old version of opencv, just upgrade it

I updated to the newest version of opencv (4.9.0.80) with the same results (I also tried a couple of other versions)

**Comment by cubiq** [comment]
try to uninstall all opencv and start over

**Comment by yedidyakfir** [comment]
> try to uninstall all opencv and start over

Same results

**Comment by cubiq** [comment]
try with version 4.8.1.78

**Comment by yedidyakfir** [comment]
> try with version 4.8.1.78

The version you gave me did not work.
However, I am using docker on my linux device (for technical reasons), when I try to install and import the library on my windows device or linux device without docker, I was successful.
Moreover, I download the cv2.dnn.__init__.pyi file from  my container and it seems the DictValues class exists there.
Any idea what is going on? this is very weird.

**Comment by cubiq** [comment]
google: module 'cv2.dnn' has no attribute 'DictValue'

https://github.com/facebookresearch/nougat/issues/40

**Comment by Tanglinling** [comment]
I just updated to the latest version and I have a similar issue when using it.![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/146339730/c1f4f381-bcd9-4d5b-805c-5e72e179f9b6)

**Comment by yedidyakfir** [comment]
> google: module 'cv2.dnn' has no attribute 'DictValue'
> 
> [facebookresearch/nougat#40](https://github.com/facebookresearch/nougat/issues/40)

Thank you so much for you help.
I found my answer in the link you provided (specifically [this ](https://github.com/facebookresearch/nougat/issues/40#issuecomment-1713702899) response worked for me)
