### ISSUE TITLE
About InstantStyle

### ISSUE THREAD

**Issue by ziyaxuanyi** [cubiq/ComfyUI_IPAdapter_plus#457]
Note that one of the methods mentioned in the paper: subtracted clip's embeddings as distinguished representation, but it does not seem to be implemented in the relevant implementation of this code (the workflow used is: [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus)examples/ipadapter_style_composition.json)

Has this code implemented this? If so, could you provide a sample workflow?

**Comment by cubiq** [comment]
you can send the image (or actually any image) and negative conditioning. This can be very effective and the effect can be calibrated also adding noise

**Comment by cubiq** [comment]
I also talk about this in this video https://www.youtube.com/watch?v=gmwZGC8UVHE
