### ISSUE TITLE
Question about the mask of the IPAdapter Encoderd node

### ISSUE THREAD

**Issue by wencxxxxxx** [cubiq/ComfyUI_IPAdapter_plus#459]
When I used the mask of the IPAdapter Encoderd node, the generated image turned yellow and gray, which was not the normal sampling result

**Comment by cubiq** [comment]
impossible to say without looking at what you are exactly doing

**Comment by wencxxxxxx** [comment]
> impossible to say without looking at what you are exactly doing

![屏幕截图 2024-04-13 012607](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/165638226/a3c4cf3e-d426-4fce-9e17-8ca307d1626e)
![屏幕截图 2024-04-13 012702](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/165638226/d33f93c8-634b-43f8-8fde-60603fd52a08)
like this, What's the problem, please? thank you.

**Comment by cubiq** [comment]
that is correct. you are removing over 50% of the image and keep a weight of 1.0.

you need to fill what is not covered by the clip vision with some other conditioning (another IPAdapter for example or stronger text prompt) and/or lower the weight.

**Comment by wencxxxxxx** [comment]
I see. The meaning of masking is not to select a specific part of the reference image to affect the sampling result, but to blacken a certain part of the image to get a new reference image to affect the sampling result. Why not change the meaning of the mask to select specific parts of the reference diagram to affect the sampling results, and the other parts do not affect the sampling results.

**Comment by t00350320** [comment]
reference image mask @wencxxxxxx 
https://github.com/cubiq/ComfyUI_IPAdapter_plus/pull/768
