### ISSUE TITLE
When should we be using ip_adapter vs ip_adapter plus?

### ISSUE THREAD

**Issue by vedantroy** [cubiq/ComfyUI_IPAdapter_plus#46]
Hi! Thanks for making this extension--much appreciated. 2 questions:

- What is the difference between ip_adapter and ip_adapter plus?
- Also, for the image encoders--what are their actual values? I.e, I'm currently using open_clip_pytorch (which I'm guessing is a ViT-H) for the SD1.5 image encoder. But what is the image encoder for SDXL?

**Comment by cubiq** [comment]
- the gist is that the plus model uses more tokens
- the encoder for the sdxl is https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k
