### ISSUE TITLE
IPAdapterUnifiedLoaderFaceID:  cannot import name 'builder' from 'google.protobuf.internal' (F:\AI painting\ComfyUI\ComfyUI_aki\Python310\lib\site-packages\google\protobuf\internal\__init__.py)

### ISSUE THREAD

**Issue by EdisonHaJimi** [cubiq/ComfyUI_IPAdapter_plus#461]
What's going on? Please help me.
![屏幕截图 2024-04-13 110509](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/159610840/a0a41352-c231-4ecd-be84-9af781dce786)
![屏幕截图 2024-04-13 110549](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/159610840/be091c1b-d049-44d2-8e51-d678570a416d)
![屏幕截图 2024-04-13 110605](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/159610840/49658b95-2b86-4680-8ebb-58379622b18e)

**Comment by cubiq** [comment]
you have dependency issues with insightface. might be an old (or too new) version of protobuf

**Comment by EdisonHaJimi** [comment]
I found the reason, it was a conflict with other plug-ins, thank you
