### ISSUE TITLE
Apply IPAdapter FaceID 没有这个对话框

### ISSUE THREAD

**Issue by ericlee2023** [cubiq/ComfyUI_IPAdapter_plus#462]
![Snipaste_2024-04-13_11-49-55](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/133652787/9c9e3af7-82af-4b3e-96fa-22eea920b0d9)
![Snipaste_2024-04-13_11-50-07](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/133652787/f786c496-8ff6-421e-a561-17a892a07c85)
![Snipaste_2024-04-13_11-52-27](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/133652787/ee1c77ca-9b41-4ee3-a756-89f940f86f77)

我也安装好了ComfyUI_IPAdapter_plus，后台也没有报错。
但我这里没有  Apply IPAdapter FaceID 这个对话框。

**Comment by ariel0725** [comment]
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162
我之前也是遇到這樣，後來照這個步驟解決了
先看你python版本，下載對應連結到Comfy根目錄，照著步驟安裝
然後重啟Comfy，如果看到node還是紅色你就refresh試試看 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/50534836/e1a39d40-02c4-4742-bba9-b7bbf771c44f)
