### ISSUE TITLE
size mismatch for proj_in. weight   Can you please help me！！

### ISSUE THREAD

**Issue by q1446227740** [cubiq/ComfyUI_IPAdapter_plus#464]
Hello, I'm sorry, I'm a beginner and my English is not very good. I can only rely on translation software to read English,
I haven't figured out the problem with "size mismatch for proj_in. weight" and haven't understood what you're saying,
Can you explain in detail what 'SD1.5 image encoder' means? I don't understand 'clip vision encoder'
I did use the sd1.5 Checkpoint model,
I can only use 'VIT-G (medium strength)' at the moment,
If you see it, I hope you can help me!
Other friends also hope that you can help me, I have been sitting in front of the computer for 3 hours now!
thanks！！

**Comment by q1446227740** [comment]
![Uploading 1712993125533.png…]()

**Comment by q1446227740** [comment]
![1712993125533](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65085692/d10e89cd-a4f0-4248-a477-9a58dfcb8f2b)

**Comment by q1446227740** [comment]
size mismatch for proj_in.weight: copying a param with shape torch.Size([..., ...]) from checkpoint, the shape in current model is torch.Size([..., ...])
Any tensor size mismatch error is caused by the wrong combination of IPAdapter model, image encoder and/or base checkpoint.

All -vit-h models require the SD1.5 image encoder. At the moment only one SDXL model and the vit-G SD1.5 model need the bigger image encoder.

I don't understand what that means

**Comment by cubiq** [comment]
please post the full error from the console

**Comment by q1446227740** [comment]
Error occurred when executing IPAdapterAdvanced:

Error(s) in loading state_dict for Resampler:
size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).

File "D:\SD,ai\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\SD,ai\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\SD,ai\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\SD,ai\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 673, in apply_ipadapter
return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
File "D:\SD,ai\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 324, in ipadapter_execute
ipa = IPAdapter(
File "D:\SD,ai\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 68, in __init__
self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
File "D:\SD,ai\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by q1446227740** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65085692/3e49c28f-f7ab-40ed-86a6-81657c129f16)

**Comment by q1446227740** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65085692/6c3090d8-fc9c-419f-8dce-5bb792ec3cba)

**Comment by q1446227740** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65085692/9da69218-ff55-4ba1-94ec-6d5220c020fa)

**Comment by q1446227740** [comment]
> please post the full error from the console

I know you're very busy, can you help me

**Comment by cubiq** [comment]
you are using a wrong combination of models, you probably named them wrong. try to re-download the encoders and rename them as instructed in the documentation

**Comment by q1446227740** [comment]
![1712996508829](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65085692/1d96d52c-0e0b-4a9a-a9c3-61d2843ab2a4)

**Comment by q1446227740** [comment]
> 您使用了错误的模型组合，您可能将它们命名错误。尝试重新下载编码器并按照文档中的说明重命名它们

Can I put the 'IP Adapter' model and 'faceid' together

**Comment by cubiq** [comment]
yes

**Comment by q1446227740** [comment]
> yes

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65085692/b7a87df1-61f0-41db-a75a-f87650d367df)
I don't seem to have gotten these names wrong
I have created separate folders circled in red. Let me try it out

**Comment by cubiq** [comment]
the image encoders! not the ipadapter models

**Comment by q1446227740** [comment]
Sorry, I'm not sure which one is "the image encoders". Can you mark it on "GitHub"

**Comment by cubiq** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/81419986-801b-4b38-9d34-541f38c6e14e)

**Comment by q1446227740** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/65085692/a89ac7b0-f420-45b4-a1bb-c16ed5745282)
I don't seem to be making any mistakes with this one

**Comment by q1446227740** [comment]
Wtf! Sorry, they seem to be one file!! How could this be? I'm really sorry, thank you very much

**Comment by q1446227740** [comment]
What did I do! Maybe my network fluctuated and my download interrupted once. I made a mistake with the file!

**Comment by Jonfr0** [comment]
Hey @cubiq, I have the same problem but the solution you gave didn't work for me, I don't know why. Mi potete aiutare? 
                                                                                                                    
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/62057689/fd9fd6d4-b2e1-413c-bc88-76cac39ca4f0)

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/62057689/d7461ec8-6683-4ad4-bd48-afbd70c0311e)

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/62057689/814a3dc9-aae8-4997-9ba0-551c55740903)
