### ISSUE TITLE
IPAdapter model not found ,  IPAdapterUnifiedLoader  When selecting LIGHT -SD1.5   

### ISSUE THREAD

**Issue by samen168** [cubiq/ComfyUI_IPAdapter_plus#465]
[ip adapter sd15 light_v11. bin] in README, mismatch with expression
pattern = 'sd15.light\.(safetensors|bin)$'

in file custom_nodes/ComfyUI_IPAdapter_plus/utils.py:36

**Comment by cubiq** [comment]
you might have an old version installed, try to upgrade

**Comment by samen168** [comment]
Yes, there is no problem with the update, thank you!
