### ISSUE TITLE
When using a square image as a reference, the ipadapter tiled apply causes the resulting image to blur

### ISSUE THREAD

**Issue by emptybamboo** [cubiq/ComfyUI_IPAdapter_plus#467]
If the square image is used as the positive image of the ipadapter tiled, the resulting image will be blurred. At present, I can only avoid this problem by judging the plug-in area logically. Once the side length of the reference image is consistent, the ipadapter apply will be used, otherwise the ipadapter tiled apply will be used.Can this problem be circumvented directly at the plug-in code level
![360截图20240413175202901](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/47071080/ea037832-755f-4d42-b3b8-61d29b87b1d9)
![QQ截图20240413175209](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/47071080/0d6328cd-4752-43d4-8303-a2062beb9797)

**Comment by cubiq** [comment]
for square images you should use two IPAdapters, one for the tiles and one for the overall composition. To do what you say we would need an additional option "do not tile square images". It's doable but I have other priorities at the moment

**Comment by emptybamboo** [comment]
In fact, I don't really understand how the two IPadapters are used together, it would be great if you could give an example, but it doesn't matter if you don't have one, or thank you very much for your effort
