### ISSUE TITLE
what models should put at CLIP Vesion Load?

### ISSUE THREAD

**Issue by lilyzlt** [cubiq/ComfyUI_IPAdapter_plus#47]
from this example, it should put the model "IPAdapter_image_encoder_sd15.safetensors", where I find it? it's not CLIP base/large/big model here?
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/15058321/c4517c1f-ea32-4fee-9496-d72a293825e8)

**Comment by cubiq** [comment]
you can use the models linked in the readme documentation or clip vit-h
