### ISSUE TITLE
comfyui 运行一个生成卡通手办工作流时报错

### ISSUE THREAD

**Issue by brotherlei** [cubiq/ComfyUI_IPAdapter_plus#473]
有没有comfyui 大神帮我解决一下这个问题，[rgthree] Using rgthree's optimized recursive execution.

!!! Exception during processing !!!

Traceback (most recent call last):

 File "D:\workspace\ComfyUI\execution.py", line 151, in recursive_execute

   output_data, output_ui = get_output_data(obj, input_data_all)

 File "D:\workspace\ComfyUI\execution.py", line 81, in get_output_data

   return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)

 File "D:\workspace\ComfyUI\execution.py", line 74, in map_node_over_list

   results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))

 File "D:\workspace\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 597, in apply_ipadapter

   raise Exception("Missing CLIPVision model.")

Exception: Missing CLIPVision model.

Prompt executed in 0.33 seconds

**Comment by 4thanks** [comment]
缺啥补啥，报错`Missing CLIPVision model`缺少了这个模型，按教程把下面两个下载放到对应路径。

> Remember you can also use any custom location setting an ipadapter entry in the extra_model_paths.yaml file.
>     `/ComfyUI/models/clip_vision`
      [CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors), download and rename
      [CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors), download and rename
