### ISSUE TITLE
Error occurred when executing IPAdapte

### ISSUE THREAD

**Issue by longge0126** [cubiq/ComfyUI_IPAdapter_plus#477]
Error occurred when executing IPAdapter:

Error(s) in loading state_dict for ImageProjModel:
size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1280]) from checkpoint, the shape in current model is torch.Size([8192, 1024]).

**Comment by cubiq** [comment]
size mismatch is covered here. https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108

remember to update the extension!
