### ISSUE TITLE
'ClipVisionModel' object has no attribute 'processor'

### ISSUE THREAD

**Issue by Guillaume-Fgt** [cubiq/ComfyUI_IPAdapter_plus#48]
I got this error this morning after updating Comfy

> Error occurred when executing IPAdapterApply:
> 
> 'ClipVisionModel' object has no attribute 'processor'
> 
>   File "C:\Users\guill\Documents\ai\ComfyUI\execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "C:\Users\guill\Documents\ai\ComfyUI\execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "C:\Users\guill\Documents\ai\ComfyUI\execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "C:\Users\guill\Documents\ai\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 326, in apply_ipadapter
>     clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
>   File "C:\Users\guill\Documents\ai\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 99, in zeroed_hidden_states
>     inputs = clip_vision.processor(images=img, return_tensors="pt")

I think a commit in ComfyUI ([ComfyUI@723847f6b3d5da21e5d712bc0139fb7197ba60a4](https://github.com/comfyanonymous/ComfyUI/commit/723847f6b3d5da21e5d712bc0139fb7197ba60a4)) has caused this error when using ipadapterplus because `self.processor` was deleted from `ClipVisionModel` class

**Comment by cubiq** [comment]
the new processor grants slightly better results for some reason. not that I complain

**Comment by Guillaume-Fgt** [comment]
thank you for the quick fix!

> the new processor grants slightly better results for some reason. not that I complain
yeah, I agree:

before commit:
![ComfyUI_00599_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/66461774/6936f6d6-30d0-4ab5-9e28-ed817461bd13)
after commit:
![ComfyUI_00600_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/66461774/48010817-9127-4cfa-9c14-ba808dee652b)

No changes in the parameters.
ref image:
![superb-cg-jc0l219a4-orangecat-lookwindow-display-4k](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/66461774/4740cd98-faee-4ba7-94ab-c93467a95e17)

**Comment by Manish-cel** [comment]
> thank you for the quick fix!
> 
> > the new processor grants slightly better results for some reason. not that I complain
> > yeah, I agree:
> 
> before commit: ![ComfyUI_00599_](https://user-images.githubusercontent.com/66461774/278244101-6936f6d6-30d0-4ab5-9e28-ed817461bd13.png) after commit: ![ComfyUI_00600_](https://user-images.githubusercontent.com/66461774/278244107-48010817-9127-4cfa-9c14-ba808dee652b.png)
> 
> No changes in the parameters. ref image: ![superb-cg-jc0l219a4-orangecat-lookwindow-display-4k](https://user-images.githubusercontent.com/66461774/278244505-4740cd98-faee-4ba7-94ab-c93467a95e17.jpg)

how did you fixed it please explain, i am having tis same issue

**Comment by Manish-cel** [comment]
> the new processor grants slightly better results for some reason. not that I complain

what new processor please explain, i am having this issue

**Comment by aqgasa** [comment]
> > the new processor grants slightly better results for some reason. not that I complain
> 
> what new processor please explain, i am having this issue

I got it to work when I updated all through the ComfyUI Manager. Manager -> Update All

**Comment by crimpproduction** [comment]
I got the same error. updated the comfyui, update all, but still get this error message:

Error occurred when executing IPAdapterApply:

'ClipVisionModel' object has no attribute 'get'

File "C:\AI STABLE DIFFUSION\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI STABLE DIFFUSION\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI STABLE DIFFUSION\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI STABLE DIFFUSION\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 510, in apply_ipadapter
clip_embed = clip_vision.get(tensorToCV(image)) # TODO: support multiple images (is it needed?)
^^^^^^^^^^^^^^^

**Comment by Grewlz** [comment]
> > > the new processor grants slightly better results for some reason. not that I complain
> > 
> > 
> > what new processor please explain, i am having this issue
> 
> I got it to work when I updated all through the ComfyUI Manager. Manager -> Update All

I updated ComfyUI Manager but still have the issue. What am I doing wrong?
![Uploading Screenshot 2024-04-03 182116.png…]()

**Comment by yurigushiken** [comment]
Hi. I'm randomly getting this issue all of a sudden from a workflow that has been consistent. No changes made. Srsly all of a sudden. Any ideas? Much thanks
