### ISSUE TITLE
CLIP model IPAdapters FaceID error

### ISSUE THREAD

**Issue by littleyeson** [cubiq/ComfyUI_IPAdapter_plus#481]
![QQ截图20240417001143](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/70052345/c0e88580-c6c2-4649-8150-c64dfca59f2f)
change a new IPAdapter FaceID is error.How to fixed.

**Comment by cubiq** [comment]
connect insightface

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/a3a95e0a-7126-44d8-a396-b60a15e743f9)

**Comment by littleyeson** [comment]
> connect insightface
> 
> ![image](https://private-user-images.githubusercontent.com/427614/322922634-a3a95e0a-7126-44d8-a396-b60a15e743f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MTE4MzgsIm5iZiI6MTcxMzQxMTUzOCwicGF0aCI6Ii80Mjc2MTQvMzIyOTIyNjM0LWEzYTk1ZTBhLTcxMjYtNDRkOC1hMzk2LWI2MGExNWU3NDNmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwMzM4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTU0NDVkMTY2MmM5MjY4NDVmZjI0YmUwMjg1MjM2ZDNhMDE1ODNkYmZlNjY0NjQ1NWVjZTNhY2Q4NWYwYThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fk9ZffeiwS1uL9kqwBIDUHhmwA-ydRLPUB4SmSdkUQo)

thx
