### ISSUE TITLE
Prepare Image For InsightFace

### ISSUE THREAD

**Issue by GuyRichardib** [cubiq/ComfyUI_IPAdapter_plus#483]
Hi

I can't seem to find the "Prepare Image For InsightFace" node is a feature within ComfyUI that is related to IPAdapter models, and it's a reference implementation for these models within the ComfyUI ecosystem.

This particular node has options to adjust the crop position, sharpening, and padding around the image, which are used to prepare images for further processing by InsightFace. 

Have there been any updates or changes to the nodes?

![Screenshot_2024-04-18-05-12-01-220_com google android youtube-edit](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/72995913/28b4e49e-cc35-4a66-9373-eeef0300a4ef)

**Comment by JEONGOLDTREE** [comment]
i want to use  Prepare Image For InsightFace but i cannot find out this node, how can i use?
