### ISSUE TITLE
Tensor dimension mismatch error when using Embeds of type Plus after v2 upgrade

### ISSUE THREAD

**Issue by petercham** [cubiq/ComfyUI_IPAdapter_plus#485]
Tensors must have same number of dimensions: got 4 and 3
I've saved a lot of Plus Embeds, and now all of them are giving this error, but non-Plus Embeds are executing just fine!

**Comment by petercham** [comment]
![57ba0167-138f-4654-8f05-9e1268d62bd2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/3765653/930025d6-ac74-4481-b40a-da075d461312)

**Comment by cubiq** [comment]
were the embeds saved with the previous version?

**Comment by petercham** [comment]
> were the embeds saved with the previous version?

Yes, it's Embeds made during v1. Is it only possible to re-save them all again with v2? It would be a lot of work, and a lot of it may not be able to recover the exact parameters from before. Is it possible to provide a compatibility mode that runs using v1 alignment?

**Comment by cubiq** [comment]
I believe it should be fairly simple to convert the old embeds, I can add it to my to-do but it's a very low priority at the moment, sorry

**Comment by petercham** [comment]
> I believe it should be fairly simple to convert the old embeds, I can add it to my to-do but it's a very low priority at the moment, sorry

Ok, thanks for the suggestion, let's try to recreate all the Plus mode Embeds first!
