### ISSUE TITLE
How to extract lora file?

### ISSUE THREAD

**Issue by UrwLee** [cubiq/ComfyUI_IPAdapter_plus#489]
Hi, could please offer the solution that how to extract lora from pytorch_model.bin or ip_adapter.bin, much appreciate!

**Comment by cubiq** [comment]
you should probably ask the guys at tencent, I don't think they released the code for all of them. I was able to extract the lora for the sd1.5 because it's easy enough

**Comment by UrwLee** [comment]
Could please offer the solution to extract sd1.5 lora

**Comment by UrwLee** [comment]
> you should probably ask the guys at tencent, I don't think they released the code for all of them. I was able to extract the lora for the sd1.5 because it's easy enough


Could please offer the solution to extract sd1.5 lora
