### ISSUE TITLE
The "Weight_type" in "IPAdapterAdvanced" does not have "style transfer(SDXL)" and "compostion(SDXL)".

### ISSUE THREAD

**Issue by benj-pan** [cubiq/ComfyUI_IPAdapter_plus#495]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/166602243/799d6975-cfa2-42f4-9ea2-5fe05a67624d)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/166602243/3d783f64-3cdd-42b7-988a-cb4308636ee1)
Other functions are working fine, but there is no "style transfer(SDXL)" and "compostion(SDXL)", I would like to have a separate reference for styles, but I can't get it to work. How to solve this problem?

**Comment by cubiq** [comment]
style/composition transfer now works with SDXL and SD1.5.

**Comment by benj-pan** [comment]
> style/composition transfer now works with SDXL and SD1.5.风格/构图传输现在适用于 SDXL 和 SD1.5。

OH, I see, thank you very much for your answer!
