### ISSUE TITLE
Is something like Magnific.ai Style Transfer possible?

### ISSUE THREAD

**Issue by andyderuyter** [cubiq/ComfyUI_IPAdapter_plus#497]
Magnific.ai produces some amazing results regarding style transfer (with an additional 4x upscale afterwards). Is something like this possible in IPAdapter Plus?

![magnific-vs-comfyui](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/646590/a479c688-9561-416e-ad75-738afe2b0161)

I fail to get coherent composition structure, no matter what I try.

Used pictures:

![input-1](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/646590/e0c31e34-97fb-4a85-8952-7287f06872d7)
![reference-1](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/646590/3313cf50-c294-4ddd-a2a7-1b68d36c730c)
![reference-3](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/646590/a8b8a214-e622-4cc0-98d3-6cc926f547c2)

Edit, this is my setup (not pictured: Image Comparer on the right)

![photo_2024-04-21 19 45 47](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/646590/65cdc2c4-2940-4fd4-ad4a-031fd81aae4d)

**Comment by cubiq** [comment]
the style transfer is similar, the extra details are generated by the upscaler

**Comment by andyderuyter** [comment]
Could composition be improved by using some controlnet maybe? Never worked with it before though.

**Comment by cubiq** [comment]
of course, this is with lineart without upscaling

![ComfyUI_temp_hneyn_00010_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/726131d2-23d6-413f-8143-fe3195ba169b)

**Comment by andyderuyter** [comment]
This looks amazing! Mind sharing the workflow? This is exactly what I'm after

**Comment by cubiq** [comment]
It's just a style transfer with lineart...

[dog.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/15058757/dog.json)
