### ISSUE TITLE
Error when using "Combine Params"

### ISSUE THREAD

**Issue by JoBilert** [cubiq/ComfyUI_IPAdapter_plus#498]
Whenever I use the "combine Params"-node I get the following error:

>The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

If i plug a single IP-Params into the IPadapter from Params it works.

**Comment by cubiq** [comment]
please show the workflow

**Comment by JoBilert** [comment]
Sorry for the late answer. The problem was on my side.  I tried pictures from a source I previously never had issues with. Turned out that the 4 pictures I tried this workflow on where RGBA. Problem could be fixed by using the "Image to RGB"-Node.

**Comment by xxyuluocha** [comment]
> Sorry for the late answer. The problem was on my side. I tried pictures from a source I previously never had issues with. Turned out that the 4 pictures I tried this workflow on where RGBA. Problem could be fixed by using the "Image to RGB"-Node.

How can i find Image to "Image to RGB"-Node? I can't find it.Ths
