### ISSUE TITLE
Explanation of the "ideal faceid" workflow

### ISSUE THREAD

**Issue by ghostsquad** [cubiq/ComfyUI_IPAdapter_plus#499]
In the ideal faceid workflow, here: https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/examples/ipadapter_ideal_faceid_config.json

it looks like there are 2 IPAdapter passes going on. Why is that?

**Comment by cubiq** [comment]
https://www.youtube.com/watch?v=oBKcjY-JO3Y
