### ISSUE TITLE
cannot import name 'clip_preprocess' from 'comfy.clip_vision

### ISSUE THREAD

**Issue by Autantpourmoi** [cubiq/ComfyUI_IPAdapter_plus#50]
Hello  import failed since today update on mac osx

**Comment by cubiq** [comment]
try to update the ipadapter extension

**Comment by Autantpourmoi** [comment]
which mean ? soory i don't understand
  File "/Users/lucvaligny/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/lucvaligny/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/__init__.py", line 1, in <module>
    from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Users/lucvaligny/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 8, in <module>
    from comfy.clip_vision import clip_preprocess
ImportError: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (/Users/lucvaligny/ComfyUI/comfy/clip_vision.py)

Cannot import /Users/lucvaligny/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus module for custom nodes: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (/Users/lucvaligny/ComfyUI/comfy/clip_vision.py)

**Comment by cubiq** [comment]
you need the latest version of IPAdapter

**Comment by Autantpourmoi** [comment]
you mean the models ? like 'ip-adapter_sd15_light.bin'

**Comment by cubiq** [comment]
you need to download the latest version of ComfyUI_IPAdapter_Plus, this very same extension

**Comment by Autantpourmoi** [comment]
i did 3 times already

**Comment by cubiq** [comment]
then you need to update comfyui itself

**Comment by opensourcefan** [comment]
> then you need to update comfyui itself

That fixed it.
