### ISSUE TITLE
Error occurred when executing IPAdapterUnifiedLoader: IPAdapter model not found.

### ISSUE THREAD

**Issue by cybearvision** [cubiq/ComfyUI_IPAdapter_plus#502]
I'm not sure why I keep getting this error message. Appreciate any help!

<img width="610" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/111700402/cff487ff-cf2f-45c6-bd49-ba35edb0b36e">

I believe I downloaded all models.
 
<img width="740" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/111700402/5ddefe4e-1db0-4b11-9256-343e93c83dbf">
<img width="736" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/111700402/fca83806-d83c-447b-a969-cbc37d02e58f">

<img width="1057" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/111700402/6edd5153-b63f-48cf-860e-8ee444340239">

**Comment by Guillaume-Fgt** [comment]
* you need to have the model files in the `ipadapter` folder, not `controlnet`
* you have to use ipadapter models, not t2i ones
* you have to respect [naming conventions](https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#installation)

So in the `ComfyUI\models\ipadapter` folder, you can put for example [ip-adapter_sdxl_vit-h.safetensors](https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors) as you are using an sdxl checkpoint.

**Comment by cubiq** [comment]
the controlnet for the lineart is correct, they only miss the ipadapter models. we've talked about this multiple times and it's described in the documentation

**Comment by Israel-Laguan** [comment]
SO I debugged and seems like ComfyUI's file `<root>/folder_paths.py` don't have `ipadapter` path, when I added it it worked for me:

```python
folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)
```

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/36519478/ec598c17-855a-4a5f-b25c-2b16a022de28)
