### ISSUE TITLE
Pony XL 6 models problem.

### ISSUE THREAD

**Issue by tomudo** [cubiq/ComfyUI_IPAdapter_plus#505]
IPAdapter I'm not sure that it my mistake or not really know to use. The SDXL Pony XL 6 models have problem to transfer characteristic to image, for example, I generate a super man and apply a ipadapter of Eienstein face. The face is look weird.  And change from realistic style to cartoon style.
Pony XL 6 quite popular lately but has problem with normal loras too. Someone mentioned that it overfit training which require to special train for this models.

**Comment by cubiq** [comment]
pony models are trained in such a way that nothing is compatible with it :smile: 

It might be possible to finetune the IPAdapter for them, but I personally don't have time (or motivation)
