### ISSUE TITLE
IPAdapterApplyEncoded "SDXL+vit-h+sd1.5clip vision" error

### ISSUE THREAD

**Issue by suede299** [cubiq/ComfyUI_IPAdapter_plus#52]
If you don't use "Encode IPAdapter Image" and "Apply IPAdapter from Encoded", it works fine, but then you can't use img weights.
Of course, when using a CLIP Vision Encode node with a CLIP Vision model that uses SD1.5, and the basemodel is an SDXL model, there would have been an error and it wouldn't have run.
So regarding your image weighting feature, can it be implemented in this case?
----------------------------------------------------------------
Error occurred when executing IPAdapterApplyEncoded:

Error(s) in loading state_dict for Resampler:
size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1024]).

File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 316, in apply_ipadapter
self.ipadapter = IPAdapter(
^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 161, in __init__
self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
File "D:\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by suede299** [comment]
The description above may be too confusing. It simply means that "ip-adapter-plus-face_sdxl_vit-h.bin" needs to use the 1.5 encoder model. When I use "Apply IPAdapter", everything works fine. When I use "Apply IPAdapter from Encoded", I get an error.

**Comment by cubiq** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/863212f7-a99f-4576-b7eb-e954e0b3b45d)

you need to select "ipadapter_plus" when use plus models

**Comment by suede299** [comment]
> need to select "ipadapter_plus" when use plus mo
Sorry, always forgetting to change the settings here
