### ISSUE TITLE
A way to get back the values when node types were not found?

### ISSUE THREAD

**Issue by johan-pardo** [cubiq/ComfyUI_IPAdapter_plus#527]
Hello @cubiq 

First of all thanks the amazing work you provide. Huge respect.  I made the update, super nice optimisation, but I have hundreds of experiments and it can be a pain to get back to similar results by tweaking again my weights for each experiment. 

So my question is: Is there way to get / to see the old values back even when node types were not found? Off course the node appears in red, so i lost my weight parameters. Is there any tick to achieve this except getting back to old versions (it's gonna be complicated....I'm digging all the time in all stuffs? This could be so helpfull

Thanks in advance

**Comment by cubiq** [comment]
you can open the json file with the workflow and check the value from there. it's a simple text file

**Comment by johan-pardo** [comment]
Man it was so obvious. Thx so much for your time

**Comment by johan-pardo** [comment]
Ok I found the values easily. What correspond to the noise value and unfold batch true/false in the new nodes?

**Comment by cubiq** [comment]
connect the ipadapter noise node to the negative image. connect the reference to the noise and select shuffle.
