### ISSUE TITLE
Unable to install the latest version

### ISSUE THREAD

**Issue by Trobinou** [cubiq/ComfyUI_IPAdapter_plus#53]
Hello,

I have the version from October 12, 2023, which works without any problems.
However, I'm unable to install the update (ConfyUI indicates that it wasn't loaded). 
I've completely uninstalled IPA+ with the Manager and then tried to reinstall it, but without success.

What information do you need to resolve this issue?

**Comment by cubiq** [comment]
you probably need to update ComfyUI

**Comment by Trobinou** [comment]
For some reason, ComfyUI didn't want to update and I was stuck on version 1610 [56f742e9] | Released on '2023-10-21'
After installing a new version, the 1631 [c837a173] | Released on '2023-10-30', everything works again.
I'll close this issue, thank you.
