### ISSUE TITLE
Sudden problem loading IPadapter/clipvision on two computers

### ISSUE THREAD

**Issue by Kallamamran** [cubiq/ComfyUI_IPAdapter_plus#530]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/25354644/673e5b68-6af6-469e-b705-99fbd0f6556d)

I suddenly have this error on two of my computers. Both the computer at home and the computer at work. Since it worked last time I have only updated ComfyUI and all nodes and I cant solve this. I have downloaded and renamed the models correctly and put them in folders according to the manual, but still... No luck

**Comment by cubiq** [comment]
can you please post the full error message from the console?

**Comment by Kallamamran** [comment]
got prompt
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI_P\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_P\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_P\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_P\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 444, in load_models
    if clipvision_file != pipeline['clipvision']['file']:
                          ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'clipvision'

**Comment by cubiq** [comment]
please also post the workflow

**Comment by Kallamamran** [comment]
[workflow.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/15198162/workflow.json)

**Comment by cubiq** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/401d5770-f67b-447d-9525-132c02617df3)

**Comment by Kallamamran** [comment]
Yeah.... Tried remaking the workflow and just noticed 😒 WTF did that come from 🤔 Thanks for your time!
