### ISSUE TITLE
 FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

### ISSUE THREAD

**Issue by petercham** [cubiq/ComfyUI_IPAdapter_plus#534]
The InsightFace Loader node failed to load and reported the following error:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/3765653/88494deb-307d-4ddb-9c75-d9fadad15ff8)

ComfyUI version is 72508a8(https://github.com/comfyanonymous/ComfyUI/commit/72508a8d19121e2814ea4dfbce8a5311f37dcd61) May 4, 2024.
IPAdapter_plus node version is a336127 (https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/a336127797485aeaa255cd20ecfe64b7f3d52d75) May 2, 2024.

All fresh installations, no residual issues with older IPAdapter_plus node versions.

The same error is reported regardless of CPU, CUDA, or ROCM selection.

**Comment by petercham** [comment]
> The InsightFace Loader node failed to load and reported the following error:
> 
> ![image](https://private-user-images.githubusercontent.com/3765653/327993882-88494deb-307d-4ddb-9c75-d9fadad15ff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4OTE5MDUsIm5iZiI6MTcxNDg5MTYwNSwicGF0aCI6Ii8zNzY1NjUzLzMyNzk5Mzg4Mi04ODQ5NGRlYi0zMDdkLTRkZGItOWM3NS1kOWZhZGFkMTVmZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDVUMDY0NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBlNmM1M2E2ZDAwY2E3ZmVkNzhmZDI2ODcxYjlmMWIzZmVkYWQyNDZkZDYyMDIyZGQ0OGU1Y2VlNjliMjkwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FoZItLbLPcIbAqAdIcRFR4m8sOqR2URRuMWLOC4ndOI)
> 
> ComfyUI version is 72508a8([comfyanonymous/ComfyUI@72508a8](https://github.com/comfyanonymous/ComfyUI/commit/72508a8d19121e2814ea4dfbce8a5311f37dcd61)) May 4, 2024. IPAdapter_plus node version is [a336127](https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/a336127797485aeaa255cd20ecfe64b7f3d52d75) ([a336127](https://github.com/cubiq/ComfyUI_IPAdapter_plus/commit/a336127797485aeaa255cd20ecfe64b7f3d52d75)) May 2, 2024.
> 
> All fresh installations, no residual issues with older IPAdapter_plus node versions.
> 
> The same error is reported regardless of CPU, CUDA, or ROCM selection.

Since all models are placed in the intranet shared directory, could it be because the IPAdapter models can be configured with the IPAdapter model extension directory via ComfyUI's extra_model_paths.yaml, and the InsightFace models, which are not included by ComfyUI in folder_path. py so it can only be loaded locally?

**Comment by cubiq** [comment]
can I see the full error message? This looks like a problem with insightface installation

**Comment by petercham** [comment]
> 我能看到完整的错误消息吗？这看起来像是 insightface 安装的问题

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/3765653/6beb3a62-7731-48ee-8195-976e22332878)

> can I see the full error message? This looks like a problem with insightface installation

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/3765653/d61275b5-1977-40c0-a898-299a7233e15a)

**Comment by cubiq** [comment]
you probably miss onnxruntime and/or onnxruntime-gpu

alternatively you may have an older version of insightface installed

**Comment by petercham** [comment]
> you probably miss onnxruntime and/or onnxruntime-gpu
> 
> alternatively you may have an older version of insightface installed

While this issue may not be directly related to your node, can I ask though, how should I install Insightface? It seems that the old version worked after installing IPAdapter_plus before, and this is the first time I encountered this problem with this reinstallation of ComfyUI.

**Comment by vesper8** [comment]
In my case, running `pip install insightface` was always installing `insightface===0.2.1`

I then ran `pip install insightface==0.7.3` and that installed the latest version and then the problem went away
