### ISSUE TITLE
Not able to use the node

### ISSUE THREAD

**Issue by IamME1311** [cubiq/ComfyUI_IPAdapter_plus#535]
Hello guys, my issue is very annoying. my insight face is installed but when I try to add the node
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/122204392/27a9ec85-3444-4cb5-8d74-d4fbb8149ce2)
its not showing in my case
![Uploading image.png…]()
Any clues? @cubiq

**Comment by cubiq** [comment]
I'm sorry I don't understand what you mean

**Comment by IamME1311** [comment]
when I am trying to add the node name " Apply IPAdapter FaceID" and "Apply IPAdapter" , the node is not listed in the search results.
No worries, I rolled back to previous version of IPAdapter to make it work.
Just a question my system specs are Ryzen 5 3600 (6-core 12-thread @ 4.2GHz), 16 GB RAM @ 3200MHz and Nvidia 6GB GTX 1660Ti. It it enough for using complex workflows or should I upgrade it.

**Comment by cubiq** [comment]
if you can add ram and upgrade the gpu

**Comment by nurettn** [comment]
@IamME1311 hi, how did you roll back to the previous version? I need the same thing too

**Comment by IamME1311** [comment]
@nurettn 
- open this path in cmd  E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus.
- In CMD type git log --oneline, you shall see this 
  ![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/122204392/16df0f94-b78d-4397-8816-e285cff2555f)
- press Down arrow key to navigate to this which says "complete code rewrite. there will be blood"
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/122204392/67648d15-0d29-4b10-81ee-f8930d730a0d)
- copy the branch code of the below branch which is 6a411dc and press "q" to exit log
- then type "git checkout 6a411dc"
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/122204392/63668557-ee13-44c7-aa1b-498491433c7a)
- congrats, you just rolled back
