### ISSUE TITLE
Feature Request: PuLID

### ISSUE THREAD

**Issue by taoisu** [cubiq/ComfyUI_IPAdapter_plus#537]
Hi @cubiq, this is such a nice work you're doing, truly appreciate it.

There is a recent work of consistent id generation: https://github.com/ToTheBeginning/PuLID/tree/main, which seems to share many similarities with IP adapters, I think it quite fit into this repo, wondering if you would consider implementing it in this repo?

**Comment by cubiq** [comment]
I think I'll make a separate repo for that, I implemented everything already but the weights are not applied correctly so I'm doing something wrong somewhere. I'll check when I have time

**Comment by cubiq** [comment]
https://github.com/cubiq/PuLID_ComfyUI
