### ISSUE TITLE
Error:  cannot import name 'clip_preprocess' from 'comfy.clip_vision'

### ISSUE THREAD

**Issue by rafstahelin** [cubiq/ComfyUI_IPAdapter_plus#54]
I am getting the following error:

`Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\__init__.py", line 1, in <module>
    from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 7, in <module>
    from comfy.clip_vision import clip_preprocess
ImportError: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (D:\ComfyUI\ComfyUI\comfy\clip_vision.py)

Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus module for custom nodes: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (D:\ComfyUI\ComfyUI\comfy\clip_vision.py)
`

I am up to date with ComfyUI and IP-plus. 

What seems to be the problem? 

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/64715158/df70efd0-8170-41dc-9e6d-ecdb201887d2)

**Comment by cubiq** [comment]
you need to update comfyui

**Comment by rafstahelin** [comment]
I have. I updated ComfyUi through manager and with git pull. Still getting the above traceback.
The strange thing is, I cannot find any IP-Adapter nodes in the search bar, and these nodes aren't working either

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/64715158/45bc3441-e272-4013-9d13-f15abbc5f412)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/64715158/113c352c-20c7-4a3c-af0f-d4576227abcd)

**Comment by rafstahelin** [comment]
Maybe an extension is conflicting?

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/64715158/6fbac920-eadd-4283-b20a-9590f9aa0fe5)

**Comment by cubiq** [comment]
have you also updated comfyui_ipadapter_plus?

**Comment by rafstahelin** [comment]
Yes, i have. I wonder though, maybe it has to do with extra paths? the fact that I am using paths to webui? even though i have clip vision installed?

**Comment by cubiq** [comment]
have you restarted comfyui after updating it?

that error means that you are still using an older version, you can verify it by opening the file `/comfy/clip_vision.py`, if line 12 doesn't look like this `def clip_preprocess(image, size=224):` you have an old version

**Comment by rafstahelin** [comment]
this is what I am seeing
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/64715158/24903690-030d-4d61-9257-cd226edadb00)

by updating Comfyu, do you mean one of these two bat files?
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/64715158/ebaa6076-045d-4313-b816-aef1b864ff52)

**Comment by cubiq** [comment]
download the latest standard alone version, then you can try to update it if it still doesn't work

**Comment by rafstahelin** [comment]
Ok

**Comment by rafstahelin** [comment]
ok, installed cu121, and installed IP-Adapter and works now
