### ISSUE TITLE
IpAdapter (mainly FaceID) got extremely slow over time

### ISSUE THREAD

**Issue by TobiTomatoe** [cubiq/ComfyUI_IPAdapter_plus#547]
As the title says, the IpAdapter FaceID got slower over time, to the point where the bar of the KSampler is barely moving. The behavior was hit or miss at first for the longest time when I was clicking the prompt button, meaning sometimes it was going slower causing me to just cancel the prompt, clicking prompt again and it sometimes would go faster again. Now it is just slow, no matter what. I know that my specs are not the best and it is normal that it wont be very fast with the workflows I built, since I generate at a bigger image scales using thePatchModelAddDownscale (Kohya Deep Shrink) node,  however it has always been fast enough to be able to still work with it. I would also like to mention that I update comfyUI and all custom nodes on a daily basis. Has this kind of behavior already been mentioned and does someone know what I can do about it?

Operating System: Windows 11 Home 64-bit
Processor: 12th Gen Intel(R) Core(TM) i5-12400F (12 CPUs), ~2.5GHz
Memory: 16384MB RAM
Available OS Memory: 16216MB RAM

Card name: NVIDIA GeForce RTX 3060
Manufacturer: NVIDIA
Dedicated Memory: 12115 MB
Shared Memory: 8108 MB

**Comment by cubiq** [comment]
please provide a minimal workflow that replicates the issue

**Comment by TobiTomatoe** [comment]
Sure. There you go
[ExampleWorkflow.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/15277480/ExampleWorkflow.json)

**Comment by cubiq** [comment]
thanks, I would really appreciate if you trim it down to just the bare minimum that triggers the issue. Ideally only base nodes and ipadapter

**Comment by TobiTomatoe** [comment]
I'm sorry. I thought the deep shrink and freeU might be relevant, that's why I didn't remove them.

This is as basic as it can get. Here you go. 
[ExampleWorkflow02.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/15277848/ExampleWorkflow02.json)

Interestingly, with everything removed it does now run consistently faster as it used to. But I need the loras, deepshrink and freeU as I used it all the time with faceID.

**Comment by TobiTomatoe** [comment]
I tested it again and it seems like the "PatchModelAddDownscale (Kohya Deep Shrink)" is what slows it down that extremely (probably even more in conjunction with FreeU). What a shame. It used to work well before.

**Comment by cubiq** [comment]
I don't know what could have caused it honestly but it's impossible to keep track of all the updates of all the extensions

**Comment by TobiTomatoe** [comment]
I understand that. Well, I'm glad that I at least now know which nodes don't play nice with faceID, at least on my personal machine and install. Tanks for taking the time.
