### ISSUE TITLE
ETA on PDXL support?

### ISSUE THREAD

**Issue by Winnougan** [cubiq/ComfyUI_IPAdapter_plus#548]
Pony Diffusion XL, aka PDXL or just "Pony," is the hottest checkpoint right now in the Stable Diffusion universe. All of the derivative Pony checkpoints are great too. I have been using your IPAdapter Plus custom nodes ever since they came out. However, SDXL LORAs are not optimized for PDXL. Is there anyway we can get IPAdapter to work with PDXL LORAs? Or is it just "tough potatoes"? Thanks,

**Comment by cubiq** [comment]
I'm not familiar with the way pony models are trained. I don't think there's any effort in training a specific models for them at the moment. If the community works on it I will add support
