### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by i30226** [cubiq/ComfyUI_IPAdapter_plus#55]
![image](https://github.com/laksjdjf/IPAdapter-ComfyUI/assets/122668340/d7f5dab1-4b38-43d4-9320-ce4dacc9465f)
一切准备就绪，但是出些了如下报错
![image](https://github.com/laksjdjf/IPAdapter-ComfyUI/assets/122668340/605a0ba7-3de6-422d-9f96-6706a225a45e)

**Comment by cubiq** [comment]
that is a very weird error message.

try to:
1) re-download the latest version of comfy
2) re-download the IPAdapter models

**Comment by i30226** [comment]
已解决，谢谢
