### ISSUE TITLE
Style + Composition transfer is only available for SDXL models at the moment.

### ISSUE THREAD

**Issue by Yvelinmoon** [cubiq/ComfyUI_IPAdapter_plus#553]
![1](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/156613969/1828f5e4-d322-4504-bae1-581d4244be39)
![2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/156613969/ddf6db1c-33a5-4783-a801-965c4968f90b)
![3](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/156613969/049ad96c-fd5f-4c74-ae8f-3fabd2f43b29)

I've put all these models in the right place, but the ComfyUI can't find those sdxl models, which is necessary for style transfer...
Please help >_<

**Comment by shushengshu** [comment]
I have the same problem, how did you solve it, thank you

**Comment by soyh** [comment]
I also meet this,anyone can help?
