### ISSUE TITLE
Pinokio and ComyUI_IPAdapter_plus

### ISSUE THREAD

**Issue by Nawoh** [cubiq/ComfyUI_IPAdapter_plus#556]
I installed ComfyUI with Pinokio. 
I set in the extra_model_paths.yaml like in your README

```
comfyui:
     base_path: Users/ingopolster/pinokio/api/ComfyUI/app/
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/
     ipadapter: models/ipadapter/

```

and got in the terminal the message 
`Adding extra search path ipadapter Users/ingopolster/pinokio/api/ComfyUI/app/models/ipadapter/`

I still get this error message. 

```
Error occurred when executing IPAdapterUnifiedLoader:

IPAdapter model not found.

File "/Users/ingopolster/pinokio/api/ComfyUI/app/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/Users/ingopolster/pinokio/api/ComfyUI/app/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/Users/ingopolster/pinokio/api/ComfyUI/app/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/Users/ingopolster/pinokio/api/ComfyUI/app/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 468, in load_models
raise Exception("IPAdapter model not found.")
```

**Comment by cubiq** [comment]
I'm sure Pinokio's customer service can help you there

**Comment by Nawoh** [comment]
> I'm sure Pinokio's customer service can help you there
Hi cubiq, 
I tried to specify the problem a bit. Maybe you could take a look again at my first post. 
the folder Users/ingopolster/pinokio/api/ComfyUI/app/models/ipadapter/ is for sure right and all models present.

**Comment by Nawoh** [comment]
> I'm sure Pinokio's customer service can help you there

Now i installed ComfyUI without Pinokio again manually. Exactly the same Error with a clean install. Downloaded and copied all like in the README. 
Maybe its not working because im on a Mac. 

Would it maybe be possible to implement better Error Messages. I saw many people on multiple threads having issues like me and Nonne knows whats the problem.

**Comment by Laisvydas3030** [comment]
Same problem on windows

**Comment by Nawoh** [comment]
> Same problem on windows

I finally found this issue tonight wich identified the problem. 

[LINK](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/536)

The names of the linked models are simply wrong.
They are also wrong at the README page. 

As a test just rename the `ip-adapter_sd15.safetensors` to `ip.adapter.sdxl.vit.h.safetensors`
in the `models/ipadapter` folder. This is the STANDARD model in your IPAdapter UnifiedLoader.
So if you choose STANDARD now it should work without an error. 

Now we have to find out wich model corresponds with wich menu selection.
