### ISSUE TITLE
Witch node replace "IPAdapterApply" or "IPAdaptapply" with this update of IPAdapter_Advance?

### ISSUE THREAD

**Issue by softyoda** [cubiq/ComfyUI_IPAdapter_plus#559]
Hi, it seems there was an update that broke a lot of workflows? I never used IPAdapter but it is required for [this workflow](https://openart.ai/workflows/seven947/easy-8k-upsacle/YVBJsz3eSc8HUKQnXjvQ)
On a [reddit thread](https://www.reddit.com/r/comfyui/comments/1bqy774/question/), someone had the same issue without explaining the solution he found.

Thanks.

**Comment by cubiq** [comment]
ipadapter advanced is a drop in replacement for the old ipadapterapply.
