### ISSUE TITLE
can you also support safetensors? 

### ISSUE THREAD

**Issue by xiaohu2015** [cubiq/ComfyUI_IPAdapter_plus#56]
https://huggingface.co/h94/IP-Adapter/tree/main

**Comment by cubiq** [comment]
it should already support safetensors

**Comment by xiaohu2015** [comment]
> it should already support safetensors

you should add some code following https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/56#issuecomment-1790223960

**Comment by cubiq** [comment]
oh you mean they converted the models to safetensors. that is new :smile: I thought you meant the image encoders.

Damn it was added 2 hours ago and you guys are already on it :smile:

**Comment by xiaohu2015** [comment]
> oh you mean they converted the models to safetensors. that is new 😄 I thought you meant the image encoders.
> 
> Damn it was added 2 hours ago and you guys are already on it 😄

yes, I have converted the model to safetensors, but it need some codes. I hope you can also support that.

**Comment by cubiq** [comment]
I get incredibly weird results, I need to check better what is going on

![view](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/04a0c05f-2f7f-45b9-9af4-4e5080037841)

**Comment by xiaohu2015** [comment]
I use the following code to convert:
```python
from glob import glob

from safetensors.torch import save_file
import torch


if __name__ == "__main__":
    bin_files = glob("*.bin")


    for bin_file in bin_files:

        data = torch.load(bin_file, map_location="cpu")                                                                                                                       
        outputs = {}
        for k, v in data["ip_adapter"].items():
            outputs["ip_adapter." + k] = v 

        for k, v in data["image_proj"].items():
            outputs["image_proj." + k] = v 

        save_file(outputs, bin_file.replace(".bin", ".safetensors"))

```

**Comment by cubiq** [comment]
yes, it was just the order of the keys that was messing up. I did a very quick patch for the moment, I'll see if there's a better way to do it later, but .safetensors format is now supported. Thanks for the heads-up and for the great work on the IPAdapter!

**Comment by xiaohu2015** [comment]
> yes, it was just the order of the keys that was messing up. I did a very quick patch for the moment, I'll see if there's a better way to do it later, but .safetensors format is now supported. Thanks for the heads-up and for the great work on the IPAdapter!

I am not sure if safetensors support orderdict? If it can, I can upload new weight file

**Comment by cubiq** [comment]
> I am not sure if safetensors support orderdict? If it can, I can upload new weight file

that would be ideal

**Comment by xiaohu2015** [comment]
https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/IPAdapterPlus.py#L253 it seems that this line is not needed

**Comment by cubiq** [comment]
> https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/IPAdapterPlus.py#L253 it seems that this line is not needed
> 
> and I don't understand that why you need sort?

you are absolutely right :smile: it was a left over

**Comment by cubiq** [comment]
> 
> and I don't understand that why you need sort?

sorry I missed your question. It's how the weights are processed later, it's something that I wanted to change and this might be the right time. reordering them lets me keep the current code unchanged, but I'll do better, I promise :smile:
