### ISSUE TITLE
'Attn2Replace' object has no attribute 'set_new_condition'

### ISSUE THREAD

**Issue by mr-bob-chang** [cubiq/ComfyUI_IPAdapter_plus#561]
The following error message is displayed when the PuLid and IPAdapter are used together

Error occurred when executing IPAdapterTiled:

'Attn2Replace' object has no attribute 'set_new_condition'

File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 943, in apply_tiled
model, _ = ipadapter_execute(model, ipadapter_model, clip_vision, **ipa_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 393, in ipadapter_execute
set_model_patch_replace(model, patch_kwargs, ("input", id, index))
File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 146, in set_model_patch_replace
to["patches_replace"]["attn2"][key].set_new_condition(**patch_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error workflow.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/15345007/error.workflow.json)

**Comment by cubiq** [comment]
please read https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108

**Comment by setothegreat** [comment]
> please read #108

I've read and, to the best of my knowledge, implemented everything suggested in the topic but still get this error. It only occurs with SDXL models; 1.5 models function just fine.

**Comment by AhinoK** [comment]
> please read #108

Still got no clue to fix this! Please advise!

**Comment by yq-Liang** [comment]
> > please read #108
> 
> Still got no clue to fix this! Please advise!
Hello, I met 'Attn2Replace' object has no attribute 'set_new_condition' as same as you. After I update InstantID,ComfyUI_Plus,and ComfyUI，the json file goes well. Hope it helps!

**Comment by cubiq** [comment]
you have an old version of comfyUI installed. You need to upgrade
