### ISSUE TITLE
DualCFG support

### ISSUE THREAD

**Issue by claychinasky** [cubiq/ComfyUI_IPAdapter_plus#562]
using SamplerCustomAdvanced node with dualCFG or PerpNegGuider, returns this error:
```
Error occurred when executing SamplerCustomAdvanced:
tuple index out of range
```

bypassing IPAdapterFaceID node, error doesn't appear and generation works as expected. Not sure if this related to SamplerCustomAdvanced  or IPA nodes tho.

**Comment by glyfspace** [comment]
this is the same as the thread w/ cosxl since you have to use DualCFG with cosxl 
#446

**Comment by cubiq** [comment]
please check this https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/446#issuecomment-2156429387
