### ISSUE TITLE
Error when excuting Ksampler

### ISSUE THREAD

**Issue by Hanz-89** [cubiq/ComfyUI_IPAdapter_plus#564]
i updated my comfy and all of the extension are uptodate, but when i tried to run my workflow i got this error, i would be thankful for any suggestion to solve this issue. 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/59022738/6da70c40-a97e-45ff-85ae-00adf1ce87f0)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/59022738/d065a841-564a-4d89-b204-af7e29351fc9)

**Comment by cubiq** [comment]
you are using the wrong controlnet
