### ISSUE TITLE
Move the default IP Adapter nodes in their own submenu.

### ISSUE THREAD

**Issue by StellarBeing25** [cubiq/ComfyUI_IPAdapter_plus#566]
Can you move default IP Adapter nodes under their own basic or default submenu like all the other IP Adapter nodes? My problem is that whenever I come back to ComfyUI after not using it for a long time, my dumb brain always thinks that these nodes are the common nodes for all the types of IP adapters since they are not under any submenu, like the unified loader here would load all the IP Adapter models, including FaceID, only to realize later that the FaceID unified loader is under the FaceID submenu. Same with apply IP Adapter nodes.
![SC](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/152368658/b748da13-0ece-44c0-91da-6bdb4ebd5d62)

**Comment by cubiq** [comment]
those are the basic nodes, if you don't know how to use IPA, you can get started with those
