### ISSUE TITLE
Fooocus Image Prompt?

### ISSUE THREAD

**Issue by laksjdjf** [cubiq/ComfyUI_IPAdapter_plus#57]
Fooocus seems to make its own [improvements](https://github.com/lllyasviel/Fooocus/blob/main/fooocus_extras/ip_adapter.py). I have tried to implement them myself. I'm not quite sure what's different, but please consider it. Only the process inside the CrossAttentionPatch has changed.

https://github.com/laksjdjf/IPAdapter-ComfyUI/tree/fooocus_ip

**Comment by cubiq** [comment]
thanks for the heads up! I'll look into it.

Yesterday I've worked on the safetensors, wanted to tell you but I saw you already implemented it :smile: man, we should really merge :laughing:

**Comment by cubiq** [comment]
have you tested the focoous implementation? I can't get any decent result out of it

**Comment by xiaohu2015** [comment]
do you find if focoous method is better?

**Comment by cubiq** [comment]
> do you find if focoous method is better?

it's generally sharper and very good at high weight (over 1.0), but it's not always "better".

The weight that I call "linear" is very nice and gives a little more importance to the text embeds. If you see from the picture "linear" is closer to the image generated without IPAdapter

![difference](https://raw.githubusercontent.com/cubiq/ComfyUI_IPAdapter_plus/main/examples/weight_types.jpg)

**Comment by xiaohu2015** [comment]
> > do you find if focoous method is better?
> 
> it's generally sharper and very good at high weight (over 1.0), but it's not always "better".
> 
> The weight that I call "linear" is very nice and gives a little more importance to the text embeds. If you see from the picture "linear" is closer to the image generated without IPAdapter
> 
> ![difference](https://raw.githubusercontent.com/cubiq/ComfyUI_IPAdapter_plus/main/examples/weight_types.jpg)

you also use text prompt?

**Comment by cubiq** [comment]
> you also use text prompt in the examples?

yes text prompt is: "portrait illustration of a warrior woman in full armor in a dungeon, highly detailed, dramatic lighting, 4k"

**Comment by xiaohu2015** [comment]
> > you also use text prompt in the examples?
> 
> yes text prompt is: "portrait illustration of a warrior woman in full armor in a dungeon, highly detailed, dramatic lighting, 4k"

I think you can do some other comparison, for example, you can use some text to edit the hair color ("green hair"), or change the backgroud ("in a garden")

**Comment by cubiq** [comment]
With green hair in a garden, ipadapter plus, weight 0.65

linear | original | channel penalty
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/744d65dc-4747-4165-9916-a79c580de617)

**Comment by xiaohu2015** [comment]
> With green hair in a garden, ipadapter plus, weight 0.65
> 
> linear | original | channel penalty ![image](https://user-images.githubusercontent.com/427614/281650150-744d65dc-4747-4165-9916-a79c580de617.png)

linear is best?

**Comment by cubiq** [comment]
> linear is best?

well... depends, linear keeps IPAdapter down a little (even PLUS is less strong), it may or may not be what you want. But I find all three methods interesting. I'll keep testing

**Comment by xiaohu2015** [comment]
> > linear is best?
> 
> well... depends, linear keeps IPAdapter down a little (even PLUS is less strong), it may or may not be what you want. But I find all three methods interesting. I'll keep testing

I think Editability and consistency are often in conflict, so a compromise can only be made. However, if what you want to edit does not conflict too much with the input, there should be a way to get a good result.
