### ISSUE TITLE
Apply IPAdapter faceid removed ?

### ISSUE THREAD

**Issue by ritavkashyap123** [cubiq/ComfyUI_IPAdapter_plus#572]

**Comment by cubiq** [comment]
no

**Comment by cubiq** [comment]
please check the example workflows

**Comment by rachelcenter** [comment]
> please check the example workflows

i dont follow. i went to your example page https://github.com/cubiq/ComfyUI_IPAdapter_plus/tree/main/examples and do a command F search for the word apply and nothing came up

**Comment by cubiq** [comment]
check the faceid workflow

**Comment by rachelcenter** [comment]
> check the faceid workflow

I'm in that workflow and NONE of the boxes say  "apply ipadapter faceid" verbatim. they said "ipAdapter FaceID" and "IPAdapter Unified loader FaceID" but NONE OF THEM SAY  "apply ipadapter faceid" so  @ritavkashyap123 and i stand uncorrected. its not there any more

**Comment by cubiq** [comment]
just use the new node, the example shows you how

**Comment by rachelcenter** [comment]
ps I took Roblaughter's AnimateDiffUnsampling workflow and added InstantID and now every frame is a different image. is that normal? did i do something wrong in how i connected the nodes? or did i leave off a certain connection that is making the image change in every frame?
