### ISSUE TITLE
weird blue texture when using facewarp after make it to second processes

### ISSUE THREAD

**Issue by abuyazid955** [cubiq/ComfyUI_IPAdapter_plus#574]
after following your tutorial on youtube, changing the facewarp into second process, after passing "face bounding box" nodes, i encountered a problem like the image below

*Using SD 1.5 (512x768)
*Using insightface

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/07ddcc7d-0c51-437f-991e-d7c492d3f883)

please let me know if you need any details, thank you!

**Comment by cubiq** [comment]
would need to see the whole workflow and the reference images

**Comment by abuyazid955** [comment]
So i try to add 2x upscale (1024x1536) nodes after generating the images. it's slight reduced the blue texture, but it's still visible, but not as much as using 512x768. 

also i tried to change the faceanalysismodel to dlib, but there is no option for it. i've already installed it and put the models on the dlib folder.

here is my workflow 
[workflow.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/15445978/workflow.json)

reference images
![9905c6bf384cdc1ed38da69f3232761d](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/5a2d2fd1-2396-427a-8a66-3d49f8f2a0ee)
![82b108f2e53caeb136e5da0a24a07a18](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/71344185-a3bd-4d1a-b0aa-a1a219144fcd)

Thank you for your response!

**Comment by cubiq** [comment]
works without issues using standard nodes. I guess it's an issue with the efficiency nodes

![ComfyUI_temp_ziyzg_00005_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/09b72c5d-db1b-4a4c-9171-24b2a5152e01)

**Comment by abuyazid955** [comment]
I've checked my workflow that you have fixed above, but i don't see the facewarp nodes. I think you missed the point here. the weird blue texture will appears after applying the facewarp then goes through the face bounding box. you can see the blue texture appears again in the output preview image from the face bounding box
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113452309/0db45d21-3a83-46fe-b8d2-2e532424a864)

**Comment by abuyazid955** [comment]
also, is there any way to fix the face analysis model, there is no option for dlib on it. I've already downloaded the dlib models and put it in the folder.

**Comment by cubiq** [comment]
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/89255113-a77e-4967-8913-a1827ec0eccb)

I still can't replicate

**Comment by cubiq** [comment]
btw, this is an issue with face analysis not IPAdapter. post the most basic workflow without extensions that generates the issue on the face analysis repository if you want me to keep looking into this

**Comment by abuyazid955** [comment]
Thank you for your response, I will proceed this issue to your face analysis repository.
