### ISSUE TITLE
IPAdapter Encoder

### ISSUE THREAD

**Issue by linuxreitt** [cubiq/ComfyUI_IPAdapter_plus#577]
What can I replace the red Apply with, when I try with any other nodes that have pos/neg embeds I get an error regarding Image 1 not being a value.
![ip](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/124739751/b25e4516-289f-455b-9e63-c6820b46f4d8)

**Comment by cubiq** [comment]
`ipadapter embeds'

**Comment by linuxreitt** [comment]
Hi, thank you for your reply, I appreciate it. I did previously try this but I still have the error message about image 1. I'm sure there is something simple I am missing.
![error](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/124739751/3e8d97e2-a924-404b-beae-bb6e268a1d07)
