### ISSUE TITLE
IPAdapter is not working when included in the workflow. It is giving me the following error. I have updated everything in ComfyUI

### ISSUE THREAD

**Issue by Manish-cel** [cubiq/ComfyUI_IPAdapter_plus#582]
`RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: struct c10::Half key.dtype: float and value.dtype: float instead.`

**Comment by lopez-** [comment]
Same issue here

**Comment by lopez-** [comment]
> Same issue here

Actually, from https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/108 I found that you can just add `--force-fp16` and now it's working for me.
