### ISSUE TITLE
[Question] Working with multiple IP-Adapters

### ISSUE THREAD

**Issue by whlp-synth** [cubiq/ComfyUI_IPAdapter_plus#59]
Hi, 

I am working on a workflow in which I wanted to have two different ip-adapters: `ip-adapter-plus_sd15.bin` for images of clothes and `ip-adapter-plus-face_sd15.bin` for the face of a character. How would you recommend setting the workflow in this case? 

Should I use two different `Apply Adapter` nodes (one for each model and set of images) and then connect them in cascade (in this case, would it be okay to use the weights and noise the same way as a single node?)? Or is there a better way?

Btw, thanks for the great custom nodes that you created!

**Comment by cubiq** [comment]
I would do this:

![daisychain](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/54e1a3e0-2674-4f17-ae26-2b672268a516)

Not sure if the order matters, give it a try

**Comment by whlp-synth** [comment]
Thanks! I will try it!
