### ISSUE TITLE
Help!!: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by okwunnaanyaoku** [cubiq/ComfyUI_IPAdapter_plus#591]
![Screenshot 2024-06-06 030716](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/83955448/f79c6064-44c9-4345-b274-cfb12a9fc10b)
![Screenshot 2024-06-06 030828](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/83955448/9859c7ec-a550-4408-a97e-27494db850ec)
![Screenshot 2024-06-06 030840](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/83955448/a9160093-5c14-4c02-82d3-b0729ca3543f)
I'm getting this issue when trying to run this workflow please any help will be appreciated!

**Comment by okwunnaanyaoku** [comment]
i think the issue is with this ipadapter_plus-face_sdxl_vit-h.safetensor file even if i use IPadapter model loader i get a similar error

**Comment by cubiq** [comment]
try to re-download the model

**Comment by okwunnaanyaoku** [comment]
this worked thanks

**Comment by okwunnaanyaoku** [comment]
redownloading the model worked
