### ISSUE TITLE
IPADAPTER MODEL NOT FOUND!

### ISSUE THREAD

**Issue by mujahidanshary** [cubiq/ComfyUI_IPAdapter_plus#594]
Is there anyone who wants to help me, even though I have placed all the files in the correct folder?
![Screenshot 2024-06-10 232310](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/47288108/2e641f89-113e-414a-9550-1333e2a0f1cd)
![Screenshot 2024-06-10 232412](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/47288108/bdb71ba8-e3f8-49d9-9355-d7db777d7a54)

**Comment by cubiq** [comment]
duplicate https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/586
