### ISSUE TITLE
(IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus

### ISSUE THREAD

**Issue by jyju972** [cubiq/ComfyUI_IPAdapter_plus#596]
![image_2024-06-11_233938232](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/169610368/b3665da7-1ff7-4030-bb5e-19d913db008d)
![image_2024-06-12_124935863](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/169610368/f182a9f4-88a3-4e00-84b0-55aa82cafd69)

**Comment by jyju972** [comment]
Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus module for custom nodes: No module named 'node_helpers'

**Comment by cubiq** [comment]
you may need to update comfyui

**Comment by huang5656151** [comment]
If I dont want update comfyui, what I should do to fix it ?
