### ISSUE TITLE
Probably the worst description and install guide I ever see

### ISSUE THREAD

**Issue by TheOldRustyCrown** [cubiq/ComfyUI_IPAdapter_plus#605]
Also one of the worst install method for comifyui too (you need to download model, but need to rename okay, rename for a which name? Also there is need lora and rename and go rename yourself, and that's not all, you also need... uuughhh...... I'am outta here..)

Next time : "Before installing plugin - rename your username, after that you should rename the folder, then rename downloaded files, and rename all of it again, rename you name my mind in flame ;)

**Comment by cubiq** [comment]
such is life

**Comment by TheOldRustyCrown** [comment]
Arrrrr!!!! Aaaaarrrr!!! }:->
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/13091768/da3796c6-6be0-4f9a-8872-0b683bf8c073)
Simply just write into description that all you need is just these nodes and no rename (in the main section) Iam sure there is many dump guys like me
