### ISSUE TITLE
Prompt outputs failed validation IPAdapter:     - Required input is missing: ipadapter

### ISSUE THREAD

**Issue by robitronathon** [cubiq/ComfyUI_IPAdapter_plus#606]
When I try to use this node, i always get the error Prompt outputs failed validation IPAdapter: - Required input is missing: ipadapter
however there is no way to input an ipadapter anywhere that i can see.

**Comment by cubiq** [comment]
in what workflow? have you tried the examples?

**Comment by blurymind** [comment]
I get the same error in this workflow
https://github.com/nerdyrodent/AVeryComfyNerd/blob/main/workflows/SDXL/SDXL_Instant_LoRA_3.png
