### ISSUE TITLE
Input conditioning?

### ISSUE THREAD

**Issue by papersplease** [cubiq/ComfyUI_IPAdapter_plus#61]
Right now, the result often ends up being contaminated by unwanted features of the reference image(s). Say, I have a reference picture of a lizard, but it also picks up foliage, a nearby tree trunk, and an occasional rock. Hunting for the ideal crop doesn't do much, you'll inevitably have unwanted features in the frame.

Is it possible to condition the feature extraction step on a text prompt, so it will only extract the concept you need? Ideally, it should look like prompting a "lizard", a "hat", or "freckles", so it would only pass these concepts further down the pipeline.

Also, it seems to have the negative image input; can it be exposed for the user to filter unwanted concepts out?

**Comment by cubiq** [comment]
I think most of your questions are answered in the here #60

**Comment by papersplease** [comment]
So if I understand this correctly, the answer is the model has to be modified and retrained to do that?

**Comment by cubiq** [comment]
the best way to do what you are asking is to use a "light" model and put all the unwanted elements in the negative prompt... or better edit the image so it contains only what you need... or yeah train your own IPAdapter model to respond to only what you want.
