### ISSUE TITLE
Red Distortion

### ISSUE THREAD

**Issue by MrSpaceCosmos** [cubiq/ComfyUI_IPAdapter_plus#612]
Images coming out with red distortions/pixelation, when the image is being created and loading, it looks perfect but when it's finally loaded, there's this weird distortion on it. Using IP Adapter Face ID Plus as processor and it's counter part for Model. Using Realistic Vision 6 as Checkpoint. My device specifications are - i9 12th Gen with RTX 4060. My Prompt - realistic, 1girl, solo, human, bust, breasts, long hair, brown hair, brown eyes, portrait, looking at viewer, black dress, standing, outdoors, <lora:ip-adapter-faceid-plus_sd15_lora:0.1> Negative Prompt - (nsfw, naked, nude, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation, distortion
![00003-1461653437](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/56875283/e4532581-09df-4dbd-8dc3-dcad295b7ff0)
![00004-1461653437](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/56875283/d201f5ec-177c-43ea-a7c9-ffa11bb92bda)
![00000-1461653437](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/56875283/5147a156-a0e2-452f-8ba9-10923b7fd478)
![00001-1461653437](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/56875283/3b294b16-8309-4b7e-b297-08706e9dc673)
![00002-1461653437](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/56875283/d667abf9-5b10-41fe-abbd-14c434b71682)

**Comment by cubiq** [comment]
please check the example directory. you are applying the faceid lora without the ipadapter node.
