### ISSUE TITLE
I made a slider node for  "IPAdapter Mad Scientist"

### ISSUE THREAD

**Issue by chflame163** [cubiq/ComfyUI_IPAdapter_plus#613]
Hi Cubiq, The ```IPAdapter Mad Scientist``` is simply amazing, but input parameters are quite cumbersome.  So I made a [slider node](https://github.com/chflame163/ComfyUI_IPAdapter_plus_V2) for more convenient and intuitive input of numerical values.  If you like, you can merge it into your warehouse.  Thank you for your great work.

**Comment by cubiq** [comment]
thanks, I'm working on a more complex node where you can set the image for each layer
