### ISSUE TITLE
Error occurred when executing IPAdapterAdvanced:  Provided interpolation parameters can not be handled with current algorithm implementation. Please reduce the scale factor. Too much shared memory required: 57460 vs 49152

### ISSUE THREAD

**Issue by mehbayat** [cubiq/ComfyUI_IPAdapter_plus#616]
Error occurred when executing IPAdapterAdvanced:

Provided interpolation parameters can not be handled with current algorithm implementation. Please reduce the scale factor. Too much shared memory required: 57460 vs 49152

**Comment by cubiq** [comment]
is this on a mac?

**Comment by mehbayat** [comment]
no

**Comment by mehbayat** [comment]
It required the 'prep image for clip vision' node prior to input into the ipadapter image parameter. It has been resolved.
