### ISSUE TITLE
Insightface "no faces detected"

### ISSUE THREAD

**Issue by MaraScott** [cubiq/ComfyUI_IPAdapter_plus#620]
Hi,

I'm testing some face consistency generation and it works fine but sometimes I have an issue like the one below with a face like the one attached and if I provide the face as 512 or 1024 square it is the same issue

Issue:

![Screenshot_4-7-2024_16741_local marascott ai](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/482210/32294a76-2f70-4018-82dd-897e36fe800c)

portrait which trigger an issue :

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/482210/8d4aaef6-5ce1-459f-a099-70aca34df3ff)

portrait that do not trigger issue :

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/482210/2830340b-9315-444f-9d2a-5feb710561c3)

What am I doing wrong ?

**Comment by lord-lethris** [comment]
FTR - I'm also having this issue - It seems Insightface has lost the ability to detect Anime/manga/toon faces.  This is even after I have used SEGS to detect the Toon face, and force face only content into IPAdapter.

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/1736720/c253ec4a-7526-452b-9e20-74a83c563c55)

**Comment by cubiq** [comment]
the models are not trained for cartoons or strongly stylized characters

**Comment by MaraScott** [comment]
Aouch, okay make sense.
I would love to follow up on that if I can help but I never trained anything.
If you have insight for me to learn and then help to fix I'm all in

**Comment by lord-lethris** [comment]
> the models are not trained for cartoons or strongly stylized characters

But it use to though - that's how I was able to create this workflow...

https://openart.ai/workflows/lord_lethris/random-character-concept-creator-with-image-consistency-examples-v16/8lkARBtEyg4dE9hYY2CD

**Comment by cubiq** [comment]
realistic style works, if it's too stylized it won't work
