### ISSUE TITLE
Error(s) in loading state_dict for ImageProjModel: size mismatch for proj.weight: copying a param with shape torch.Size([3072, 1280]) from checkpoint, the shape in current model is torch.Size([3072, 768]).

### ISSUE THREAD

**Issue by xixi-97-byte** [cubiq/ComfyUI_IPAdapter_plus#621]
hello,cubiq,when I run the ipadapter,something wrong happened,If it is possible,could you please give me some help. Forward your response.
Error occurred when executing IPAdapterAdvanced:

Error(s) in loading state_dict for ImageProjModel:
size mismatch for proj.weight: copying a param with shape torch.Size([3072, 1280]) from checkpoint, the shape in current model is torch.Size([3072, 768]).

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 769, in apply_ipadapter
work_model, face_image = ipadapter_execute(work_model, ipadapter_model, clip_vision, **ipa_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 396, in ipadapter_execute
ipa = IPAdapter(
^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 70, in __init__
self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
File "D:\ComfyUI_windows_portable\ComfyUI\.ext\Lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by cubiq** [comment]
you are probably using the wrong combination of models, possibly a wrong controlnet (like an sdxl controlnet with an sd1.5 checkpoint or vice versa). Or something like that

**Comment by xixi-97-byte** [comment]
I do not know maybe the ipadapter is embeded any models in itself,or I can choose the model by myself?

**Comment by cubiq** [comment]
can I see the workflow?

**Comment by xixi-97-byte** [comment]
of course.and thank you so much.
[个人建立.json](https://github.com/user-attachments/files/16107505/default.json)

**Comment by cubiq** [comment]
I don't get any error, be sure your file are not corrupted. Sometimes they get corrupted when downloading them

**Comment by xixi-97-byte** [comment]
so sad,or maybe could you please tell me how to set up, such as the correspondence between the ipadapter model and the clipvision model?
Hope I will not disturb you so much.

**Comment by DucNM-media** [comment]
@xixi-97-byte Have you fixed the error yet? I'm also experiencing the same issue :((

**Comment by 520xielaoban** [comment]
我也是，报错
RuntimeError: Error(s) in loading state_dict for ImageProjModel:
        size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([8192, 768]).

**Comment by 520xielaoban** [comment]
需要注意，其中名字带有 sd15 适用于 sd15 大模型，带有 sdxl 的适用于 sdxl 大模型；

其中名字带有 vit-h 的使用 ViT-H 视觉编码器，名字带有 vit-G 的使用 ViT-G 视觉编码器；

SDXL 大模型默认使用 ViT-G，SD15 大模型默认使用 ViT-H。
————————————————
clip视频编码器

**Comment by Kevinchen985** [comment]
@xixi-97-byte 
CLIP-ViT-H-14-laion2B-s32B-b79K  / CLIP-ViT-bigG-14-laion2B-39B-b160k
这两个文件你可能命名反了，检查一下

**Comment by xixi-97-byte** [comment]
> @xixi-97-byte Have you fixed the error yet? I'm also experiencing the same issue :((

not yet

**Comment by LAWSON666888** [comment]
我也遇到了同样的问题，模型和编码器在一一对应的情况下，还是报错“ File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).”  不知道怎么回事···

**Comment by Sdreamtale** [comment]
I found the problem. The IPA model and the Clip vision model were mismatched. Here, they need to be aligned correctly.
![Uploading 微信截图_20250107154759.jpg…]()

**Comment by Sdreamtale** [comment]
I found the problem. The IPA model and the Clip vision model were mismatched. Here, they need to be aligned correctly.
![20250107154759](https://github.com/user-attachments/assets/c7311414-2295-4d42-a20b-cd23a5eca5ee)

**Comment by DBay81** [comment]
> 我找到了问题所在。IPA 模型和 Clip 视觉模型不匹配。这里需要正确对齐它们。 ![20250107154759](https://github.com/user-attachments/assets/c7311414-2295-4d42-a20b-cd23a5eca5ee)

具体怎么操作？怎么对齐他们？
