### ISSUE TITLE
'CrossAttentionPatch' object has no attribute 'add'

### ISSUE THREAD

**Issue by NeilWang079** [cubiq/ComfyUI_IPAdapter_plus#625]
When I use ipadapter and instantid in parallel I get the error AttributeError: 'CrossAttentionPatch' object has no attribute 'add', while using the two nodes separately works fine!

got prompt
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! 'CrossAttentionPatch' object has no attribute 'add'
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\comfyui\comfyui\custom_nodes\PuLID_ComfyUI\pulid.py", line 437, in apply_pulid
    set_model_patch_replace(work_model, patch_kwargs, ("input", id, index))
  File "E:\comfyui\comfyui\custom_nodes\PuLID_ComfyUI\pulid.py", line 92, in set_model_patch_replace
    to["patches_replace"]["attn2"][key].add(pulid_attention, **patch_kwargs)
AttributeError: 'CrossAttentionPatch' object has no attribute 'add'

Prompt executed in 3.38 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\comfyui\comfyui\models\insightface\models\antelopev2\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\comfyui\comfyui\models\insightface\models\antelopev2\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\comfyui\comfyui\models\insightface\models\antelopev2\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\comfyui\comfyui\models\insightface\models\antelopev2\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\comfyui\comfyui\models\insightface\models\antelopev2\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
!!! Exception during processing!!! 'CrossAttentionPatch' object has no attribute 'add'
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\comfyui\comfyui\custom_nodes\ComfyUI_InstantID\InstantID.py", line 353, in apply_instantid
    _set_model_patch_replace(work_model, patch_kwargs, ("input", id, index))
  File "E:\comfyui\comfyui\custom_nodes\ComfyUI_InstantID\InstantID.py", line 136, in _set_model_patch_replace
    to["patches_replace"]["attn2"][key].add(instantid_attention, **patch_kwargs)
AttributeError: 'CrossAttentionPatch' object has no attribute 'add'
![Uploading 屏幕截图 2024-07-08 194703.png…]()

**Comment by NeilWang079** [comment]
![屏幕截图 2024-07-08 194703](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/42379975/16525827-6b8d-429a-b3d5-5908af73d299)

**Comment by cubiq** [comment]
you need to update both extensions
