### ISSUE TITLE
IPAdapter Unified Loader throw KeyError: 'clipvision' and my solution

### ISSUE THREAD

**Issue by wakacuka** [cubiq/ComfyUI_IPAdapter_plus#627]
bottom has the code.

Hi, recently I installed IPAdapter_plus again.
It worked well in someday before, but not yesterday.

I could not find solution.
so, I add some code in IPAdapterPlus.py file
it worked with no errors.
I'm not used to github so I post here.
someone fix it better than my code.

## MESSAGE ##
Using pytorch attention in VAE
!!! Exception during processing!!! 'clipvision'
Traceback (most recent call last):
  File "/home/waka/Workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/waka/Workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/waka/Workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/waka/Workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 514, in load_models
    if clipvision_file != pipeline['clipvision']['file']:
KeyError: 'clipvision'

Prompt executed in 15.46 seconds

## CODE ##

```
# 1. Load the clipvision model
        clipvision_file = get_clipvision_file(preset)
        if clipvision_file is None:
            raise Exception("ClipVision model not found.")
        if clipvision_file != self.clipvision['file']:
            if 'clipvision' in pipeline.keys() and 'file' in pipeline['clipvision'] and clipvision_file != pipeline['clipvision']['file']:
                self.clipvision['file'] = clipvision_file
                self.clipvision['model'] = load_clip_vision(clipvision_file)
                print(f"\033[33mINFO: Clip Vision model loaded from {clipvision_file}\033[0m")
            elif 'clipvision' not in pipeline.keys() or 'file' not in pipeline['clipvision']:
                self.clipvision['file'] = clipvision_file
                self.clipvision['model'] = load_clip_vision(clipvision_file)
                print(f"\033[33mINFO: Clip Vision model loaded from {clipvision_file}\033[0m")
            else:
                self.clipvision = pipeline['clipvision']
        # 2. Load the ipadapter model
        is_sdxl = isinstance(model.model, (comfy.model_base.SDXL, comfy.model_base.SDXLRefiner, comfy.model_base.SDXL_instructpix2pix))
        ipadapter_file, is_insightface, lora_pattern = get_ipadapter_file(preset, is_sdxl)
        if ipadapter_file is None:
            raise Exception("IPAdapter model not found.")

        if ipadapter_file != self.ipadapter['file']:
            if 'ipadapter' in pipeline.keys() and 'file' in pipeline['ipadapter'].keys() and pipeline['ipadapter']['file'] != ipadapter_file:
                self.ipadapter['file'] = ipadapter_file
                self.ipadapter['model'] = ipadapter_model_loader(ipadapter_file)
                print(f"\033[33mINFO: IPAdapter model loaded from {ipadapter_file}\033[0m")
            elif 'ipadapter' not in ipadapter.keys() or 'file' not in ipadapter['ipadapter']:
                self.ipadapter['file'] = ipadapter_file
                self.ipadapter['model'] = ipadapter_model_loader(ipadapter_file)
                print(f"\033[33mINFO: IPAdapter model loaded from {ipadapter_file}\033[0m")
            else:
                self.ipadapter = pipeline['ipadapter']

        # 3. Load the lora model if needed```

**Comment by cogelito** [comment]
Thank you for the suggestion. Part one worked for me – clipvision isn't the problem anymore.
But now ComfyUI is struggling with finding the IPAdapter model. Either with the original code nor with your optimized code.

**Comment by jacobg-jellyfish** [comment]
can confirm @cogelito 's findings.

**Comment by cubiq** [comment]
I would like to see a workflow that generates this error. the reason for the OP error might be a misuse of the loaders

**Comment by jacobg-jellyfish** [comment]
[clipvision-error.json](https://github.com/user-attachments/files/16261309/clipvision-error.json)

You'll find this workflow suffers from the same error.

**Comment by jacobg-jellyfish** [comment]
![Screenshot 2024-07-17 at 07 48 58](https://github.com/user-attachments/assets/2ede87a9-67aa-4ab7-accd-56665ae09fe5)

and here is a screenshot of the offending nodes

**Comment by cubiq** [comment]
This is incorrect. The ipadapter input in the unified loader is used exclusively to daisy chain unified loaders. Please check the examples.

![image](https://github.com/user-attachments/assets/8dfb4a83-c43a-4733-aee8-90e624a4242f)

**Comment by jacobg-jellyfish** [comment]
thanks for your help @cubiq - will give that a try

**Comment by cubiq** [comment]
I will work on better error reporting sooner or later, thanks for pointing that out. I'm closing this for now

**Comment by DucNM-media** [comment]
@cogelito "Could I ask you rename the two clip_vision models to what?"
