### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'patcher'

### ISSUE THREAD

**Issue by easeclick** [cubiq/ComfyUI_IPAdapter_plus#63]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\a\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ComfyUI\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
    cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ComfyUI\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 229, in clip_vision_encode
    comfy.model_management.load_model_gpu(clip_vision.patcher)
                                          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'patcher'

**Comment by cubiq** [comment]
upgrade comfyui and the extension

**Comment by 2shou** [comment]
Still errors after upgrade

**Comment by Arethkiotis** [comment]
Any fixes for this having the same, also tried updating both comfyui and extension but still getting same

**Comment by Tapyon** [comment]
YES !!!! 
YOU NEED TO CHANGE THE NODE, FOR ONE THAT HAS THE CLIP VISION, AND ADD "CLIP_VISION_H.SAFETENSOR"
at least that was my issue on : AttributeError: 'NoneType' object has no attribute 'patcher'

![Image](https://github.com/user-attachments/assets/a45e60ff-bb23-42d3-93be-4da9e5c251ff)
