### ISSUE TITLE
Error occurred when executing IPAdapterFaceID:  IPAdapterAdvanced.apply_ipadapter() missing 1 required positional argument: 'model'

### ISSUE THREAD

**Issue by mikelee6010** [cubiq/ComfyUI_IPAdapter_plus#631]
Error occurred when executing IPAdapterFaceID:

IPAdapterAdvanced.apply_ipadapter() missing 1 required positional argument: 'model'

File "F:\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))

**Comment by Jesssssss123** [comment]
I had the same error.I think you forget to download models.
Click on the link:https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#installation

**Comment by cubiq** [comment]
please check the example workflows
