### ISSUE TITLE
[FEATURE REQUEST] Support for Kolors IP-Adapter

### ISSUE THREAD

**Issue by syddharth** [cubiq/ComfyUI_IPAdapter_plus#639]
They recently released IP-Adapters for the Kolors model here [https://huggingface.co/Kwai-Kolors/Kolors-IP-Adapter-Plus](https://huggingface.co/Kwai-Kolors/Kolors-IP-Adapter-Plus). 
Support would be awesome.

**Comment by cubiq** [comment]
this is done
