### ISSUE TITLE
Can you please tell me, with the recent update, has there been a change to the nosie implementation?

### ISSUE THREAD

**Issue by suede299** [cubiq/ComfyUI_IPAdapter_plus#64]
Since the release of the sdxl face model, I've noticed that the impact of the noise value seems to have changed, and that the noise value has more of an impact on the overall composition when using the face model when multiple images are entered, I'm not sure if this is a feature of the face model, or if there has been a recent change to the nosie functionality.

**Comment by cubiq** [comment]
no, I haven't touched the noise feature sine a long time. As far as I understand the SDXL face model is still in a beta stage though

**Comment by suede299** [comment]
Thanks for the explanation.
