### ISSUE TITLE
Is  a bug of IPAdapter Unified Loader with load Kolors models?

### ISSUE THREAD

**Issue by chflame163** [cubiq/ComfyUI_IPAdapter_plus#644]
There is a significant difference in the results achieved when I use ```IPAdapter Unified Loader``` and nodes that load models separately.
![workflow (7)](https://github.com/user-attachments/assets/6b2489a1-8232-4a86-bc32-d24e85e56873)
(Image contains workflow)

**Comment by cubiq** [comment]
kolors is in the "community unified loader"

**Comment by chflame163** [comment]
> kolors is in the "community unified loader"

Thanks, I switched to the ```IPAdatper Unified Loader Community```  and now it works normally.
