### ISSUE TITLE
Switch any cannot connect to ipadpter of the same type

### ISSUE THREAD

**Issue by LPG-VERSION** [cubiq/ComfyUI_IPAdapter_plus#652]
![image](https://github.com/user-attachments/assets/f338e45a-46b8-4d35-a1de-bbb2262fd61d)
Switch any cannot connect to ipadpter of the same type :“combine_embeds,weight_type,embeds_scaling",This is a disaster for people who want to customize components.

**Comment by LPG-VERSION** [comment]
Can you also provide some necessary ipadpter components for custom components? I found that the comfyui primitive node performs poorly on some ipadpter parameters when customizing components

**Comment by cubiq** [comment]
that's how comfy works, I don't think there's anything I can do about it

**Comment by LPG-VERSION** [comment]
> that's how comfy works, I don't think there's anything I can do about it

ok, I will try to write a custom node to solve this problem. Thank you for developing this excellent plugin

**Comment by LPG-VERSION** [comment]
以下是我解决这个问题的过程：(The following is the process of how I solved this problem:)

问题描述：我发现 ComfyUI 中的 "Any Switch" 节点无法提取某些相同类型的输入，这阻碍了我创建自定义组件
(Problem Description: I have discovered that the "Any Switch" node in ComfyUI is unable to extract certain inputs of the same type, which hinders me from creating custom components.)
﻿
1. 解决方案：通过实验，我发现：ComfyUI 中的 weight_type 本质上是一个字符串。ComfyUI_Comfyroll_CustomNodes 插件中的 "CR String To Combo" 节点展示了一种将特定数据类型转换为通用数据类型的机制。(1.Solution: Through experimentation, I found that: The weight_type in ComfyUI is essentially a string. The "CR String To Combo" node in the ComfyUI_Comfyroll_CustomNodes plugin demonstrates a mechanism for converting specific data types into a universal data type.)
﻿
![image](https://github.com/user-attachments/assets/9a2106bb-18b5-413d-a9d9-1bab6ebe0e2a)
![image](https://github.com/user-attachments/assets/60049897-3d18-4b70-9060-8dfd42ad18a4)

2. 类比分析：可以这样类比：如果将 weight_type 比作“苹果”，我们可以用更广泛的类别“水果”或“食物”来表示它。类似地，其他数据类型，如“字符串”，也可以归类为“水果”或“食物”。这使得我们可以将 weight_type（苹果）和“字符串”视为属于同一类别（“水果/食物”），尽管它们的包装（输入/输出类型）不同。请注意，前提是数据类型本质上相同, 输入/输出包装不同。(2.Analogical Analysis: Here's an analogy: If weight_type is an "apple," we can represent it using broader categories like "fruit" or "food." Similarly, other data types like "string" can also be categorized under "fruit" or "food." This allows us to consider weight_type (apple) and "string" as belonging to the same category ("fruit/food"), despite their different packaging (input/output types). Note that this is premised on the fact that the data types are same, with different input/output packaging.)
﻿
3. 重写类型检查：通过分析 ComfyUI 的工作机制和代码，我意识到可以重写 Python 的类型检查机制，以实现将输出转换为任何数据类型。这种方法类似于 "CR String To Combo" 节点的工作原理。(3.Rewriting Type Checking: By analyzing the working mechanism and code of ComfyUI, I realized that I could rewrite the Python type checking mechanism to achieve converting outputs to any data type. This approach is similar to the working principle of the "CR String To Combo" node.)
```
class AnyType(str):
    def __ne__(self, __value: object) -> bool:
        return False
any_type = AnyType("*")
```
4. 数据类型等效性：combine_embeds，embeds_scaling 和 weight_type 是同样的数据类型。(4.Equivalence of Data Types: combine_embeds, embeds_scaling, and weight_type are all of the same data type.)
﻿
5. 自定义节点设计：
基于这些发现，我设计了一个自定义节点：该节点具有三个输出，均为 any_type 类型，旨在提供上面三个输入各自的统一提取，从而方便自定义组件的创建。该方法可以延展到任何输入无法统一提取的场景。(5.Custom Node Design: Based on these findings, I have designed a custom node: This node has three outputs, all of the any_type type, aiming to provide unified extraction for each of the three inputs mentioned above, thus facilitating the creation of custom components. This method can be extended to any scenario where inputs cannot be uniformly extracted.)

![image](https://github.com/user-attachments/assets/990c32f2-0664-44bd-8299-e17c7c9a0147)
![image](https://github.com/user-attachments/assets/23c53d47-ac84-4f58-bea9-98fb76af655e)
![image](https://github.com/user-attachments/assets/74957830-fa21-488e-9c62-ddf0b87f1605)

6. 自定义节点代码：(6.Custom Node Code:)
![image](https://github.com/user-attachments/assets/5516b641-40ac-4318-be0a-ade26801ee41)
![image](https://github.com/user-attachments/assets/2e599209-52de-4aa2-9089-96f4f307e971)
![image](https://github.com/user-attachments/assets/550d803c-f8d7-4c03-984a-2f2c95d44263)
![image](https://github.com/user-attachments/assets/16126779-f200-44ad-8917-cacce7aeb14e)

8. 结论：通过提供通用的 any_type 输出，有效地统一了不同数据类型的“包装”，解决了输入类型限制问题，使其能够在 ComfyUI 工作流程中集成(7.Conclusion: By providing universal any_type outputs, different data types' "packaging" has been effectively unified, resolving input type restrictions and enabling their integration into the ComfyUI workflow.)
![image](https://github.com/user-attachments/assets/87c0d3f0-6c4e-4c72-bfe6-c2ebb9b87314)

希望这个可以帮助需要的人
Hope this can help those who need it
