### ISSUE TITLE
Issue with simple IPAdapter_plus workflow

### ISSUE THREAD

**Issue by ALBIHANY** [cubiq/ComfyUI_IPAdapter_plus#656]
Hi,

I'm new to IPAdapter_plus, I'm pretty sure i installed all the required models and clip visions, i started with sample workflow and i got this error message, any idea why i'm seeing this error message?

![image](https://github.com/user-attachments/assets/7c8dd345-3456-48be-8f35-1b97d78014dd)

**Comment by ALBIHANY** [comment]
and i also came across this other issue with the other workflow:
![image](https://github.com/user-attachments/assets/ba3b11fe-8064-49a1-a930-8b9fbf4643cd)

i looked it up on Ridit and it seems that almost everyone is having suffering from the same thing: 

https://www.reddit.com/r/comfyui/comments/1br0mod/clipvision_ipadapter_error_does_anybody_know_the/

i'm also 100% confident that i followed the exact naming convention as advice :

![image](https://github.com/user-attachments/assets/c839be60-b888-40c0-a24d-c4e43c20e9af)

I'm really frustrated it's been almost 2 months trying to make a single IPAdapter_plus workflow to actually work and after downloading all required models' checkpoints, clip visions and Loras never succussed, it's really disappointing

**Comment by KhoaVan0904** [comment]
https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#installation
I fixed a similar issue like yours this way. Follow the instructions! I hope you can fix it just like I did.
