### ISSUE TITLE
ipadater_plus与faceid中的各种问题，求大佬出个完整的教程。

### ISSUE THREAD

**Issue by laochendeai** [cubiq/ComfyUI_IPAdapter_plus#663]
我安装的IPADATER节点是cubiq的，这个里面提示的是69个冲突。不理解为什么我在comfyui中加载的节点都是bizyair的。

![error1](https://github.com/user-attachments/assets/37c746d7-b1bf-4935-9965-21b37948eaf7)
我尝试了各种解决办法。
这个faceid总是会各种各样的报错。这太让人痛苦了。

【ComfyUI_IPAdapter_plus】Conflicted Nodes (69)
IPAAdapterFaceIDBatch [ComfyUI-Kolors-MZ]
IPAAdapterFaceIDBatch [BizyAir]
IPAdapter [ComfyUI-Kolors-MZ]
IPAdapter [BizyAir]
IPAdapterAdvanced [ComfyUI-Kolors-MZ]
IPAdapterAdvanced [BizyAir]
IPAdapterBatch [ComfyUI-Kolors-MZ]
IPAdapterBatch [BizyAir]
IPAdapterCombineEmbeds [ComfyUI-Kolors-MZ]
IPAdapterCombineEmbeds [BizyAir]
IPAdapterCombineParams [ComfyUI-Kolors-MZ]
IPAdapterCombineParams [BizyAir]
IPAdapterCombineWeights [ComfyUI-Kolors-MZ]
IPAdapterCombineWeights [BizyAir]
IPAdapterEmbeds [ComfyUI-Kolors-MZ]
IPAdapterEmbeds [BizyAir]
IPAdapterEmbedsBatch [ComfyUI-Kolors-MZ]
IPAdapterEmbedsBatch [BizyAir]
IPAdapterEncoder [ComfyUI-Kolors-MZ]
IPAdapterEncoder [BizyAir]
IPAdapterFaceID [ComfyUI-Kolors-MZ]
IPAdapterFaceID [BizyAir]
IPAdapterFromParams [ComfyUI-Kolors-MZ]
IPAdapterFromParams [BizyAir]
IPAdapterInsightFaceLoader [ComfyUI-Kolors-MZ]
IPAdapterInsightFaceLoader [BizyAir]
IPAdapterLoadEmbeds [ComfyUI-Kolors-MZ]
IPAdapterLoadEmbeds [BizyAir]
IPAdapterMS [ComfyUI-Kolors-MZ]
IPAdapterMS [BizyAir]
IPAdapterModelLoader [ComfyUI-Kolors-MZ]
IPAdapterModelLoader [BizyAir]
IPAdapterNoise [ComfyUI-Kolors-MZ]
IPAdapterNoise [BizyAir]
IPAdapterPreciseComposition [ComfyUI-Kolors-MZ]
IPAdapterPreciseComposition [BizyAir]
IPAdapterPreciseCompositionBatch [ComfyUI-Kolors-MZ]
IPAdapterPreciseCompositionBatch [BizyAir]
IPAdapterPreciseStyleTransfer [ComfyUI-Kolors-MZ]
IPAdapterPreciseStyleTransfer [BizyAir]
IPAdapterPreciseStyleTransferBatch [ComfyUI-Kolors-MZ]
IPAdapterPreciseStyleTransferBatch [BizyAir]
IPAdapterPromptScheduleFromWeightsStrategy [ComfyUI-Kolors-MZ]
IPAdapterPromptScheduleFromWeightsStrategy [BizyAir]
IPAdapterRegionalConditioning [ComfyUI-Kolors-MZ]
IPAdapterRegionalConditioning [BizyAir]
IPAdapterSaveEmbeds [ComfyUI-Kolors-MZ]
IPAdapterSaveEmbeds [BizyAir]
IPAdapterStyleComposition [ComfyUI-Kolors-MZ]
IPAdapterStyleComposition [BizyAir]
IPAdapterStyleCompositionBatch [ComfyUI-Kolors-MZ]
IPAdapterStyleCompositionBatch [BizyAir]
IPAdapterTiled [ComfyUI-Kolors-MZ]
IPAdapterTiled [BizyAir]
IPAdapterTiledBatch [ComfyUI-Kolors-MZ]
IPAdapterTiledBatch [BizyAir]
IPAdapterUnifiedLoader [ComfyUI-Kolors-MZ]
IPAdapterUnifiedLoader [BizyAir]
IPAdapterUnifiedLoaderCommunity [ComfyUI-Kolors-MZ]
IPAdapterUnifiedLoaderCommunity [BizyAir]
IPAdapterUnifiedLoaderFaceID [ComfyUI-Kolors-MZ]
IPAdapterUnifiedLoaderFaceID [BizyAir]
IPAdapterWeights [ComfyUI-Kolors-MZ]
IPAdapterWeights [BizyAir]
IPAdapterWeightsFromStrategy [ComfyUI-Kolors-MZ]
IPAdapterWeightsFromStrategy [BizyAir]
PrepImageForClipVision [ComfyUI-Kolors-MZ]
PrepImageForClipVision [BizyAir]
IPAdapterClipVisionEnhancer [BizyAir]

**Comment by cubiq** [comment]
I don't understand the question, just remove the bizyair extension I guess

**Comment by Remember2015** [comment]
> 我安装的IPADATER节点是cubiq的，这个里面提示的是69个冲突。不理解为什么我在comfyui中加载的节点都是bizyair的。
> 
> ![error1](https://private-user-images.githubusercontent.com/176562843/353551013-37c746d7-b1bf-4935-9965-21b37948eaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTk5MzQsIm5iZiI6MTcyMjQ5OTYzNCwicGF0aCI6Ii8xNzY1NjI4NDMvMzUzNTUxMDEzLTM3Yzc0NmQ3LWIxYmYtNDkzNS05OTY1LTIxYjM3OTQ4ZWFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwODA3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTg0OTBhYzZkZjYyMGNhODRlYmNlMDU2YmQ5MTY0ZjE4NzNkOTEyNWM0NjVmNTc3MWM1MjBjOGUxZGI2Yzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bzKthZzuQ1YHAOE0CubQVLibD74KyXs97uDeqsfnvdI) 我尝试了各种解决办法。 这个faceid总是会各种各样的报错。这太让人痛苦了。
> 
> 【ComfyUI_IPAdapter_plus】Conflicted Nodes (69) IPAAdapterFaceIDBatch [ComfyUI-Kolors-MZ] IPAAdapterFaceIDBatch [BizyAir] IPAdapter [ComfyUI-Kolors-MZ] IPAdapter [BizyAir] IPAdapterAdvanced [ComfyUI-Kolors-MZ] IPAdapterAdvanced [BizyAir] IPAdapterBatch [ComfyUI-Kolors-MZ] IPAdapterBatch [BizyAir] IPAdapterCombineEmbeds [ComfyUI-Kolors-MZ] IPAdapterCombineEmbeds [BizyAir] IPAdapterCombineParams [ComfyUI-Kolors-MZ] IPAdapterCombineParams [BizyAir] IPAdapterCombineWeights [ComfyUI-Kolors-MZ] IPAdapterCombineWeights [BizyAir] IPAdapterEmbeds [ComfyUI-Kolors-MZ] IPAdapterEmbeds [BizyAir] IPAdapterEmbedsBatch [ComfyUI-Kolors-MZ] IPAdapterEmbedsBatch [BizyAir] IPAdapterEncoder [ComfyUI-Kolors-MZ] IPAdapterEncoder [BizyAir] IPAdapterFaceID [ComfyUI-Kolors-MZ] IPAdapterFaceID [BizyAir] IPAdapterFromParams [ComfyUI-Kolors-MZ] IPAdapterFromParams [BizyAir] IPAdapterInsightFaceLoader [ComfyUI-Kolors-MZ] IPAdapterInsightFaceLoader [BizyAir] IPAdapterLoadEmbeds [ComfyUI-Kolors-MZ] IPAdapterLoadEmbeds [BizyAir] IPAdapterMS [ComfyUI-Kolors-MZ] IPAdapterMS [BizyAir] IPAdapterModelLoader [ComfyUI-Kolors-MZ] IPAdapterModelLoader [BizyAir] IPAdapterNoise [ComfyUI-Kolors-MZ] IPAdapterNoise [BizyAir] IPAdapterPreciseComposition [ComfyUI-Kolors-MZ] IPAdapterPreciseComposition [BizyAir] IPAdapterPreciseCompositionBatch [ComfyUI-Kolors-MZ] IPAdapterPreciseCompositionBatch [BizyAir] IPAdapterPreciseStyleTransfer [ComfyUI-Kolors-MZ] IPAdapterPreciseStyleTransfer [BizyAir] IPAdapterPreciseStyleTransferBatch [ComfyUI-Kolors-MZ] IPAdapterPreciseStyleTransferBatch [BizyAir] IPAdapterPromptScheduleFromWeightsStrategy [ComfyUI-Kolors-MZ] IPAdapterPromptScheduleFromWeightsStrategy [BizyAir] IPAdapterRegionalConditioning [ComfyUI-Kolors-MZ] IPAdapterRegionalConditioning [BizyAir] IPAdapterSaveEmbeds [ComfyUI-Kolors-MZ] IPAdapterSaveEmbeds [BizyAir] IPAdapterStyleComposition [ComfyUI-Kolors-MZ] IPAdapterStyleComposition [BizyAir] IPAdapterStyleCompositionBatch [ComfyUI-Kolors-MZ] IPAdapterStyleCompositionBatch [BizyAir] IPAdapterTiled [ComfyUI-Kolors-MZ] IPAdapterTiled [BizyAir] IPAdapterTiledBatch [ComfyUI-Kolors-MZ] IPAdapterTiledBatch [BizyAir] IPAdapterUnifiedLoader [ComfyUI-Kolors-MZ] IPAdapterUnifiedLoader [BizyAir] IPAdapterUnifiedLoaderCommunity [ComfyUI-Kolors-MZ] IPAdapterUnifiedLoaderCommunity [BizyAir] IPAdapterUnifiedLoaderFaceID [ComfyUI-Kolors-MZ] IPAdapterUnifiedLoaderFaceID [BizyAir] IPAdapterWeights [ComfyUI-Kolors-MZ] IPAdapterWeights [BizyAir] IPAdapterWeightsFromStrategy [ComfyUI-Kolors-MZ] IPAdapterWeightsFromStrategy [BizyAir] PrepImageForClipVision [ComfyUI-Kolors-MZ] PrepImageForClipVision [BizyAir] IPAdapterClipVisionEnhancer [BizyAir]

友情提醒下，除了去除冲突的节点，kolors 需要专属的 ip-adapter-faceid-plus，原版应该是无效的

**Comment by Remember2015** [comment]
> I don't understand the question, just remove the bizyair extension I guess

He/she means comfyui nodes conflict, and [BizyAir](https://github.com/siliconflow/BizyAir) is used for running workload on the cloud (silicon clouds). Maybe it's better to take issue to BizyAir repo

**Comment by cubiq** [comment]
I believe this was a bug with the manager that was recently fixed
