### ISSUE TITLE
How to run it with ASCEDND npu

### ISSUE THREAD

**Issue by MrXsc** [cubiq/ComfyUI_IPAdapter_plus#668]

**Comment by cubiq** [comment]
let me have one and I'll let you know :smile:

**Comment by MrXsc** [comment]
hhhh, I'’ve done some work adapting to npu, and a basic workflow can run  barely on ascend.

**Comment by SubStatham** [comment]
> hhhh, I've done some work adapting to torch npu, and a basic workflow can run barely on ascend.

I have recently encountered the same problem , what work you have done to adapt to torch npu

**Comment by MrXsc** [comment]
> > hhhh, I've done some work adapting to torch npu, and a basic workflow can run barely on ascend.
> 
> I have recently encountered the same problem , what work you have done to adapt to torch npu

maybe u cloud create a new issue then @ me 😄
