### ISSUE TITLE
When "ipadapter_plus" on, error occurred "CrossAttentionPatch.set_new_condition() got an unexpected keyword argument 'weight_type'"

### ISSUE THREAD

**Issue by bartly** [cubiq/ComfyUI_IPAdapter_plus#67]
When "ipadapter_plus" on, error occurred "CrossAttentionPatch.set_new_condition() got an unexpected keyword argument 'weight_type'"
Kindly help.

**Comment by cubiq** [comment]
please try to upgrade the extension
