### ISSUE TITLE
onnx==1.16.2 causes dll error

### ISSUE THREAD

**Issue by revaraver** [cubiq/ComfyUI_IPAdapter_plus#670]
For some reason, onnx was recently updated to version 1.16.2, which causes the IPAdapterFaceID loader to encounter DLL loading errors when using FaceID, leading to the "famous" "insightface model is required for FaceID models" message. Downgrading to version 1.16.1 resolves the issue. Additionally, version 1.18.0 of onnxruntime also causes errors; I upgraded to version 1.18.1 to fix the problem.

Perhaps this project needs a requirements.txt file to specify some critical component versions?

**Comment by cubiq** [comment]
that doesn't seem the root of the problem. I have all the latest versions installed and it still works, so setting a specific version into the requirements doesn't seem to be the right solution
```
$ pip list | grep onnx
onnx                               1.16.2
onnxruntime                        1.18.1
onnxruntime-gpu                    1.18.1
```
