### ISSUE TITLE
I will bang my head to walls.. I can't download Insightface

### ISSUE THREAD

**Issue by anseltrust** [cubiq/ComfyUI_IPAdapter_plus#671]
C:\Comfy\ComfyUI_windows_portable>python_embeded\python.exe -m pip install C:\Users\MSI-NB\Desktop\insightface-0.7.3-cp311-cp311-win_amd64.whl
Processing c:\users\msi-nb\desktop\insightface-0.7.3-cp311-cp311-win_amd64.whl
Requirement already satisfied: numpy in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.26.4)
Requirement already satisfied: onnx in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.16.2)
Requirement already satisfied: tqdm in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (4.66.4)
Requirement already satisfied: requests in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (2.32.3)
Requirement already satisfied: matplotlib in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (3.9.0)
Requirement already satisfied: Pillow in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (9.5.0)
Requirement already satisfied: scipy in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.13.0)
Requirement already satisfied: scikit-learn in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.5.0)
Requirement already satisfied: scikit-image in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (0.24.0)
Requirement already satisfied: easydict in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.13)
Requirement already satisfied: cython in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (3.0.10)
Requirement already satisfied: albumentations in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (1.4.10)
Requirement already satisfied: prettytable in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from insightface==0.7.3) (3.10.0)
Requirement already satisfied: PyYAML in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Requirement already satisfied: typing-extensions>=4.9.0 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from albumentations->insightface==0.7.3) (4.12.2)
Requirement already satisfied: pydantic>=2.7.0 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from albumentations->insightface==0.7.3) (2.8.0)
Requirement already satisfied: albucore>=0.0.11 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from albumentations->insightface==0.7.3) (0.0.12)
Requirement already satisfied: opencv-python-headless>=4.9.0.80 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from albumentations->insightface==0.7.3) (4.10.0.84)
Requirement already satisfied: networkx>=2.8 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->insightface==0.7.3) (3.3)
Requirement already satisfied: imageio>=2.33 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->insightface==0.7.3) (2.34.2)
Requirement already satisfied: tifffile>=2022.8.12 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->insightface==0.7.3) (2024.7.2)
Requirement already satisfied: packaging>=21 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->insightface==0.7.3) (23.2)
Requirement already satisfied: lazy-loader>=0.4 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->insightface==0.7.3) (0.4)
Requirement already satisfied: joblib>=1.2.0 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-learn->insightface==0.7.3) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib->insightface==0.7.3) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib->insightface==0.7.3) (2.9.0.post0)
Requirement already satisfied: protobuf>=3.20.2 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from onnx->insightface==0.7.3) (4.25.3)
Requirement already satisfied: wcwidth in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->insightface==0.7.3) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->insightface==0.7.3) (1.26.19)
Requirement already satisfied: certifi>=2017.4.17 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->insightface==0.7.3) (2024.6.2)
Requirement already satisfied: colorama in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: tomli>=2.0.1 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from albucore>=0.0.11->albumentations->insightface==0.7.3) (2.0.1)
Requirement already satisfied: annotated-types>=0.4.0 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from pydantic>=2.7.0->albumentations->insightface==0.7.3) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.0 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from pydantic>=2.7.0->albumentations->insightface==0.7.3) (2.20.0)
Requirement already satisfied: six>=1.5 in c:\comfy\comfyui_windows_portable\python_embeded\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
insightface is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

Please just help.. It has been months, I tried everything

**Comment by aaltulea** [comment]
it says "insightface is already installed with the same version as the provided wheel"?

**Comment by cubiq** [comment]
possible duplicate
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/162
