### ISSUE TITLE
I have fixed the error: Error occurred when executing IPAdapterUnifiedLoader: ClipVision model not found.

### ISSUE THREAD

**Issue by traithanhnam90** [cubiq/ComfyUI_IPAdapter_plus#677]
After spending a whole working day to consult to fix this annoying error, I found a way to fix this error thanks to a member on reddit!
![Ảnh chụp màn hình 2024-08-07 175115](https://github.com/user-attachments/assets/edca473c-83de-4f1c-868d-5cf86fa389a6)
![Ảnh chụp màn hình 2024-08-07 175037](https://github.com/user-attachments/assets/e15486c6-d719-4dd8-b0c8-eee7585f586b)

How to fix: download these models according to the author's instructions:
![image](https://github.com/user-attachments/assets/fd94bd73-ec7b-4f08-b706-fdc4c5218b67)

Folders in my computer:
![Ảnh chụp màn hình 2024-08-07 175217](https://github.com/user-attachments/assets/25747a53-31e1-4169-a1c2-e1e35bbe9a6f)
![Ảnh chụp màn hình 2024-08-07 175148](https://github.com/user-attachments/assets/4bbe12b7-3b99-4caf-921b-d53d710904d2)

Then restart ComfyUi and you still see the above error?
**and here is how to fix it: rename the files in the clip_vision folder as follows
CLIP-ViT-bigG-14-laion2B-39B-b160k     -------->  CLIP-ViT-bigG-14-laion2B-39B.b160k
CLIP- ViT-H -14-laion2B-s32B-b79K        -------->  CLIP-ViT-H-14-laion2B-s32B.b79K**

![image](https://github.com/user-attachments/assets/ebb30874-87ec-4ae2-8392-f2787b466d73)
illustration image on reddit!

 restart ComfyUi! Complete!

**Comment by Tanglinling** [comment]
I encountered the same problem, but after trying to reinstall the node and the method you mentioned, the problem has not been resolved.

**Comment by CoolCoolTomato** [comment]
wc! nb!

**Comment by Jotakak-yu** [comment]
thx! solved my issue.
