### ISSUE TITLE
the number of layers in MadScientist node was 11 or 16?

### ISSUE THREAD

**Issue by GoodGoodstudy0daydayup** [cubiq/ComfyUI_IPAdapter_plus#679]
<img width="1190" alt="ca85276bd68b20d67dff7da1481a198" src="https://github.com/user-attachments/assets/bcc6d413-6484-4bcd-a422-afe14e0034c5">
I read the code of CrossAttentionPatch.py. Does line 36 mean that the number of layers will be 11 or 16? Sometimes I input 12:1 or 15:1 in the MadScientist node and it will change the effect of the output image.
<img width="1244" alt="1723266011719" src="https://github.com/user-attachments/assets/f25b1381-9a38-48c3-8027-fd02770fa756">
i input 15:1 in the madscientist node ,The color saturation of the output image is improved, and it looks better, but I want to know which layers will affect the color of the output image, because I am trying to convert some 2D anime images to real photography images recently. There is no tile_colorfix+sharp preprocessor in comfyui, so the color of the output image cannot be controlled according to the color of the original image. I want to use the ipadapter madscientist node to achieve a similar effect to tile_colorfix very Stably
<img width="1244" alt="1f4a305af3a86af06704b8ee9e4e366" src="https://github.com/user-attachments/assets/947e1620-86ed-41fb-84b1-201d2047b578">

**Comment by cubiq** [comment]
11 for SDXL otherwise 16

**Comment by GoodGoodstudy0daydayup** [comment]
Thank you for your answer
