### ISSUE TITLE
InsightFace usually can't detect anime faces. 

### ISSUE THREAD

**Issue by fangwenjump** [cubiq/ComfyUI_IPAdapter_plus#681]
InsightFace can't detect very clear anime face photos, for example:

![Snipaste_2024-08-12_11-18-22](https://github.com/user-attachments/assets/66a5e1ff-f0d1-4f01-a576-83949a151fd2)
![Snipaste_2024-08-12_11-28-21](https://github.com/user-attachments/assets/826622ba-94fb-45c4-9aff-619bf9857fc5)

![Snipaste_2024-08-12_13-36-43](https://github.com/user-attachments/assets/4cef0a50-e3e8-4df7-aa3e-b5909fbb7d31)

**Comment by cubiq** [comment]
buffalo_l models are not trained for anime or cartoon style in general. you might get like once or twice but generally speaking you would need a dedicated model for that.

**Comment by fangwenjump** [comment]
> buffalo_l models are not trained for anime or cartoon style in general. you might get like once or twice but generally speaking you would need a dedicated model for that.

I can't detect it using antelopev2 either. Are there any other models?
