### ISSUE TITLE
diffusers

### ISSUE THREAD

**Issue by lhjlhj11** [cubiq/ComfyUI_IPAdapter_plus#697]
Is there any reference for IPAdapter style & composition for diffusers?

**Comment by sherlhw** [comment]
+1

**Comment by cubiq** [comment]
there's instant-style or how it is called

**Comment by sherlhw** [comment]
Is https://github.com/instantX-research/InstantStyle?

**Comment by cubiq** [comment]
yes

**Comment by sherlhw** [comment]
Thanks
