### ISSUE TITLE
[Feature Request] Ipadapter pipe for Flux and Kolors.

### ISSUE THREAD

**Issue by Vigilence** [cubiq/ComfyUI_IPAdapter_plus#698]
Flux and Kolors ipadapter pipe to use segs detailer.  Impact and Inspire packs.

**Comment by Vigilence** [comment]
I tried kolors and would get a size mis match when using the iPadapter, sets tile and segs detailer workflow.  Can you confirm this was tested for the nodes of the impact and inspire pact?

here is the base workflow i tried:


https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/MakeTileSEGS_upscale_sdxl-lightning_ipadapter.png

**Comment by cubiq** [comment]
check this https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/examples/ipadapter_kolors.json

**Comment by Vigilence** [comment]
Oh I meant if you can add a ipadapter pipe node.  I know the regular style transfer itself works but I would love it if you have a pipe node, as the one I am using has the error described above.

Here is what I would appreciate if your node pack had.

![Screenshot 2024-08-29 100821](https://github.com/user-attachments/assets/d22ec81a-27d4-4a0a-ae65-b65878da37c0)

This in particular.
![Screenshot 2024-08-29 100757](https://github.com/user-attachments/assets/a565f55e-4158-4035-ad2a-0a2943230cf4)

**Comment by ltdrdata** [comment]
> Oh I meant if you can add a ipadapter pipe node. I know the regular style transfer itself works but I would love it if you have a pipe node, as the one I am using has the error described above.
> 
> Here is what I would appreciate if your node pack had.
> 
> ![Screenshot 2024-08-29 100821](https://private-user-images.githubusercontent.com/22781570/362729292-d22ec81a-27d4-4a0a-ae65-b65878da37c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDYzMzMsIm5iZiI6MTcyOTAwNjAzMywicGF0aCI6Ii8yMjc4MTU3MC8zNjI3MjkyOTItZDIyZWM4MWEtMjdkNC00YTBhLWFlNjUtYjY1ODc4ZGEzN2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MjcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNzlhYzRiMTNlMjU1NTM1OGE3ZTY1OTU5ODdiYmUwMGNmOWU2Njc2MWVmNGQwNjMwYTBkZDVjNWFiYThiNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nVvl8hZ4X1Wwja0UTn4gi693F1YlXhnw_UUq02h4U0w)
> 
> This in particular. ![Screenshot 2024-08-29 100757](https://private-user-images.githubusercontent.com/22781570/362729406-a565f55e-4158-4035-ad2a-0a2943230cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDYzMzMsIm5iZiI6MTcyOTAwNjAzMywicGF0aCI6Ii8yMjc4MTU3MC8zNjI3Mjk0MDYtYTU2NWY1NWUtNDE1OC00MDM1LWFkMmEtMGEyOTQzMjMwY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MjcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNTgwMmJkNDM1Njk2NDM3MzliNDZhYTNhYjFjYzlmOTZjNDEzOTQyZDYwMjM2ODQxMTFiOTI1MDZjYTU1ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JsAnbKSFVSVSnjOTlQ9RI56aurC3F23UanrJzFqC_nA)

Inspire Pack supports Kolors model.
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/IPAdapterModelHelper-Kolors.png

**Comment by Vigilence** [comment]
> > Oh I meant if you can add a ipadapter pipe node. I know the regular style transfer itself works but I would love it if you have a pipe node, as the one I am using has the error described above.
> > Here is what I would appreciate if your node pack had.
> > ![Screenshot 2024-08-29 100821](https://private-user-images.githubusercontent.com/22781570/362729292-d22ec81a-27d4-4a0a-ae65-b65878da37c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDYzMzMsIm5iZiI6MTcyOTAwNjAzMywicGF0aCI6Ii8yMjc4MTU3MC8zNjI3MjkyOTItZDIyZWM4MWEtMjdkNC00YTBhLWFlNjUtYjY1ODc4ZGEzN2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MjcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNzlhYzRiMTNlMjU1NTM1OGE3ZTY1OTU5ODdiYmUwMGNmOWU2Njc2MWVmNGQwNjMwYTBkZDVjNWFiYThiNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nVvl8hZ4X1Wwja0UTn4gi693F1YlXhnw_UUq02h4U0w)
> > This in particular. ![Screenshot 2024-08-29 100757](https://private-user-images.githubusercontent.com/22781570/362729406-a565f55e-4158-4035-ad2a-0a2943230cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDYzMzMsIm5iZiI6MTcyOTAwNjAzMywicGF0aCI6Ii8yMjc4MTU3MC8zNjI3Mjk0MDYtYTU2NWY1NWUtNDE1OC00MDM1LWFkMmEtMGEyOTQzMjMwY2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE1MjcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNTgwMmJkNDM1Njk2NDM3MzliNDZhYTNhYjFjYzlmOTZjNDEzOTQyZDYwMjM2ODQxMTFiOTI1MDZjYTU1ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JsAnbKSFVSVSnjOTlQ9RI56aurC3F23UanrJzFqC_nA)
> 
> Inspire Pack V1.5 supports Kolors model. https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/IPAdapterModelHelper-Kolors.png

Thanks!
