### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ImageProjModel:

### ISSUE THREAD

**Issue by lrzjason** [cubiq/ComfyUI_IPAdapter_plus#7]
I have tried with the example workflow which also produce this error.

All nodes and comfy are updated.

RuntimeError: Error(s) in loading state_dict for ImageProjModel:
        size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([8192, 1280]).

**Comment by cubiq** [comment]
Are you using the new SDXL model? It has a different size and I have to work on that. Hopefully tomorrow.

All the other models should work.

**Comment by lrzjason** [comment]
Yes, sdxl

**Comment by cubiq** [comment]
there are two models for SDXL, the bigger one works, the small one that was released a couple of days ago I believe was trained with smaller pictures. It should be an easy fix, check back tomorrow :)

**Comment by lrzjason** [comment]
OhISee. I would try the bigger one.

**Comment by cubiq** [comment]
okay this is not an error on my part (for once)... to make things even more complicated the `ip-adapter_sdxl_vit-h.bin` model has to be used with the SD1.5 image encoder (not the SDXL one). So in the Load clip vision node you should load the file you'd load for sd1.5 but then use an SDXL model for image generation.

I'll check if there's any way for me to detect and help users with meaningful error messages
