### ISSUE TITLE
channel penalty(Fooocus) different results

### ISSUE THREAD

**Issue by liangkun43** [cubiq/ComfyUI_IPAdapter_plus#70]
This is my reference image.
![273487475-0f81b24d-e55d-4e4d-b82c-336edb194c2f](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/ead7b99e-3631-40e5-9dab-e55ce06fddd3)
use ip-adapter-plus_sdxl_vit-h model
Positive text:`photograph dragon, 50mm . cinematic 4k epic detailed 4k epic detailed photograph shot on kodak detailed cinematic hbo dark moody, 35mm photo, grainy, vignette, vintage, Kodachrome, Lomography, stained, highly detailed, found footage`
Negative text:`Brad Pitt, bokeh, depth of field, blurry, cropped, regular face, saturated, contrast, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, text, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck`
This is the result in fooocus.
![微信截图_20231108211713](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/6f5bb8cd-5555-411e-973f-a17d45a5c7bd)
This is the result of channel penalty.(including workflow)
![workflow2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/ae28aa0f-bb0f-460d-9100-1ab2297e79e0)
This is the result I got from this [branch](https://github.com/laksjdjf/IPAdapter-ComfyUI/tree/fooocus_ip).
![workflow](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/bdace301-8fd2-4a25-92ac-28cff8e57a60)

**Comment by cubiq** [comment]
fooocus and the other repo both use an implementation that in my opinion is not ideal and too far from the IPAdapter intended behavior. In fact at a strength 0.6 it makes sense that the bird is still very visible while in the other implementations has basically disappeared.

My theory is confirmed by the fact that the original IPAdapter implementation is closer to the "channel penalty" than it is the "fooocus" one.

I haven't checked but I also believe that the other comfyui implementation doesn't work with multiple images (or at least the result would be very unpredictable).

I'm open to discussion.

**Comment by liangkun43** [comment]
Thank you very much for your work.Below are the results of the two reference pictures，The results are indeed unpredictable
![微信截图_20231108222014](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/93cf12dd-be23-45f1-8c02-d274be99a545)
![two picture workflow](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/04986f9e-fd01-44aa-ab4f-2201d600802a)
![two picture workflow2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/666f0a0a-8bce-446c-844c-d3592ab8728f)
"channel penalty" image are very bad，"linear" and "original"result combines the features of the two images
![two picture workflow3](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/fda757f9-60b7-4082-9364-607f255cd031)
![two picture workflow4](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/ea49f337-ce67-4e55-8f0d-c183fe060de1)
Maybe some people just need an option to accomplish the same result in other UI

**Comment by liangkun43** [comment]
An interesting thing seems to have happened during my testing, I don't know what happened, but got good results
![two picture workflow5](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/b2f89df7-593c-4d79-89d0-e72b209c1ea5)
Cancel the queue when the "apply IPAdapter" is loaded, and then reconnect to another node，queue prompt
![微信截图_20231108233828](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/135417715/0db3331a-c2b0-4dc9-9048-e5f8d1df006e)

**Comment by cubiq** [comment]
if you add a little "noise" it usually helps to stabilize the composition

**Comment by xiaohu2015** [comment]
I think Fooocus also stop early (at step 0.4) for image prompt, which is important?

**Comment by cubiq** [comment]
> I think Fooocus also stop early (at step 0.4) for image prompt, which is important?

I haven't checked the full code. The way fooocus merges the embeds is completely different to how I do it. In foooocus implementation the text prompt has a very strong influence but if they stop at 0.4 that might explain why the results are widely different.

Timestepping is something that I wanted to do as well but it can be already simulated stopping the generation at X step and resuming it with a second pipeline. It can be done both with diffusers and comfyui

This is the generation with IPAdapter stopped at 50% of the generation:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/23227805-4e9d-492f-9624-579f454b719a)

this is stopped at 60%
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/0e14e4f2-39f5-40d1-bf44-8d86ba800529)

and so on

**Comment by hben35096** [comment]
Request add support for start _steps and end _steps.

**Comment by ttulttul** [comment]
> Request add support for start _step and end _step.

Your wish has now been granted.

**Comment by hben35096** [comment]
> > Request add support for start _step and end _step.
> 
> Your wish has now been granted.
Thank you very much, this is a very useful feature.
