### ISSUE TITLE
IpAdapterUnifiedLoader > IpAdapter model not found >> old IpAdapter not visible in UI

### ISSUE THREAD

**Issue by hirschferkel** [cubiq/ComfyUI_IPAdapter_plus#708]
IPAdapterUnifiedLoader  IPAdapter model not found.
It works with Ipadapter model load but does not with ipadapter unified loader. Does anyone have an idea how to resolve this issue?

![Screenshot 2024-09-07 024516](https://github.com/user-attachments/assets/001251ef-5c3e-4f42-8d53-b17654b7b501)
```
# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterUnifiedLoader
- **Exception Type:** Exception
- **Exception Message:** IPAdapter model not found.
## Stack Trace

  File "C:\Users\user\Eigene Programme\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\Eigene Programme\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\Eigene Programme\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\user\Eigene Programme\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\user\Eigene Programme\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 573, in load_models
    raise Exception("IPAdapter model not found.")

```

**Comment by hirschferkel** [comment]
O.k. I got closer to the issue. 
It happens only, when I use juggernautXL as checkpoint. Any idea, why it does not work with juggernaut safetensors?

**Comment by hirschferkel** [comment]
Finally I found the issue: It was an old adapter used in former workflows, but it was not visible that it is old! After I created a new Adapter everything works ... what a mess.

**Comment by senpaiiss** [comment]
> Finally I found the issue: It was an old adapter used in former workflows, but it was not visible that it is old! After I created a new Adapter everything works ... what a mess.

![Desktop 2024-09-07 12-28-30 PM-91](https://github.com/user-attachments/assets/d574d4a7-f9d6-486b-9d0b-966789e0b793)
[New Text Document.txt](https://github.com/user-attachments/files/16919784/New.Text.Document.txt)
help i cant figure out what is causing the same issue

**Comment by senpaiiss** [comment]
> Finally I found the issue: It was an old adapter used in former workflows, but it was not visible that it is old! After I created a new Adapter everything works ... what a mess.

how do you find out its old ipadapter?

**Comment by hirschferkel** [comment]
@senpaiiss I found a youtube video where one guy said he has ideas how to fix it. So i loaded my workflow and it did not work. Then I deleted the IpAdapterUnifiedLoader and inserted a new one. Made all connections again and it worked. So the reason is an outdated deprecated adapter from former workflows.

**Comment by hirschferkel** [comment]
So your issue is different: the adapter tries has mismatching image ratio. You have to fit adapter in all parameters. Input image and computing size do not match and you the adapter is locked to recalculate a fitting ratio.

> > Finally I found the issue: It was an old adapter used in former workflows, but it was not visible that it is old! After I created a new Adapter everything works ... what a mess.
> 
> ![Desktop 2024-09-07 12-28-30 PM-91](https://private-user-images.githubusercontent.com/118785113/365398305-d574d4a7-f9d6-486b-9d0b-966789e0b793.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDEyNTUsIm5iZiI6MTcyNTc0MDk1NSwicGF0aCI6Ii8xMTg3ODUxMTMvMzY1Mzk4MzA1LWQ1NzRkNGE3LWY5ZDYtNDg2Yi05ZDBiLTk2Njc4OWUwYjc5My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QyMDI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTgwMDcxODM4MzhjYWQ2YTBmYTVkYjJmNTE1Njc3YTJlNTJkYjMxMDY4ZTRjNDU0NTBmYzk0ZGVkMmUwODQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dbbW2eOq59gtj2PXjW0Xn5IeOV1jEHUvbbFEaQnNsJc) [New Text Document.txt](https://github.com/user-attachments/files/16919784/New.Text.Document.txt) help i cant figure out what is causing the same issue

**Comment by senpaiiss** [comment]
> @senpaiiss I found a youtube video where one guy said he has ideas how to fix it. So i loaded my workflow and it did not work. Then I deleted the IpAdapterUnifiedLoader and inserted a new one. Made all connections again and it worked. So the reason is an outdated deprecated adapter from former workflows.

This is where i found my solution and it work for me. Apparently old and new Ipadapters don't work well so this combines the two so they now work together. 
https://www.reddit.com/r/comfyui/comments/1bov4xw/maintaining_legacy_ipadapter_nodes_alongside_new/

**Comment by KLL535** [comment]
To be honest, I didn't understand how to fix this.
