### ISSUE TITLE
Missing Node Types When Loading Workflow

### ISSUE THREAD

**Issue by hishambarakat16** [cubiq/ComfyUI_IPAdapter_plus#713]
When loading the workflow from the IPAdapter_FaceIDv2_Kolors.json file, I encounter the following warning about missing node types:
Warning: Missing Node Types
When loading the graph, the following node types were not found:

MZ_ChatGLM3_V2
MZ_KolorsUNETLoaderV2
MZ_ChatGLM3Loader
No selected item
![image](https://github.com/user-attachments/assets/f752eeb9-c67c-4423-8228-7eefc870667e)

These nodes are showing as red on the graph, indicating that they failed to load.

Steps to Reproduce
Load the workflow file IPAdapter_FaceIDv2_Kolors.json.
Observe the warning about missing node types.
Nodes appear as red on the graph.

**Comment by cubiq** [comment]
you just need to install [ComfyUI-Kolors-MZ](https://github.com/MinusZoneAI/ComfyUI-Kolors-MZ)
