### ISSUE TITLE
Models not loading

### ISSUE THREAD

**Issue by arujjval** [cubiq/ComfyUI_IPAdapter_plus#739]
I am trying to use Unified loader and have the necessary models in the `models/ipadapter` folder with the correct naming, but it still is showing `IpAdapter model not found`. 

How to resolve it?

My PC specs are 
16GB RAM
RTX 3050 (4 GB VRAM)
Processor: AMD Ryzen 5 6600H

**Comment by alkemann** [comment]
Does ANY of the example workflows work for anyone? Or is this project dead now?

**Comment by cubiq** [comment]
all the example workflows work
