### ISSUE TITLE
sorry.close this issue1

### ISSUE THREAD

**Issue by isamu2025** [cubiq/ComfyUI_IPAdapter_plus#747]

**Comment by dancemanUK** [comment]
python_embeded>python -s -m pip install florence_2
WARNING: Ignoring invalid distribution - (g:\comfyui+animatediff\python_embeded\lib\site-packages)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement florence_2 (from versions: none)
ERROR: No matching distribution found for florence_2
