### ISSUE TITLE
IPAdapter Advanced issues with torch Size, n

### ISSUE THREAD

**Issue by ggarra13** [cubiq/ComfyUI_IPAdapter_plus#752]
Latest ComfyUI and IPAdapter_plus. I am using IPAdapter Advanced, IPAdapter Unified Loader, IPAdapter Embeds like shown in the picture and getting:

![image](https://github.com/user-attachments/assets/850df603-ca60-466b-ac89-28d9bdf3d0e2)

IPAdapter chokes with:

size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1668])

I've checked the current clip_vision model size and and it is indeed 1280, 1664:

json_config= ComfyUI\comfy\clip_vision_config_g.json
Loading json_config= ComfyUI\comfy\clip_vision_config_g.json
CLIPVision embed_dim= 1664
CLIPVisionEmbeddings embed_dim= 1664
INFO: Clip Vision model loaded from ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
INFO: IPAdapter model loaded from models\ipadapter\ip-adapter-plus_sdxl_vit-h.safetensors
ipadapter has clip_vision {'image_size': 224, 'load_device': device(type='cuda', index=0), 'dtype': torch.float16, 'model': CLIPVisionModelProjection(
(vision_model): CLIPVision(
(embeddings): CLIPVisionEmbeddings(
(patch_embedding): Conv2d(3, 1664, kernel_size=(14, 14), stride=(14, 14), bias=False)
(position_embedding): Embedding(257, 1664)
)
(pre_layrnorm): LayerNorm((1664,), eps=1e-05, elementwise_affine=True)
(encoder): CLIPEncoder(
(layers): ModuleList(
(0-47): 48 x CLIPLayer(
(layer_norm1): LayerNorm((1664,), eps=1e-05, elementwise_affine=True)
(self_attn): CLIPAttention(
(q_proj): Linear(in_features=1664, out_features=1664, bias=True)
(k_proj): Linear(in_features=1664, out_features=1664, bias=True)
(v_proj): Linear(in_features=1664, out_features=1664, bias=True)
(out_proj): Linear(in_features=1664, out_features=1664, bias=True)
)
(layer_norm2): LayerNorm((1664,), eps=1e-05, elementwise_affine=True)
(mlp): CLIPMLP(
(fc1): Linear(in_features=1664, out_features=8192, bias=True)
(fc2): Linear(in_features=8192, out_features=1664, bias=True)
)
)
)
)
(post_layernorm): LayerNorm((1664,), eps=1e-05, elementwise_affine=True)
)
(visual_projection): Linear(in_features=1664, out_features=1280, bias=False)
), 'patcher': <comfy.model_patcher.ModelPatcher object at 0x0000018BDB749BE0>}
INFO: the IPAdapter reference image is not a square, CLIPImageProcessor will resize and crop it at the center. If the main focus of the picture is not in the middle the result might not be what you are expecting.
embedding_dim 1664
dim 1280
output_dim 2048

I've also checked all the safetensor files and they are named correctly and have the right checksum, Any clues?

**Comment by msgtobala** [comment]
What is the solution and How did you fix this?

**Comment by ggarra13** [comment]
In my case, it was a problem with one of the checkpoint files which I downloaded manually.  At least, that's what I recall.
