### ISSUE TITLE
Add support for animations

### ISSUE THREAD

**Issue by cubiq** [cubiq/ComfyUI_IPAdapter_plus#76]
Explore the possibility to add animation support.

Ideally you'd be able to change mask and reference image for each "frame".

**Comment by nathanshipley** [comment]
Would LOVE to be able to use an animated mask for IPAdapter attention masking!  Thanks for all that you've shared so far

**Comment by zerolocker** [comment]
Hi cubiq, thank you so much for the wonderful work , also love your [YT channel](https://www.youtube.com/watch?v=vp_5Sm4V-Ds&t=357s)! 

Is it currently possible to adjust the weight of the IPAdapter during an Animatediff animation?  basically , I am looking for a "weight schedule" feature which allows users to specify a weight and an image at timestamp T1, but let the weight gradually decay to 0 at timestamp T2.

**Comment by cubiq** [comment]
> 
> Is it currently possible to adjust the weight of the IPAdapter during an Animatediff animation? basically , I am looking for a "weight schedule" feature which allows users to specify a weight and an image at timestamp T1, but let the weight gradually decay to 0 at timestamp T2.

yeah this would be possible, animatediff tends to blur the attention a lot. it means that a weight difference from 0.1 to 0.2 might not be visible and animatediff would just average the result. Needs testing.

**Comment by brbbbq** [comment]
I'm also looking to animate ipadapter with animatediff. Simply being able to animate the weights would be really helpful. 

Being able to feed an image sequence into the masking channel would be even more useful. The potential there seems really big. I hope this is something that can be done.

**Comment by cubiq** [comment]
this is freaking done!

**Comment by nathanshipley** [comment]
Grazie mille!  Seriously appreciate it, Matteo.  This is so, so cool.
