### ISSUE TITLE
furusu models

### ISSUE THREAD

**Issue by cubiq** [cubiq/ComfyUI_IPAdapter_plus#77]
@laksjdjf what is your model trained to? https://huggingface.co/furusu/IP-Adapter

do you want to add it to the documentation?

**Comment by laksjdjf** [comment]
it is for https://huggingface.co/waifu-diffusion/wd-1-5-beta3

**Comment by cubiq** [comment]
did you use the original data for the training? is it available? I would like to make a training tutorial sooner or later.

**Comment by laksjdjf** [comment]
I used crawled illustrations and forget the detailed information.
I am not sure about that as I do not use the original training code.
