### ISSUE TITLE
ClipVision model not found when running your simple workflow

### ISSUE THREAD

**Issue by icemagno** [cubiq/ComfyUI_IPAdapter_plus#771]
When I try to run https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/examples/ipadapter_simple.json

IPAdapterUnifiedLoader
ClipVision model not found.

**Comment by icemagno** [comment]
Figured out. Thnks

**Comment by msgtobala** [comment]
@icemagno Please post the solution

**Comment by icemagno** [comment]
Simply download a ClipVision model. I did't post the solution because I was  embarrassed with so simple question and I think no one had been through this.
