### ISSUE TITLE
add support for lcm lora

### ISSUE THREAD

**Issue by Eaven21** [cubiq/ComfyUI_IPAdapter_plus#80]
lcm lora is a very powerful acceleration module, looking forward to seeing compatibility with LCM Lora.

**Comment by laksjdjf** [comment]
No implementations are necessary, and it should already be usable. However, the IP-Adapter model may require training for LCM.

**Comment by cubiq** [comment]
IPAdapter works pretty well with LCM. The result is probably a little burned but I haven't played much with it.

![LCM](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/d2f947a4-5aa3-4660-95af-6f7e1a7111f6)

**Comment by Laidawang** [comment]
It seems to me that lcm causes the ipadapter to have less impact.
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/85244566/37828563-a564-4938-9b74-fb7446781d66)

**Comment by Laidawang** [comment]
I used controlnet in the picture above, and when I removed them, the ipadapter's capabilities seemed to be restored some
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/85244566/c28c047e-6129-495e-89b2-ed514f0c4cb7)
