### ISSUE TITLE
Is controlling the starting/ending step possible?

### ISSUE THREAD

**Issue by guillaume86** [cubiq/ComfyUI_IPAdapter_plus#83]
In A1111 the IPAdapter is implemented as a control net (even if I guess it is not technically a control net but wathever) and it seems possible to control the starting/ending step, is it possible to do something similar in ComfyUI?

**Comment by cubiq** [comment]
I'm exploring this possibility. I believe we would need to the route the "conditioning" pipeline too and I don't like that very much

**Comment by laksjdjf** [comment]
Adding timestep to `transformer_options` and `extra_options` can get current steps.
https://github.com/comfyanonymous/ComfyUI/blob/7114cfec0eefe713340257c85a2b342e98fdcfb2/comfy/ldm/modules/diffusionmodules/openaimodel.py#L607-L608

https://github.com/comfyanonymous/ComfyUI/blob/7114cfec0eefe713340257c85a2b342e98fdcfb2/comfy/ldm/modules/attention.py#L396-L407

**Comment by cubiq** [comment]
comfyanonymous says he's going to add "percent" to the transformer_options... let's see

**Comment by cubiq** [comment]
@laksjdjf this is where I am:

```
sigma_start = model.model.model_sampling.percent_to_sigma(start)
sigma_end = model.model.model_sampling.percent_to_sigma(end)
```
this will return our window

then from:
```
model.set_model_input_block_patch(input_block_patch)
```

we can get the sigma:
```
def input_block_patch(h, transformer_options):
    sigma = transformer_options["sigmas"][0].item()
    return h
```

what do you think? I don't think comfy is willing to add the sigmas in the extra options at the moment
