### ISSUE TITLE
Batch images (out of memory) error 

### ISSUE THREAD

**Issue by Daggle24** [cubiq/ComfyUI_IPAdapter_plus#84]
When I upload a batch of images in order to load it into the AnimateDiff Loader Model input, I'm getting an error of (out of memory)

I cannot for example load 200 images I have to limit the amount of images to for example (24) to input on the Apply IpAdapter node.

I was wondering if there was any way to free the VRAM for every image iteration (saving it to the CPU or something) before passing the final vector that goes the model output.

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/46680055/25bf156e-ed48-4e8b-a9fd-d5e3e0815f6d)

This is the error I get:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/46680055/d569d01f-3605-455f-a0d5-f7f5ceea0998)

**Comment by cubiq** [comment]
IPAdapter at the moment doesn't take "frames" as input. Sending 24 images (or 200) would only result in one huge embed applied to all frames at once.

We would need something specific for animations. I'm trying to explore the feasibility of that.
