### ISSUE TITLE
How does noise change the output?

### ISSUE THREAD

**Issue by ParthGandhi** [cubiq/ComfyUI_IPAdapter_plus#86]
I understand _what_ it does based on the README, but I can't seem to find any noticeable difference in output quality based on setting it very low or very high. So what does it actually do? And is there a recommended value?

**Comment by cubiq** [comment]
like anything in SD, there is not firm answer. Depends on many factors. Generally speaking a 0.33 noise grants better results (but depends on the checkpoint). A higher noise gives more importance to the original checkpoint that shows more of its character.
