### ISSUE TITLE
Can you share the workflow shown in your last video?

### ISSUE THREAD

**Issue by EricLiuEricLiu** [cubiq/ComfyUI_IPAdapter_plus#87]
<img width="1038" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/40813414/a8fc7b8b-86c0-407e-ba43-cc6240e11969">
Can you share the workflow of this image? It seem to work very well. I'm just looking to merge two pet characters into the same image with consistent appearances. I tried with all of the methods you talked about, but the result is a little off.

My best try was something like this:
![pet](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/40813414/ae5c50c6-d635-4b8c-b2fe-26d41b909c69)
![pet_6550847b8db90f6086e79675_pet](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/40813414/39b903e5-f138-4b60-9f4b-9f8a4374362f)
![ComfyUI_00056_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/40813414/8aea84bc-b2c9-431a-96c3-4b7cf67848cc)
![ComfyUI_00052_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/40813414/2f168d2c-7143-40f3-a797-cc22351b3b13)
Wander what modification should I make to improve it.

Thanks!

**Comment by cubiq** [comment]
I don't know what result you are trying to reach but I don't see any issue (workflow should be embedded)

![ComfyUI_temp_pdbrf_00035_](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/427614/773b25fc-79e6-4e1c-90be-35566d447553)
