### ISSUE TITLE
The ip-adapter-plus_sdxl_vit-h.bin and ip-adapter-plus-face_sdxl_vit-h.bin does not work

### ISSUE THREAD

**Issue by 779575267** [cubiq/ComfyUI_IPAdapter_plus#88]
![D20231119T011312](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/128579823/bf34b88a-9b47-4768-987c-f99139299c7e)
![D20231119T011353](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/128579823/ac1d7664-0314-4c6d-8e53-13701ea06768)
The ip-adapter-plus_sdxl_vit-h.bin and ip-adapter-plus-face_sdxl_vit-h.bin does not work, even use SD1.5 encoders clip model.

**Comment by 779575267** [comment]
![微信截图_20231119012307](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/128579823/6c4f003f-4e35-431c-a7cd-76ac3e81781b)
When turn the ipadapter_plus option on , the Error content changed...

**Comment by cubiq** [comment]
you need to update comfyUI, you have an older version

**Comment by 779575267** [comment]
> you need to update comfyUI, you have an older version

My version is 7e3fe3a

**Comment by cubiq** [comment]
then you need to update the ipadapter extension

**Comment by 779575267** [comment]
> then you need to update the ipadapter extension

Thank you so much, problem solved.
