### ISSUE TITLE
error on m1 macbookpro

### ISSUE THREAD

**Issue by AltairAlAnon** [cubiq/ComfyUI_IPAdapter_plus#89]
Hello,
I get this error when running the ip adapter mask workflow
In comfy on a m1 MacBook Pro, any ideas?(on the apply ipadapter node)

Error occurred when executing IPAdapterApply: IPAdapterApply.apply_ipadapter() got an unexpected keyword argument 'attn_mask' File "/Users/xxx/ComfyUI/execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/Users/xxx/ComfyUI/execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/Users/xxx/ComfyUI/execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))

**Comment by cubiq** [comment]
you probably have updated the extension but haven't restarted comfy

**Comment by AltairAlAnon** [comment]
Thanks for replying! I just updated comfy via the comfy ui manager, but still get the same error for some reason

**Comment by cubiq** [comment]
try to delete the ipadapter node, refresh the page and recreate it.

for some reason your installation is not fully updated. either the ipadater extension, comfyui or the browser cache

**Comment by AltairAlAnon** [comment]
Updated some additional nodes and restarted, seems to work now, thanks!!!
