### ISSUE TITLE
Can't get a workflow with SDXL working.  Have an example to share?

### ISSUE THREAD

**Issue by jbluew** [cubiq/ComfyUI_IPAdapter_plus#9]
Me and another person have tried modifying the 1.5 example workflows shared in this repo to work with SDXL.  We're getting the black square output, not matter what checkpoint, vae, or fp16 on or off we use.  Do you have an example of a working one that we can try to use for troubleshooting?

**Comment by cubiq** [comment]
Try the new sdxl model, note that it has to be paired with the sd1.5 clip vision, not the sdxl one (I know it's messy)Altro be sure to have the latest xformers installed. Tomorrow I am also pushing a new version, check that out as wellPs: the sdxl models are not great but the new one is alright On Sep 14, 2023 23:24, jbluew ***@***.***> wrote:
Me and another person have tried modifying the 1.5 example workflows shared in this repo to work with SDXL.  We're getting the black square output, not matter what checkpoint, vae, or fp16 on or off we use.  Do you have an example of a working one that we can try to use for troubleshooting?

**Comment by jbluew** [comment]
Thanks.  I'm still have trouble with the suggested models, but I'll check it out with the new update tomorrow.

**Comment by cubiq** [comment]
can you also try ```--fp32-vae``` option?
