### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by somebush** [cubiq/ComfyUI_IPAdapter_plus#90]
log: https://pastebin.com/AVwX1JyS

**Comment by somebush** [comment]
First installed via Manager, then uninstalled and installed via git clone. This is git clone.

**Comment by Arron17** [comment]
Update ComfyUI, your version is over a month out of date and several changes have been made to comfy that also required changes in this module.

From your log:
### ComfyUI Revision: 1541 [1c5d6663] | Released on '2023-10-07'

Newest version is:
### ComfyUI Revision: 1700 [8a451234] | Released on '2023-11-18'
