### ISSUE TITLE
Ipadapter not working. "AttributeError: 'NoneType' object has no attribute 'encode_image'"

### ISSUE THREAD

**Issue by KosDyatlov** [cubiq/ComfyUI_IPAdapter_plus#94]
Hi! Who has had a similar error? I'm trying to run ipadapter in ComfyUi, I've read half the internet and can't figure out what's what. I suspect that something is wrong with the clip vision model, but I can't figure out what it is. The xl model as well as the 1.5 model do not work.
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/143892154/600fe94f-9fb3-4308-b1bd-a8383997f85e)

**Comment by cubiq** [comment]
you have  very old comfyui version installed. you need to update

**Comment by KosDyatlov** [comment]
@cubiq I have a version installed  _"ComfyUI Revision: 1707 [6ff06fa7] | Released on '2023-11-21'"_

**Comment by cubiq** [comment]
update the extension, stop comfy and restart it

**Comment by KosDyatlov** [comment]
I apologize for the question. But I've updated everything on these lists. I restarted (shut down and restarted) ComfyUI. But the error still persists
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/143892154/6c75d3ad-f2d9-48e9-9751-365c8f0d9e34)

**Comment by cubiq** [comment]
I'm sorry but still your extension is not actually updated. The manager often fails to update for some reason. You need to update the extension manually or reinstall it.

**Comment by cubiq** [comment]
in this case it's the extension that it's not updated (or the manager that is not able to update it for some reason). It happens sometimes.

**Comment by KosDyatlov** [comment]
Uninstalled and reinstalled, re-downloaded all the models and renamed them correctly. Everything worked! Thank you!
