### ISSUE TITLE
scheduling image weights

### ISSUE THREAD

**Issue by pizurny** [cubiq/ComfyUI_IPAdapter_plus#96]
Hello, is it possible to schedule different image weights over time? I want to use it alongside animdiff, 
Ive tried batchvalueschedule from fizz nodes ,but getting this error:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 528, in preprocess
    weight_1 = 1.19e-05 if weight_1 <= 1.19e-05 else weight_1
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by cubiq** [comment]
it should be possible but it's very expensive computationally (the embeds have to be recalculated at each step).

The weight only accept floats, so you have to find a node that can schedule floats

**Comment by ttulttul** [comment]
Perhaps a half measure could be to use the new time step feature to create a few IPAdapter nodes with different time step settings and weights.

**Comment by cubiq** [comment]
yeah the image weight thing will likely change soon with the addition of a new node

**Comment by brbbbq** [comment]
Hello, I'm curious if this issue has been revisited at all. I understand we can animate the weights of the IPAdapter through the attention mask input, but from my understanding it requires animating a grayscale image sequence, which is cumbersome when you are finetuning the timing. It would be nice to simply schedule the weight value for basic fading between images with the Encode IPAdapter Image node.

**Comment by cubiq** [comment]
yes I'm working on a complete code rewrite and I will include that as well

**Comment by brbbbq** [comment]
That sounds amazing. Really appreciate it, looking forward to it!

**Comment by cubiq** [comment]
took me a while but it's finally on
