### ISSUE TITLE
Workflows work onn SD 1.5 but missmatch shapes errors happen when changing

### ISSUE THREAD

**Issue by if-ai** [cubiq/ComfyUI_IPAdapter_plus#98]
I hope this is not annoying but even when using the 1.5 clip on the vit-h like mentioned on the readme I get errors when reaching the ip-adapter nodes. I also try xl clip but got the same error I am using recommended models form the readme installation section and all models on the workflow are set to use XL 

![vUeykSvLv6](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/21185218/44657048-f93a-4f8c-9dfd-13a5d6e8aaed)

```
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/impactframes/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/impactframes/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/impactframes/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/impactframes/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 390, in apply_ipadapter
    self.ipadapter = IPAdapter(
  File "/home/impactframes/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 178, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "/home/impactframes/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ImageProjModel:
        size mismatch for proj.weight: copying a param with shape torch.Size([8192, 1024]) from checkpoint, the shape in current model is torch.Size([8192, 1280]).

Prompt executed in 0.71 seconds
```
this is the workflow it happens when changing models to the XL pipeline
https://comfyworkflows.com/workflows/f796d4b9-fe0f-4a4f-ada6-94ebd54cf35b

**Comment by if-ai** [comment]
The problem is not the iPadapter. Thanks

**Comment by traugdor** [comment]
What was the problem? I ask because I am getting the same issue. I just downloaded this and it's not working out of the box.

**Comment by if-ai** [comment]
> What was the problem? I ask because I am getting the same issue. I just downloaded this and it's not working out of the box.

The problem was I forgot to select the plus toggle on the ip adapter encode. It needs to set plus or uncheck when you don't use a plus model. The plus is on the name of the model if it doesn't says plus in the name is not a plus type model

**Comment by traugdor** [comment]
I see. I was able to correct it by disabling the other CLIP model that I had already downloaded from somewhere else. 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/6344355/cbfea8ee-39ee-4184-b0e1-2ab85acd658a)
