### ISSUE TITLE
Embedding locations

### ISSUE THREAD

**Issue by MrGingerSir222** [cubiq/ComfyUI_IPAdapter_plus#99]
Where does the embedding loader draw from? The saver saves by default to an embedding folder it creates in the default output folder for comfyui, but I cannot figure out where the loader node is trying to pull embeddings from. I’ve tried several locations and it can never find them. Thanks in advance!

**Comment by cubiq** [comment]
`/input`

**Comment by MrGingerSir** [comment]
thank you!
